Ensure track is looping in song select immediately
ppy/osu pull request #10146
Opened 2020-09-12 21:24 UTC by bdach

Resolves #10127.

# Summary

I'm PRing this mostly for feedback. As I mentioned in the issue thread, tests exposed that it was possible for tracks to complete and switch away on their own in song select instead of looping, therefore causing a potential race between asserts checking the track and the track switching away in song select tests that caused the intermittent failure.

The reason it was possible for the track to switch away is that because the looping flag was being set in the following call tree:

```
performUpdateSelected+run()
    updateComponentFromBeatmap()
```

which doesn't necessarily execute right away - it can be delayed up to 200ms if a map was previously selected:

https://github.com/ppy/osu/blob/5740fc2bd099b2141f2d5c9be7282611f769012c/osu.Game/Screens/Select/SongSelect.cs#L454-L457

The resolution aims to resolve this by subscribing to `MusicController.TrackChanged` to immediately set the loop flag on every track change handled by the music controller.

This can be tested by running `TestScenePlaySongSelect.TestPresentNewBeatmapNewRuleset` *in the visual test browser* (*not* headless with nunit runner, as in that variant asserts can pretty often win the race). In visual tests the test should fail almost every time and look wrong on `master`, and work with this branch.

# Remarks

[As discussed on discord](https://discord.com/channels/188630481301012481/188630652340404224/754297416039006269), the alternatives were:

* moving the `Looping = true` set somewhere where it would be executed immediately in the beatmap change callback, but it would have to be scheduled to be 100% safe, because the music controller *also* changes track in a beatmap change callback, so without the schedule we'd be relying on callback execution order for the fix to work,
* adding some sort of global field in `MusicController` that would have all loaded tracks loop - sucks because now there are two sources for one setting.

This resolution has some risk in it because events, so there's a potential for missed unsubscribes, but compared to the alternatives above I think it's way better. I've tested it a little bit and it seems to behave ok and pass tests, but this is the sort of change where I wouldn't necessarily trust that that's enough to catch all possible kinks.

2020-09-12 21:38 UTC, frenzibyte approved these changes, later dismissed
Sounds like a good solution, and also logical as it shows now that the current track would get looped if the user is in the song select screen.

2020-09-14 08:12 UTC, smoogipoo commented
I'd really like an unsubscription to be added to `Dispose()` just as a safeguard - screens don't necessarily have to be exited if their parenting `ScreenStack` is disposed.

Seems fine otherwise :+1:

2020-09-14 08:12 UTC, smoogipoo requested changes
As mentioned

2020-09-15 05:17 UTC, peppy approved these changes

2020-09-15 05:17 UTC, merged

2020-09-15 05:33 UTC, smoogipoo commented on osu.Game/Screens/Select/SongSelect.cs
> +            music.TrackChanged -= ensureTrackLooping;
this needs a `if (music != null)`.