Various fixes
ppy/osu pull request #1025
Opened 2017-07-18 09:43 UTC by huoyaoyuan

Also implement Ctrl+Enter for Auto in song select.

2017-07-24 03:16 UTC, peppy commented on osu.Game/OsuGame.cs
> +            LoadComponentAsync(userProfile = new UserProfileOverlay { Depth = -2 }, mainContent.Add);
this has already been fixed elsewhere, so please rebase or revert this

2017-07-24 03:17 UTC, peppy commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +            this.input = input;
really don't like this. handle keyboard KeyDown and KeyUp events and store the current state of control if anything.

2017-07-24 14:06 UTC, turbedi requested changes

2017-07-24 14:06 UTC, turbedi commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPresssed;
Typo, `controlPressed` and not `controlPresssed`

2017-07-25 00:52 UTC, peppy commented on osu.Game/OsuGame.cs
> +            LoadComponentAsync(userProfile = new UserProfileOverlay { Depth = -1 }, mainContent.Add);
this is still wrong (all modifications to this file).

2017-07-25 01:02 UTC, peppy commented
Want to split this up into one PR per fix? We've been avoiding "various fix" branches as of late.

2017-07-25 06:03 UTC, huoyaoyuan commented
Should be sure. But at this time, this PR is just doing one thing.

2017-07-31 07:50 UTC, peppy commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private IEnumerable<Mod> originalMods;
why are we storing `originalMods` here?

2017-07-31 09:31 UTC, huoyaoyuan commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private IEnumerable<Mod> originalMods;
The behavior in stable: when Auto selected manually and returned from player, the Auto is deselected too.
I think this behavior is troubling in some occasions (like mouse-only presentation), so this marking how the Auto mod is selected.

2017-08-02 08:12 UTC, smoogipoo submitted a review, later dismissed

2017-08-02 08:12 UTC, smoogipooo commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
Would rather store the inputmanager from load() and checking inputManager.CurrentState.Keyboard.ControlPressed.

2017-08-02 08:12 UTC, smoogipooo commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        }
Why not just create a new virtual method as part of Ruleset to create the auto mod for you? I find this stuff pretty ugly.

2017-08-03 04:07 UTC, huoyaoyuan commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
This is against ppy's previous opinion. Hope you to get agreement.

2017-08-03 04:13 UTC, huoyaoyuan commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        }
Things will be better if mods are equtable.  But seems too much stuff.

2017-08-03 05:14 UTC, smoogipooo commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
@peppy please confirm and provide reason if so.

2017-08-03 05:15 UTC, peppy commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
If anything, store a Func<bool> that you create in `load()`. Don't want a local instance of `UserInputManager` just for this

2017-08-03 05:17 UTC, smoogipooo commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
Why does it matter if you have a local instance of the UserInputManager?

2017-08-03 05:18 UTC, peppy commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
feels unnecessary just to check a modifier key.

2017-08-03 05:18 UTC, smoogipooo commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        }
Anything is better than this ugliness :/ We're not at the point where we need to do hacks because we can't implement functionality.

2017-08-03 05:38 UTC, smoogipooo commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private bool controlPressed;
Just discussed with @peppy, let's modify `OnSelected()` to accept an input state parameter, which can be null when called through code.

2017-08-04 07:20 UTC, peppy commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private IEnumerable<Mod> originalMods;
How about just storing a `bool removeAutoModOnResume` rather than this?

2017-08-04 07:30 UTC, huoyaoyuan commented on osu.Game/Screens/Select/PlaySongSelect.cs
> +        private IEnumerable<Mod> originalMods;
Would make a bit more work, but seems more clear and extensible.

2017-08-04 08:28 UTC, peppy commented on osu.Game/OsuGame.cs
> +            LoadComponentAsync(userProfile = new UserProfileOverlay { Depth = -1 }, mainContent.Add);
???

2017-08-04 08:48 UTC, peppy approved these changes

2017-08-04 08:48 UTC, merged