Make DifficultyIcon support dynamic star difficulty
ppy/osu pull request #10306
Opened 2020-09-30 16:04 UTC by smoogipoo

Preview: https://drive.google.com/file/d/1syCxOYoG6ci56pWy_jUZZJxzGR30CgBi/view?usp=sharing

This is set up to work for timeshift, however it doesn't work in practice since timeshift doesn't retrieve the locally-available beatmap so it falls back to whatever's coming in via `BeatmapInfo.StarDifficulty`. _Something_ needs to retrieve the local beatmap somewhere, unsure if multiplayer or `BeatmapDifficultyManager` at this point. I think there was a reason why I didn't do it for multiplayer.

2020-09-30 20:24 UTC, Gonzalo-Bruna commented
is it a known issue that the star rating in the beatmap wedge doesn't update when you apply mods?

2020-09-30 20:25 UTC, bdach commented
I'm pretty sure it is, the buffered container there doesn't update entirely correctly. It's a separate issue.

2020-10-01 10:16 UTC, peppy commented on osu.Game/Beatmaps/BeatmapDifficultyManager.cs
> +                if (Stars < 2.0) return DifficultyRating.Easy;
where are these values coming from? osu-web? may be good to leave an inline comment linking it up.

2020-10-01 12:09 UTC, peppy requested changes

2020-10-01 12:09 UTC, peppy commented on osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
> +        private class DifficultyRetriever : Drawable
```suggestion
        private class DifficultyRetriever : Component
```

not hugely important, but better defines what it is.

2020-10-01 18:52 UTC, bdach approved these changes
this looks real cool :+1:

2020-10-05 08:38 UTC, peppy approved these changes

2020-10-05 10:40 UTC, merged