Fix some backgrounds filenames not being parsed correctly
ppy/osu pull request #1036
Opened 2017-07-20 07:20 UTC by ColdVolcano

This fixes these two scenarios (and combinations of them):
- Background files which had a `$` on their filename would freeze the game
- Background files which had a `,` on their filename won't load. (even osu!stable has problems loading these!)
Here's an example beatmapset with a combination of the mentioned fixes: 
[Deorro - Yee.zip](https://github.com/ppy/osu/files/1161478/Deorro.-.Yee.zip)

2017-07-20 10:43 UTC, peppy commented
Not a huge fan of the way you solved this. I'd search for a solution that avoids requiring the `needsRecheck` bool.

2017-07-21 06:05 UTC, peppy commented
sorry, this is shocking logic still

2017-07-21 06:33 UTC, Nabile-Rahmani requested changes

2017-07-21 06:33 UTC, Nabile-Rahmani commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +        private void handleFilenames(ref string[] split)
Arrays are always reference type, by the way. `ref` does absolutely nothing.

2017-07-21 06:53 UTC, Tom94 commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +        private void handleFilenames(ref string[] split)
Yes it does. Without it line 290 would not have any effect outside of the method. The `ref` keyword turns it into a reference to a reference to a string array.

2017-07-21 07:44 UTC, Nabile-Rahmani commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +        private void handleFilenames(ref string[] split)
That was an amazing brainfart. Thanks for correcting me.

2017-07-22 17:57 UTC, ColdVolcano commented
Closing as not what we want

2017-07-22 17:57 UTC, closed without merging