Fix first hitobject in osu! hidden mod not getting correct fade applied
ppy/osu pull request #10427
Opened 2020-10-08 18:14 UTC by peppy

Closes #8153

2020-10-08 21:12 UTC, bdach requested changes

2020-10-08 21:12 UTC, bdach commented on osu.Game/Rulesets/Mods/ModHidden.cs
> +                var firstObject = drawables.FirstOrDefault();
I believe this should be

```suggestion
                var firstObject = drawables.FirstOrDefault(IsFirstHideableObject);
```

or, probably better, rewrite this logic a bit to be

```csharp
if (IncreaseFirstObjectVisibility.Value)
{
    drawables = drawables.SkipWhile(h => !IsFirstHideableObject(h));

    var firstObject = drawables.FirstOrDefault();
    if (firstObject != null)
        firstObject.ApplyCustomUpdateState += ApplyFirstObjectIncreaseVisibilityState;

    drawables = drawables.Skip(1);
}
```

Can be tested on any map that starts with a spinner - the second object won't fade out at all while the third will work like normal hidden.

2020-10-08 22:18 UTC, bdach submitted a review, later dismissed

2020-10-09 09:21 UTC, smoogipoo commented
The weird part is that the approach circle is not supposed to fade out, but I'm not good enough at HD to know how confusing this actually is. Maybe this should instead fade out just `circle.CirclePiece` if `increasedVisibility = true`?

2020-10-09 09:23 UTC, bdach commented
That's what `master` does already, doesn't it?

2020-10-09 09:25 UTC, smoogipoo commented
Master:
- Doesn't fade out anything.

This PR:
- Fades out everything.

Stable:
- Fades out only the circle.

2020-10-09 09:26 UTC, bdach commented
Oh the issue is formulated weirdly. Sure.

2020-10-09 09:29 UTC, peppy commented
That wasn't the intention.

2020-10-09 09:35 UTC, smoogipoo commented
To me it feels weird because the approach is hidden way before it touches the circle, making it kinda useless? Again I can't really provide much insight here but the reason for it not hiding in the first place is because players maintain an afterimage of the circle in their mind specifically so they can hit the first note accurately, assuming that the approach is visible.

2020-10-09 09:36 UTC, peppy commented
Okay, will change it to match stable for now.

2020-10-09 10:23 UTC, smoogipoo approved these changes

2020-10-09 10:23 UTC, merged