Expose BreakTracker.IsBreakTime in Player
ppy/osu pull request #10472
Opened 2020-10-10 13:09 UTC by LeNitrous

Required by https://github.com/ppy/osu/pull/9606. This allows others such as mods to subscribe to the break state of the player.

2020-10-10 16:17 UTC, peppy requested changes

2020-10-10 16:17 UTC, peppy commented on osu.Game/Screens/Play/Player.cs
> +        public IBindable<bool> IsBreakTime => breakTracker?.IsBreakTime;
Should probably add xmldoc, and it should never be null. If there's a reason `breakTracker` can be null then initialise this bindable locally and bind to the `breakTracker` one in load/`LoadComplete`

2020-10-11 08:55 UTC, bdach commented on osu.Game/Screens/Play/Player.cs
> +            IsBreakTime.BindTo((BindableBool)breakTracker.IsBreakTime);
what's this cast for?

2020-10-11 13:25 UTC, peppy approved these changes

2020-10-11 13:36 UTC, merged