Fix Mod Customisation Container not absorbing input correctly
ppy/osu pull request #10495
Opened 2020-10-13 12:24 UTC by FamousPig

Fixes #10210

Previously hovering and right clicks were passed through the customisation menu to buttons behind it. Left clicks were and are absorbed by the `OsuScrollContainer` inside `ModSettingsContainer`. Mouse clicks and hover events are now absorbed by `ModSettingsContainer`.

I'm honestly not sure whether the way I have implemented the testing is correct or too hacky, if there is an easier way and if testing is even worth it for this issue.

2020-10-13 13:02 UTC, bdach requested changes

2020-10-13 13:02 UTC, bdach commented on osu.Game.Tests/Visual/UserInterface/TestSceneModSettings.cs
> +                return ModSectionsContainer.Children.Single(s => s.ModType == mod.Type)
Going through `Children` and `ButtonsContainer` can probably be skipped. `ChildrenOfType<>` works recursively across the entire subtree.

2020-10-13 13:02 UTC, bdach commented on osu.Game.Tests/Visual/UserInterface/TestSceneModSettings.cs
> +            public float SetModSettingsWidth(float newWidth)
Return value can probably be skipped.

2020-10-13 13:02 UTC, bdach commented on osu.Game/Overlays/Mods/ModSelectOverlay.cs
> +        protected class MouseInputAbsorbingContainer : Container
This is a little too generic to live here as `protected`. I'd consider extracting `ModSettingsContainer` to a separate component and apply the input handler overrides there.

2020-10-14 06:57 UTC, peppy commented
I've made two further changes to get this in a mergeable state:

- 24eff8c6 Rename the class to ModSettingsContainer (all surrounding variables refer to "settings", not "cusomisation")
- 3e326a92 Reworked how you are propagating state between the two containers to use bindable flow. I figured it was easier to commit this to show how it should be done than attempt to do so in a review. Let me know if you have any questions.

2020-10-14 06:58 UTC, peppy submitted a review, later dismissed

2020-10-14 22:38 UTC, bdach approved these changes, later dismissed

2020-10-14 22:45 UTC, bdach commented
I've had to resolve a merge conflict here, but thankfully it was trivial (two new tests at same position of file). Please double check if you can, though.

2020-10-14 22:45 UTC, bdach approved these changes

2020-10-15 09:20 UTC, smoogipoo approved these changes

2020-10-15 09:25 UTC, merged