Add Seasonal backgrounds
ppy/osu pull request #10586
Opened 2020-10-23 12:17 UTC by hbnrmx

Resolves #7055

PRing this as a first draft because I would like some assistance with the remaining issues.

1. stable gives the user the option Seasonal Backgrounds: `Always` / `Sometimes` (default) / `Never`
Not sure if this is worth keeping around in lazers Background source. For now, I only added `Seasonal` (default) 

1. we definitely need some way of caching or prefetching, but I would like some guidance on which level to do that.

1. In `BackgroundScreenDefault` I had to change the initial load to `LoadComponentAsync`
 because of `[LongRunningLoad]` but chaining `LoadComponentAsync`s like that looks very wrong to me.

2020-10-23 13:22 UTC, bdach commented
No offence, but I think it would have been wiser to ask your questions in an issue comment. Fetching the images every time is pretty shocking.

Here's a proposal of a completely different flow instead:

* On game load, check if there are seasonal backgrounds available
* If there are new backgrounds, fetch them all at once in the background and persist them to storage, then display a notification to the user prompting if they would like to switch
* If the backgrounds went away, clean up the old ones and restore the user's setting to the one before going to seasonal

Could also have seasonal as a separate option, I guess. It can't be as done currently as every switch to seasonal will then require users to revert back manually.

2020-10-23 13:26 UTC, peppy commented
All at once sounds like not a great idea. Stable currently downloads each time a new one is required asynchronously, and caches after retrieval.

2020-10-23 13:33 UTC, bdach commented
I guess it's a pretty huge footprint, true. The seasonal background API response should probably persist across the current session, though, to avoid re-querying to check if there is a need to fetch a new one (`SessionStatics`?)

2020-10-23 14:27 UTC, hbnrmx commented
For reference, the current Halloween event has 15 images, so ~6Mb.
`SessionStatics` only stores boolean configuration values currently, so it may not be built with textures in mind.
That said, I don't know half a thing about caching...

2020-10-23 15:11 UTC, bdach commented
I was suggesting storing the API response there, not the textures themselves. For textures, the framework `LargeTextureStore` already does some caching, but I believe it won't have much of an effect here as the textures are refcounted - so if all references to a background are lost the texture will get unloaded, which I think will happen on screen transitions rendering the caching pretty pointless in this particular case.

2020-10-29 11:03 UTC, PercyDan54 commented
A suggestion: We might want to split the settings into two
Use seasonal background: Sometimes, always, never
Background Source: Beatmap, Skin

2020-10-29 17:20 UTC, hbnrmx commented
@bdach 
@PercyDan54 

Thanks for your feedback, and sorry I didn't get to this earlier.
In this iteration I
* split out Seasonal Backgrounds (Always/Sometimes/Never) from Background Source (Beatmap/Skin)
(I also feel this makes more sense in the case where no seasonal event is happening.)

* changed background fallback such that Beatmap/Skin source choice
 is respected when no Seasonal event is happening.

* made `SeasonalBackgroundLoader` read from `SessionStatics` 
(this should make sure that the API is queried only once for the index)

This still leaves:

* repeated texture fetching issue
* ugly `LoadComponentAsync` chain as described in the OP.

2020-10-30 05:42 UTC, peppy commented
"Sometimes" is based off whether we are currently "in season". This is provided by the api response [already](https://osu.ppy.sh/docs/index.html#apiv2seasonal-backgrounds) in the form of a timestamp (`ends_at`) so you should be able to consume this.

2020-10-30 14:37 UTC, peppy requested changes

2020-10-30 14:37 UTC, peppy commented on osu.Game/Configuration/SessionStatics.cs
> +            Set(Static.SeasonalBackgrounds, new List<APISeasonalBackground>());
Can probably just store the the whole response to one static?

2020-10-30 14:37 UTC, peppy commented on osu.Game/Configuration/SeasonalBackgrounds.cs
> +    public enum SeasonalBackgrounds
`SeasonalBackgroundMode` will probably feel better

2020-10-30 14:37 UTC, peppy commented on osu.Game/Screens/Backgrounds/BackgroundScreenDefault.cs
> +            }
this should probably be above everything else in this method. as it is, a different background is constructed above, then potentially thrown away due to the current sequence.

2020-10-30 14:37 UTC, peppy commented on osu.Game/Screens/Backgrounds/BackgroundScreenDefault.cs
> +                        goto case SeasonalBackgrounds.Always;
rather than using `goto`,  just write this as

`if (showSeasonalBackgrounds.Value == Always || (showSeasonalBackgrounds.Value == Sometimes))`

2020-10-30 14:37 UTC, peppy commented on osu.Game/Graphics/Backgrounds/SeasonalBackgroundLoader.cs
> +        public bool IsInSeason() => DateTimeOffset.Now < endDate.Value;
```suggestion
        public bool IsInSeason => DateTimeOffset.Now < endDate.Value;
```

2020-10-30 19:13 UTC, bdach commented
For the record I've fixed the test failures locally and am currently in the process of writing a test scene for this.

2020-10-30 21:11 UTC, bdach commented
I've fixed the test failures, made a few stylistic changes, added test coverage, and also added support for delayed fetching of the backgrounds if API is not immediately available on launch, as the game would actually hard-crash if network was not available. The side effect of that change is that even though the API endpoint seems to be guest-accessible, the backgrounds won't be loaded until login, as we don't have an online-but-not-logged-in API state.

There's one transition at load that looks a little off that I want to look at but other than that I guess this is ok if we don't want to deal with caching the downloaded assets yet.

2020-10-30 21:52 UTC, bdach commented
It should be *sliiightly* better now. The fade in `SeasonalBackground.load` is a bit dodge but unsure if there's a better way to make sure it just doesn't come in without any transition at all and look absolutely janky.

2020-10-31 06:14 UTC, peppy approved these changes

2020-10-31 06:28 UTC, merged