Add more search options to Beatmap Listing
ppy/osu pull request #10607
Opened 2020-10-27 20:20 UTC by EVAST9919

![Screenshot_2](https://user-images.githubusercontent.com/22874522/97357533-fcd11580-18aa-11eb-9b88-b0959e9621cf.png)

2020-10-27 20:39 UTC, turbedi commented on osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
> +                req.AddParameter("e", string.Join(".", Extra.Select(e => e.ToString().ToLowerInvariant())));
```suggestion
                req.AddParameter("e", string.Join('.', Extra.Select(e => e.ToString().ToLowerInvariant())));
```

2020-10-27 20:39 UTC, turbedi commented on osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
> +                req.AddParameter("r", string.Join(".", Ranks.Select(r => r.ToString())));
```suggestion
                req.AddParameter("r", string.Join('.', Ranks.Select(r => r.ToString())));
```

2020-10-27 22:24 UTC, bdach requested changes, later dismissed

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/SearchRank.cs
> +    public enum SearchRank
Skeptical this needs to exist alongside `ScoreRank`. Would just use that instead and provide a way to override `ScoreRank`'s `Description`s.

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapSearchMultipleSelectionFilterRow.cs
> +            }
`Bindable<List<T>>` is not done anywhere. `BindableList<T>` exists in framework and has proper handling of callbacks on add/remove/replace/move/reset operations. You wouldn't have to do this whole rigamarole of reconstructing the entire list to trigger a value change if you used it.

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapSearchMultipleSelectionFilterRow.cs
> +            public event Action StateUpdated;
This needs to go. You even already had a bindable `Active` in `TabItem` itself, used it, and then added this anyway...

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapSearchMultipleSelectionFilterRow.cs
> +                Active.Value = !Active.Value;
```suggestion
                Active.Toggle();
```

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapSearchMultipleSelectionFilterRow.cs
> +            protected abstract MultipleSelectionFilterTabItem[] CreateItems();
What is the point? All you care about is the underlying models, not the drawables themselves. How about a

```suggestion
            protected abstract T[] CreateItems();
```

or, even if you decided you want to customise the display text for each model, then

```suggestion
            protected abstract (T model, string description)[] CreateItems();
```

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/FilterTabItem.cs
> +        private Color4 getStateColour() => IsHovered ? colourProvider.Light1 : colourProvider.Light3;
does not match web design
```suggestion
        private Color4 getStateColour() => IsHovered ? colourProvider.Light1 : colourProvider.Light2;
```

2020-10-27 22:24 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/FilterTabItem.cs
> +            text.FadeColour(Active.Value ? Color4.White : getStateColour(), 200, Easing.OutQuint);
```suggestion
            text.FadeColour(Active.Value ? colourProvider.Content1 : getStateColour(), 200, Easing.OutQuint);
```

also the hover colour actually overrides the active colour on web

2020-10-28 22:42 UTC, bdach commented
I've made several stylistic changes here. @EVAST9919 please look through them whenever you have the chance.

2020-10-29 03:04 UTC, smoogipoo approved these changes
lgtm

2020-10-29 03:42 UTC, merged