Add RanksSection
ppy/osu pull request #1061
Opened 2017-07-26 17:02 UTC by jorolf

2017-07-27 02:12 UTC, peppy commented
What are you basing the model's (`Play`) name and structure on?

2017-07-27 22:14 UTC, jorolf commented
Not quite sure if I get what you're trying to say.

2017-08-01 09:19 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/Ranks/DrawableScore.cs
> +        private class ModIcon : Container
why couldn't you use the existing ModIcon implementation?

2017-08-01 09:21 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/Ranks/DrawableScore.cs
> +        private class LinkContainer : OsuClickableContainer
Why couldn't you use the existing LinkText implementation? Code duplication is bad.

2017-08-01 09:23 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/RanksSection.cs
> +                shownScores = Math.Min(Children.Count, shownScores + 5);
This method could be written a lot nicer (you shouldn't need the `shownScores` field at all).

2017-08-01 09:24 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/RanksSection.cs
> +            private class ShowMoreContainer : OsuClickableContainer
This seems to be the same thing as a clickable link container just with a different action. Code duplication is bad.

2017-08-01 09:24 UTC, peppy requested changes
see reviews above

2017-08-09 15:56 UTC, jorolf commented on osu.Game/Overlays/Profile/Sections/Ranks/DrawableScore.cs
> +        private class ModIcon : Container
![image](https://user-images.githubusercontent.com/12570757/29131066-ef91b91a-7d2b-11e7-8ae8-69ad84fd5003.png)

2017-09-14 11:10 UTC, peppy commented
I took the liberty of adding API integration.

Todo:

- Remove redundant code – there are two sections being displayed that are almost identical inside `RanksSection`. These should be extracted into their own container to de-dupe the pagination and display logic.
- Make pagination work.
- Load ranking screen when selecting a score.

Let me know whether you want to attempt these remaining tasks or need any advice on a direction to go to make them work.

2017-09-14 11:12 UTC, peppy requested changes
Fix specified issues

2017-09-21 20:39 UTC, jorolf commented
The only things thats missing now is loading the ranking screen as I'm not sure how a overlay should push a screen

2017-09-26 12:50 UTC, peppy commented
There's already a method in `OsuGame` to perform results loading (`LoadScore(Score s)`). You could try making this `internal` or `public` then calling it using DI on `OsuGame`.

If you want to avoid DI, then you can add an `Action<Score> ScoreDisplayRequested` to` ProfileOverlay` and assign the protected method to it in `OsuGame` itself (this way causes less interdependencies so would probably be preferred).

2017-10-13 14:01 UTC, peppy approved these changes

2017-10-13 14:01 UTC, merged