Disable spectator streaming connection logic on iOS to avoid startup crash
ppy/osu pull request #10655
Opened 2020-11-02 06:55 UTC by peppy

Due to an [issue](https://github.com/dotnet/runtime/issues/35988) at xamarin's end (which *should* have been fixed via [this pr](https://github.com/xamarin/xamarin-macios/pull/8615) but still fails on latest preview release) we can't support this just yet.

2020-11-02 06:56 UTC, smoogipoo approved these changes, later dismissed

2020-11-02 07:02 UTC, peppy commented
Don't merge just yet, looking to be too late in the method to actually stop the issue (possibly `static ctor` at net core's end..?)

2020-11-04 05:54 UTC, peppy commented
This looks to be the best solution for now. Leaving it as a local downgrade is a bit iffy as behaviour may differ as we move forward, but I think it's better than targeting the lower version at the `osu.Game` level?

I've tested this works on device and simulator (can spectate from device with no issues).

2020-11-04 05:57 UTC, smoogipoo requested changes

2020-11-04 05:57 UTC, smoogipoo commented on osu.iOS.props
> +    <NoWarn>NU1605</NoWarn>
```suggestion
    <NoWarn>$(NoWarn);NU1605</NoWarn>
```

2020-11-04 06:24 UTC, smoogipoo approved these changes

2020-11-04 06:47 UTC, merged