Fix looping mode not being set on first track after entering song select
ppy/osu pull request #10660
Opened 2020-11-02 15:58 UTC by peppy

Closes #10656.

2020-11-02 17:40 UTC, bdach requested changes

2020-11-02 17:40 UTC, bdach commented on osu.Game/Screens/Select/SongSelect.cs
> +            Debug.Assert(isHandlingLooping);
As evidenced by the failing test, `endLooping()` can actually run twice on the same screen if it is suspended, and then exited from due to unwinding the screen stack to a screen lower down. Probably fine to remove this assert, or turn it into a guard statement? Not sure.

2020-11-03 22:35 UTC, bdach commented
Weird thing is, I can't seem to reproduce... I suppose this can't hurt either, though - hopefully there's no conceivable way looping can *not* get set anymore.

2020-11-03 22:43 UTC, bdach approved these changes

2020-11-04 05:37 UTC, smoogipoo approved these changes

2020-11-04 05:37 UTC, merged