Add missing user activities for Multi screens
ppy/osu pull request #10740
Opened 2020-11-08 14:00 UTC by Game4all

# Summary

This adds "missing" user activities for the multi screens which are already live. 

I also took this opportunity to refactor the user activity handling logic in OsuScreen which was making it basically impossible to share the current activity to the screen stack (in the case of screens being subscreens and not actual screens). The logic now uses a bindable flow, very similarly to how it's done for OverlayActivationMode.

I'm hesitant to push the one-liner change to display the room name on the discord integration as it looks weird right now (the status and details are reversed)

2020-11-08 14:25 UTC, bdach requested changes
i guess this seems mostly fine

2020-11-08 14:25 UTC, bdach commented on osu.Game/Screens/OsuScreen.cs
> +                Activity.Value = InitialActivity;
can use `??=`

2020-11-08 14:25 UTC, bdach commented
> I'm hesitant to push the one-liner change to display the room name on the discord integration as it looks weird right now (the status and details are reversed)

you're going to have to give more detail than that to get a meaningful answer to that question (i.e. why does it look weird)

2020-11-08 17:42 UTC, Game4all commented
Actually, after comparing with with other rich statuses it looks normal in fact ... So I think there's no harm in getting it into that branch then ...

2020-11-08 20:48 UTC, bdach commented on osu.Desktop/DiscordRichPresence.cs
> +                    return lobby.Room.Name.ToString();
weird to call `.ToString()` on a... string - the rest have `.ToString()` calls for better formatting, but this one doesn't make much sense at all

2020-11-09 06:26 UTC, peppy requested changes

2020-11-09 06:26 UTC, peppy commented on osu.Game/Screens/OsuScreen.cs
> +            Activity = new Bindable<UserActivity>();
move to field itself

2020-11-09 06:26 UTC, peppy commented on osu.Game/Screens/Multi/Multiplayer.cs
> +            if (lastScreen is IOsuScreen lastOsuScreen)
not hugely fond of this whole flow, but seems like about the best we can do with the current structure of multiplayer.

2020-11-09 13:44 UTC, bdach approved these changes

2020-11-10 05:23 UTC, merged