Add File Import screen
ppy/osu pull request #10882
Opened 2020-11-17 12:38 UTC by PercyDan54

The code is from [a custom osu build](https://gitee.com/matrix-feather/osu)
It's useful for Android users who can't import files because they can't open multiple windows.
We may need a design change, maybe moving it to the settings section, but I don't know how to convert a `Screen` to a `DialogOverlay`
Gif showcase (Large file):
![2](https://user-images.githubusercontent.com/50285552/99391147-b5bbca80-2914-11eb-913f-570dc68eaad3.gif)

2020-11-17 12:43 UTC, bdach commented
First of all, @MATRIX-feather, are you aware that this has been PRed on your behalf? Did you agree to this?

@PercyDan54, you cannot PR changes that are not your own without declaring whether you have consent to do so first.

Secondly, I am 99% sure this cannot be upstreamed in its current form. If (and that's a big if) this screen is to be added, it should only be visible to Android users. I don't believe we should be adding this at all, however, as it's a major workaround of a major shortcoming of the current Android build.

2020-11-17 12:50 UTC, MATRIX-feather commented
> First of all, @MATRIX-feather, are you aware that this has been PRed on your behalf? Did you agree to this?
> 
> @PercyDan54, you cannot PR changes that are not your own without declaring whether you have consent to do so first.
> 
> Secondly, I am 99% sure this cannot be upstreamed in its current form. If (and that's a big if) this screen is to be added, it should only be visible to Android users. I don't believe we should be adding this at all, however, as it's a major workaround of a major shortcoming of the current Android build.

Yes, I agree

2020-11-17 12:52 UTC, peppy commented
Rather than this, how about adding proper file import support? Surely this can be done much easier without this weird UX.

2020-11-17 12:53 UTC, bdach commented
Please clarify what part you agree with as it's not clear to me. Also, are you sure you don't want at least authorship credit for the commit? The change has been committed in @PercyDan54's name and by their own admission it's not their code.

2020-11-17 13:01 UTC, PercyDan54 commented
> it should only be visible to Android users.

Maybe add `RuntimeInfo.OS == RuntimeInfo.Platform.Android` ?

2020-11-17 13:05 UTC, peppy commented
See my previous comment. As is the case in iOS, files should be pulled in from outside the app via associations, not vice versa.

2020-11-17 13:11 UTC, LittleEndu commented
If the user gives permission for the app to access files on their phone, then on android it makes at least a little sense to have it inside the app. iirc that's not the case on iOS because apps  don't have file level access to anything, unlike android where it's managed by the permission.

2020-11-17 13:14 UTC, MATRIX-feather commented
@bdach I agreed with @PercyDan54  to submit my code upstream, commit message is not very necessary to me tho.

2020-11-17 14:16 UTC, peppy commented
@LittleEndu iOS can also do this. but again, it's not the UX i am going for. there's no reason for it to be done this way, and the file selector wasn't made with mobile in mind. this may come at a later point but it should be preceded with support for importing files the opposite direction.

there is zero chance of this PR getting merged unless it is a button under the debug settings or something completely isolated and temporary like that.

2020-11-24 07:07 UTC, peppy requested changes

2020-11-24 07:07 UTC, peppy commented on osu.Game/Screens/Import/FileImportScreen.cs
> +            };
this just can't exist. you probably want to split some of this out into its own component or re-think structure in general.

2020-11-24 07:07 UTC, peppy commented on osu.Game/Screens/Import/FileImportScreen.cs
> +                                                        new SettingsEnumDropdown<FileFilterType>
Rather than having this, why not just always show every filetype? I don't see much benefit to being able to filter it.

2020-11-24 07:07 UTC, peppy commented on osu.Game/Screens/Import/FileImportScreen.cs
> +                                                        new GridContainer
as an example of restructuring, this should not require a `GridContainer` at all.

2020-11-24 07:07 UTC, peppy commented on osu.Game/Screens/Import/FileImportScreen.cs
> +                                                                        Text = "Refresh",
I'd argue this just shouldn't exist. If we're adding a refresh button it would be part of the file chooser itself.

2020-11-24 07:07 UTC, peppy commented on osu.Game/Screens/Import/FileImportScreen.cs
> +        }
remove this to simplify implementation

2020-11-24 07:07 UTC, peppy commented on osu.Game/Screens/Import/FileImportScreen.cs
> +        }
remove this to simplify implementation

2020-11-25 08:00 UTC, peppy commented
Curious why you can't use the existing [MigrationSelectScreen](https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Settings/Sections/Maintenance/MigrationSelectScreen.cs) rather than this custom design?

2020-11-29 14:59 UTC, peppy commented
Were the above actions intentional?

2020-11-29 15:04 UTC, PercyDan54 commented
> Were the above actions intentional?

I accidentally did that

2020-12-15 04:05 UTC, peppy commented
I've tidied this up into a mergeable state. Not going to dwell on implementation for now because I'm not sure how permanent this will even be.

A second pass would see it sharing dialog logic with `ManageCollectionsDialog` (which requires some refactoring to handle non-global dialogs like this). But that's for another day.

2020-12-15 04:05 UTC, peppy approved these changes

2020-12-15 06:03 UTC, merged