Define blueprint order similarly to hitobjects
ppy/osu pull request #10883
Opened 2020-11-17 13:59 UTC by smoogipoo

Fixes the ordering issue I mentioned in https://github.com/ppy/osu/issues/10857

Implementation is similar to that of `HitObjectContainer`, although `SelectionBlueprintContainer` doesn't need to worry about binding directly to hitobject start times since they are tied directly to the lifetime of a DHO already.

Most noticeable in the timeline, with this PR: https://drive.google.com/file/d/1WbOfqEwYFqS4I7K3yztZqMEtjzGxXwPS/view?usp=sharing

2020-11-17 15:00 UTC, peppy requested changes

2020-11-18 04:24 UTC, smoogipoo commented on osu.Game/Screens/Edit/Compose/Components/SelectionBlueprintContainer.cs
> +                return base.Compare(x, y);
This was copypasta from `HitObjectContainer`, I'll rewrite as:

2020-11-18 04:40 UTC, smoogipoo commented
See if you guys are fine with the newest changes, specifically:
* Sealing the new class since supporting deriving gets messy.
    * his required reverting the change to the type of `CreateSelectionBlueprintContainer()`.
    * Also cleans up the comparer.
* Renamed the class to `HitObjectOrderedSelectionContainer`.

2020-11-18 09:44 UTC, peppy approved these changes

2020-11-18 09:46 UTC, merged