Add global actions; improve default assignment
ppy/osu pull request #1094
Opened 2017-08-09 08:10 UTC by peppy

2017-08-10 07:16 UTC, peppy commented
So currently this system works on the premise that a single keydown can only trigger a single action in all cases. This means that in a usage with `allowConcurrentActions`, all bindings must be non-colliding – ie. they should not share a subset of keys

So having `D` and `Shift-D` is a no-go, but having `Shift-D` and `Shift-F` is fine.

2017-08-10 10:32 UTC, peppy commented
Considering `Action` -> `Button`, feedback appreciated

2017-08-10 11:33 UTC, peppy commented on osu.Game.Rulesets.Osu/OsuInputManager.cs
> +                    keyboard.Keys = keyboard.Keys.Concat(new[] { Key.LastKey + 1 });
this is obviously temporary. we probably want to make our own framework-level `Key` enum or consider other options for extensibility.

2017-08-11 00:36 UTC, peppy commented on osu.Game/Input/Binding.cs
>          [Indexed]
rename to `KeyBinding`?

2017-08-11 00:36 UTC, peppy commented on osu.Game/Input/ActionMappingInputManager.cs
> +        UniqueAndSameActions,
Rename to `All`?

2017-08-11 00:36 UTC, peppy commented on osu.Game/Input/ActionMappingInputManager.cs
> +        None,
Consider changing the behaviour of modifier keys to match OSes closer (modifiers shouldn't be checked until a non-modifier is pressed).

2017-08-11 00:37 UTC, peppy commented on osu.Game/Input/KeyCombination.cs
> +        public override int GetHashCode() => Keys != null ? Keys.Select(k => k.GetHashCode()).Aggregate((h1, h2) => h1 + h2) : 0;
this is probably wrong

2017-08-11 03:15 UTC, smoogipoo requested changes

2017-08-11 03:15 UTC, smoogipooo commented on osu.Game/Input/KeyCombination.cs
> +        public override int GetHashCode() => Keys != null ? Keys.Select(k => k.GetHashCode()).Aggregate((h1, h2) => h1 + h2) : 0;
I think this might be okay if h1 is multiplied by a prime. So `Aggregate((h1, h2) => h1 * 17 + h2)` should be fine.

2017-08-11 03:16 UTC, peppy commented on osu.Game/Input/ActionMappingInputManager.cs
> +            if (!args.Repeat && (concurrencyMode > ConcurrentActionMode.None || pressedBindings.Count == 0))
already fixed

2017-08-12 14:32 UTC, smoogipoo approved these changes
This all looks okay to me

2017-08-12 14:32 UTC, merged

2017-08-12 14:35 UTC, Tom94 commented on osu.Game.Rulesets.Catch/CatchInputManager.cs
> +            new KeyBinding( Key.Z, CatchAction.MoveLeft),
Why are there spaces in front of the first argument?

2017-08-12 14:42 UTC, Tom94 commented on osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
> +                        //Binding = registerLink
This rename should be reverted.

2017-08-12 14:43 UTC, Tom94 commented on osu.Game/Screens/Select/Footer.cs
> +        /// <param name="action">Binding the button does.</param>
So should these. In fact, they should be <see>.