Fix DrawableJudgement not always animating correctly on skin change
ppy/osu pull request #10951
Opened 2020-11-24 06:25 UTC by peppy

If the skin is changed before gameplay has started (at the loading screen) it is possible for a sequence of events to occur which results in the animation not being played:

- `SkinReloadableDrawable` runs its BDL load (and calls `OnSkinChanged` once)
- User changes skin, triggering `DrawableJudgement`'s skin change handling (binding directly on the `SkinSource` locally)
- This will call `PrepareDrawables` and reinitialise the `SkinnableDrawable` child hierarchy, then immediately apply the
animations to it.
- The new `SkinnableDrawable` will then get the `SkinChanged` event and schedule a handler for it, which will run on its first Update call.
- Any added animations will be lost as a result.

Fixed by binding directly to the `SkinnableDrawable`'s `OnSkinChanged`.  This has the added bonus of not needing to reinitialise the child hierarchy on skin change (which felt a bit weird in the first place).

2020-11-24 22:00 UTC, bdach requested changes

2020-11-25 01:22 UTC, peppy commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +            // ClearTransforms(true);
ah yes, it can be swicthed back on

2020-11-25 19:11 UTC, bdach approved these changes
seems to have the desired effect & works in my head :+1:

2020-11-30 04:58 UTC, smoogipoo approved these changes

2020-11-30 07:36 UTC, merged