Hide progress bar in the music controller depending on the current screen
ppy/osu pull request #1104
Opened 2017-08-13 20:54 UTC by EVAST9919

2017-08-14 03:38 UTC, peppy commented
hell no. why not just disable it? that manual movement is made of broken dreams; don't do this *ever*.

2017-08-14 03:38 UTC, peppy requested changes
.

2017-08-17 02:29 UTC, MrTheMake commented on osu.Game/Overlays/MusicController.cs
> +            private bool enabled;
Shouldn't an enabled property be implemented in the SliderBar class rather than in here?

2017-08-17 02:29 UTC, MrTheMake commented on osu.Game/Overlays/MusicController.cs
> +            public bool Enabled
A property with a set and get being simple like this is not needed. You can save the `enabled` variable and just use `Enabled` as a normal public bool

2017-08-18 02:29 UTC, peppy commented
This should be done using the bindable's `Disabled` property. `SliderBar` already completely supports this.

2017-08-18 02:29 UTC, peppy requested changes
see comment

2017-08-21 01:53 UTC, peppy commented
@EVAST9919 just making sure you saw my previous comment on this.

2017-08-24 02:14 UTC, peppy commented
Closing this due to inactivity. Pleas reopen when you address the issues.

2017-08-24 02:14 UTC, closed without merging