Fix selected item not being highlighted on some setting dropdowns
ppy/osu pull request #11216
Opened 2020-12-20 03:05 UTC by Joehuu

Fixes https://github.com/ppy/osu/issues/8912.

2020-12-20 03:07 UTC, frenzibyte requested changes

2020-12-20 03:07 UTC, frenzibyte commented on osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
> -                    ItemSource = windowModes,
Does not respect `host.Window.SupportedWindowModes` anymore.

2020-12-20 03:21 UTC, frenzibyte commented
This technically is hiding the issue instead of fixing it, I believe the underlying issue is about `Dropdown.Current` set to a value that does not have a corresponding item yet (because `Items` is set **after** `Current` is), therefore selecting a temporarily-created item.

This can be solved framework-side by updating selection to the real item when `Items` is set.

2020-12-20 05:32 UTC, peppy commented
@frenzibyte sure, but the dropdowns which can be changed to use the enum type still should be (code quality improvement). only issue is `windowModeDropdown`, as you pointed out, which has changed behaviour.

2020-12-22 04:05 UTC, peppy approved these changes

2020-12-22 08:09 UTC, merged