Fix incorrectly provided texture loader store to skins
ppy/osu pull request #11226
Opened 2020-12-21 06:23 UTC by peppy

This fixes the remaining cases of local `TextureLoaderStore` construction (bypassing host implementation). In the process, I attempted to clean up the way information is passed down to `WorkingBetamap` and `LegacySkin` classes, as the constructors / data feeding for both of these was getting pretty ugly.

2020-12-21 18:52 UTC, bdach requested changes
Not feeling 100% on this pull... The new pattern feels solid for normal code (apart from the comments below), but sort of flaky when tests become involved. Stuff is sometimes null and sometimes non-null, which is maybe fine, but puts me at some unease.

I guess the interface members could get nullability annotations - the biggest obstacle to that is `SkinnableTestScene`'s implementation of `Files`, which is the only one that can return nulls. I don't know, maybe fine to have test code not feel completely safe.

2020-12-21 18:52 UTC, bdach commented on osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
> +        public IResourceStore<TextureUpload> CreateTextureLoaderStore(IResourceStore<byte[]> underlyingStore) => null;
These implementations are all in pretty big classes, so I'd `#region` them, at least in order to be able to visually separate them out.

2020-12-21 18:52 UTC, bdach commented on osu.Game/Beatmaps/BeatmapManager.cs
> +        private readonly GameHost host;
As per default ctor argument, this is a potentially

```suggestion
		[CanBeNull]
        private readonly GameHost host;
```

field.

2020-12-21 18:52 UTC, bdach commented on osu.Game/Beatmaps/BeatmapManager.cs
> +        IResourceStore<TextureUpload> IStorageResourceProvider.CreateTextureLoaderStore(IResourceStore<byte[]> underlyingStore) => host.CreateTextureLoaderStore(underlyingStore);
Above suggestion shows that this has an unchecked access to possibly-null host. Only caller (`LegacySkin`) is null-tolerant, so I'd null-check here and call it a day.

```suggestion
        IResourceStore<TextureUpload> IStorageResourceProvider.CreateTextureLoaderStore(IResourceStore<byte[]> underlyingStore) => host?.CreateTextureLoaderStore(underlyingStore);
```

2020-12-21 18:52 UTC, bdach commented on osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
> +                : base(beatmapInfo, resources?.AudioManager)
Sort of confused by the null-check on `resources` there, especially seeing that the rest of this class assumes the converse, and the only caller of this ctor passes `this`. Would remove this null-check (and maybe annotate param as `[NonNull]`).

2020-12-21 18:53 UTC, bdach commented on osu.Game/Skinning/LegacySkin.cs
>          {
These are also a tiny bit confusing - public ctor can assume non-null `resources`, but protected can already have null `storage` and `resources`.

2020-12-22 03:02 UTC, peppy commented
@bdach regarding your comment on testing: is that important? if there's a null ref, it's going to fail in the test anyway. if you look at the previous code, we were already throwing around nulls (sometimes) and generally only providing implementations / instances where actually required by the test.

2020-12-22 05:17 UTC, bdach commented
Yeah as I said at the end there it's probably fine, the current state seems better than it was previously anyway.

2020-12-22 05:18 UTC, bdach approved these changes

2020-12-22 10:50 UTC, peppy commented
@smoogipoo can you take a quick look at this and make sure you're okay with the general structure?

2020-12-23 07:40 UTC, peppy commented
In discussion this is fine to go in for now.

2020-12-23 07:41 UTC, merged