Fix leaderboard showing score updates for quit users
ppy/osu pull request #11320
Opened 2020-12-26 03:13 UTC by peppy

The spectator data feed was not unbound if a user quit the room, meaning if they continued to join another room (or play solo) their now incorrect score was still showing up on the leaderboard.

This change unsubscribes and also shows quit users visually (via a tint of their panel to gray).

2020-12-26 12:24 UTC, bdach requested changes

2020-12-26 12:24 UTC, bdach commented on osu.Game/Screens/Play/HUD/GameplayLeaderboardScore.cs
> +                return;
Doing it this way has a quirk - if the user that quit was first on the leaderboard, their panel will still have a wider size, even as the user drops down in rankings naturally. I'd probably jam the "has quit" case in here (and rename the method, as it clearly does more than just update colour).

2020-12-26 12:24 UTC, bdach commented on osu.Game/Screens/Play/HUD/MultiplayerGameplayLeaderboard.cs
> +            // BindableList handles binding in a really bad way (Clear then AddRange) so we need to do this manually..
side note - `BindableList.Clear()` should maybe be raising a `NotifyCollectionChangedAction.Reset` on clear, although that's debatable. sort of unwieldy indeed.

2020-12-27 07:44 UTC, peppy commented
The asssert failing can be fixed by changing the `.Expire` i added to a forced `Remove` then `Dispose` (as below) but this is pretty ugly.

![image](https://user-images.githubusercontent.com/191335/103166162-b3795400-4862-11eb-839d-55c4135ee167.png)


I don't think there's actually much point in having this assert (and it could also fail of the scoring mode was changed, see `updateAllScores`) so i've opted to just remove it.

2020-12-27 12:03 UTC, bdach approved these changes

2020-12-27 12:35 UTC, merged