Fix menu button icon being stuck in a rotated position if no beatmap is playing
ppy/osu pull request #1139
Opened 2017-08-19 14:44 UTC by jorolf

2017-08-20 09:26 UTC, peppy commented
Pretty sure this won't fix the problem if the beatmap stops playing while a button is hovered

2017-08-20 11:52 UTC, jorolf commented
I would've tested it, but there's no way to do that right now. _Probably should've done it anyway_

2017-08-30 04:24 UTC, smoogipoo requested changes
As stated, this won't fix the case where music is stopped while the button is hovered, and also will break if the music starts while the button is hovered.

Closing this for now until further testing/implementation is done.

2017-08-30 04:24 UTC, smoogipooo commented on osu.Game/Graphics/Containers/BeatSyncedContainer.cs
> +        public bool BeatmapPlaying { get; private set; }
This should really be `AudioPlaying`.

2017-08-30 04:24 UTC, closed without merging