Fix multiplayer mod select showing autoplay as a choice
ppy/osu pull request #11528
Opened 2021-01-18 08:52 UTC by peppy

This is the first step towards fixing https://github.com/ppy/osu/issues/11293. Further checking is still required in `osu-server-spectator` (currently we are relying on `osu-web` for server-side checks, which only works for the initial game creation).

Just wanted to get this out to stop the sane case (where the user isn't trying to circumvent measures).

2021-01-18 21:34 UTC, bdach requested changes

2021-01-18 21:34 UTC, bdach commented on osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
> +        private bool isValidMod(Mod mod) => !(mod is ModAutoplay) && (mod as MultiMod)?.Mods.Any(mm => mm is ModAutoplay) != true;
This should probably be in `MatchSongSelect` to avoid the same scenario for the playlists mode.

2021-01-19 20:47 UTC, bdach commented
FWIW, resolving the above might be a good opportunity to do some clean-up with online song select screens (the playlists one is named `MatchSongSelect` and is in the wrong namespace, could extract a base `OnlineSongSelectSubScreen` or similar...) I had a shot at it but it came out a bit larger than I'm comfortable with pushing outright without discussion on whether that's the correct direction.

2021-01-20 12:02 UTC, smoogipoo commented
Let's do it locally for now. I'm not sure how it'll pan out in the future and what sort of parameters such a method will need - requirements are probably going to change a bit as the playlists system evolves.

2021-01-20 12:49 UTC, smoogipoo approved these changes

2021-01-20 12:49 UTC, merged