Sort SkinSection in alphabetical order
ppy/osu pull request #11536
Opened 2021-01-18 20:08 UTC by rednir

Excluding `<Random Skin>` and the built-in skins, all skins are sorted alphabetically as opposed to by date added. This matches behavior from stable, and it is much easier to find skins when you have a large amount.
Also, `<Random Skin>` makes more sense to be at the very top of the list imo.

This is my first PR so I realize I may have gone about doing this in the worst way possible.

2021-01-18 21:08 UTC, bdach requested changes
In addition to these comments, please see CI errors due to whitespace that does not adhere to our code convention.

2021-01-18 21:08 UTC, bdach commented on osu.Game/Overlays/Settings/Sections/SkinSection.cs
> -                Schedule(() => skinDropdown.Items = skinDropdown.Items.Where(i => !i.Equals(item)).Append(item).ToArray());
The `.Where(i => !i.Equals(item))` check has been incorrectly removed. `itemUpdated` is also fired on skin updates, not necessarily always additions.

2021-01-18 21:08 UTC, bdach commented on osu.Game/Overlays/Settings/Sections/SkinSection.cs
> +            skinsList.Insert(0, random_skin_info);
Several issues with this:

* This needlessly removes three items and reinserts them back to the start again, incurring unnecessary six linear operations on the entire list, while it should only be sorting the section of the list that this cares about (so user skins). `List<T>.Sort()` has an overload that takes an index and count.
* Due to the above this also wrongly pushes the `Random Skin` option to the top, while it intentionally used to be third in the order.

2021-01-19 14:06 UTC, rednir commented
Didn't use the `List<T>.Sort()` overload you mentioned because it required a parameter that kept returning a "user locale could change string comparison" error, so instead copied user skins to a new list and then sorted that. Should that be fine?

2021-01-19 17:32 UTC, rednir commented
Seems like I still can't use git properly. Should I do something about this commit spam?

2021-01-19 17:33 UTC, bdach commented
No need. I'm in the middle of applying changes to this branch anyways.

2021-01-19 18:38 UTC, bdach commented
I've made a few changes to this. I think I'm personally OK with how this looks now, but would appreciate a double-check on this to be sure.

@rednir make sure to read through the changes and the commit messages to see what was changed and why.

2021-01-19 18:39 UTC, bdach approved these changes

2021-01-19 19:04 UTC, rednir commented
I really appreciate the comments and your support, I'll definitely keep in mind these practices if I ever open another PR. Thanks!

2021-01-20 12:15 UTC, smoogipoo approved these changes

2021-01-20 12:49 UTC, merged

2026-02-28 15:32 UTC, fem-al-e commented
While renaming my skin collection today, I noticed that _lowercase letters are sorted separately_ from their uppercase variants, appearing at the bottom of SkinSection.

I couldn't find this being mentioned elsewhere, and I doubt that this is intended behavior, so I'm hoping that it's fine for me to bring it up here.

https://github.com/user-attachments/assets/041c394e-a756-46ac-9fe9-db5644b9540e

The list sorting order in the video above (excluding the default options) seems to be roughly:
1. Non-Alpha characters (here: dash)
2. Uppercase letters (A-Z)
3. More non-alpha characters (here: square brackets)
4. Lowercase letters (a-z)

I did not check for other non-alpha characters (numbers, curly brackets, parantheses etc.) yet.