Add custom MessagePack resolver for mod settings dictionary
ppy/osu pull request #11671
Opened 2021-02-03 10:58 UTC by peppy

This was failing until now (causing potential runtime crashes) when attempting to play with a mod that had adjusted settings (due to MessagePack now knowing how to serialises bindables).

Note that this is not in a working state. While the tests pass, it causes disconnections/errors at a server-side level which I am still investigating. I'm PRing this because I spent the good part of an hour investigating and I'm 99.99% sure there are no issues with my code.

```
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[2]
      Error when processing requests.
      System.IO.InvalidDataException: Reading array length for 'streamIds' failed.
       ---> System.InvalidOperationException: code is invalid. code:202 format:float 32
         at MessagePack.Decoders.InvalidArrayHeader.Read(Byte[] bytes, Int32 offset, Int32& readSize)
         at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.ReadArrayLength(Byte[] input, Int32& offset, String field)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.ReadArrayLength(Byte[] input, Int32& offset, String field)
         at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.ReadStreamIds(Byte[] input, Int32& offset)
         at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.CreateInvocationMessage(Byte[] input, Int32& offset, IInvocationBinder binder, IFormatterResolver resolver, Int32 itemCount)
         at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.ParseMessage(Byte[] input, Int32 startOffset, IInvocationBinder binder, IFormatterResolver resolver)
         at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
2021-02-03 10:46:19 [3504]: Disconnected
```

The exception points at the offset not being incremented correctly for the next read (`streamIds` is part of the parent object in signalr's messagepack message protocol), but I have confirmed that the returned `readSize` matches on serialisation and deserialisation of the same message, both at a client-client level and also client-server.

My next step will be to test after updating SignalR to see if it is actually a SignalR (or `Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol`) bug.

- Closes #11660

2021-02-03 11:01 UTC, peppy commented on osu.Game/Online/API/ModSettingsDictionaryFormatter.cs
> +                offset += readSize;
Note that this is a pretty shoddy API. It's improved in the newer version of messagepack. I've implemented this copying the way the official formatters are implemented in the previous version, as there is no direct documentation on the interface itself.

You can find examples here: https://github.com/neuecc/MessagePack-CSharp/blob/v1.7.3.7/src/MessagePack/Formatters/PrimitiveFormatter.cs / https://github.com/neuecc/MessagePack-CSharp/blob/v1.7.3.7/src/MessagePack.UnityShims/Formatters.cs

2021-02-03 11:02 UTC, peppy commented on osu.Game/Online/API/ModSettingsDictionaryFormatter.cs
> +                switch (MessagePackBinary.GetMessagePackType(bytes, offset))
During my investigation I found https://github.com/neuecc/MessagePack-CSharp/blob/v1.7.3.7/src/MessagePack/Formatters/PrimitiveObjectFormatter.cs, which can likely replace this code. I will update it to use this once I figure out what the cause of the remaining issue is.

2021-02-03 11:43 UTC, peppy commented
For reference, here's the 5.0 API, which is about 5 magnitudes nicer

https://github.com/ppy/osu/compare/master...peppy:fix-mod-settings-serlisation-signalr50?expand=1

2021-02-03 22:44 UTC, bdach commented
API is indeed pretty bare-bones, but the implementation looks all good as far as I can see. The index/offset math (worst part of all of this, probably) seems to check out.

2021-02-03 22:44 UTC, bdach approved these changes, later dismissed

2021-02-03 23:13 UTC, frenzibyte requested changes
`ModEasyWithExtraLives` is still suffering from this issue, as it defines a setting of type `BindableInt` which is not handled in the formatter here.

It all feels like bindable should expose an `object` value somehow, but given that it's been rejected multiple times for reasons I can't recall, going with switch cases is the way.

2021-02-04 06:11 UTC, peppy commented
I'm not going to update this PR because it still doesn't work. Will be testing against iOS today and PR the 50 version (https://github.com/ppy/osu/compare/master...peppy:fix-mod-settings-serlisation-signalr50?expand=1) if I can get everything working.

2021-02-04 06:51 UTC, peppy commented
Fixes have been applied on #11673.

Closing this as it doesn't work due to upstream bugs.

2021-02-04 06:51 UTC, closed without merging