Show a notification after a successful update
ppy/osu pull request #1168
Opened 2017-08-22 10:42 UTC by peppy

Allows access to the github changelog.

2017-08-22 12:20 UTC, smoogipoo requested changes

2017-08-22 12:20 UTC, smoogipooo commented on osu.Desktop/Overlays/VersionManager.cs
> +            if (char.IsNumber(version[0]) && version != lastVersion)
How about just using game.IsDeployedBuild?

2017-08-22 12:20 UTC, smoogipooo commented on osu.Desktop/Overlays/VersionManager.cs
> +                if (!string.IsNullOrEmpty(lastVersion))
Can we move this conditional outside of this if? SOmething like
```
if (string.IsNullOrEmpty(lastVersion))
    return;

if (game.IsDeployedBuild && version != lastVersion) { /* etc */ }
```

2017-08-22 12:20 UTC, smoogipooo commented on osu.Desktop/Overlays/VersionManager.cs
> +            State = Visibility.Hidden;
What's the point of setting state to hidden if it's just going to be set to visible in loadcomplete?

2017-08-22 12:20 UTC, smoogipooo commented on osu.Desktop/OsuGameDesktop.cs
>                      versionManager.State = Visibility.Visible;
Again, is there any point to setting visibility here given that it's going to be visible in loadcomplete?

2017-08-22 12:20 UTC, smoogipooo commented on osu.Game/Overlays/Notifications/SimpleNotification.cs
> +        private string text = string.Empty;
This is the default value.

2017-08-22 12:23 UTC, peppy commented on osu.Game/Overlays/Notifications/SimpleNotification.cs
> +        private string text = string.Empty;
default is null; causes a nullref

2017-08-22 12:24 UTC, peppy commented on osu.Desktop/Overlays/VersionManager.cs
> +            State = Visibility.Hidden;
actually hidden is the default state, so this is redundant.

2017-08-22 12:25 UTC, peppy commented on osu.Desktop/Overlays/VersionManager.cs
> +            if (char.IsNumber(version[0]) && version != lastVersion)
good point

2017-08-22 12:25 UTC, smoogipooo commented on osu.Game/Overlays/Notifications/SimpleNotification.cs
> +        private string text = string.Empty;
whoah. ok

2017-08-22 12:26 UTC, peppy commented on osu.Desktop/OsuGameDesktop.cs
>                      versionManager.State = Visibility.Visible;
yep, one of these is redundant. i left too many in (found a pretty serious bug with VisibleContainer - see framework PR)

2017-08-22 12:27 UTC, peppy commented on osu.Desktop/Overlays/VersionManager.cs
> +                if (!string.IsNullOrEmpty(lastVersion))
can do

2017-08-22 13:48 UTC, peppy commented on osu.Desktop/Overlays/VersionManager.cs
> +                if (!string.IsNullOrEmpty(lastVersion))
can't do; the set to config needs to only happen under the conditionals it is contained by

2017-08-22 14:51 UTC, smoogipooo commented on osu.Desktop/Overlays/VersionManager.cs
> +                if (!string.IsNullOrEmpty(lastVersion))
Right.

2017-08-23 01:19 UTC, smoogipoo approved these changes

2017-08-23 01:19 UTC, merged