Fix beatmap removed post-creation in multiplayer tests
ppy/osu pull request #11928
Opened 2021-03-01 08:44 UTC by smoogipoo

The main part of this is the addition of `GetOnlineBeatmapSet()`, which is overridden in tests to provide the given beatmap set.

2021-03-01 20:38 UTC, bdach requested changes

2021-03-01 20:38 UTC, bdach commented on osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
> +                    PlaylistItemId = apiRoom.Playlist.Last().ID
All multiplayer tests that join a room at start are failing on this (correctly) due to the playlist being empty. Honestly I'm not quite sure how it ever even worked in the first place. I think it didn't and the beatmap was shoved in at a later stage...?

2021-03-01 20:40 UTC, bdach commented
For what it's worth, something like the following diff seems to resolve *most* failures:

```diff
diff --git a/osu.Game/Tests/Visual/Multiplayer/MultiplayerTestScene.cs b/osu.Game/Tests/Visual/Multiplayer/MultiplayerTestScene.cs
index 2e8c834c65..7775c2bd24 100644
--- a/osu.Game/Tests/Visual/Multiplayer/MultiplayerTestScene.cs
+++ b/osu.Game/Tests/Visual/Multiplayer/MultiplayerTestScene.cs
@@ -7,8 +7,10 @@
 using osu.Framework.Graphics;
 using osu.Framework.Graphics.Containers;
 using osu.Game.Online.Multiplayer;
+using osu.Game.Online.Rooms;
 using osu.Game.Screens.OnlinePlay;
 using osu.Game.Screens.OnlinePlay.Lounge.Components;
+using osu.Game.Tests.Beatmaps;
 
 namespace osu.Game.Tests.Visual.Multiplayer
 {
@@ -48,7 +50,16 @@ protected MultiplayerTestScene(bool joinRoom = true)
             RoomManager.Schedule(() => RoomManager.PartRoom());
 
             if (joinRoom)
+            {
+                Room.Name.Value = "test name";
+                Room.Playlist.Add(new PlaylistItem
+                {
+                    Beatmap = { Value = new TestBeatmap(Ruleset.Value).BeatmapInfo },
+                    Ruleset = { Value = Ruleset.Value }
+                });
+
                 RoomManager.Schedule(() => RoomManager.CreateRoom(Room));
+            }
         });
 
         public override void SetUpSteps()
```

`TestSceneMultiplayerRoomManager` also needs similar logic. Also the name specification is mandatory as-is, otherwise `MultiplayerRoomSettings` dies on a nullref.

2021-03-02 08:23 UTC, peppy commented
Is this aiming to fix a test failure somewhere?

2021-03-02 08:36 UTC, bdach commented
The above patch is intended as a proposal on how to fix the test failures, yeah.

2021-03-02 17:45 UTC, bdach commented
There are still remaining test failures that I'd indicated would be there (in `TestSceneMultiplayerRoomManager`) but I'm frankly too lost in the structure to be sure what's going wrong. From what I can tell even populating the new created rooms in that test doesn't help. `apiRoom` still ends up being without a playlist.

I'm not even entirely sure why for example `TestMultiplayerRoomJoinedWhenAPIRoomJoined` is named that exactly.

2021-03-03 03:12 UTC, peppy commented
I meant the PR in general, rather than the diff. Wondering if this came up in some future use case or if it's the result of a CI failure somewhere. Lacking context.

2021-03-03 10:10 UTC, smoogipoo commented
It was originally intended to improve the testability, but I'm not using it anymore. I noticed that when the match is created (e.g. in `TestSceneMultiplayerMatchSubScreen`), the beatmap is not displayed in the panel in the room, because it was being cleared via https://github.com/ppy/osu/blob/8a660b2bf545d886412be1b114f0c9041e661b06/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs#L512-L514 and then the retrieve beatmap request was failing.

2021-03-03 19:50 UTC, bdach commented
I think this change is nice to have. I did notice before that the beatmap was disappearing in the tests but chose to ignore it in favour of other things. Definitely good to have the multi tests behave the same way the real thing does in my book.

2021-03-03 19:50 UTC, bdach approved these changes

2021-03-04 01:29 UTC, smoogipoo commented
For the most part you can go through an entire multi lobby in `TestSceneMultiplayer`, at least up until the results screen which you can't exit because there's no back button >_>

2021-03-04 14:43 UTC, peppy approved these changes
Looks logical enough

2021-03-04 14:43 UTC, merged