Move frame-handling spectator logic into abstract base class
ppy/osu pull request #12254
Opened 2021-04-01 13:55 UTC by smoogipoo

The current `Spectator` screen is quite inextensible since the UI logic is very coupled to the frame-handling business logic.

In this PR, the business logic has been moved to a base `SpectatorScreen` class. This class handles an arbitrary number of users, and exposes three methods:
1. `OnUserStateChanged` which is invoked when a spectate state changes. This is used to show the beatmap panel in the solo spectator.
2. `StartGameplay` which is invoked when a spectated user begins playing _and_ the client is able to play the map.
3. `EndGameplay` which is invoked when a spectated user stops playing.

There will be a `MultiplayerSpectator` screen inheriting from this that provides more custom logic and shares none of the UI logic of the current `Spectator` screen. Current implementation can be found in https://github.com/smoogipoo/osu/blob/multiplayer-spectate/osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiplayerSpectator.cs

2021-04-01 14:04 UTC, smoogipoo commented on osu.Game/Screens/Spectate/SpectatorScreen.cs
> +                    convertibleFrame.FromLegacy(frame, gameplayState.Beatmap.Beatmap);
While refactoring this, I also noticed that this line is completely wrong. The logic hasn't changed but the method expects the playable beatmap at this point (see: `ManiaReplayFrame`).

It's just good to know at this point - I'm unsure exactly how to handle this yet, but it'll be fixed in some future PR.

2021-04-02 08:05 UTC, peppy requested changes
Seems pretty logical overall, just a few questions

2021-04-02 08:06 UTC, smoogipoo commented on osu.Game/Screens/Spectate/SpectatorScreen.cs
> +        private readonly object stateLock = new object();
not really because this is a screen, so it may stop getting updated at some point :/

2021-04-02 08:08 UTC, peppy commented on osu.Game/Screens/Spectate/SpectatorScreen.cs
> +        private readonly object stateLock = new object();
Is that specifically for the disposal case? If so, can't we gaurantee that locking isn't required at that point?

2021-04-02 08:08 UTC, smoogipoo commented on osu.Game/Screens/Spectate/SpectatorScreen.cs
> +        private readonly object stateLock = new object();
No, screens stop updating when a subscreen is pushed, like the player in solo-spectator case.

2021-04-02 08:09 UTC, peppy commented on osu.Game/Screens/Spectate/SpectatorScreen.cs
> +        private readonly object stateLock = new object();
Oh... right.

I guess this is why there was the lock logic in the previous iteration as well. I think it's fine to leave as-is, but definitely should have a comment attached explaining the reasoning, as this likely won't be the last time I question why it's there.

2021-04-02 12:29 UTC, smoogipoo commented on osu.Game/Screens/Spectate/SpectatorScreen.cs
> +        private readonly object stateLock = new object();
Comment added.

2021-04-02 12:47 UTC, smoogipoo commented
I've made a few more changes to this - scheduling all the abstract callbacks since they're scheduled in every case and otherwise it's a bit of a hidden detail that you're on the async context.

In the process I noticed a potential edge case where the callbacks could happen _after_ `OnResuming()` is called, so the pending beatmap won't be updated in time. The existing test says this scenario works fine because it hits the `attemptStart` inside `StartGameplay`, but it's just a little bit too flimsy for me because the callback does indeed happen after `OnResuming()` - I believe there may be a timing-dependent case where it could break if gameplay is restarted during the initial screen suspension.

Hopefully the new code is more readable.

2021-04-03 08:23 UTC, peppy approved these changes

2021-04-03 08:23 UTC, merged