Add missing author links in Beatmap Details
ppy/osu pull request #12488
Opened 2021-04-19 15:08 UTC by Denrage

Closes #7518 

SongSelect
https://user-images.githubusercontent.com/22132579/115258697-81ea0880-a131-11eb-873e-dc4256933fb8.mp4

BeatmapSetOverlay
https://user-images.githubusercontent.com/22132579/115258770-9201e800-a131-11eb-9551-fe9b7b651e1a.mp4

If there are other places where the author link is missing, let me know

2021-04-19 15:10 UTC, bdach commented
[This has the exact same issue that the previous attempt at this had](https://github.com/ppy/osu/pull/7540#discussion_r376642332) in that the link doesn't change colour when hovered on the beatmap wedge.

2021-04-19 15:16 UTC, bdach requested changes
in addition to the above

2021-04-19 15:16 UTC, bdach commented on osu.Game/Screens/Select/BeatmapInfoWedge.cs
> +                                Children = new[] { getMapper(metadata) },
```suggestion
                                Child = getMapper(metadata),
```

2021-04-19 15:16 UTC, bdach commented on osu.Game/Screens/Select/BeatmapInfoWedge.cs
> +                    return new LinkFlowContainer();
```suggestion
                    return Empty();
```

\+ change return type of method to `Drawable`

2021-04-19 18:22 UTC, Denrage commented
Does an issue exists which describes the goal splitting up the BufferedWedgeInfo? @bdach

2021-04-19 20:25 UTC, bdach commented
I don't believe so, no. Not everything has to be a separate issue.

2021-05-07 05:33 UTC, peppy approved these changes

2021-05-07 20:41 UTC, merged