[WIP] Online beatmap set overlay
ppy/osu pull request #1253
Opened 2017-09-13 01:12 UTC by DrabWeb

![screen shot 2017-09-12 at 10 09 41 pm](https://user-images.githubusercontent.com/6215387/30355051-21ae486e-9807-11e7-968b-d92fbb9b8d7e.png)

API integration coming in a follow up PR.

WIP because I can't figure out for the life of me why `BeatmapTile` won't update the bindable.

2017-09-13 06:49 UTC, peppy commented
A few visual issues I noticed:

- Would be nice if the stats tween like they do on the BeatmapDetails display, rather than starting from zero (https://streamable.com/9q39c)
- Success rate appears from wrong side when loading a new beatmap (https://streamable.com/0rvn2)
- Appear animation for video/novideo buttons feels a bit weird (https://streamable.com/g1xb2)
- Weird button effect when loading a new beatmap (https://streamable.com/dbh0n)

2017-09-13 21:26 UTC, DrabWeb commented
https://streamable.com/mpbxz

2017-09-14 09:32 UTC, peppy commented on osu.Game/Overlays/OnlineBeatmapSet/PreviewButton.cs
> +                preview = audio.Track.Get(BeatmapSet.OnlineInfo.Preview);
this needs to be done asynchronously. currently it causes hard blocking on the update thread.

i'd possibly consider only loading it when the play button is hit.

2017-09-14 11:12 UTC, peppy requested changes
Fix synchronous preview loading logic

2017-09-25 09:57 UTC, peppy commented
Why is there a `User` inside `BeatmapSetOnlineInfo`? I'm pretty sure this isn't the correct place for it.

2017-09-26 01:17 UTC, peppy approved these changes

2017-09-26 01:17 UTC, merged

2017-09-26 01:19 UTC, peppy commented
Would like to offer a bounty of $500 for this feature. Please reach out via email or discord DM to claim.