Add method to safely refresh DrawableHitObject transforms
ppy/osu pull request #12585
Opened 2021-04-26 18:22 UTC by LumpBloom7

`DrawableHitObject`s have overridden `ClearTransforms` and `ApplyTransformsAt` methods to prevent unintended screwing up of transforms. This is problematic for DHOs that need to account for user-adjustable transform parameters (e.g note animation speed), 

Previously, a workaround that could be used to refresh animations was to call `updateState(State.Value, true)` indirectly via `SkinChanged(SkinSource)`, but the latter method was removed in #12500. 

This PR adds a method `RefreshStateTransforms` that removes and reapplies all transforms, that could be called should the need to do so arises.

2021-04-26 18:35 UTC, frenzibyte approved these changes, later dismissed
Sounds good.

2021-04-27 08:07 UTC, smoogipoo requested changes

2021-04-27 08:07 UTC, smoogipoo commented on osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
> +        /// This also takes in account potential overrides defined in <see cref="ApplyCustomUpdateState"/>.
This comment is quite duplicated imo.

```suggestion
        /// Reapplies the current <see cref="ArmedState"/>.
```

2021-04-27 10:14 UTC, peppy approved these changes

2021-04-27 10:15 UTC, merged