Update `ComboCounter` components to use DI to attach data source
ppy/osu pull request #12670
Opened 2021-05-03 08:52 UTC by peppy

This is the first of a few updates to how HUD components consume their data sources.

Starting with just one so I can make sure everyone is happy with the direction before converting the rest. I've tested this to work with skin editing and component toolbox as expected.

2021-05-03 08:53 UTC, peppy commented on osu.Game/Screens/Play/HUDOverlay.cs
> +        protected SkinnableHealthDisplay CreateHealthDisplay() => new SkinnableHealthDisplay();
These will eventually be dismantled; just leaving in place for the time being (need to plan where these "defaults" will sit going forward).

2021-05-03 08:54 UTC, peppy commented on osu.Game/Screens/Play/HUD/SkinnableComboCounter.cs
> +    public class SkinnableComboCounter : SkinnableDrawable
I left this class in place as it feels cleander than shoving the `base()` spec inline at usages.

2021-05-03 10:01 UTC, bdach requested changes
No issues in principle with the approach here. Just a few tangential things to clean up maybe.

2021-05-03 10:13 UTC, peppy commented on osu.Game/Screens/Play/HUD/SkinnableComboCounter.cs
> +    public class SkinnableComboCounter : SkinnableDrawable
Can remove if that's what we decide on, sure.

2021-05-08 03:46 UTC, frenzibyte commented
I think this is in a pretty good state and direction, but I only have one slight issue with this, which is that `ScoreProcessor` is currently completely exposed to the skinnable elements in a mutable state, whereas it could be exposed as read-only instead via an `IScoreProcessor` interface.

2021-05-08 15:06 UTC, bdach commented
Yeah I could get behind `IScoreProcessor`. Not sure whether it should be a thing in this PR or a separate one, but it'd be nice to have it in these usages.

2021-05-08 17:03 UTC, bdach commented
Actually, looking at other usages of `ScoreProcessor` again, there are other components (`HitErrorDisplay`, `BreakTracker`, `MultiplayerGameplayLeaderboard`) that also receive a direct mutable reference to a `ScoreProcessor` without needing it to be mutable. So if this PR was to add an encapsulating interface, all of those should be using it too, which in my mind makes this a larger code quality change, out of scope of this one. So while I don't disagree with that direction I'm going to go ahead and approve this.

2021-05-08 17:03 UTC, bdach approved these changes

2021-05-08 17:06 UTC, frenzibyte commented
Well, those components are explicitly getting it from constructor (`HitErrorDisplay` is a special case since that reference already has that removed in #12708), but yeah I don't see any problem in merging this and considering that a code-quality issue to be resolved in a separate PR. (after all the PRs in the chain have been merged)

2021-05-08 17:06 UTC, frenzibyte approved these changes

2021-05-08 17:57 UTC, merged