Don't show warning screen when registering on dev server
ppy/osu pull request #12857
Opened 2021-05-18 21:26 UTC by Joehuu

2021-05-18 21:28 UTC, Joehuu commented
Didn't see the `load()` method have `OsuGame`. Will put out.

2021-05-19 02:07 UTC, peppy commented
The problem with making changes like this is it means this flow will never get tested by devs any more.

I'm not sure if we want to do this or not. That said, I'm pretty neutral on the issue so will wait for further opinions.

2021-05-19 04:35 UTC, smoogipoo commented
I'm pretty neutral on this too, but I don't think the "never get tested by devs any more" argument is super valid. I don't need to create any more accounts so can't confirm that this screen will never break, but also this doesn't apply in tests (due to the `OsuGame` dependency that doesn't exist in tests) and I think this is better tested there.

2021-05-19 04:37 UTC, frenzibyte commented
This might be a duplicate of what's said above, but, writing a test scene for this that goes through the registering flow and ensuring the right screen is pushed would do better I think.

I'm not really fussed with hiding the warning screen, but I think this is the right job for test scenes.

2021-05-19 19:59 UTC, bdach requested changes
I *also* don't really have a strong opinion on this - I suppose I am weakly in favour of doing this, to avoid answering the same questions from new contributors about this dialog in context of the dev environment. But I *do* think this ought to have comprehensive tests - as to why, see suggestion below, which was not caught.

2021-05-19 19:59 UTC, bdach commented on osu.Game/Overlays/AccountCreation/ScreenWarning.cs
> +            if (string.IsNullOrEmpty(api?.ProvidedUsername) || game.UseDevelopmentServer)
If nullability of `game` is to be allowed (which it wasn't before), then this should be

```suggestion
            if (string.IsNullOrEmpty(api?.ProvidedUsername) || game?.UseDevelopmentServer)
```

lest it crash on a `null`.

2021-05-20 04:20 UTC, peppy approved these changes

2021-05-20 05:05 UTC, merged