Add multiplayer room music dimming option
ppy/osu pull request #13224
Opened 2021-05-27 22:39 UTC by OliBomby

Closes #13173

- Added settings slider "Music (multiplayer room)" (default value is 100%).
- Added a BackgroundTrackManager for handling muting/dimming of the music track.
- The multiplayer room screen now dims the music track by the amount defined in the settings.
- Updated PreviewTrackManager to mute the music track using BackgroundTrackManager and added a 100ms transition.

2021-05-28 05:26 UTC, ekrctb requested changes
I left only nits. Looks like a nice implementation.
Not sure what is going on on the commit history (duplicated commits?)

2021-05-28 05:26 UTC, ekrctb commented on osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
> +            return base.OnExiting(next);
Factor out code duplication.

2021-05-28 05:26 UTC, ekrctb commented on osu.Game/Audio/PreviewTrackManager.cs
>          [Resolved]
`muteBindable` field can be removed.

2021-05-28 06:44 UTC, bdach commented
Just so this doesn't go by unsaid, I still disagree with having this as a separate setting, and the descriptions are now actively confusing. There are:
* Master
* Master (window inactive)
* Effect
* Music
* Music (multiplayer room)

I think it's quite messy and nigh indecipherable. And it also runs the risk of someone saying that we need another 3 sliders for another 3 screens. I still think it should really either happen on its own always without a setting (opinionated choice) or be a part of the master (inactive) setting, and the user can potentially decide where the dim is applied.

2021-05-28 06:46 UTC, peppy commented
Agree, undecided on which of the proposed directions is better.

Curious why this PR was made before discussion had reached any kind of consensus. I haven't read any of the code and don't intend to until the proposed behaviour is unanimously agreed on.

2021-05-28 14:26 UTC, OliBomby commented
I got a bit cocky and made a PR too early. I wrongly thought the discussion reached enough of a consensus to make a PR. Should I close this PR and come back when a consensus is reached or can I leave it here?

What bdach said about the risk of needing another 3 sliders for another 3 screens is right, so I changed my mind. I think it's best if there is a way to configure volume dimming for each screen individually but without using the settings overlay (maybe the volume overlay is good for this?). 

Using the inactive dim setting seems like a worse option, because how are you gonna explain that it controls the master volume dimming for inactive window and controls the music volume for X other screens. That makes everything much more complicated imo.

2021-05-31 02:37 UTC, smoogipoo commented
Closing as there's still a lot of differing opinions, direction is not clear yet, and this is a low priority issue for us.

2021-05-31 02:37 UTC, closed without merging