Preparation for pending localisation
ppy/osu pull request #13911
Opened 2021-07-17 11:42 UTC by kj415j45

2021-07-17 12:04 UTC, bdach requested changes

2021-07-17 12:04 UTC, bdach commented
In addition to the above, this PR does not even build. There are build errors in tests that need resolving after the adjustments made to the game components.

2021-07-17 12:57 UTC, huoyaoyuan commented on osu.Game/Graphics/UserInterface/OsuTabControl.cs
> +                        },
I'm just curious about the reason that you don't use it. The debugger support has been improved since initial release.

2021-07-17 13:20 UTC, bdach commented on osu.Game/Graphics/UserInterface/OsuTabControl.cs
> +                        },
@huoyaoyuan We've been over this once before at https://github.com/ppy/osu/pull/7269. The reasoning hasn't changed.

2021-07-17 13:42 UTC, bdach commented
Not sure why I was given authorship credit for some of these changes. That's not normal operating procedure.

2021-07-18 00:51 UTC, frenzibyte approved these changes
Not sure if what happened in the commit history above is fine, but code seems correct.

2021-07-18 11:04 UTC, bdach commented
I'm willing to let it slide this time, but I have set up gpg commit signing going forward and I would very much ask @kj415j45 to never push changes that are incorrectly attributed to me again.

2021-07-18 11:16 UTC, bdach approved these changes

2021-07-18 17:09 UTC, peppy approved these changes

2021-07-18 17:09 UTC, merged