Create `Catcher` in `CatchPlayfield`, not `CatcherArea`
ppy/osu pull request #13934
Opened 2021-07-19 12:03 UTC by ekrctb

In my view, the `CatcherArea` type is only a "container" type, and should only weakly coupled to the contents (the catcher).
The extra constructor chain was always a bit cumbersome when writing testing for example.

`DroppedObjectContainer` is passed via constructor instead of DI. This effectively reverts my PR #13648.
It is now just one level deep, so it is not beneficial to use DI here anymore.

2021-07-19 18:28 UTC, bdach commented
I feel like I've seen these catcher components go back and forth so many times that I'm not really comfortable approving any "code quality" changes in this area that seem to have no discernible end goal. Especially that - as stated in the OP - this PR essentially reverts another "code quality" pull.

2021-07-20 04:34 UTC, smoogipoo submitted a review, later dismissed
I have a different perspective on code quality changes. These days, if there are no issues pointed out, I'm willing to let them pass in order to keep our backlog small and reduce total time wasted (out of sight, out of mind).

2021-07-20 05:29 UTC, peppy requested changes

2021-07-20 05:29 UTC, peppy commented on osu.Game.Rulesets.Catch/UI/CatcherArea.cs
> +        public Catcher MovableCatcher
I'm not against this, but I think there should be xmldoc, probably on the `CatcherArea` class explaining that a catcher needs to be set on this property in order for things to work. That said, is there a reason this isn't in the `ctor` args?

Also, shall we rename this to `Catcher`? I'm not sure `MovableCatcher` adds anything any more..

2021-07-21 09:00 UTC, peppy approved these changes

2021-07-21 09:43 UTC, merged