Playsongselect design tweaks
ppy/osu pull request #141
Opened 2016-11-06 10:27 UTC by grafitter

Added a back button
Play button is being disposed when there is no beatmaps present
Selected track is used as a background
Wedge is no longer overlapping with other containers

Overlapping :
![3](https://cloud.githubusercontent.com/assets/8558077/20036817/57727620-a413-11e6-90c9-d9230f998252.PNG)

Fixed :
![4](https://cloud.githubusercontent.com/assets/8558077/20036816/54333256-a413-11e6-8daa-081da328a9ab.PNG)

The whole thing :
![5](https://cloud.githubusercontent.com/assets/8558077/20036818/5a0c3f1a-a413-11e6-8b0e-e146e1a132da.PNG)

2016-11-06 10:32 UTC, peppy commented
that's not how backgrounds should be initialised. you need to use the CreateBackground logic.

2016-11-06 11:40 UTC, UselessToucan requested changes
Disposing playButton looks questionable.

2016-11-06 11:40 UTC, UselessToucan commented on osu.Game/GameModes/Play/PlaySongSelect.cs
> +            if (database.Query<BeatmapSetInfo>().Count() > 0)
Use `Any` instead of `Count() > 0`

2016-11-06 11:40 UTC, UselessToucan commented on osu.Game/GameModes/Play/PlaySongSelect.cs
> +            else playButton.Dispose(); // not sure about this
I think you should just hide the button instead of disposing it.

2016-11-06 11:40 UTC, UselessToucan commented on osu.Game/GameModes/Play/PlaySongSelect.cs
> +                    Size = Vector2.One,
Not sure that we need to specify Size here. As far as I understand, RelativeSizeAxes should be enough.

2016-11-07 02:58 UTC, peppy commented on osu.Game/GameModes/Play/Player.cs
> +            background = new BackgroundModeCustom(Beatmap.Background);
this ain't gonna work as you want it to.. are you on discord so i can explain it to you?

2016-11-07 08:19 UTC, UselessToucan requested changes

2016-11-07 08:19 UTC, UselessToucan commented on osu.Game/GameModes/Play/PlaySongSelect.cs
> +            else playButton.Hide();
As far as I can see, there is no way to restore playButton's visibility. I guess .Show() should be called somewhere(for example, in the if block above).

2016-11-07 23:15 UTC, SirCmpwn commented
:+1: visually, taking a look at the code

2016-11-07 23:17 UTC, SirCmpwn commented
LGTM :+1:

2016-11-07 23:20 UTC, peppy reviewed
the play button show/hide code isn't going to work going forward. please consider all scenarios before implementing something that only works in one particular use case

2017-01-29 06:21 UTC, closed without merging