Correct icons in beatmap details
ppy/osu pull request #14321
Opened 2021-08-15 21:17 UTC by danielkariv

In relation to #13968. 
Replacing incorrect icons in beatmap details panel to correct ones from BeatmapStatisticsIcon class.

Old:
![image](https://user-images.githubusercontent.com/38776931/129493071-e460428f-ad99-41ae-b640-8155a56156f7.png)

New:
![image](https://user-images.githubusercontent.com/38776931/129493111-2f927853-26e0-45b7-9a53-e0790d9c6c94.png)

2021-08-15 21:21 UTC, frenzibyte commented
Missing the rings around the icon, see [osu!web](https://osu.ppy.sh/beatmapsets/1271180#osu/2727386):
![CleanShot 2021-08-16 at 00 20 30](https://user-images.githubusercontent.com/22781491/129493268-df5eaada-e366-4618-a18c-3983d1a17dd4.png)

2021-08-15 21:21 UTC, frenzibyte requested changes, later dismissed
As per above. Also inconsistent code style, starting bracket (`{`) should be in its own line, see surrounding code.

2021-08-15 21:44 UTC, danielkariv commented
Okay, fixed the styling of the icons.
<img width="321" alt="image" src="https://user-images.githubusercontent.com/38776931/129493697-d0acf0f5-b4ed-4bfc-96fb-6f47fd6f3f0e.png">

2021-08-16 01:36 UTC, smoogipoo approved these changes
lgtm, thanks!

2021-08-16 02:05 UTC, merged