Don't select random beatmap when previous was filtered
ppy/osu pull request #14499
Opened 2021-08-25 19:06 UTC by LittleEndu

* Supersedes #8384 (deleted my previous fork so can't push there)

This PR will not let carousel root use a random selection when previous selection is filtered and instead makes it use the default selection (the default is `GetNextToSelect()`). I think this is preferred, because when the user doesn't explicitly randomize the carousel then the selection should be near the previous one (so the user wouldn't need to scroll back to where their previous selection was after carousel selected a random beatmap)

The diff for tests looks weird, but I'm actually changing out the test completely.

As per [peppy's comment](https://github.com/ppy/osu/pull/8384#discussion_r547059703) readability of `GetNextToSelect()` has been improved. The code that figures out the distance to next beatmap now only counts filtered beatmaps, but that means using `.SkipWhile(pred + counting)` instead of `.FirstOrDefault(pred)` which sounds like a performance concern. Although we can afford `GetNextToSelect()` being a bit slow to perform because carousel only ever calls it eagerly when it loses its selection (which can only happen during filter changes).

2021-08-31 16:21 UTC, peppy requested changes

2021-08-31 16:21 UTC, peppy commented on osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
> +        public void TestCarouselSelectsNextWhenPreviousIsFiltered(int makeThisManyGroups, int haveThisManySetsInGroup)
This isn't how we name variables

`groupCount` and `setsPerGroup` would work better.

2021-08-31 16:22 UTC, peppy commented
I'm still waiting on more feedback from others regarding whether this is the UX we want, but I've also noticed that the tests don't even cover the new behaviour you've added. You'd want to add a test showing how your change "remembers" previous search history in a potentially unexpected way.

Are you waiting for feedback before adding test coverage or is this an oversigth?

2021-08-31 17:07 UTC, LittleEndu commented
Just to make sure peppy, are you commenting on the right PR? I have two PR changing carousel behaviour open, this is the one which changes behaviour when applying a new filter, the other (https://github.com/ppy/osu/pull/14572) is the one changing behaviour when returning to old filters.

Pretty sure my tests from 2020 are testing the new behaviour of carousel root not selecting randomly anymore. But I wrote them in 2020 so I don't remember.

2022-08-26 10:35 UTC, peppy commented
@LittleEndu I still generally agree with the premise of this change, but the tests are impossible to understand. I've brought the code to a compiling state, but the tests don't work.

If you're still interested, please rewrite the tests with comments (and required fixes) and either reopen this PR or open a fresh one.

2022-08-26 10:35 UTC, closed without merging