Add Beatmaps Section in the Profile Overlay [WIP]
ppy/osu pull request #1465
Opened 2017-11-03 23:12 UTC by EVAST9919

Pr'ing for a review

2017-11-06 04:28 UTC, smoogipoo requested changes

2017-11-06 04:28 UTC, smoogipoo commented on osu.Game/Online/API/Requests/GetUserBeatmapsRequest.cs
> +        protected override string Target => $@"users/{userId}/beatmapsets/{type.ToString().ToLower()}?offset={offset}";
Instead of this, I'd like to see the type stored as a string privately with the correct casing/styling, and the enum with CamelCase.

2017-11-07 07:41 UTC, peppy commented on osu.Game/Online/API/Requests/GetUserBeatmapsRequest.cs
> +                case BeatmapSetType.Favourite:
can we not just do this correctly as i described in discord?

add nuget package [Humanizer](https://www.nuget.org/packages/Humanizer) and use extension method `.Underscore()` directly in the `Target` string property

2017-11-09 10:51 UTC, smoogipoo submitted a review, later dismissed
In general I'm pretty okay with this.

I disagree with @peppy that Humanizer is required for the request - it should be hardcoded imo, but I'm not super stingy on this as I recognise a potential need for Humanizer in other areas.

PaginatedContainer definitely needs a lot of work, but that goes beyond the scope of this PR imo -- the manual showing/hiding of the button/loading animation is weird, and the container's size flickers when the "Show More" button is pressed.

One minor issue, but other than that I think this looks good to go.

2017-11-09 10:51 UTC, smoogipoo commented on osu.Game/osu.Game.csproj
> +      <HintPath>..\packages\Humanizer.Core.2.2.0\lib\netstandard1.0\Humanizer.dll</HintPath>
This should use `$(SolutionDir)\packages\`

2017-11-13 11:02 UTC, peppy approved these changes

2017-11-13 12:16 UTC, merged