Fix random/target mods not working in spectator
ppy/osu pull request #14739
Opened 2021-09-14 08:28 UTC by smoogipoo

Fixes https://github.com/ppy/osu/issues/13751

I tried writing a test for this, but `TestSceneSpectator` currently works without instantiating the "playing" player which bypasses this whole `BeginPlaying` pathway. Making it work requires significant work so I'm excluding it for now.

2021-09-14 19:56 UTC, bdach commented
Failing tests need attention here. The obvious solutions are to either ensure that all tests have `ScoreInfo` populated correctly (the beatmap in particular), or make `SpectatorClient` tolerant towards that by allowing null `ScoreInfo.Beatmap` and falling back to the provided `GameplayBeatmap` if so.

The former seems like a better solution given `Player` ensures that these properties are populated before `PrepareReplay()`, but I'm not 100% on that so I'll leave the decision up to you.

2021-09-15 04:36 UTC, peppy requested changes

2021-09-15 04:36 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecording.cs
> +                                ScoreInfo = { Beatmap = new TestBeatmap(new OsuRuleset().RulesetInfo).BeatmapInfo }
Any reason for not using the already constructed beatmap? Seems to work okay (requires removing some using statements).

```suggestion
                                ScoreInfo = { Beatmap = gameplayBeatmap.BeatmapInfo }
```

2021-09-15 04:36 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestSceneSpectatorPlayback.cs
> +                : base(new Score { ScoreInfo = { Beatmap = new TestBeatmap(new OsuRuleset().RulesetInfo).BeatmapInfo } })
```suggestion
                : base(new Score { ScoreInfo = { Beatmap = new BeatmapInfo() } })
```

Above can also use this if deemed more appropriate, just feels better as it's not actually meaningful for this test to make a full `TestBeatmap`.

2021-09-15 04:36 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecorder.cs
> +                                ScoreInfo = { Beatmap = new TestBeatmap(new OsuRuleset().RulesetInfo).BeatmapInfo }
```suggestion
                                ScoreInfo = { Beatmap = gameplayBeatmap.BeatmapInfo }
```

2021-09-15 04:55 UTC, peppy approved these changes

2021-09-15 05:15 UTC, merged