Preserve current time and clipboard contents when switching between difficulties
ppy/osu pull request #14737
Opened 2021-09-13 19:46 UTC by bdach

As suggested in https://github.com/ppy/osu/pull/14640#issuecomment-914078373.

https://user-images.githubusercontent.com/20418176/133144192-a07a99d3-70cc-480b-9b4b-4f1b4a677820.mp4

Obviously these two pieces of state listed in the title aren't the only ones that should ever get transferred, they were just the easiest/most obvious to move over. The main point is adding the mechanism that facilitates this (which is achieved by passing `EditorState`). Clipboard does not work cross-ruleset for simplicity/prevention of crashes.

79d0f48 also includes a nullcheck to an existing unprotected `GetClipboard()` usage (which is the only game-side usage), as a follow-up to my framework change at https://github.com/ppy/osu-framework/pull/4769. Removing it won't actually fail/crash the test now that I'm using `EditorTestScene` and its `Copy()`/`Paste()` methods directly, but I figured I might as well keep that change here to get it out of the way before the framework bump.

2021-09-14 01:16 UTC, smoogipoo requested changes

2021-09-14 01:16 UTC, smoogipoo commented on osu.Game/Screens/Edit/EditorLoader.cs
> +        public EditorState State;
Does this need to be publicly settable?

2021-09-14 01:24 UTC, bdach commented on osu.Game/Screens/Edit/EditorLoader.cs
> +        public EditorState State;
It was not supposed to be. Will fix.

2021-09-14 14:43 UTC, peppy commented
Took the liberty of making some changes here:

- Removed nullability from the `EditorState` properties. It didn't seem like we need it, and in general I think the goal is to avoid using nullables wherever possible
- Updated the xmldoc in `EditorState` to not be specific to difficulty switching. I'm thinking we may want to use this in other scenarios, and it read a bit better this way I think?
- Removed the upwards call on `loader`, instead having `EditorLoader` do a state restore call on the editor. Want to try and keep calls going downwards where possible (even though a couple of the other calls on `loader` are fine due to how much of a closed system that is).

Felt easier to push these rather than review feedback, lemme know if you disagree with any of the changes.

2021-09-14 18:05 UTC, bdach commented
I'm okay with the changes.

Making the restore operation public and calling it from the loader is more of a lateral change to me rather than a straight-up improvement - while it does allow keeping `EditorLoader.state` private, it also splits the store/restore operations apart in source (I liked how they were next to each other, and always done inside the editor) and adds a schedule to enforce proper operation ordering (i.e. that the restore doesn't run before `OnEntering()`). But as stated I don't necessarily think any of that is a problem.

2021-09-14 18:11 UTC, peppy commented
I'd almost push for the retrieval of the state to also be done in `EditorLoader` as well, but that's probably best left until we see more usage around this area.

2021-09-14 18:17 UTC, bdach commented
Sure, I'd likely have to keep a reference to the last-pushed editor in the loader to do that but it sounds doable. I'll leave it as is here but do it as a follow-up on request / if I feel it will work better with some future upcoming changes.

2021-09-15 03:38 UTC, peppy approved these changes

2021-09-15 03:38 UTC, merged