Fix usages of `SettingsTextBox` having `null` as the default
ppy/osu pull request #14935
Opened 2021-10-02 12:50 UTC by Susko3

Discussed in https://github.com/ppy/osu/issues/5124#issuecomment-930743828.

These are all the usages I could find in `osu`. There could possible be more in dependents of `osu` (eg. custom rulesets), but I don't know how to search that.

>Although we probably also want to eventually change TextBox to also never allow null in the bindable (larger change).

Not sure if a new issue should be created for this, or if the existing one should stay.

2021-10-02 17:19 UTC, bdach commented
These are not all usages that need this, if this is to be fixed by adding `string.Empty` defaults. A few others I've found:

* `SettingsTextBox`es created directly in `RoundEditorScreen.RoundRow`
* `SettingsTextBox`es created directly in `SeedingEditorScreen.SeedingResultRow`
* The `Bindable<string>` case in `SettingsSourceExtensions.CreateSettingsControls()`

2021-10-02 17:19 UTC, bdach requested changes
as above

2021-10-08 04:55 UTC, peppy commented
I've fixed the remaining cases and added guarding against this happening in the future. Requesting a second review.

2021-10-08 04:56 UTC, peppy approved these changes

2021-10-08 09:35 UTC, smoogipoo approved these changes
lgtm

2021-10-08 09:36 UTC, merged