Implement Relax difficulty calculation in osu!
ppy/osu pull request #14942
Opened 2021-10-03 15:34 UTC by apollo-dw

Since it was confirmed that automation mods like Relax and Autopilot will be submitting to leaderboards in lazer, I thought I'd go ahead and account for it in osu! difficulty calculation. I'm not sure whether Relax scores will be processed and assigned a pp value in the first place, especially with profile top plays in mind, but I have balanced the values so that relax and non-relax scores could theoretically co-exist. This was done with feedback.

This is done by the following:

- Return 0 for accuracy pp. Not requiring to tap means not needing to tap accurately.
- Set `speedBonus` to 0 in the Speed skill. This means Speed should only return distance-related values (flow aim). This also means Relax will change the SR of a map.
- Add 100s and 50s to the miss count. You have to really mess up aiming to get a 100 or a 50, so we harshen the penalty so that score performance calculator sees those as misses.
- Apply a flat 0.6x nerf to Aim and Speed. Aiming with relax is easier, since you can essentially "fling" your cursor without worrying about tapping or being on time and you can still hit circles.

Example values (these RX scores are real scores set): https://hastebin.com/raw/izuwacuren

And just saying for lurkers: not intended for stable by any means, of course.

2021-10-06 03:40 UTC, smoogipoo commented
@ppy/performance-points-committee Maybe just a quick review on this one to reduce backlogs.

2021-10-06 04:52 UTC, MBmasher approved these changes, later dismissed

2021-10-06 04:54 UTC, MBmasher commented
Values look okay to me. Looking towards the future, not sure how this could be implemented in another way (how would a "relax skill" work? is there another way?), so keeping the values low on purpose is good to ensure this doesn't break anything.

Could we get some clarity on whether mods such as Relax and Autopilot will actually give pp in the future?

2021-10-06 05:16 UTC, peppy commented
> Could we get some clarity on whether mods such as Relax and Autopilot will actually give pp in the future?

Such a timeline may exist. But ample warning and consideration will be given if/when this happens.

2021-10-06 07:53 UTC, stanriders commented on osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
> +                aimValue *= 0.6;
Wouldn't it be easier to just adjust global multiplier instead of multiplying every skill separately?

2021-10-06 14:52 UTC, emu1337 requested changes

2021-10-06 14:52 UTC, emu1337 commented on osu.Game.Rulesets.Osu/Difficulty/Skills/Speed.cs
> +                speedBonus = 0.0;
If you do this every object resolves to `0.2375 * angleBonus` , distance scaling is always zero. What is the intention here?

Returning zero for speed in PerformanceCalculator could be more straightforward, or you could return `angleBonus * Math.Pow(distance / single_spacing_threshold, 3.5)` here if you want the 'aiming' part of speed counted towards pp.

2021-10-06 23:15 UTC, emu1337 approved these changes

2021-10-07 00:25 UTC, MBmasher approved these changes

2021-10-08 01:03 UTC, stanriders approved these changes

2021-10-08 07:46 UTC, smoogipoo approved these changes

2021-10-08 07:47 UTC, merged