Add various logging output in an atttempt to figure multiplayer test failure
ppy/osu pull request #14959
Opened 2021-10-05 09:55 UTC by peppy

I can't figure out why this is happening, but looking to most probably be something very low level in the screen loading code. A starting point is understanding where things get stuck, so let's add logging and wait for the issue to arise again.

Open to any suggestions of further logging to add.

https://github.com/ppy/osu/pull/14907/checks?check_run_id=3794347620

2021-10-05 20:00 UTC, bdach requested changes

2021-10-05 20:00 UTC, bdach commented on osu.Game/Tests/Visual/ScreenTestScene.cs
> +using osu.Framework.Screens;
```suggestion
```

2021-10-05 20:00 UTC, bdach commented on osu.Game.Tests/Visual/Multiplayer/TestSceneTeamVersus.cs
> +            AddUntilStep("wait for dependencies to start load", () => dependenciesScreen.LoadState > LoadState.Ready);
Shouldn't this be

```suggestion
            AddUntilStep("wait for dependencies to start load", () => dependenciesScreen.LoadState > LoadState.NotLoaded);
```

The enum goes `NotLoaded` -> `Loading` -> `Ready` -> `Loaded`, so wouldn't `> Ready` just amount to another `IsLoaded` check...?

2021-10-05 21:01 UTC, bdach approved these changes
Seems like useful logging to have on a `ScreenTestScene` anyhow so no objections from me :+1:

2021-10-06 01:11 UTC, smoogipoo approved these changes

2021-10-06 01:11 UTC, merged