Localise toasts
ppy/osu pull request #15036
Opened 2021-10-11 03:37 UTC by Joehuu

- [x] Depends on framework bump (https://github.com/ppy/osu-framework/pull/4817)

I did my best to use existing translations for the tracked settings, but the music playback toast is a special case where one action can do multiple things and has no header translation. Just not sure how to structure new strings, put everything related to toasts under `ToastStrings`?

2021-10-11 16:36 UTC, bdach requested changes

2021-10-19 08:21 UTC, peppy submitted a review, later dismissed

2021-10-19 18:44 UTC, bdach submitted a review, later dismissed
as above

2021-10-20 06:04 UTC, smoogipoo approved these changes

2021-10-20 06:36 UTC, merged