Approximate amount of effective misses using combo
ppy/osu pull request #15086
Opened 2021-10-13 17:05 UTC by stanriders

Port of https://github.com/ppy/osu-performance/pull/131

2021-10-14 00:58 UTC, emu1337 requested changes

2021-10-16 11:40 UTC, smoogipoo commented
This score causes NaN values: https://osu.ppy.sh/scores/osu/2917569263. For the time being you'll need to download that beatmap pack to extract the .osu (I've reported this to @peppy). The following osu-tools args repro it:
```
simulate osu x.osu -c 1 -X 623 -M 0 -G 0 -m dt -m nf
```

2021-10-16 11:47 UTC, stanriders commented
Huh, seems like `effectiveMissCount` can be bigger than `totalHits` because it's being derived from combo. I think clamping it to `totalHits` max should be good enough since its pretty much an edge case

2021-10-17 02:30 UTC, smoogipoo commented
[Spreadsheet](https://docs.google.com/spreadsheets/d/18ssROsGUrh-q4ROQyqNmm_Y7HpYd9-EMYGyGWasrW4w/edit#gid=1165396648) of top PP changes as a result.

If there's no pushback, I'll merge with approvals from the PP committee.

2021-10-17 03:28 UTC, emu1337 approved these changes

2021-10-17 04:46 UTC, MBmasher approved these changes

2021-10-17 11:55 UTC, apollo-dw approved these changes

2021-10-18 01:01 UTC, smoogipoo approved these changes

2021-10-18 01:01 UTC, merged