Add a combo offset setting to Flashlight mod
ppy/osu pull request #15180
Opened 2021-10-18 13:46 UTC by MBmasher

For the Flashlight mod, the current combo affects the size of the flashlight radius (changing at 100 and 200 combo). Many flashlight players use separate difficulties called "practice difficulties" to practice certain sections of a map. At the beginning of such practice difficulties, things such as buzz sliders or stacked spinners are used to artificially raise the combo so that the appropriate flashlight size is reached. This "combo offset" setting removes the need for that, as it allows the initial combo to be changed.

2021-10-18 14:41 UTC, bdach requested changes

2021-10-18 23:38 UTC, MBmasher commented
> Does this need to be an osu!-specific setting? As in the other rulesets could probably benefit from this, too.

Agreed that taiko and catch would benefit, however I also agree with mk56-spn in which it probably wouldn't make sense for mania. So I've just added it to taiko and catch

2021-10-19 02:49 UTC, peppy requested changes

2022-04-13 07:16 UTC, smoogipoo commented
Closing due to inactivity.

2022-04-13 07:16 UTC, closed without merging