Fix spinner judgements on old beatmaps get incorrectly stacked
ppy/osu pull request #15279
Opened 2021-10-24 22:50 UTC by Flux3on

Due to the game not checking if the judged object is a spinner before displaying the judgement, spinner judgements would stack from the top left in an awkward fashion. This patch ensures that the judgement location will always be in the centre of the screen.

BEFORE:
![osu_2021-10-24_15-44-20](https://user-images.githubusercontent.com/28934062/138616037-624d47fc-1c2d-4d44-8378-271b2d761057.png)

AFTER:
![osu_2021-10-24_15-46-02](https://user-images.githubusercontent.com/28934062/138616046-c7da3f40-00c4-4260-9056-8ce946a0090d.jpg)

NOTE TO SELF: Do not put "For some reason" in a commit description

2021-10-24 23:24 UTC, frenzibyte requested changes
As per above.

2021-10-25 21:30 UTC, frenzibyte requested changes

2021-10-29 03:15 UTC, peppy approved these changes

2021-11-02 00:21 UTC, frenzibyte approved these changes
While I favour fixing this at a `BeatmapProcessor` level, wouldn't mind this in the interim.

2021-11-02 05:46 UTC, smoogipoo approved these changes

2021-11-02 05:46 UTC, merged