Improve user ratings calculations to make more sense
ppy/osu pull request #1573
Opened 2017-11-23 09:10 UTC by peppy

Closes #1552.

2017-11-23 12:05 UTC, smoogipoo requested changes

2017-11-23 12:05 UTC, smoogipoo commented on osu.Game/Screens/Select/Details/UserRatings.cs
> +                ratingsBar.Length = (float)negativeCount / totalCount;
Can we maybe early return or set this to 0 if `totalCount` == 0? I.e. the map hasn't been rated yet?

2017-11-23 14:32 UTC, peppy commented
Good catch, handling that case now.

2017-11-24 03:11 UTC, smoogipoo approved these changes

2017-11-24 03:46 UTC, merged