Improve reliability of exiting gameplay in multiplayer
ppy/osu pull request #16237
Opened 2021-12-24 05:48 UTC by smoogipoo

Fixes https://github.com/ppy/osu/issues/16236

This one's not easy to test for the time being because `TestMultiplayerClient` assumes `UserStateChanged` completes instantly...

Can be tested by exiting immediately after gameplay finishes with the following:
```diff
diff --git a/osu.Game/Online/Multiplayer/MultiplayerClient.cs b/osu.Game/Online/Multiplayer/MultiplayerClient.cs
index 903aaa89e3..630f080f09 100644
--- a/osu.Game/Online/Multiplayer/MultiplayerClient.cs
+++ b/osu.Game/Online/Multiplayer/MultiplayerClient.cs
@@ -478,10 +478,13 @@ Task IMultiplayerClient.SettingsChanged(MultiplayerRoomSettings newSettings)
             return Task.CompletedTask;
         }

-        Task IMultiplayerClient.UserStateChanged(int userId, MultiplayerUserState state)
+        async Task IMultiplayerClient.UserStateChanged(int userId, MultiplayerUserState state)
         {
             if (Room == null)
-                return Task.CompletedTask;
+                return;
+
+            if (state == MultiplayerUserState.FinishedPlay)
+                await Task.Delay(5000).ConfigureAwait(false);

             Scheduler.Add(() =>
             {
@@ -494,8 +497,6 @@ Task IMultiplayerClient.UserStateChanged(int userId, MultiplayerUserState state)

                 RoomUpdated?.Invoke();
             }, false);
-
-            return Task.CompletedTask;
         }

         Task IMultiplayerClient.MatchUserStateChanged(int userId, MatchUserState state)
```

2021-12-24 10:32 UTC, peppy submitted a review, later dismissed

2021-12-24 12:40 UTC, bdach requested changes
General idea seems okay, just not 100% on some of the details.

2021-12-24 12:40 UTC, bdach commented on osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayerLoader.cs
> +            player = (Player)next;
A bit unorthodox - could also opt for exposing from base as protected, but sure.

2021-12-24 12:40 UTC, bdach commented on osu.Game/Screens/OnlinePlay/Multiplayer/Multiplayer.cs
> +            client.RoomUpdated += onRoomUpdated;
Subscription is not removed on disposal.

2021-12-24 12:47 UTC, smoogipoo commented on osu.Game/Screens/Play/Player.cs
> +            GameplayCompleted = true;
So just to confirm, you want basically `GameplayCompleted => ScoreProcessor.HasCompleted`? I'm not sure I understand your point about the unconditional set to true - it seems like the precheck above is indicating that the score processor could indicate completion but the player has actually failed, and my xmldoc on `GameplayCompleted` states "completed without the user having failed".

2021-12-24 12:51 UTC, bdach commented on osu.Game/Screens/Play/Player.cs
> +            GameplayCompleted = true;
I'll admit that I glossed over the xmldoc, but with a name like `GameplayCompleted` I wouldn't even think that pass/fail state would factor into it at all until I did check it. I'd be fine with renaming to something like `GameplayPassed` then maybe? Not sure.

2021-12-24 12:58 UTC, smoogipoo commented on osu.Game/Screens/Play/Player.cs
> +            GameplayCompleted = true;
See if you agree with the latest changes.

2021-12-24 13:05 UTC, bdach commented on osu.Game/Screens/Play/Player.cs
> +            GameplayCompleted = true;
Works for me, yep.

2021-12-24 13:14 UTC, bdach approved these changes

2021-12-25 06:32 UTC, peppy approved these changes

2021-12-25 06:32 UTC, merged