Add failsafe to `IntroScreen` to stop users with incorrect audio configuration getting stuck
ppy/osu pull request #16710
Opened 2022-01-30 09:54 UTC by peppy

The most common case of this seems to be linux users with incorrect or unsupported audio driver configurations. It continues to be brought up in discussions as people are unsure of why their game freezes on startup, and unable to easily recover.

Note that I have not confirmed this worked with the specific case that many linux users run into, but I expect it will do fine.

See https://github.com/ppy/osu-framework/issues/3297 for relevant framework side issue. I propose we add this as a failsafe for not just that said issue, but as a catch-all to allow users to get to the main menu at very least. The same issue will (from my experience with osu-stable) also happen in some cases where no devices are available on the system.

2022-01-30 12:10 UTC, frenzibyte requested changes
On a simulated real test (via applying a `ManualClock` on the intro), the background will hide correctly but never show back even after the failsafe logic fires:

![CleanShot 2022-01-30 at 15 04 46](https://user-images.githubusercontent.com/22781491/151698843-faeeab8b-71b0-46ec-915a-ac3642a590ef.png)

That's because the hiding and showing logic is done in `TrianglesIntroSequence`, in which the hiding would apply at `LoadComplete` while the showing will apply after the intro is finished before calling `LoadMenu`.

2022-01-30 12:28 UTC, peppy commented on osu.Game/Screens/Menu/IntroScreen.cs
> +                    Text = "osu! doesn't seem to be able to play audio correctly.\n\nPlease try changing your audio device to a working setting."
That makes no sense to a user.

2022-01-30 13:07 UTC, bdach approved these changes
i guess this is fine? for what it's worth i still cannot reproduce the original issue and i'm not hugely interested in trying to break my audio setup to do so

2022-01-30 13:08 UTC, frenzibyte commented on osu.Game/Screens/Menu/IntroScreen.cs
> +                    Text = "osu! doesn't seem to be able to play audio correctly.\n\nPlease try changing your audio device to a working setting."
Sure I suppose.

2022-01-30 13:22 UTC, frenzibyte approved these changes
Seems alright to me. I think we can get this in for now. Don't have any way to confirm this works on a broken audio setup but can at least confirm it's working as intended with a `ManualClock`.

2022-01-31 04:40 UTC, smoogipoo approved these changes

2022-01-31 04:40 UTC, merged