Singleplayer Mods No Longer Carry to Multiplayer
ppy/osu pull request #17352
Opened 2022-03-19 19:06 UTC by nagilson

In response to: https://github.com/ppy/osu/issues/17306 

Please tell me if I'm completely off-base here, but I think this is alright. I was a bit confused why SelectedItem was the sole determining factor for the set of Mods; maybe I'm misunderstanding the system. If it's good I can add regression tests next. 

To observe the fix: 
----
Try adding automation or other mods in singleplayer on an account with no playlists.
Enter playlist creation, observe that the automation mod (or other mods) are no longer active, unlike before. (Also true for multiplayer screen)

If you edit an existing playlist, mods from the selected item or last item in the playlist will become active automatically.

2022-03-19 22:50 UTC, bdach commented
This diff seems much too complicated. I believe it should take about one line to fix this issue, namely:

```diff
diff --git a/osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs b/osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs
index bf1699dca0..c56d04d5ac 100644
--- a/osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs
+++ b/osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs
@@ -115,6 +115,8 @@ public override void OnEntering(IScreen last)
             this.FadeIn();
             waves.Show();
 
+            Mods.SetDefault();
+
             if (loungeSubScreen.IsCurrentScreen())
                 loungeSubScreen.OnEntering(last);
             else
```

The reason why the above fixes is that each screen takes a lease on the game-global mods bindable, so it can modify it as it wants and the changes will be reverted when the screen is exited. So resetting `Mods` to default on entering any online play screen (which covers both playlists and multiplayer) will make sure the mods do not carry over *but also* keep the mod selection from solo when solo is returned to.

This should also have automated test coverage. There is none right now.

2022-03-19 22:51 UTC, bdach requested changes
see above - needs test cases at the least

2022-03-19 23:16 UTC, nagilson commented
> see above - needs test cases at the least

Thank you, I'll add tests next, yes; I appreciate that you explained why the one-line solution works. Something of note: My proposed solution also retains selected Singleplayer mods. But one difference between the two proposals is that the original retains selected mods when editing an existing playlist. (Try: Creating a copy of a playlist containing tracks with mods and editing it -- the original proposal will automatically reselect those mods.) But maybe that's undesirable and obviously your code is much cleaner. 

I'm sorry for the ping btw, @bdach **_should I close this PR until I have the tests done? Or mark it as draft? (contributing.md says no)_**

2022-03-19 23:18 UTC, bdach commented
> one difference between the two proposals is that the original retains selected mods when editing an existing playlist

Adding this behaviour wasn't discussed anywhere in the original thread and is out of scope in a "fix" PR. Not to say that it can't be added, just best not to bundle it here.

> should I close this PR until I have the tests done?

Fine to keep as is currently until tests are added. Won't be merged with an unaddressed review anyway.

2022-03-21 04:20 UTC, frenzibyte commented
> > one difference between the two proposals is that the original retains selected mods when editing an existing playlist
> 
> Adding this behaviour wasn't discussed anywhere in the original thread and is out of scope in a "fix" PR. Not to say that it can't be added, just best not to bundle it here.

That sounds like it regresses the following logic though:
https://github.com/ppy/osu/blob/bdc3b76df0b58406796e2b08db13be7f2140fa7e/osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs#L87-L93

I think alternatively we can consider null `rulesetInstance`s to clear the `Mods` and `FreeMods` bindables instead, so that the issue can still be resolved while retaining the aforementioned behaviour.

2022-03-21 05:14 UTC, bdach commented
> That sounds like it regresses the following logic though

not sure what this is aimed at - do you mean the current implementation or my proposal above? i'm not seeing a connection between what you quoted and the logic you mentioned. can you elaborate?

2022-03-21 05:15 UTC, frenzibyte commented
The behaviour stated in "one difference between the two proposals is that the original retains selected mods when editing an existing playlist", unless I'm misunderstanding what it's saying (which I might be, actually).

2022-03-21 08:43 UTC, frenzibyte commented
Okay I can see the difference, and I agree that it is out of scope as not being discussed. Going to agree with the proposed solution above to simplify this.

2022-03-21 11:15 UTC, nagilson commented
Sounds good, my plan is to add that and the tests tonight or tomorrow night (waiting to add that change to prevent pinging the PR until I'm done with tests too.)

2022-03-22 02:38 UTC, closed without merging