Calculate sample playback position using screen-space drawable rectangles
ppy/osu pull request #17860
Opened 2022-04-18 05:34 UTC by frenzibyte

- Closes #17719 

As there are mods which could modify the positioning of the `DrawableHitObject` representation directly, the playback position of the hit samples will still remain unadjusted given that they read from the `HitObject`'s stored position.

Instead, the playback position has changed to now be calculated using the `DrawableHitObject`'s actual coordinates at a screen-space level, relative to the parenting container (retrieved by a recursive `ParentHitObject?.Parent ?? Parent`).

2022-04-18 05:52 UTC, peppy commented
This seems to not work great for slider "sliding" sounds applied via

https://github.com/ppy/osu/blob/90e34d7686b9a9762ba153ca841c5ad685497f3b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs#L209-L211

Sounds correct at a non-rotated playfield, but if applying a mod like barrel roll, the positional playback seems out.

https://user-images.githubusercontent.com/191335/163761659-83de93a0-4b4f-4271-8768-347a5008e208.mp4

2022-04-18 05:53 UTC, peppy requested changes
Issue as mentioned.

2022-04-18 06:22 UTC, frenzibyte commented
Good catch. Thought sliding samples never had balance adjusted according to ball position, but turns out it's because I was testing on master with "Barrel Roll" enabled. Have updated it to use the screen-space logic instead, and it seems to work properly now.

2022-04-21 07:57 UTC, peppy approved these changes

2022-04-21 17:48 UTC, merged