Fix nested song select in first-run dialog fiddling with global audio
ppy/osu pull request #17930
Opened 2022-04-22 12:24 UTC by peppy

Closes #17924.

Still figuring out how to write test coverage for this, if it's required..

The following works if you wait a bit before running the final step in visual tests, but fails in headless. Can't figure how to wait long enough to ensure the looping is applied.

```diff
diff --git a/osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenUIScale.cs b/osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenUIScale.cs
index 5ca09b34aa..5cd6086221 100644
--- a/osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenUIScale.cs
+++ b/osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenUIScale.cs
@@ -1,19 +1,27 @@
 // Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
 // See the LICENCE file in the repository root for full licence text.
 
+using System.Linq;
 using osu.Framework.Screens;
+using osu.Framework.Testing;
 using osu.Game.Overlays.FirstRunSetup;
 
 namespace osu.Game.Tests.Visual.UserInterface
 {
     public class TestSceneFirstRunScreenUIScale : OsuManualInputManagerTestScene
     {
+        private ScreenUIScale screen;
+
         public TestSceneFirstRunScreenUIScale()
         {
             AddStep("load screen", () =>
             {
-                Child = new ScreenStack(new ScreenUIScale());
+                Child = new ScreenStack(screen = new ScreenUIScale());
             });
+
+            AddUntilStep("wait for nested screen load", () => screen.ChildrenOfType<Screens.Select.SongSelect>().FirstOrDefault()?.Beatmap.Value != null);
+
+            AddAssert("music not looping", () => !MusicController.CurrentTrack.Looping);
         }
     }
 }

```

2022-04-22 13:01 UTC, smoogipoo requested changes, later dismissed

2022-04-22 13:01 UTC, smoogipoo commented on osu.Game/Screens/Select/SongSelect.cs
> +        protected virtual bool ControlGlobalMusic => true;
I think this PR is missing a file? It's not overridden anywhere as far as I can see.

2022-04-24 09:32 UTC, bdach commented
Not sure if a new test case is coming, but I will note that previously `TestSceneFirstRunSetupOverlay` would start music on the "UI scale" screen, but it doesn't do that anymore with this change.

Tentatively approving just in case this is supposed to go into an upcoming release.

2022-04-24 09:33 UTC, bdach approved these changes

2022-04-24 10:08 UTC, peppy commented
Maybe it's fine without a test. Testing this is very fiddly...

2022-04-24 10:18 UTC, merged