Add more context to sentry error reports
ppy/osu pull request #18218
Opened 2022-05-11 06:00 UTC by peppy

Adds config, realm, beatmap, clock and global statistics. Should be enough to get by for now. I've gone with the easiest implementation possible, rather than fumbling with trying to get json serialisation working.

- [ ] Depends on https://github.com/ppy/osu-framework/pull/5168

Sample report: https://sentry.ppy.sh/organizations/ppy/issues/431/?project=2

2022-05-11 21:05 UTC, bdach approved these changes, later dismissed

2022-05-12 01:25 UTC, smoogipoo requested changes

2022-05-12 01:25 UTC, smoogipoo commented on osu.Game/OsuGame.cs
> +                    Previous = current.GetType().Name,
Should check for null I think? For entering into the first screen and exiting from the last screen.

2022-05-12 03:11 UTC, smoogipoo approved these changes

2022-05-12 04:59 UTC, merged