Consider current culture while searching in settings
ppy/osu pull request #18270
Opened 2022-05-15 00:21 UTC by maromalo

- Closes https://github.com/ppy/osu/issues/14802

Search in settings only searches in english terms because their FilterTerms use LocalisedString.ToString(), which passes the default value (english, which is then used by framework's SearchContainer to make matches). 

My solution is using LocalisationManager to pass the string in it's appropiate culture, however I'm not sure if creating a new LocalisationManager for each element that needs it is efficient, so any suggestions would be appreciated.

2022-05-15 02:50 UTC, frenzibyte commented
This is not the right direction for solving such issue, bindables should not be allocated for *every* single filterable implementation *every* time a filter is changed.

What might at the very least work instead is turning `FilterTerms` into an enumerable of `LocalisableString`s, and have a way to evaluate the string without allocating a bindable for it in `SearchContainer` itself, and update the filter on localisation change.

2022-05-15 02:51 UTC, frenzibyte requested changes
As mentioned.

2022-05-15 03:22 UTC, peppy commented on osu.Game/Overlays/Settings/SettingsButton.cs
> +                    return base.FilterTerms.Append(localisation.GetLocalisedBindableString(TooltipText).Value);
In addition, the base english text should also always be included, as many people who use a non-english language will still search for keywords in english (by habit or preference).

2022-05-16 05:12 UTC, smoogipoo commented
Going to supersede this PR via https://github.com/ppy/osu/pull/18299, which is more up-to-date for anyone that needs to test with a local framework.

2022-05-16 05:12 UTC, closed without merging