Add toggle mod hotkey support in multiplayer room
ppy/osu pull request #18348
Opened 2022-05-21 07:59 UTC by maromalo

- Closes https://github.com/ppy/osu/issues/18140

2022-05-21 13:01 UTC, bdach requested changes

2022-05-21 13:01 UTC, bdach commented on osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
> +            public virtual bool OnPressed(KeyBindingPressEvent<GlobalAction> e)
There's no actual reason why any of the two methods added in this pull should be virtual.

2022-05-21 13:05 UTC, bdach commented
Would be nice to see test coverage for this, too. Expected place: probably somewhere around `TestSceneMultiplayerMatchSubScreen`, expected range of coverage: pressing F1 opens user mod select if there are any free mods in the current playlist item, and doesn't open user mod select if there are no free mods in the current playlist item.

2022-05-22 17:33 UTC, bdach approved these changes
have adjusted test slightly, looks good otherwise

2022-05-23 04:44 UTC, smoogipoo approved these changes

2022-05-23 04:45 UTC, merged