Scrolling hitobjects rewrite
ppy/osu pull request #1874
Opened 2018-01-10 08:51 UTC by smoogipoo

WIP

2018-01-11 07:52 UTC, smoogipoo commented
Added prereq on https://github.com/ppy/osu-framework/pull/1321

2018-01-12 06:52 UTC, peppy requested changes

2018-01-12 06:52 UTC, peppy commented on osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
> +            {
I think this could probably do with a comment in the body just mentioning why we are inhibiting the base call here

2018-01-12 06:52 UTC, peppy commented on osu.Game/Overlays/Settings/Sections/Gameplay/ScrollingSettings.cs
> +                    LabelText = "Scrolling algorithm",
Should probably be renamed to:

```csharp
enum SpeedChangeVisualisationMethod
{
    Overlapping,
    Sequential // or Chained?
}
```

and visible to the user
```
Visualise speed changes as:
- Overlapping
- Sequential
```

2018-01-12 06:52 UTC, peppy commented on osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
> +            if (initialStateCache.IsValid)
i'd invert this condition for readability

2018-01-12 08:48 UTC, peppy approved these changes

2018-01-12 08:48 UTC, merged