[WIP] Visual settings overlay
ppy/osu pull request #1879
Opened 2018-01-11 21:27 UTC by UselessToucan

Creating PR since I need feedback.

I'm not sure about these things:
1. What to do with fail/pause overlays? It it ok to just add this VisualSettings object there too? I guess this is how it is implemented in osu! stable.
2. Is it acceptable to implement visual settings the same way as "Playback" thing which is used only for replays? For me it looks natural to implement it that way, but it is only my opinion.
3. What do you guys think about the logic behind auto hiding and time stopping?

If you are interested, here are a couple videos which shows appearance/behaviour: [Gameplay](https://youtu.be/XQKnQHVtniw), [Replay](https://youtu.be/GcwjoMPyyeM)

2018-01-15 05:36 UTC, smoogipoo requested changes

2018-01-15 05:36 UTC, smoogipoo commented on osu.Game/Screens/Play/PlayerSettings/PlayerGroup.cs
> +    public abstract class PlayerGroup : Container
Let's rename this to `PlayerSettingsGroup`.

2018-01-17 01:13 UTC, peppy commented
Probably need @arflyte's input for this. Not sure if it should be separate from the global settings display, as opposed to just providing a default filter when in a gameplay screen.

2018-01-27 18:16 UTC, UselessToucan commented
What's new:
Visual settings object which is created on the Player screen now behaves the same way as Playback settings. It is visible during replay and invisible during actual gameplay.
Another one visual settings was added to the PlayerLoader screen. It is available during gameplay. Please note that it prevents Player from loading while hovered.

[Gameplay video](https://www.youtube.com/watch?v=nq6pk16IK-4)
[Replay video](https://www.youtube.com/watch?v=RSiy5HthsxA)

2018-01-29 06:52 UTC, smoogipoo commented
Dunno if you had a microphone spying on us while we talked about having it in PlayerLoader, but that was definitely a good move. A few comments:

1. It should be previewable during `PlayerLoader`.
2. It should be changeable from `PauseOverlay`, with the same sort of preview as osu-stable.

2018-01-29 06:53 UTC, peppy commented
(i gave feedback in discord on that part)

2018-01-29 09:31 UTC, UselessToucan commented
@smoogipoo What do you mean by "previewable"? Do you mean that expander should be collapsed when PlayerLoader screen is displayed for the first time?
About `PauseOverlay`: as far as I remember, @peppy wrote to keep it only on PlayerLoader screen for now.

2018-01-29 09:31 UTC, peppy commented
By preview, he means that you should instantly be able to see the effect, possibly just while hovering.

2018-01-29 09:37 UTC, UselessToucan commented
This [blur](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/Player.cs#L385) and [dim](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/Player.cs#L386) related magic is implemented inside of Player class. I planned to extract it in separate "code quality" PR later, but I can do it here.

2018-01-29 09:38 UTC, peppy commented
I'd prefer a separate PR, personally. I'm fine with this being merged initially with no preview.

2018-01-31 19:55 UTC, UselessToucan commented
@peppy @smoogipoo Could you please check this PR again and write what should be done in order to merge it?

2018-02-01 07:44 UTC, smoogipoo approved these changes
LGTM

2018-02-01 07:44 UTC, merged