Fix custom rulesets not importing scores at all
ppy/osu pull request #19025
Opened 2022-07-07 07:45 UTC by peppy

Replaces the error with the ability to import, minus replays.

Closes https://github.com/ppy/osu/issues/17350 (arguably, but let's go with it for now).

2022-07-07 07:46 UTC, smoogipoo commented
This replaces https://github.com/ppy/osu/pull/17787, correct?

2022-07-07 16:13 UTC, frenzibyte requested changes

2022-07-07 16:16 UTC, peppy commented on osu.Game/Tests/Visual/PlayerTestScene.cs
> +        /// </summary>
I can try to move it, but wedging in the correct place is frustrating as anything, and trying to find other similar usages is nigh impossible.

2022-07-08 07:06 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestScenePlayerLocalScoreImport.cs
> +            };
Tempted to just drop the tests at this point.

2022-07-08 09:42 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestScenePlayerLocalScoreImport.cs
> +            };
@frenzibyte for my own sanity, can you confirm that you meant "not enough to TEST importing scores"?

![Safari 2022-07-08 at 09 42 29](https://user-images.githubusercontent.com/191335/177964957-4ab0459f-4257-4608-88e1-f5e774de2499.png)

2022-07-08 10:18 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestScenePlayerLocalScoreImport.cs
> +            };
Presuming that's what you meant, this should now be fixed. Have tested that the new tests does fail against `master`.

2022-07-08 16:25 UTC, frenzibyte approved these changes

2022-07-08 17:01 UTC, merged