Fix editor playing object samples while paused after cancelling exit
ppy/osu pull request #19063
Opened 2022-07-09 19:23 UTC by Joehuu

- Fixes https://github.com/ppy/osu/issues/19062

2022-07-11 07:44 UTC, peppy requested changes

2022-07-11 07:44 UTC, peppy commented on osu.Game.Tests/Visual/Editing/TestSceneEditorSaving.cs
> +            AddAssert("Sample playback disabled", () => Editor.SamplePlaybackDisabled.Value);
This still passes on `master`. Please make sure to check tests actually fail without the fix.

2022-07-11 20:00 UTC, bdach approved these changes
Seems better now.

2022-07-11 20:18 UTC, frenzibyte approved these changes

2022-07-12 03:51 UTC, smoogipoo approved these changes

2022-07-12 03:51 UTC, merged