Remove score multiplier on difficulty-increasing mods with customised settings
ppy/osu pull request #19208
Opened 2022-07-18 04:42 UTC by frenzibyte

- Closes #7698 

As mentioned in https://github.com/ppy/osu/discussions/19191#discussioncomment-3166121, as a first step, all mods with increased score multiplier are nullified if the mod uses custom configuration.

I've added a property for this to allow including it in all mods which have an increased score multiplier, to avoid requiring to add every new setting in the multiplier field (e.g. `OsuModFlashlight` which has three different settings with varying states to abuse it).

I've considered moving this to a higher level but realised it'll have to be specific to mods with a >1 score multiplier, and also somehow still allow mods which have a proper customisation-respecting score multiplier (in the future), therefore I went with doing it on a per-mod basis instead.

2022-07-18 07:51 UTC, peppy commented
An alternative implementation would be to apply this globally to all mods. And potentially set the multiplier to something very low by default until we address the larger issue (ie. to handle people using difficulty adjust and changing the settings to make a beatmap much easier).

Will wait to hear @smoogipoo (and anyone else that cares to chime in) thoughts on this one.

2022-07-18 11:24 UTC, Moltanicaa commented
I have a couple of thoughts on this.  
1. As far as DA is concerned, the biggest problem is changing the size of the notes. When the size is changed, the starrate changes, so the change in the multiplier can be tied to the ratio of the change in the starrate from the usual one. Same 
2. As for the DT/HT customization, even a 1.01x multiplier still speeds up the map by 1%, so it would be fair to also have a dynamic multiplier, so instead of 1.12x one could give...1.024x (1+0.12/50, so how do we have 50 values ​​from the usual 1.5x speed)? This would give me a total bonus of +2400 points (if i will SS the map), which is not much.

2022-07-18 11:38 UTC, peppy commented
> I have a couple of thoughts on this.  
> 1. As far as DA is concerned, the biggest problem is changing the size of the notes. When the size is changed, the starrate changes, so the change in the multiplier can be tied to the ratio of the change in the starrate from the usual one.  
> 2. As for the DT/HT customization, even a 1.01x multiplier still speeds up the map by 1%, so it would be fair to also have a dynamic multiplier, so instead of 1.12x one could give...1.024x (1+0.12/50, so how do we have 50 values ​​from the usual 1.5x speed)? This would give me a total bonus of +2400 points (if i will SS the map), which is not much.

Both valid points but also for a different discussion as I mentioned. This is an initial fix until we figure things out.

2022-07-19 09:40 UTC, smoogipoo approved these changes
I think this is probably fine for the time being.

2022-07-19 09:40 UTC, smoogipoo commented on osu.Game/Overlays/Mods/ModSelectOverlay.cs
> +                modSettingChangeTracker.SettingChanged += _ => updateMultiplier();
Should probably be around an `if (AllowCustomisation)` similar to the above optimisation. Concern is selecting all mods in the freemods overlay.

2022-07-19 09:41 UTC, smoogipoo requested changes
Uh.. Minus the review above

2022-07-20 05:52 UTC, peppy approved these changes

2022-07-20 11:12 UTC, smoogipoo approved these changes

2022-07-20 11:13 UTC, merged