Save toasts for Beatmap & Skin Editor
ppy/osu pull request #19243
Opened 2022-07-19 20:54 UTC by LukynkaCZE

This is thing I have been missing in lazer for a long time. When mapping or editing skin I hit the save button/ctrl + s and I get no feedback from the game if it was saved or not. This is also feature in stable that is missing in lazer.

https://user-images.githubusercontent.com/48604271/179846239-7cf8eefc-94ab-4f61-87c4-a20c7c4ab02f.mp4

https://user-images.githubusercontent.com/48604271/179846245-de05fe8e-59ab-4a54-b86d-13286a9793bc.mp4

.

2022-07-20 04:41 UTC, peppy requested changes

2022-07-20 04:41 UTC, peppy commented on osu.Game/Localisation/ToastStrings.cs
> +        public static LocalisableString SkinEditor => new TranslatableString(getKey(@"skin_editor"), @"Skin Editor");
Use `SkinSettingsStrings.SkinLayoutEditor`

2022-07-20 04:41 UTC, peppy commented on osu.Game/Localisation/ToastStrings.cs
> +        public static LocalisableString BeatmapEditor => new TranslatableString(getKey(@"beatmap_editor"), @"Beatmap Editor");
Use `EditorSection.EditorSection`.

2022-07-20 04:41 UTC, peppy commented on osu.Game/Localisation/ToastStrings.cs
> +        public static LocalisableString EditorSaveBeatmap => new TranslatableString(getKey(@"beatmap_editor_save"), @"Beatmap Saved");
I have no idea what's being done here.

Are you manually making these files? We generally use a rider tool to do this.

If you are manually doing it, you will need to pay very close attention to the format. The property name should match the key should match the string.

In this case, the string should be `Beatmap saved` (not title case) and the key should be `BeatmapSaved` / `beatmap_saved` to match.

Same applies to others.

2022-07-22 00:52 UTC, LukynkaCZE commented
I did all the requested changes 👍🏻  Also I wasn't aware there was tool to do the Localization stuff.. Well now I know and I'm gonna be using it from now on

2022-07-22 04:09 UTC, peppy approved these changes, later dismissed

2022-07-22 05:06 UTC, peppy approved these changes

2022-07-22 05:06 UTC, merged