Add Toast notification to ExternalLinkButton's context menu
ppy/osu pull request #19410
Opened 2022-07-27 06:26 UTC by novialriptide

Continuation from: https://github.com/ppy/osu/pull/19375

2022-07-27 06:34 UTC, frenzibyte requested changes

2022-07-27 06:34 UTC, frenzibyte commented on osu.Game/Graphics/UserInterface/ExternalLinkButton.cs
> +        }
Nested classes go to bottom.

2022-07-27 06:34 UTC, frenzibyte commented on osu.Game/Graphics/UserInterface/ExternalLinkButton.cs
> +            }
Link is guaranteed not to be null from `ContextMenuItems`.
```suggestion
            host.GetClipboard()?.SetText(Link);
            onScreenDisplay?.Display(new CopyUrlToast(ToastStrings.CopiedUrl));
```

2022-07-27 06:34 UTC, frenzibyte commented on osu.Game/Graphics/UserInterface/ExternalLinkButton.cs
> +                    items.Add(new OsuMenuItem("Copy URL", MenuItemType.Standard, () => copyUrl()));
```suggestion
                    items.Add(new OsuMenuItem("Copy URL", MenuItemType.Standard, copyUrl));
```

2022-07-27 06:34 UTC, frenzibyte commented on osu.Game/Localisation/ToastStrings.cs
> +        public static LocalisableString CopiedUrl => new TranslatableString(getKey(@"copied_url"), @"Copied URL");
Probably want this to be "URL copied" inline with the two messages above.

2022-07-28 03:17 UTC, peppy approved these changes

2022-07-28 04:43 UTC, merged