Add keybind for showing profile
ppy/osu pull request #19657
Opened 2022-08-09 06:50 UTC by novialriptide

Fixes: https://github.com/ppy/osu/issues/9941

2022-08-09 06:53 UTC, smoogipoo requested changes

2022-08-09 06:53 UTC, smoogipoo commented on osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
> +        public static LocalisableString ShowProfile => new TranslatableString(getKey(@"toggle_notifications"), @"Show Profile");
```suggestion
        public static LocalisableString ShowProfile => new TranslatableString(getKey(@"show_profile"), @"Show profile");
```

2022-08-09 06:53 UTC, smoogipoo commented on osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
> +        /// "Show Profile"
```suggestion
        /// "Show profile"
```

2022-08-09 07:01 UTC, smoogipoo requested changes

2022-08-09 07:01 UTC, smoogipoo commented on osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
> +        public static LocalisableString ShowProfile => new TranslatableString(getKey(@"toggle_notifications"), @"Show profile");
```suggestion
        public static LocalisableString ShowProfile => new TranslatableString(getKey(@"show_profile"), @"Show profile");
```

2022-08-09 07:02 UTC, novialriptide commented on osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
> +        public static LocalisableString ShowProfile => new TranslatableString(getKey(@"toggle_notifications"), @"Show profile");
That was silly of me.

2022-08-09 07:13 UTC, smoogipoo requested changes

2022-08-09 07:27 UTC, smoogipoo submitted a review, later dismissed

2022-08-09 07:50 UTC, peppy commented
Feels a bit weird that this isn't a toggle, but maybe okay?

2022-08-09 07:56 UTC, peppy commented
@bdach can i get an opinion from you on this being a non-toggle? can't decide which feels better. in fact i'm almost leaning to making all overlays non-toggle and have people use escape to close, but not sure.

maybe best to make this PR be a toggle and discuss the UX later?

2022-08-09 08:10 UTC, novialriptide commented
> maybe best to make this PR be a toggle and discuss the UX later?

@peppy Done.

2022-08-09 08:13 UTC, smoogipoo commented
@peppy wants the entire overlay to toggle, not just the text to be changed.

2022-08-09 18:11 UTC, novialriptide commented
I'm not too keen on this, because it doesn't actually bring up the user profile overlay.

2022-08-09 19:25 UTC, bdach commented
> @bdach can i get an opinion from you on this being a non-toggle? can't decide which feels better.

I don't have a strong opinion to give. I will say that I've gotten quite used to these being toggles - escape is not always a viable and reliable alternative, as you may need to press it however many times if there are nested focused elements in the overlay. I also think say that this PR should probably be consistent with everything else, i.e. it should toggle, and if toggle is deemed bad, then all of the overlays should be changed to not toggle in one PR.

2022-08-10 07:12 UTC, peppy requested changes

2022-08-10 07:12 UTC, peppy commented on osu.Game/Overlays/UserProfileOverlay.cs
> +        }
Please move this to `OsuGame` to keep everything in one place. This kind of cross-dependency makes understanding and ensuring correctness very hard.

You can call `userProfile.Hide()` in the case it is already shown.

2022-08-11 04:17 UTC, peppy approved these changes

2022-08-11 17:47 UTC, merged