Reset track adjustments after returning to MainMenu
ppy/osu pull request #1968
Opened 2018-01-23 21:11 UTC by UselessToucan

Resolves #1961 
There are no null checks because I did not see any null values here during manual testing(both with and without beatmaps imported).

2018-01-23 21:52 UTC, ThePyrotechnic commented
I think that, while this fix works, the problem to be solved is whether mod selections should persist when returning to the menu. In stable they currently do, with the only difference being that DT/NC and HT don't actually change the speed/pitch.

2018-01-23 21:59 UTC, UselessToucan commented
@ThePyrotechnic 
> the problem to be solved is whether mod selections should persist when returning to the menu.

In my opinion, this thing is not related to #1961 .
Mods are not saved because we create new song select screen whenever returning to main menu.

2018-01-23 22:05 UTC, ThePyrotechnic commented
@UselessToucan I believe that it is related because if the decision was made that mod selections should persist through returning to the main menu, then this PR would have to be reverted. Even if it were decided that the speed and pitch should be reset and then set again upon reentering the the selection screen, a different solution would be required which involves holding onto the state of the mods.

2018-01-23 22:13 UTC, UselessToucan commented
I did not know that it was decided to save mod selection. :-(
Will investigate situation tomorrow and update/rename this PR.

2018-01-23 22:14 UTC, LittleEndu commented
Regardless, people who want to use osu as jukebox would appreciate if track speed is reset when returning to main menu. I don't see why we can't have both, that is, DT/NC/HT/DC would just reapply when going back to song select.

2018-01-24 05:09 UTC, smoogipoo requested changes

2018-01-24 05:09 UTC, smoogipoo commented on osu.Game/Screens/Menu/MainMenu.cs
> +            Beatmap.Value.Track.ResetSpeedAdjustments();
Rather than this, `PlaySongSelect` should set Beatmap.Value.Mods to an empty list.

2018-01-24 21:40 UTC, peppy commented
Not sure resetting mods is a logical thing to do. It's not what I'd expect as a user.

2018-01-24 23:02 UTC, ThePyrotechnic commented
What @LittleEndu said about the jukebox is definitely important, but I think that if someone deliberately enables those mods it would be strange if the modulation stopped in the menu but then returned when back in the selection screen. 
Assuming that mods should persist, which I think is a good idea (not that my opinion should have much weight), it would probably make more sense to leave the effect on in the main menu.

2018-01-24 23:17 UTC, peppy commented
If mods are only available to change from song select inwards, they should not be applied at a higher level.

2018-01-29 04:38 UTC, peppy commented
Closing as #1983 resolves this in a better way.

2018-01-29 04:38 UTC, closed without merging