Fix osu star rating calculation
ppy/osu pull request #1981
Opened 2018-01-25 19:42 UTC by thomastanck

The main bug was that the beatmap was not being processed prior to
having its Skill values calculated, causing stacking to be ignored in
difficulty calculation. The fix involves processing the beatmap with
OsuBeatmapProcessor.

Another minor bug was that sliders were not taking into account the
stacked position midway through the slider (PositionAt does not return
stacked position.), so I corrected by adding StackOffset.

2018-01-25 19:48 UTC, Aergwyn commented on osu.Game/Beatmaps/DifficultyCalculator.cs
> -        protected readonly Beatmap<T> Beatmap;
Why was this removed?

2018-01-25 19:49 UTC, thomastanck commented on osu.Game/Beatmaps/DifficultyCalculator.cs
> -        protected readonly Beatmap<T> Beatmap;
Probably a mistake.

2018-01-25 20:08 UTC, thomastanck commented
Btw, a similar bug occurs in osu!stable, probably due to the same cause (not preprocessing the beatmap, ignoring stacking). Please verify using the .osu file (https://pastebin.com/raw/XChF5emy). Use this .osz if you want the song https://osu.ppy.sh/s/720129

You can confirm that the bug exists if setting `StackLeniency: 0` doesn't change the star rating.

StackLeniency: 0 --> 7+*
StackLeniency: 0.7 --> 5+*

2018-01-29 05:57 UTC, smoogipoo requested changes

2018-01-29 05:57 UTC, smoogipoo commented on osu.Game.Rulesets.Osu/OsuDifficulty/Preprocessing/OsuDifficultyHitObject.cs
> +                var diff = slider.PositionAt(t) + slider.StackOffset - slider.LazyEndPosition.Value;
How about we expose `StackedPositionAt(double time)` from `Slider`? We'll probably want to use this elsewhere.

2018-02-01 09:33 UTC, smoogipoo approved these changes
lgtm

2018-02-01 10:32 UTC, merged