BPM display in mods overlay
ppy/osu pull request #19929
Opened 2022-08-23 21:56 UTC by Feodor0090

This PR adds BPM display next to difficulty multiplier display into mods overlay. This allows users to see final bpm after applying custom dt/nc/ht without closing the overlay.
![изображение](https://user-images.githubusercontent.com/53872073/186271358-5ada3855-dd5a-4a31-932c-cfd9a545da5d.png)

Issues here:
1) Label should be shorten to just "BPM" or localized. Which is better and in which class should i put field with localisable string?
2) Now, it will be visible only if `ShowTotalMultiplier` is true, because i share container with `DifficultyMultiplierDisplay`. I think that it's ok, because DMD is hidden only in freemods selection where this control is useless anyway.
3) Currently, opening customization panel shifts the whole overlay up, making this control invisible. Something to fix as a follow-up.
4) WU/WD/AS are not supported, like in beatmap wedge.

Test scene included.

2022-08-23 22:15 UTC, bdach commented
Dunno about this from a design standpoint. I was hoping a design for this would arrive from @arflyte but no luck I guess.

I'll review code tomorrow.

2022-08-24 05:28 UTC, peppy commented
Mentioned in OP, but this is kinda useless as it stands:

Uploading osu! 2022-08-24 at 05.27.25.mp4…


@arflyte ?

2022-08-24 05:32 UTC, peppy requested changes

2022-08-24 05:32 UTC, peppy commented on osu.Game/Overlays/Mods/BpmDisplay.cs
> +                this.FadeOut(transition_duration, Easing.OutQuint);
I disagree with fading out the whole thing in such cases. Show a `-` instead.

2022-08-24 10:47 UTC, Feodor0090 commented
> this display is potentially taking space away from a search box

Mods names are not so long. I think half of the screen will be enough for it. If we short the labels to just "BPM" and "Score", there will be space to add even more such displays.

> Mentioned in OP, but this is kinda useless as it stands

My suggestion here is to move container with this displays to a higher level, forex. in `ModSelectOverlay` itself. They won't be shifted out of screen while customization panel is open.

2022-08-24 19:41 UTC, bdach requested changes

2022-08-24 19:41 UTC, bdach commented on osu.Game/Overlays/Mods/ModSelectOverlay.cs
> +                        new BpmDisplay(),
If the BPM display is to be steered by `ShowTotalMultiplier` then that property needs a rename. Maybe something like `ShowModEffects` or something, with associated proper xmldoc to explain what the "effects" are.

2022-08-24 19:41 UTC, bdach commented on osu.Game/Overlays/Mods/BpmDisplay.cs
> +            InternalChild = new InputBlockingContainer
Having mixed feelings about all of this layout setup being essentially copy-pasted from `DifficultyMultiplierDisplay`. Is this really necessary?

2022-08-24 19:41 UTC, bdach commented on osu.Game/Overlays/Mods/BpmDisplay.cs
> +            double mostCommonBPM = Math.Round(Math.Round(60000 / beatmap.GetMostCommonBeatLength()) * rate);
Similarly mixed feelings about all this being copy-pasted from `BeatmapInfoWedge`. I initially thought this was a misguided buggy implementation due to the double rounding, until I blamed back the `BeatmapInfoWedge` copy and found https://github.com/ppy/osu/pull/18345.

2022-08-24 19:41 UTC, bdach commented on osu.Game/Overlays/Mods/BpmDisplay.cs
> +            if (double.IsNormal(mostCommonBPM))
What is this `IsNormal` check, even? Is this supposed to catch NaNs? When can this even occur? A comment below is saying something about "no map selected" - maybe the way there is to, you know, not divide by 0 in the first place?

2022-08-24 19:41 UTC, bdach commented on osu.Game/Overlays/Mods/BpmDisplay.cs
> +            working.ValueChanged += _ => refresh();
Nitpick, but why is one of these using `BindValueChanged(...)` and one is doing `ValueChanged += ...`?

2022-08-29 16:58 UTC, peppy commented
Is this intended to be dependent on #19991 now?

2022-08-29 19:01 UTC, Feodor0090 commented
After same experiments, IMO the best way is just to duplicate effect displays to `ModSettingsArea`. I also added a simple animation to create feeling that it's the same panel, just moved off-screen.

https://user-images.githubusercontent.com/53872073/187276542-6c66bc8f-15f9-4ee0-ae84-3be1344deece.mp4

Will this be accepted?


> Is this intended to be dependent on #19991

Yes.

2022-08-29 19:38 UTC, bdach commented
> Will this be accepted?

I'm not a fan of duplicating the displays, personally, from a functional standpoint. The visual look also leaves much to be desired for me (the alignment of the items seems really weird for me).

For reference, some of the [newer figma designs](https://www.figma.com/file/NkdREXr6wFkA99oLw8PnBv/Client%2FMod-Selection?node-id=0%3A1) just get rid of the customisation panel at the bottom in favour of a dropdown, which would potentially solve this. That said we direly need input from @arflyte here whether that is something that's final or just a proposal (third time the charm, maybe?)

2022-08-30 05:58 UTC, arflyte commented
I think the current problem with the design is that it's not suitable to display many types of info as it would clutter up everything (it's just bad to have a lot of boxes)

So probably, as a long-term solution, I have to design a better information container that can house multiple info, which could also be future-proof.

2022-09-08 06:22 UTC, peppy commented
@Feodor0090 I think it's fine to duplicate the display as you proposed. Please apply this change and we'll take it from ther.

2022-09-16 17:40 UTC, Feodor0090 commented
There is a failing test that i am not sure what to do with - `TestSceneFreeModSelectOverlay.TestCustomisationNotAvailable()`. It's checking the height of customization panel to know is it opened or not. The problem here is that after my changes mod overlay won't contain a customization panel at all, if it is not available (`AllowCustomisation` is false).

How should I adjust it? Or maybe just remove (there is no customization panel => it can't open anyway)?

2023-09-06 06:05 UTC, Joehuu commented
Superseded by https://github.com/ppy/osu/pull/24705.

2023-09-06 06:05 UTC, closed without merging