Slight tweak to the StarsSlider
ppy/osu pull request #20130
Opened 2022-09-04 22:35 UTC by Exanc

This is only a proposition but I think it feels more natural to have the MinimumStarsSlider display "0" instead of "∞".

 - MinimumStarsSlider now shows "0" when at it's minimum
 - Modified the tooltip and NoResultsPlaceholder to stay consistent with the changes

![image](https://user-images.githubusercontent.com/43091560/188335717-6eaf59dd-990a-47c5-a753-912d28bd2892.png)
![image](https://user-images.githubusercontent.com/43091560/188335732-bdab2082-6855-4e87-8950-bde216d800f4.png)
![image](https://user-images.githubusercontent.com/43091560/188335738-3f9fc83a-b8ea-48e9-bddc-4c061b9d637b.png)

2022-09-05 01:53 UTC, smoogipoo submitted a review, later dismissed

2022-09-08 05:21 UTC, peppy requested changes

2022-09-08 05:21 UTC, peppy commented on osu.Game/Screens/Select/NoResultsPlaceholder.cs
> +                    string lowerStar = filter.UserStarDifficulty.Min == null ? "0,0" : $"{filter.UserStarDifficulty.Min:N1}";
Baking in a foreign culture format style is not what we want.

2022-09-08 05:21 UTC, peppy commented on osu.Game/Screens/Select/DifficultyRangeFilterControl.cs
> +            protected readonly string DefaultValue;
Maybe rename to `DefaultString`

2022-09-08 06:54 UTC, peppy approved these changes

2022-09-08 08:51 UTC, merged