Simplify skin bindable flow
ppy/osu pull request #20264
Opened 2022-09-12 10:53 UTC by peppy

Now, nothing touches the configuration apart from `OsuGame`, making everything else flow better and avoid weird cyclic set bugs.

Closes https://github.com/ppy/osu/issues/20234.

2022-09-12 10:54 UTC, peppy commented
I recommend testing any edge case flows you can think of. I can't seem to break it but it's touching code which has historically been pretty delicate. In theory it shouldn't be delicate anymore but..

2022-09-13 00:02 UTC, frenzibyte commented
The dropdown selection highlight no longer appears on initial load, reset to default, or picking skin via `<Random Skin>` or hotkey:

https://user-images.githubusercontent.com/22781491/189778727-55755b01-b683-4d52-bede-932599938c10.mp4

2022-09-13 00:04 UTC, frenzibyte requested changes
See above.

2022-09-13 00:04 UTC, frenzibyte commented on osu.Game/Overlays/Settings/Sections/SkinSection.cs
>              realmSubscription = realm.RegisterForNotifications(_ => realm.Realm.All<SkinInfo>()
It's already specified in BDL:
```suggestion
            realmSubscription = realm.RegisterForNotifications(_ => realm.Realm.All<SkinInfo>()
```

2022-09-13 05:02 UTC, peppy commented
Dropdown selection should now work correctly. But of a weird cause for this, but it's not the first time it's happened..

2022-09-13 08:44 UTC, smoogipoo commented
The dropdown selection is still not working after game startup.

2022-09-13 09:58 UTC, peppy commented
Hmm, that's due to setting `Current` before populating `Items`. An easy fix is to move the `Current` initialisation to inside the realm subscription, but I'll take a look at the dropdown logic to see if there's a better way to handle that.

2022-09-13 10:49 UTC, peppy commented
Remaining issue will be resolved by https://github.com/ppy/osu-framework/pull/5401.

2022-09-13 22:31 UTC, frenzibyte approved these changes

2022-09-14 00:21 UTC, smoogipoo commented
Can this one be merged without the dependency? It's just a visual thing right?

2022-09-14 00:21 UTC, smoogipoo approved these changes

2022-09-14 00:27 UTC, frenzibyte commented
Have added it as part of the dependencies since merging this PR without is sort of regressing the dropdown's behaviour, and that a framework bump should be done before publishing a game release with this PR merged (would imagine the bug affecting up/down-arrow selection as well since the selected item is unknown).

2022-09-16 12:06 UTC, merged