Simplify flashlight
ppy/osu pull request #20358
Opened 2022-09-18 04:43 UTC by o-dasher

Just a minor code quality fix.
This pull request shapes a path for possible customization for when flashlight size changes with combo and simplifies some flashlight code.

2022-09-18 22:41 UTC, frenzibyte requested changes
I don't really see any point in this PR other than matching stable by decreasing size at 100x rather than >100x, please revert other changes and only fix that. The flashlight size calculation changes should be included in the PR which adds such customisation support.

2022-09-18 22:41 UTC, frenzibyte commented on osu.Game/Rulesets/Mods/ModFlashlight.cs
> +                    foreach (var breakPeriod in Breaks.Where(breakPeriod => breakPeriod.HasEffect && breakPeriod.Duration >= FLASHLIGHT_FADE_DURATION * 2))
Prefer how it was previously, don't like combining all conditions in one big `Where` operation.

2022-09-18 23:15 UTC, frenzibyte approved these changes
Visual difference seems quite subtle that I don't think it requires any additional action.

2022-09-19 13:03 UTC, peppy approved these changes

2022-09-19 13:03 UTC, merged