EditorBeatmap's TimelineZoom should never be zero
ppy/osu pull request #20353
Opened 2022-09-17 14:02 UTC by Drison64

fixes #20306

2022-09-17 14:56 UTC, frenzibyte commented on osu.Game/Screens/Edit/EditorBeatmap.cs
> +            if (this.beatmapInfo.TimelineZoom <= 0) this.beatmapInfo.TimelineZoom = 1;
Don't know about that. Are you aware that there are limits to zooming in the timeline? Surely zero isn't in that range, but it still ended up being used, which is not correct behaviour.

Check how zooming is set up in `Timeline`, that should be enough to tell you what's actually wrong.

2022-09-17 14:57 UTC, frenzibyte requested changes
As proposed.

2022-09-17 17:04 UTC, Drison64 commented
Hey, I updated it, but not sure if it's what you meant. Would you mind explaining what you had in mind if it isn't?

2022-09-17 17:11 UTC, frenzibyte commented
That's precisely what I had in mind. In addition, would add a validity check in `SetupZoom` that the initial zoom is between minimum and maximum values, so that this doesn't happen again.

2022-09-17 17:12 UTC, frenzibyte commented on osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
> +                float initialZoom = (float)(defaultTimelineZoom * (editorBeatmap.BeatmapInfo.TimelineZoom <= 0 ? 1 : editorBeatmap.BeatmapInfo.TimelineZoom));
There's no negative timeline zoom, that's guaranteed by `LegacyBeatmapDecoder`.
```suggestion
                float initialZoom = (float)(defaultTimelineZoom * (editorBeatmap.BeatmapInfo.TimelineZoom == 0 ? 1 : editorBeatmap.BeatmapInfo.TimelineZoom));
```

2022-09-18 09:05 UTC, peppy approved these changes
Seems okay, hopefully the new exception doesn't throw at runtime.

2022-09-18 09:06 UTC, merged