Fix intermittent leaderboard crash due to request finishing after drawable is disposed
ppy/osu pull request #20418
Opened 2022-09-23 11:19 UTC by peppy

2022-09-23 14:01 UTC, frenzibyte requested changes

2022-09-23 14:03 UTC, peppy commented on osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
> +            ));
I initially went down that path but wasn't sure how reliable cancellation is at stopping the event flow.

I think you're right about this regressing the reason for not having the schedule there.

As for why `Scheduler` still works: the only check it performs is correct thread. I don't believe it has any concept of disposal.

2022-09-26 07:04 UTC, peppy commented on osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
> +            ));
I've refactored to avoid adding the extra `Schedule`. See how it reads now.

2022-09-26 08:10 UTC, smoogipoo approved these changes

2022-09-26 08:10 UTC, merged