Toolbar localisation
ppy/osu pull request #20709
Opened 2022-10-11 07:57 UTC by Domilz

Interpreted issue [14083](https://github.com/ppy/osu/issues/14083) as one could work on any part of the localisation and create a pull request. Not sure if it is okay to use the localisation in the Toolbarbutton files. I have made some sv.resx files of the respective parts in osu-resources which I will create a pull request for.

2022-10-11 08:00 UTC, peppy commented
I'd probably move all the new localisable strings into `ToolbarStrings`, as each individual button / area is only going to have a couple each. Makes more sense to group.

https://github.com/ppy/osu/blob/5d8bd1de288efacf2481aa5f30f2bb2abdddedc4/osu.Game/Localisation/ToolbarStrings.cs#L8-L7

2022-10-12 04:55 UTC, peppy requested changes

2022-10-12 04:55 UTC, peppy commented on osu.Game/Localisation/ToolbarStrings.cs
> +        public static LocalisableString RulesetHeaderDescription => new TranslatableString(getKey(@"header_description"), @"play some");
This needs to take an argument, as depending on language the ruleset's name could move around in the sentence.

If you're using rider or visual studio, you should be able to use the bundled tool to create this:

![JetBrains Rider-EAP 2022-10-12 at 04 54 29](https://user-images.githubusercontent.com/191335/195253486-b0ab6666-d60a-4a46-a0c0-13d6059e660d.gif)

to create something like:

```csharp
        /// <summary>
        /// "play some {0}"
        /// </summary>
        public static LocalisableString PlaySome(string arg0) => new TranslatableString(getKey(@"play_some"), @"play some {0}", arg0);
```

2023-01-15 23:28 UTC, Joehuu commented
I'm going to take over this PR to ease PR count, but also because localisation is being added everywhere right now.

2023-01-17 08:22 UTC, peppy commented
Is this ready for review?

2023-01-17 08:25 UTC, Joehuu commented
Yeah, should be simple enough anyway.

2023-01-17 08:28 UTC, peppy approved these changes

2023-01-17 08:28 UTC, merged