Fix mod selection when switching from menu to mods panel
ppy/osu pull request #2079
Opened 2018-02-16 19:12 UTC by ProfessorLaw

Fixes #2018 
Each time you instanciate PlaySongSelect, it will bind a newly created modSelect.SelectedMods to game.SelectedMods.
The thing is it never gets unbound when exiting PlaySongSelect, causing weird issues when going back to it (it seemed to bind old values)

2018-02-18 05:47 UTC, peppy commented
Just to double-check, can you test this without your fix but with forcing a garbage collect after returning to the main menu (it's at the bottom of settings)?

If it's as you say, this should also result in correct behaviour.

2018-02-18 08:45 UTC, ProfessorLaw commented
You're right !
Forcing garbage collection from the settings fixes the issue when my fix is not applied

2018-02-19 00:47 UTC, peppy commented
Okay, that's good to know.

Wondering if we can apply a more universal fix for this one..

2018-02-19 06:03 UTC, smoogipoo commented
We really should force a GC on screen change...

2018-02-19 06:22 UTC, smoogipoo requested changes
For now I think we need to do this, this is also the reason why it's done to, e.g. `Beatmap` from inside OsuScreen. However I'd like to move this to OsuGame if possible, in the `Screen.Exited` event.

2018-02-20 02:53 UTC, peppy commented
Not sure if moving to that method is what smoogi was looking for.... but I'm not sure what he was looking for. I think it was better in the place it was before, personally.

2018-02-20 15:19 UTC, ProfessorLaw commented
@smoogipoo Did I do what you expected or did you think about something else?
@peppy As I don't have enough experience on the project yet, I don't go too far in the changes. So I'll just try to follow all advices for now ^^ We just all have to agree :smile:

2018-02-27 11:47 UTC, peppy commented
Please see #2129 for my proposed solution.

This issue roots deeper than expected, we'll need to apply some more changes code-wide to fix potential other cases of the same thing.

2018-02-27 11:47 UTC, closed without merging