Add a editable SkinEditor Element List
ppy/osu pull request #21119
Opened 2022-11-04 09:32 UTC by C0D3-M4513R

This pr will attempt to implement #21098 .

done:
 - [x] Add the initial list implementation
 - [x] Sync the list contents to the drawables onscreen
 - [x] Add Lists that can be minimised
 - [x] Allow items in the List to be selected from the editor.
 - [x] Allow items to be selected from the List.
 - [x] Fix naming of the elements in the editor list
 - [x] Add a drag and drop handler, or another way to move IDrawableListItem's
 - [x] Link the changes to elements onscreen
 - [x] Allow those changes to be saved and loaded to config
 - [x] ~Fix having to set a fixed height for the OsuScrollContainer inside DrawableList/RearrangeableListContainer~ I do not think, that this is possible to fix. Please correct me, if I'm wrong.
 - [x] Optional: Rework DrawableListItem to simplify Selection Logic
 - [x] Optional: Allow Nested lists. ~This would also require adding a way to group together items in the editor, since I need a representative item for the DrawableMinimizableList, if I wanted to add it to a DrawableList (due to how RearrangeableListContainer is structured).~ 
 - [x] When Switching Screens the names don't get instantly updated
 - [x] Add Tests
 - [x] Rework how Lists are minimised. I do not like the OsuCheckbox for this. Arrows might work, when looking at how the enum selector works.
 - [x] Test drag on nested lists.
 - [x] Fix the Static Height in DrawableList
 - [x] Raise some sort of event (which includes old, and new parent) when changing parents of elements
 - [x] Should `OnDragAction` continue to be customisable? - No, it shouldn't.

optional: 
 - Rework, how to highlight selected items in a list - still looks completly fine, and may be easier to read currently.
 - Add user creatable nested lists? - potentially not this pr

2022-11-08 07:43 UTC, peppy commented on osu.Game/Screens/Edit/List/DrawableContainer.cs
> +    public class DrawableContainer<T> : CompositeDrawable, IDrawableListItem<T>
This class name needs consideration.... It just can't be this.

2022-11-08 07:43 UTC, peppy commented on osu.Game/Screens/Edit/List/DrawableList.cs
> +    public class DrawableList<T> : CompositeDrawable, IDrawableListItem<T>
Is this something like `RearrangeableListContainer`? You might want to check whether you can already lean on an existing implementation like that.

2022-11-23 06:26 UTC, peppy commented
I think the general direction is good here, but it's very hard to review this change as it stands.

Here's a few pointers:
- How are you testing this? I'd hope to see some kind of test scene coverage to show how this interacts when there's more than one layer (and potentially nested layers).
- You mentioned having to give scroll container a height: this is correct. You probably want to make it `RelativeSizeAxes = Axes.Y` to have it expand to the containing grid container.
- I get that the checkbox to expand the list is temporary, but it's going to have to be replaced to get this in because it looks super weird at the moment. Maybe just use a simple `SpriteIcon` `+` and `-` (from fontawesome) for now?

2022-11-23 06:32 UTC, peppy requested changes
Very brief pass over code quality

2022-11-23 06:32 UTC, peppy commented on osu.Game/Screens/Edit/List/DrawableList.cs
> +                SelectAll(SelectionState.NotSelected);
This reads super weird. "select all in a not selected state"?

2022-11-23 06:32 UTC, peppy commented on osu.Game/Screens/Edit/List/DrawableList.cs
> +        }
All this stuff seems too custom. I'd expect the list to just be a `Container` and handle things that way.

2022-11-23 06:32 UTC, peppy commented on osu.Game/Screens/Edit/List/DrawableList.cs
> +        {
These overrides make no sense. One takes a drawable and one just..  takes a bool?

2022-11-23 06:32 UTC, peppy commented on osu.Game/Screens/Edit/List/IDrawableListItem.cs
> +        }
We generally avoid interface level default methods.

2022-11-23 06:32 UTC, peppy commented
The general code quality here isn't up to scratch with the rest of the project. I think it may pay to read around some of the other classes we have and get a bit more used to the code base. I think this is going to be hard to move forward at this rate.

2022-12-01 06:55 UTC, peppy commented
This is starting to feel quite usable.

Immediate note is that when you click a top level container and it selects all content, the item's visible selection state doesn't update after deselecting one (or all) of the elements:


https://user-images.githubusercontent.com/191335/204985875-c41b6c8d-0be7-4812-bcd3-61636b545953.mp4

2022-12-10 00:10 UTC, Feodor0090 commented
Something is wrong here.

Add something (default acc used) and something else (black box used)
![изображение](https://user-images.githubusercontent.com/53872073/206814045-c9421161-c384-4470-a6dc-31bc9c4ecfc5.png)

Black box is above everything, and it's in the bottom of list.

Then try to reorder it:
![изображение](https://user-images.githubusercontent.com/53872073/206814145-0b50f65d-60ce-430c-a6a0-dc9550c7d1ac.png)
![изображение](https://user-images.githubusercontent.com/53872073/206814162-83d4cb2a-1e14-40f7-a8b8-cc36fe23a653.png)

Now item in the bottom of list is under everything.

I checked "default" elements, they are ordered as "highest in list is the top in container":
![изображение](https://user-images.githubusercontent.com/53872073/206814456-f5a0b1f0-2fe5-4c50-8d3c-ff64a0ef5f3c.png)

Not sure which element should be above everything - top one or bottom one. Ignoring this, the only todo here is to add new elements in list on proper position (with current ordering to head, not to the end).

Blueprint ordering issue seems to be fixed by last commit.

2022-12-10 21:49 UTC, Feodor0090 commented
Now new things are under everything. Aside from subjective point that this is weird, it changes behaviour (before 2 last commits new ones were on top). You should probably fix this.
![изображение](https://user-images.githubusercontent.com/53872073/206876510-2401ea6a-4f70-4f61-a8c7-f3c46348bde5.png)

2022-12-10 21:58 UTC, Feodor0090 commented
Just noticed more weird thing: notice how elements are flipping their order each gameplay enter.

https://user-images.githubusercontent.com/53872073/206876770-2c2aab1c-41dd-46b9-a87f-9a9a8f89cdc7.mp4

2022-12-11 01:01 UTC, Feodor0090 commented
Could not find any more ways to break this yet.

Two more nitpicks:
1) margins:
![изображение](https://user-images.githubusercontent.com/53872073/206881473-c73b9953-f3b7-4b4a-aee4-fe109770f346.png)
2) add something and a black box. Try to drag black box in the list. Notice that slider and checkbox flickers each mouse movement. Seems that the settings panel is recreated each drag. Would be nice not to do it.

2023-02-03 08:01 UTC, peppy commented
This PR is unfortunately in a very hard place. The code style and sheer size of the PR (lines of code wise) makes it very hard to even start reviewing it. On the flip side, this *is* a component that we need for the skin editor, to both support depth adjustments and also in the future to support moving components between layers.

I don't really have any more to say for now, just thought I'd mention this.

2023-09-10 17:09 UTC, closed without merging