Fix distance snap grid not correctly snapping on non-1.0x reference velocities
ppy/osu pull request #21481
Opened 2022-12-01 09:32 UTC by peppy

Closes #21347.

Not 100% on this yet, PRing for more visibility and testing.

2022-12-01 19:56 UTC, bdach commented
Personally abstaining from reviewing this because my confidence in being able to tell what is correct behaviour is zero at this point.

2022-12-01 22:11 UTC, goodtrailer commented
Seems to work for fixing the relevant issue of circles not snapping to the visible DS grid.

Not sure if this belongs here or in a separate issue, but the problem I noticed in the linked issue was that the DS grid itself can be "unsnapped" if the previous sliderend is unsnapped (due to irregular SV, or simply changing the editor beat snap):

![osu_2022-12-01_13-56-35](https://user-images.githubusercontent.com/46171121/205167699-5027d23b-533a-4821-94ce-bdcbde658890.jpg)

The circle blueprint is correctly snapping to the white grid line, but the white grid line itself doesn't actually represent the white timeline tick. The white grid line instead represents a time (and distance) 4 quarter-beats away from the sliderend, which is an issue because the sliderend isn't on any tick. This also causes the weird alphas, since the true time value of the grid line is in between ticks:

https://user-images.githubusercontent.com/46171121/205169637-bf98ae7d-2d25-43b1-903c-cc82cd857c90.mp4

2022-12-02 02:25 UTC, goodtrailer requested changes

2022-12-02 02:25 UTC, goodtrailer commented on osu.Game/Rulesets/Objects/SliderPathExtensions.cs
> +            hitObject.Path.ExpectedDistance.Value = snapProvider?.FindSnappedDistance(hitObject, (float)hitObject.Path.CalculatedDistance) * hitObject.DifficultyControlPoint.SliderVelocity ?? hitObje
This needs to divide by `SliderVelocity` before passing `CalculatedDistance` into `FindSnappedDistance` as well. The slider does correctly snap, but now it sorta "snaps beyond" the control points, which is fixed by this:
```csharp
double calculatedDistance = hitObject.Path.CalculatedDistance;
double sliderVelocity = hitObject.DifficultyControlPoint.SliderVelocity;
hitObject.Path.ExpectedDistance.Value = snapProvider?.FindSnappedDistance(hitObject, (float)(calculatedDistance / sliderVelocity)) * sliderVelocity ?? calculatedDistance;
```

https://user-images.githubusercontent.com/46171121/205200544-2f207942-54e5-4b60-b226-698f0d27168b.mp4

2022-12-02 02:25 UTC, goodtrailer commented on osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
> +            HitObject.Path.ExpectedDistance.Value = HitObject.DifficultyControlPoint.SliderVelocity * (snapProvider?.FindSnappedDistance(HitObject, (float)HitObject.Path.CalculatedDistance) ?? (float
This can be simplified to `SliderPathExtensions.SnapTo(...)`, the formula is the same.

2022-12-02 07:15 UTC, peppy commented
> Personally abstaining from reviewing this because my confidence in being able to tell what is correct behaviour is zero at this point.

This is a valid response. My goal is to probably rewrite all of this, once things are in an amicably working state.

2023-05-01 17:18 UTC, OliBomby commented
I think this is a good temporary solution until it all gets rewritten.

2023-05-02 03:03 UTC, goodtrailer commented
Not sure if it's relevant anymore since everything is gonna be rewritten anyway, but a while back I did fix the issue I mentioned above https://github.com/ppy/osu/pull/21481#issuecomment-1334514023, here's the diff: https://github.com/peppy/osu/compare/fix-editor-distance-snap-again-again-again...goodtrailer:osu:fix-editor-distance-snap-again-again-again-again (it also incorporates the fixes to this PR that I mentioned in the review).

2023-05-02 03:18 UTC, peppy commented
@goodtrailer It looks like your solution is quite stand-alone from this PR, in which case are you willing to PR it? Would be easier to review if you do so.

2023-05-02 03:44 UTC, goodtrailer commented
It might be difficult to make it "standalone" because I (unfortunately) wrote the whole thing on top of all the changes in this PR (I was working off of this PR's branch). Do you want me to just PR the whole thing?

2023-05-02 03:57 UTC, peppy commented
Ah, didn't realise this. I'll push them to this branch and we can work from there.

2025-02-05 09:41 UTC, closed without merging