Include mod effects in values displayed by `BeatmapAttributeText`
ppy/osu pull request #21585
Opened 2022-12-09 01:29 UTC by C0D3-M4513R

closes https://github.com/ppy/osu/issues/21946

Applying a mod with a difficulty change did previously not update the values displayed in BeatmapAttributeText. This attempts to work around this, by taking heavy "inspiration" from `osu.Game.Screens.Select.Details.AdvancedStats` and `osu.Game.Screens.Select.BeatmapInfoWedge`.

Now the displayed mod statistics are the same in the Beatmap details section in the select screen, and in the values in BeatmapAttributeText.

One thing to keep in mind is that Length will currently not get updated at all, but that seems to be a known restriction currently.

2022-12-11 14:42 UTC, bdach requested changes

2022-12-11 14:42 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +        public BindableBool DifficultyAdjust { get; set; } = new BindableBool(true);
Should not be a setting. Either this PR is the wrong direction entirely and none of this is necessary, or the component as it is in `master` is plain wrong and this diff is required. Having this toggleable helps nobody.

2022-12-11 14:42 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +        private ModSettingChangeTracker modSettingChangeTracker = null!;
Should be annotated as nullable (as it initially is `null`, after all).

2022-12-11 14:42 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +                valueDictionary[BeatmapAttribute.StarRating] = (starRating?.Stars ?? -1).ToLocalisableString(@"F2");
Why is -1 used as the fallback value? This will be printed to the user. May as well use something like `"(not available)"` or anything.

2022-12-11 14:43 UTC, bdach commented
I will also say yet again that this component is getting very huge and complicated *very* quickly. Not happy to see increasing scope creep in this area from multiple directions.

2022-12-12 21:10 UTC, mk56-spn commented
@C0D3-M4513R 

Sorry for the wait, here ya go.

https://user-images.githubusercontent.com/74463310/207155164-ac13c855-3aee-420c-a516-2a9e14315a9d.mp4

2022-12-12 21:19 UTC, mk56-spn commented
> Can you please retest with changes in this pr added? I see from the settings that you are using regular lazer, which still has this issue.

all good now, sorry for the troubles

2023-01-03 16:59 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +        public BindableBool DifficultyAdjust { get; set; } = new BindableBool(true);
This was briefly [discussed in discord](https://discord.com/channels/188630481301012481/188630652340404224/1059872767555682405) today, and either this setting should not exist (and all values should be post-mod application), or there should be 2 sets of variables offered for pre- and post-mod values.

2023-01-03 17:07 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +        public BindableBool DifficultyAdjust { get; set; } = new BindableBool(true);
Well yes. The current implementation would probably have to somewhat improve as it is currently mighty inefficient and would only get worse. But it covers more use cases than the switch.

2023-01-11 17:29 UTC, bdach commented
> I wanted to make a new global cache that just saves these things and reuses them for `BeatmapAttributeText` and `BeatmapInfoWedge`

I don't really have the mental energy to argue over this too much - especially so that I was against merging this feature from the start precisely due to the scope creep that it has provoked - but I still don't think anything global like that is necessary.

I consider this PR as-is unmergeable, as it is adding a lot of complication to everything because `BeatmapAttributeText` is trying to coordinate everything instead of modularising the value fetch logic appropriately (which, again, *doesn't require global caching*). I described [a sketch](https://discord.com/channels/188630481301012481/188630652340404224/1062444624129560706) of how I imagine this working on discord but if I were to go into any more detail than that I'd end up writing the entirety of the solution which I don't want to do right now.

2023-01-21 23:02 UTC, bdach commented
There are too many contributions for me to get a thorough review on this as I consider this a low priority task. However at a very quick look at the current state I already don't think I'm going to like what is here now. The nine-something added members and +300 lines in `BeatmapAttributeText` alone tell me that this is likely not structured and modularised as I'd like to see it, and I cannot provide any better guidance without going to write this myself,  which I do not want to do at this time.

2023-07-05 04:55 UTC, peppy commented
This isn't the way forward. There's just too much complexity, as has already been stated. Needs to be reapproached without changing the whole structure of the component. It should not be required.

2023-07-05 04:55 UTC, closed without merging