Make all non-localized tooltips lowercase
ppy/osu pull request #21765
Opened 2022-12-22 21:40 UTC by revelsix

Step 1 of 3 in trying (again) to fix the inconsistent tooltip capitalization throughout the game. Other steps require changing localization files in osu-resources and osu-web (outlined in #21764). This change assumes all tooltip text (excluding mods and countries) should be lowercase, including tooltips that use multiple sentences, e.g.: 
![image](https://user-images.githubusercontent.com/45189851/209230739-59250eec-0f0d-4770-8958-1e6a7a2ba04b.png)

2022-12-23 20:35 UTC, Joehuu commented
I somewhat disagree with this direction of "styling" every tooltip to be *mostly all* lowercase. Personally, I prefer normalizing everything to sentence-case, even if it is the minority right now.

Apart from the multiple-sentence styling which doesn't sit right in my opinion (makes sentences harder to read), what happens to proper nouns? 
- There's a string here that has lowercase `windows`. Should it stay lowercase?
- I also saw the web-side PR. Should `show on GitHub` be `show on github` if the above stays?

2022-12-28 23:32 UTC, Joehuu requested changes
As above and just to mark this PR with changes requested.

2022-12-31 10:02 UTC, r00ster91 commented on osu.Game/Localisation/MouseSettingsStrings.cs
> +        public static LocalisableString HighPrecisionMouseTooltip => new TranslatableString(getKey(@"high_precision_mouse_tooltip"), @"attempts to bypass any operating system mouse acceleration. on w
```suggestion
        public static LocalisableString HighPrecisionMouseTooltip => new TranslatableString(getKey(@"high_precision_mouse_tooltip"), @"attempts to bypass any operating system mouse acceleration. on Windows, this is equivalent to what used to be known as ""raw input"".");
```
What about proper nouns?

2023-05-18 04:18 UTC, Joehuu commented
After looking at this again, I think we should use sentence-case. My reasons above are still the same, plus no other website/app is using lowercase. The 2+ sentence tooltip problem is unavoidable, and we shouldn't have case exceptions to sentences and non-sentences as that gets complicated.

@ppy/team-client thoughts before I attempt normalising everything to sentence-case?

2023-05-18 20:21 UTC, Joehuu commented
Closing as incorrect direction.

2023-05-18 20:21 UTC, closed without merging