Add skin support for hit judgements
ppy/osu pull request #2181
Opened 2018-03-07 09:24 UTC by peppy

Also makes sizing of skinned drawables more flexible.

2018-03-12 01:20 UTC, smoogipoo requested changes

2018-03-12 01:20 UTC, smoogipoo commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +                    legacyName = "hit300";
I don't like that we're polluting osu.Game with this stuff. This should be done individually for each legacy ruleset imo.

2018-03-12 01:20 UTC, smoogipoo commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +            Child = new SkinnableDrawable($"Play/osu/{legacyName}", _ => JudgementText = new OsuSpriteText
How about instead exposing a `virtual string GetResourceName(HitResult result) => "Play/osu/{result.ToString().ToLower()";`? Two reasons:
1. Eventually we're not going to have `Play/osu/`. When we move these resources to each gamemode they should exist as simply `Play/`.
2. Will allow us to override this lookup further depending on additional construction parameters (eg, per-key judgements in mania).

2018-03-12 01:20 UTC, smoogipoo commented on osu.Game/Skinning/LegacySkin.cs
> +                    .StoragePath;
Put this back on the same line.

2018-03-13 00:56 UTC, smoogipoo commented
<img width="584" alt="screen shot 2018-03-13 at 9 55 57 am" src="https://user-images.githubusercontent.com/1329837/37316845-c9aaa6da-26a4-11e8-8fc0-85cf1778c513.png">

Known issue? The text size is too small.

2018-03-13 03:48 UTC, peppy commented
Text size fixed via ppy/osu-framework#1459.

2018-03-13 03:58 UTC, smoogipoo approved these changes
looks ok to me

2018-03-13 03:58 UTC, merged