Implement "max PP" attribute in `BeatmapAttributeText`
ppy/osu pull request #22112
Opened 2023-01-10 15:00 UTC by cdwcgt

- [ ] depends on  https://github.com/ppy/osu/pull/21585

related to #22096 

move `CalculatePerfectPerformance` logic to `PerformanceCalculator` for easy reuse, and I think it's its best place

https://user-images.githubusercontent.com/34775378/211538591-73c2b3a4-31ed-49d7-b289-16ceb379cada.mp4

Let me know if there is a place where I need to write a test, because I can't find a place to write a test

2023-01-10 18:45 UTC, bdach requested changes

2023-01-10 18:45 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +            [BeatmapAttribute.MaxPP] = "Max PP", //There is currently no localized string for this value
you could... you know, make one

2023-01-10 18:45 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +            currentMods.BindValueChanged(s =>
handling mod changes is in scope of https://github.com/ppy/osu/pull/21585 and this pull does not adhere to the direction established therein (that both pre- and post-mod values should be available for use). so either this should be reverted and not handle mods, or this PR is hard-blocked until that one is merged

2023-01-10 18:45 UTC, bdach commented on osu.Game/Skinning/Components/BeatmapAttributeText.cs
> +            ScoreInfo score = new ScoreInfo(beatmap.Value.BeatmapInfo, beatmap.Value.BeatmapInfo.Ruleset) { Mods = currentMods.Value.ToArray() };
if the score is only manufactured to pass mods, then `CalculatePerfectPerformance` should just accept mods and not a score

2023-01-10 18:46 UTC, bdach commented
it is my opinion that this PR should not and cannot proceed until we sort out `BeatmapAttributeText` properly. the initial implementation was very simple and very naive, but the component is seeing a lot of changes that attempt to tack expensive computations onto it. the component should be properly refactored to support this in a way that does not require all values to be recomputed whenever literally anything changes, and manages state changes locally and optimally.

2023-08-31 15:19 UTC, cdwcgt commented
This PR is too old for now. need to a new pr to continue

2023-08-31 15:19 UTC, closed without merging