Fix juice stream droplets spawning in incorrect locations
ppy/osu pull request #2231
Opened 2018-03-16 06:22 UTC by peppy

Closes #2149.

2018-03-16 06:24 UTC, smoogipoo requested changes

2018-03-16 06:24 UTC, smoogipoo commented on osu.Game.Rulesets.Catch/Tests/CatchBeatmapConversionTest.cs
> -        [TestCase("basic"), Ignore("See: https://github.com/ppy/osu/issues/2149")]
Not intended?

2018-03-16 06:32 UTC, peppy commented on osu.Game.Rulesets.Catch/Tests/CatchBeatmapConversionTest.cs
> -        [TestCase("basic"), Ignore("See: https://github.com/ppy/osu/issues/2149")]
Not intended.

2018-03-16 08:04 UTC, peppy commented
Restored ignored test for now as there's deeper issues.

2018-03-20 10:35 UTC, smoogipoo commented
This seems okay for now. I'm a little bit weary of the minDistanceToEnd calculation, and if that matches stable, but need FastRandom usage to be fixed and additional tests to be done.

2018-03-20 11:06 UTC, smoogipoo approved these changes

2018-03-20 11:06 UTC, merged