Add empty space tap-streaming support for osu! ruleset on touchscreen devices
ppy/osu pull request #22375
Opened 2023-01-23 09:17 UTC by peppy

This is the one that mobile users have been waiting for.

I've tried to keep the implementation as simple as possible. The general rules are:

### If a touch occurs on a hit circle's receptor

- It is tracked as a direct touch and will be used for priority positional tracking.
- It will overwrite any existing direct touch.

### If a touch occurs **outside** all hit circle receptors

- If there is no direct touch, it will be used for positional tracking, replacing any existing non-direct touch.
- If positional tracking is from a direct touch, the **action for the direct touch will be automatically released**.

So in short, the caveat here is that the game will give the user one extra input if they tap on a hit circle directly then "stream" using two other fingers.

The only thing I'm not sure about is whether we should always alternate the left/right based on last action to make the key overlay look more balanced, or if it's fine as it is (currently if a user always releases the previous input before tapping again, they will all be `Left`). Maybe for another day. Definitely for another day.

Closes #4201.

https://user-images.githubusercontent.com/191335/214002833-47cbee25-7d68-4488-85c5-86fc6eb1dc72.mp4

2023-01-23 19:09 UTC, peppy commented on osu.Game.Rulesets.Osu.Tests/TestSceneTouchInput.cs
> +            // note that touch1 was never ended, but is no longer valid for touch input due to touch 2 occurring.
This is a minor change to existing behaviour, but I think it's actually better than what we had (stops any kind of positional feedback when more than one finger is on screen and moving at once).

2023-01-23 23:28 UTC, Susko3 requested changes
Once a `TrackedTouch` with `DirectTouch = true` is designated to be the `positionTrackingTouch` (hereinafter the 'pointer touch'), this empty space tap-streaming input method works well and behaves as expected.

My main concern is that for this to happen, the the pointer touch needs to be pressed directly on a circle (and that press counts as an `OsuAction`). This is counter-intuitive for the user, as the expected behaviour is that the pointer touch doesn't activate any `OsuAction`. For a user using this input method, it's intuitive to:
1. Initiate the pointer touch by first tapping on empty space (inside the playfield)
2. Move the pointer touch over a circle
3. Touch another finger(s) (usually outside the playfield) to use empty space tap-streaming for `OsuAction`s

The following diff feels good to play, and doesn't seem to break existing multitouch 'only tap on the circles' behaviour. (Most test fail though.)

```diff
diff --git a/osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs b/osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs
index 52b7f4c940..2db8d75d55 100644
--- a/osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs
+++ b/osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs
@@ -2,6 +2,7 @@
 // See the LICENCE file in the repository root for full licence text.
 
 using System.Collections.Generic;
+using System.Diagnostics;
 using System.Linq;
 using osu.Framework.Allocation;
 using osu.Framework.Bindables;
@@ -70,7 +71,20 @@ protected override bool OnTouchDown(TouchDownEvent e)
             {
                 // If no direct touch is registered, we always use the new (latest) touch for positional tracking.
                 if (positionTrackingTouch?.DirectTouch != true)
-                    positionTrackingTouch = trackedTouch;
+                {
+                    if (trackedTouch.DirectTouch || positionTrackingTouch == null)
+                        positionTrackingTouch = trackedTouch;
+                    else
+                    {
+                        // this touch is not a direct touch, so we treat it as the beginning of empty space tap-streaming
+                        // promote the existing touch into a direct touch, so that it sticks as the 'pointer touch'
+                        positionTrackingTouch.DirectTouch = true;
+                        Debug.Assert(positionTrackingTouch.Action != null);
+
+                        osuInputManager.KeyBindingContainer.TriggerReleased(positionTrackingTouch.Action.Value);
+                        positionTrackingTouch.Action = null;
+                    }
+                }
                 else
                 {
                     // If not a direct circle touch, consider whether to release the an original direct touch.
@@ -126,7 +140,7 @@ private class TrackedTouch
 
             public OsuAction? Action;
 
-            public readonly bool DirectTouch;
+            public bool DirectTouch;
 
             public TrackedTouch(TouchSource source, OsuAction? action, bool directTouch)
             {
```

Here's a little demo, focus on the black touch indicators on the left of the playfield. Ignore the square right-click indicator, that's just windows bugging out. (The miss at the end is my touchscreen lagging.)

https://user-images.githubusercontent.com/16479013/214174879-f8154e93-4685-4b75-a860-d4c88c543f03.mp4

2023-01-24 03:25 UTC, peppy commented on osu.Game.Rulesets.Osu/OsuInputManager.cs
> +            NonPositionalInputQueue.OfType<DrawableHitCircle.HitReceptor>().Any(c => c.ReceivePositionalInputAt(screenSpacePosition));
In the interest of keeping this implementation simple I'm against making any proposed changes for now. I should have left a note regarding this in the PR I guess.

I'm not against any improvements and the potential improvements we can add are very obvious, but they aren't happening in this PR>

2023-01-24 03:27 UTC, peppy commented on osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs
> +                    // If not a direct circle touch, consider whether to release the an original direct touch.
Can you explain which part is unclear? This still reads correct to me.

2023-01-24 03:30 UTC, peppy commented
> This is counter-intuitive for the user, as the expected behaviour is that the pointer touch doesn't activate any..

I did consider this, but again I'd prefer to change it as a follow-up if/when required. In all the video footage I watched of people playing on touch devices, finger based tracking was mostly only used for streams as it gets very tiresome to *always* be dragging. Maybe different when a stylus is involved, but I do want to get more user feedback.

I'd generally be against ALL touches resulting in a dragging touch as you have it coded. I'd probably base it on a minimum drag time and/or have a larger area lenience around hit circle receptors which are also considered direct.

2023-01-24 13:15 UTC, Susko3 commented on osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs
> +                    // If not a direct circle touch, consider whether to release the an original direct touch.
The "an" in "the an original" doesn't make sense to me. Also isn't this comment a bit misleading: nothing below the comment is "considering" whether to release the pressed action -- if there is an action to release, it'll unconditionally release it.

Also, due to the `positionTrackingTouch?.DirectTouch != true` check above, `positionTrackingTouch.DirectTouch` will always be `true` and should not be checked.

2023-01-25 05:47 UTC, peppy commented on osu.Game.Rulesets.Osu/UI/OsuTouchInputMapper.cs
> +                    // If not a direct circle touch, consider whether to release the an original direct touch.
I read over this multiple times and missed the completely incorrect "an" 😓 

I'll reword based on your feedback.

2023-01-25 20:19 UTC, Susko3 approved these changes
I've looked at some gameplay videos of people playing on phones, and it looks like this input method (as implemented) will work well for those.

I'll copy some of my unaddressed feedback to a separate issue.

2023-01-25 23:12 UTC, smoogipoo approved these changes

2023-01-25 23:12 UTC, merged