Fix beatmap listing potentially not sorting by relevance when searching via metadata
ppy/osu pull request #22449
Opened 2023-01-28 20:38 UTC by Joehuu

`Reset()` is also called in `BeatmapListingFilterControl`'s `LoadComplete()` as `resetSortControl()`:
https://github.com/ppy/osu/blob/e1e6d76f308e6187246ba415f5188ccd7595f058/osu.Game/Overlays/BeatmapListing/BeatmapListingFilterControl.cs#L154-L164

The above is executed first before one in `BeatmapListingSortTabControl` (also in `LoadComplete()`), which makes the `hasQuery` param false and resets the sort back to `Ranked`, so moved it to `load()`.

2023-01-30 18:40 UTC, bdach requested changes

2023-02-01 10:39 UTC, peppy commented
I've made a minor additional change of storing the two parameters as a tuple (and renaming slightly). Feels better this way.

2023-02-01 10:39 UTC, peppy approved these changes

2023-02-01 16:15 UTC, bdach approved these changes

2023-02-01 16:15 UTC, merged