Add ability to abort dangerous dialog button on hover lost
ppy/osu pull request #22604
Opened 2023-02-10 22:43 UTC by Joehuu

- Addresses https://github.com/ppy/osu/discussions/22594

| Before | After |
| --- | --- |
| ![osu!_126Oe5xogk](https://user-images.githubusercontent.com/35318437/218010280-3ff4dad9-4822-46fe-8f5a-6b04bf76e530.gif) | ![osu!_FcF2L6deyU](https://user-images.githubusercontent.com/35318437/218010085-1c61b345-433f-47e6-9dbf-a71dbfd1cbd3.gif) |

2023-02-11 02:07 UTC, peppy commented
It should probably continue on re-hovering if this is to be added.

2023-02-11 02:19 UTC, Joehuu commented
I had the changes for the rehover behavior, but I thought it wouldn't be something that's wanted. Will add back.

2023-02-11 16:22 UTC, bdach requested changes

2023-02-11 16:22 UTC, bdach commented on osu.Game/Overlays/Dialog/PopupDialogDangerousButton.cs
> +                lowPassFilter.CutoffTo(AudioFilter.MAX_LOWPASS_CUTOFF);
This is copied verbatim from `OnMouseUp()`; I'd argue that it shouldn't be, and it should instead be part of `AbortConfirm()` as I don't see a case in this class where you'd want to abort *without* sweeping the filter. Requires making it virtual, but I think it makes sense. Or you could split a local private method, although that is a little bit more confusing perhaps.

2023-02-12 13:43 UTC, bdach approved these changes

2023-02-13 11:40 UTC, peppy approved these changes

2023-02-13 11:40 UTC, merged