Fix automatic seeking
ppy/osu pull request #22686
Opened 2023-02-18 19:44 UTC by MaxKruse

fixes #22668 

Test for mania specifically included in `TestScenePlacementBeforeTrackStart`, unsure if another place would be better for this.

2023-02-18 22:21 UTC, bdach requested changes, later dismissed

2023-02-18 22:21 UTC, bdach commented on osu.Game/Screens/Edit/Editor.cs
> +        private Bindable<bool> editorSeekToHitobject;
nit: rename to `editorSeekToHitObject` (goes everywhere else too, I'll spare us both posting the same comment everywhere)

2023-02-18 22:21 UTC, bdach commented on osu.Game/Rulesets/Edit/HitObjectComposer.cs
> +        protected Bindable<bool> SeekToHitobject { get; private set; }
why `protected`? looks like `private` would suffice

2023-02-18 22:21 UTC, bdach commented on osu.Game/Rulesets/Edit/HitObjectComposer.cs
> +                // conditionally seek based on setting
remove comment - it restates the code and brings no value

2023-02-18 22:21 UTC, bdach commented on osu.Game/Localisation/EditorStrings.cs
> +        public static LocalisableString SeekToHitobject => new TranslatableString(getKey(@"seek_to_hitobject"), @"Seek to Object after placement");
random capitalisation

```suggestion
        /// <summary>
        /// "Seek to object after placement"
        /// </summary>
        public static LocalisableString SeekToHitObject => new TranslatableString(getKey(@"seek_to_hit_object"), @"Seek to object after placement");
```

\+ update references to match

2023-02-19 12:48 UTC, bdach reviewed
This needed more cleanup. I've cleaned up as much as I knew how to clean up, but I am going to need to get one UX thing past a second pair of eyes.

2023-02-19 12:48 UTC, bdach commented on osu.Game/Screens/Edit/Editor.cs
> +                                            new ToggleMenuItem(EditorStrings.SeekToHitObject)
This is in the "view" menu, but it isn't really a "view" option, so it kind of doesn't belong. Not sure what to do about this. @ppy/team-client your thoughts would be appreciated.

2023-02-19 12:48 UTC, peppy commented
@bdach is this ready for review?

2023-02-19 12:50 UTC, bdach commented
@peppy Yeah I was in the middle of getting through this when you typed the comment :sweat_smile: I think it should be relatively alright except for the one open question from the review above.

2023-02-19 13:30 UTC, peppy commented
One thing to note going forward is we will probably add an "auto advance" to osu! editor at some point, ie. one beat forward from actual placement. Which is slightly different to this option but also applied for the same reason.

So one way we could handle this is renaming the option to "Seek after placement" to generalise for that case to. In other words, remove the part which implies this will always seek *to the object specifically*.

2023-02-19 13:33 UTC, bdach commented
Sure, but to me that's still not really a "view" option, because it doesn't affect the editor visually like any other option in that menu, it changes its behaviour.

Could just repurpose the "view" menu into "options" and call it a day? Dunno. I don't much care, it can live in "view" for now, I just wanted to raise it as a point I find weird in how things are written right now.

2023-02-19 13:35 UTC, peppy commented
I think under "view" is fine for now until we have more menus. I wouldn't be wanting to add new top level menus just for one item yet.

2023-02-19 13:38 UTC, bdach commented
Ok, well, if we want to future-proof this for the auto-advance case we may want to swap the `bool` type of the setting for an actual enum. Not sure if it needs to happen right now.

2023-02-19 13:40 UTC, peppy commented
Well I was thinking more just change the text before it starts to get localised. I'd still hope it was a bool, but just reads as "Auto-seek on placement" or similar.

2023-02-19 13:51 UTC, bdach commented
Fair. Are you going to grab that or shall I?

2023-02-19 13:53 UTC, peppy commented
All yours, I think you'll get the wording better than I can anyway 😅

2023-02-19 14:08 UTC, bdach commented
I've attempted something, let me know if it meets your expectations.

2023-02-19 14:09 UTC, bdach approved these changes

2023-02-19 14:13 UTC, peppy approved these changes

2023-02-19 14:38 UTC, merged