Add ability to send selected skin components to front or back
ppy/osu pull request #22717
Opened 2023-02-22 09:27 UTC by peppy

An easy way of allowing the user to manage depth without creating a rearrangeable list display.

https://user-images.githubusercontent.com/191335/220578383-94699392-797a-41b1-b71d-00a2b408d046.mp4

2023-02-22 18:41 UTC, bdach commented
Code looks simple enough, but there are a few issues here:

- After bring-to-front/send-to-back, undo history is quite busted:

https://user-images.githubusercontent.com/20418176/220725821-4f9c93a8-39d5-45bf-b554-4961e6a48563.mp4

- When skin elements are brought to front, their labels momentally flash, and when skin elements are sent to back, the labels of *all other* elements momentally flash:

https://user-images.githubusercontent.com/20418176/220726488-cea80ffc-88ce-4138-a39d-44676bf7c86c.mp4

2023-02-22 18:42 UTC, bdach requested changes
as above

2023-02-23 12:11 UTC, peppy commented
I've improved the flashing a bit, but it's not going to be perfect with the current logic due to selection being lost once.

I think we can improve this further in the future.

2023-02-27 18:24 UTC, bdach approved these changes

2023-02-27 18:56 UTC, merged