Add group badges to list view
ppy/osu pull request #22744
Opened 2023-02-27 00:03 UTC by EXtremeExploit

Whenever there are no badges the class takes some extra space, so i check for any groups whenever the user changes and show/hide according to if there are groups present
![image](https://user-images.githubusercontent.com/30161277/221445540-7d49747d-6260-43ef-ad83-cf30540df983.png)

Still there is some extra spacing at the edges of the class but i am still learning how stuff works c:

2023-02-28 09:23 UTC, peppy commented
The supporter badge feels a bit big in comparison, but maybe it's okay. @arflyte can you confirm intentions here?

2023-02-28 22:08 UTC, stanriders commented
It should really be a part of https://github.com/ppy/osu/issues/22130. I haven't touched it yet because the designs turned out to be not quite polished, so I'm waiting for flyte to update it before going any further, including updating the list/brick views.

2023-03-01 03:53 UTC, peppy commented
I see. @stanriders what's your thoughts on this PR then? Should we look to merge as-is then fix the design issues as a follow up?

2023-03-01 10:08 UTC, stanriders commented
Well from the design side the supporter button definitely needs to be the same size as badges, it's something that should be done in this PR. Other than that - list view badges are supposed to be combined too, but since there's a lot of free space I think we can merge it as is for now and change it lated when flyte decides on how combining should work.

The code can benefit from some restructuring for future PRs tho

2023-03-01 10:37 UTC, stanriders requested changes

2023-03-01 10:37 UTC, stanriders commented on osu.Game/Users/ExtendedUserPanel.cs
> +        protected FillFlowContainer CreateGroupBadges()
I don't think this is required? You can just add it directly in the `UserListPanel`

2023-03-01 10:37 UTC, stanriders commented on osu.Game/Overlays/Profile/Header/Components/GroupBadgeFlow.cs
> +                    Hide();
This shouldn't really be here as the container will be 0x0 and invisible anyway
![image](https://user-images.githubusercontent.com/8269193/222115337-a6a0ae63-aa63-4c1f-8708-aada262bfaa5.png)

2023-03-01 10:37 UTC, stanriders commented on osu.Game/Users/ExtendedUserPanel.cs
> +            return groupBadgeFlow;
```suggestion
            return new GroupBadgeFlow
            {
                User = { Value = User }
            };
```

2023-03-01 10:37 UTC, stanriders commented on osu.Game/Users/UserListPanel.cs
> +                            CreateGroupBadges().With(badges =>
If you don't want fill flow container to add spacing when there are no badges then add the `GroupBadgeFlow` after the layout creation with `if (User.Groups?.Length > 0)`, similar to how supporter badge is added.

2023-03-01 10:39 UTC, stanriders commented on osu.Game.Tests/Visual/Online/TestSceneFriendDisplay.cs
> +                CoverUrl = "https://osu.ppy.sh/images/headers/profile-covers/c6.jpg",
There's a dedicated test scene for user panels - `TestSceneUserPanel`

2023-03-03 22:01 UTC, stanriders commented
![image](https://user-images.githubusercontent.com/8269193/222832713-606ef54e-619c-4767-ae96-67d1c3b2ce74.png)

The code is fine, but design-wise this needs some fixing:

- Supporter button is bigger than badges
- Nickname centering is incorrect (seems like it was centered to the hearts in the supported badge?)

![image](https://user-images.githubusercontent.com/8269193/222833303-ff17a9bf-5529-4023-b15d-1559990e2ca3.png)
New designs have all icons the same size so I think we should go the same way here

2023-03-04 04:30 UTC, frenzibyte commented
The nickname is probably not centred due to the extra space on top of the text for proper line alignment, which should be turned off for single labels. see `SpriteText.UseFullGlyphHeight`.

2023-03-07 09:16 UTC, peppy commented
@EXtremeExploit see above, are you able to apply the changes to this PR?

2023-03-07 14:20 UTC, EXtremeExploit commented
i've been trying but all my attempts to make them look the same without breaking didn't work, i need some advice on how to do it, else it could be merged without the size change

2023-03-08 15:40 UTC, stanriders commented
> i've been trying but all my attempts to make them look the same without breaking didn't work, i need some advice on how to do it, else it could be merged without the size change

Set `SupporterIcon`'s `Height` to 16, add `username.UseFullGlyphHeight = false;` to the `CreateUsername().With(username =>{})` block
![image](https://user-images.githubusercontent.com/8269193/223758512-837e7f34-cd84-4e69-8b4c-1db2dd824d88.png)

2023-03-08 18:28 UTC, stanriders approved these changes
Looks fine to me

2023-03-09 06:45 UTC, peppy approved these changes

2023-03-09 06:45 UTC, merged