Opening an extra osu! instance now raises the primary instance's window
ppy/osu pull request #22793
Opened 2023-03-05 12:41 UTC by maromalo

- Closes https://github.com/ppy/osu/issues/22519

When osu! is already running, opening another instance with a `osu://` URI param should open the link in the primary instance and raise/focus that window. In order to also do this when it's opened without an URI, I added the `osu://o` linktype which does nothing. This is disabled in debug builds to allow multiple instances.

2023-03-05 12:53 UTC, bdach commented
> In order to also do this when it's opened without an URI, I added the `osu://o` linktype which does nothing.

This is a weird implementation detail that will impact more than the IPC mechanism. Doing things this way means that someone can post an `osu://o` link in chat and... users that click on it will see the current window raised? Which is turbo-weird if you ask me.

I would like to see this removed. Possible avenue of doing this that I can see:

* Allow construction of `OsuSchemeLinkMessage` with a null `Link`
* Have `OsuSchemeLinkIPCChannel` raise the window instead when receiving any `OsuSchemeLinkMessage`, even if it has no `Link`
* If the message has a `Link`, then pass it onto the `linkHandler`
* Maybe even rename the channel and message to `OsuInstanceIPC{Channel,Message}` because they shouldn't really be about "osu! scheme links" at this point

2023-03-05 13:09 UTC, bdach commented
Test failures also look relevant.

2023-03-05 13:21 UTC, maromalo commented
> someone can post an `osu://o` link in chat and... users that click on it will see the current window raised? [...] I would like to see this removed.

Somehow the fact that those links can be shared flew way over my head. Will do.

2023-03-05 18:16 UTC, Susko3 commented
What this PR is missing:
- raising the window when files (eg. osz/osk) are imported

---

With the existing code structure, I think it'll be very hard to bring this PR to a mergeable state. The way `OsuSchemeLinkIPCChannel` and `ArchiveImportIPCChannel` currently work (subscribing to event in ctor) makes it hard to add functionally.

Additionally, there is an overlap between `OsuSchemeLinkIPCChannel`, `ArchiveImportIPCChannel` and `OsuGame.handleStartupImport()` (could also apply `OsuGameDesktop.fileDrop()`, but it's different enough). All of them are handling command line arguments, but each [slightly](https://github.com/ppy/osu/blob/78cc28d75f49eb7f7b6007278169d39473e37272/osu.Desktop/Program.cs#L135) [differently](https://github.com/ppy/osu/blob/0ad245e9e031468bbbb86e30f8f641397160bcab/osu.Game/OsuGame.cs#L1041). I think it would make sense to combine CLI argument parsing to a single method:

```cs
public partial class OsuGame
{
    protected bool HandleCommandLineArgs(string cwd, string[]? args)
    {
        // return true if a link was opened or if any files have been queued for import (regardless of the success of the import)
    }
}
```

In `Program.cs`, a new `OsuInstanceIPCChannel` could just pass trough the `cwd` and `args` to the OsuGame. It could then wait for the `bool` response to decide whether or not to early return (to avoid locally parsing the CLI arguments). Would use `SendMessageWithResponseAsync` (which doesn't yet exist in `IpcChannel<T>`, but does in `TcpIpcProvider`, requiring a framework change).

`Window.Raise()` could happen locally in `OsuGameDesktop`:

```cs
public partial class OsuGameDesktop
{
    protected override void LoadComplete()
    {
        base.LoadComplete();
        // ...
        osuInstanceIPCChannel = new OsuInstanceIPCChannel(Host);
        osuInstanceIPCChannel.MessageReceived += msg =>
        {
            bool handled = HandleCommandLineArgs(msg.Cwd, msg.Args);

            if (handled || (msg.Args.Length == 0 && !DebugUtils.IsDebugBuild))
                Window?.Raise();

            // this doesn't compile: for some reason `IpcChannel<T>` expects a raw `IpcMessage` here instead of `T`
            return new OsuInstanceIPCMessage { Handled = handled };
        };
    }
}
```

2023-03-06 22:17 UTC, Susko3 requested changes
Checked that debug and release work correctly when passing osu:// URI, `.osz` file and \~nothing\~.

Tests need updating.

2023-03-06 22:17 UTC, Susko3 commented on osu.Desktop/Program.cs
> +            Task<bool?> instanceTask = osuInstanceHandler.InstanceAsync(cwd, args);
Not sure on the naming, best I could come up with is:

```suggestion
            Task<bool?> messageAndResponseTask = osuInstanceHandler.SendAsync(cwd, args);
```

2023-03-07 12:12 UTC, maromalo commented
Both `TestSceneInterProcessCommunication` tests don't work. It sends the IPC message, but then the response has the error message `Unable to find a constructor to use for type osu.Game.IPC.OsuInstanceIPCMessage`. Adding a ctor with no parameters gets rid of the error but still returns a `null` response and nothing happens. I'm not sure what's going wrong, the IPC works properly outside the tests.

2023-03-07 13:13 UTC, Susko3 commented
You'll need to subscribe to `MessageReceived` in the test game, same as in `OsuGameDesktop`.

2023-03-07 13:50 UTC, maromalo commented
Forgot about that. Thank you.

2026-03-13 04:38 UTC, closed without merging

2026-03-13 05:28 UTC, peppy commented
head was deleted here, but FWIW i do still think we want this functionality.