Fix external links not working on Android
ppy/osu pull request #22790
Opened 2023-03-04 21:42 UTC by Joehuu

- Fixes https://github.com/ppy/osu/issues/22777

Will also make a PR framework-side but is not necessary for fixing osu!-side.

2023-03-04 23:12 UTC, bdach requested changes

2023-03-04 23:12 UTC, bdach commented on osu.Android/AndroidManifest.xml
> +		</intent>
The same intent query should be declared for the `mailto:` scheme, as [links of that scheme are also valid for use with `OpenUrlExternally()`](https://github.com/ppy/osu-framework/blob/32a7ef0ceb8eec36f9369a2d8b70cfd0c9c98366/osu.Framework/Extensions/ExtensionMethods.cs#L371-L376). Some places use these sorts of links (most notably wiki). Specifying `mailto:` allows the links to open the mail app to send an email out.

From experimentation, specifying `http` does not seem to be necessary (`https` suffices).

2023-03-04 23:13 UTC, bdach commented
Would like to get this into the upcoming hotfix release if possible, so expediting application of the review would be appreciated.

2023-03-05 03:51 UTC, Joehuu commented
I'll wait for another opinion. I might not be around for the hotfix release so feel free to apply the changes.

2023-03-05 12:34 UTC, bdach commented
The manifest merger thing seems pretty nice and looks to work, so I've applied (with minor stylistic adjustments), thanks 👍

2023-03-05 12:36 UTC, bdach approved these changes

2023-03-05 13:12 UTC, merged