Add score player avatar and flag
ppy/osu pull request #22797
Opened 2023-03-06 00:44 UTC by ItsShamed

Addresses #22761

Had this branch for while, but since it got broguht up, I decided it would be the time to PR it.
This is just a basic implementation with basic corner radius control. More could be added later but I think it's fine make the scope of this PR as little as possible.

> placeholder for video

As mentionned in https://github.com/ppy/osu/discussions/22761#discussioncomment-5202412, I'm not going to implement the `PlayerAttributeText` in this PR, because I don't want to add another `AttributeText` and I definitely do not agree with how the current text components work right now. (or at least this is not how I would see things being implemented both on a player and dev standpoint)

2023-03-06 03:10 UTC, Bruno5430 commented on osu.Game/Screens/Play/HUD/PlayerAvatar.cs
> +            MaxValue = 63,
I'm not a reviewer, but `MaxValue` shouldn't be 64?
If the size of the `PlayerAvatar` is 128 then the `MaxValue` of the corner radius should be half of it
(I tried it locally and it's not completely round when dragging the slider to the max, it's 2 pixels off)

2023-03-06 18:03 UTC, Bruno5430 commented
`CornerRadius` should not be 0 by default, it feels out of place with the rest of the components with those sharp corners.
If I had to chose for reference, I would go the profile overlay way
With a vector size of 120 (instead of 128) and a `CornerRadius` of 40
![2023-03-06_14-53](https://user-images.githubusercontent.com/111712756/223192638-73d1e884-5069-4285-a720-35ec61a0abd5.png)

2023-03-06 19:16 UTC, bdach requested changes

2023-03-06 19:16 UTC, bdach commented on osu.Game.Tests/Skins/SkinDeserialisationTest.cs
> +
```suggestion
```

2023-03-06 19:16 UTC, bdach commented on osu.Game/Screens/Play/HUD/PlayerAvatar.cs
> +            Precision = 0.01f
I'd argue that the values should be fractional/percentages here. The fact that the avatar has a size of 128 is completely arbitrary, and the avatar can be resized anyways. I'd do a range of [0. 0.5] and multiply that by 128 to get the final size.

2023-03-06 19:16 UTC, bdach commented on osu.Game/Screens/Play/HUD/PlayerAvatar.cs
> +            CornerRadius.BindValueChanged(e => avatar.CornerRadius = e.NewValue);
```suggestion
            CornerRadius.BindValueChanged(e => avatar.CornerRadius = e.NewValue, true);
```

2023-03-07 08:03 UTC, peppy approved these changes, later dismissed

2023-03-07 08:33 UTC, ItsShamed commented on osu.Game/Screens/Play/HUD/PlayerAvatar.cs
> +        }
This should probably be also moved to BDL to keep consistency with 5e90b67be09b842a9fb4b7114f49e4463afdce52

2023-03-07 08:41 UTC, peppy approved these changes, later dismissed

2023-03-07 18:48 UTC, bdach commented
Applied one more change with the end goal of having the corner radius setting show as percentage (https://github.com/ppy/osu/pull/22797/commits/7ade525eef4a3c887de1d50123682140ee9c605a).

Seems alright otherwise.

2023-03-07 18:48 UTC, bdach approved these changes

2023-03-07 19:21 UTC, merged