Update osu!mania argon colours to match new proposal
ppy/osu pull request #22814
Opened 2023-03-08 11:04 UTC by peppy

PRing this for visibility.

- [ ] Pending feedback at https://github.com/ppy/osu/discussions/21996#discussioncomment-5240235.

2023-03-08 20:42 UTC, bdach requested changes

2023-03-08 20:42 UTC, bdach commented on osu.Game.Rulesets.Mania/Skinning/Argon/ManiaArgonSkinTransformer.cs
> +                        default: throw new ArgumentOutOfRangeException();
As caught by CI, this doesn't work with the dual stages mod. The switch should be over `column % 2, 3, 4...` in each of the column count cases here.

2023-03-15 08:19 UTC, peppy commented
Haven't gotten any feedback on the colour choices so i've gone ahead and fixed 3k with some arbitrary choices.

2023-03-20 17:25 UTC, bdach approved these changes

2023-03-20 18:27 UTC, merged

2023-04-04 03:36 UTC, yuuiko commented
I'll repost this here for visibility

The colours have changed after some discussion. This set has one like and no further comments:


> yet another revision after a bit more 7K playing. I think this is the most intuitive and consistent yet.

- 3K new colour scheme (purely aesthetic, idea is to match beatmap difficulty gradient, also it matches purple middle too)
- 6K focus on middle fingers: 🟩🟦🟩 🟥🟧🟥 (different left and right to differentiate the middle two columns)
- 7K focus on middle fingers: 🟥🟧🟥 🟪 🟥🟧🟥 The outer two (🟥ring 🟧middle) are also consistent with 8K above.
- 8K up more consistent - 🟪pinky, 🟥ring, 🟧middle, 🟨/🟩🟦pointer always.

<img width="892" alt="229263798-3fc200af-4e6a-4e64-af9a-9a7c10107182" src="https://user-images.githubusercontent.com/50823728/229680921-65a4de2f-6ba2-4aaf-8488-d043df9acb76.png">