Add rotation snapping to editor selection
ppy/osu pull request #23156
Opened 2023-04-07 23:58 UTC by Micha-ohne-el

This PR adds 15° snapping to the rotation of the editor selection while holding shift.

Why shift? It was used for snapping in other places too (e.g. `osu.Framework.Graphics.UserInterface.SliderBar` snaps to its `KeyboardStep` when dragging while holding shift).

Why 15°? Completely arbitrary but it felt right I guess..?

It also fixes two small issues with the previous wrapping algorithm used:
1.  A half-turn rotation used to show up as -180° instead of 180°.
    This was not noticeable until now, because it wasn't possible to rotate by exact amounts.
2.  Rotating more than 180° in one drag event would overwhelm the algorithm and cause the value to go outside its desired range.
    This happened to me a couple of times during testing when spinning the selection really fast.

These fixes come at a small cost: The wrapping now unconditionally performs a division (modulo), which may be marginally slower than before (immeasurable, I would imagine).
I wouldn't be surprised if the removal of the if-statements increased the performance by more than the modulo decreases it.

2023-04-08 00:14 UTC, Micha-ohne-el commented
I unfortunately couldn't run `InspectCode.sh`. I'm getting an error message, but googling that leads to an open issue at the dotnet runtime itself, so I didn't troubleshoot much.
The code style *should* be fine, I apologize if it isn't.

2023-04-08 01:42 UTC, peppy commented
I've fixed the basic code quality issues. This is feeling pretty good, but one major UX issue I noticed is that pressing (or releasing) shift doesn't update that snap. I think it should trigger an update of rotation so you can see the angle snapping and unsnapping to give better feedback.

2023-04-08 01:43 UTC, peppy requested changes
As proposed.

2023-04-08 04:25 UTC, bdach commented
This was [attempted before](https://github.com/ppy/osu/pull/21368) but was then rejected for being too obscure and arbitrary. What's changed?

2023-04-08 10:43 UTC, Micha-ohne-el commented
> Also optionally, I'd update the tooltip to have a  (snapped) included when snapping to an angle.

Will do.

> pressing (or releasing) shift doesn't update that snap. I think it should trigger an update of rotation so you can see the angle snapping and unsnapping to give better feedback.

Not sure what you mean, I did implement that and it does work for me. See the added `OnKeyDown` and `OnKeyUp` overrides. Did I make a mistake?

https://user-images.githubusercontent.com/68816703/230716820-1e4d4bf2-1bf8-4351-9b3a-e79e784bb198.mp4

2023-04-08 11:25 UTC, MaxKruse commented
To chime in from a mapper's perspective coming from stable:

Increments in 15° work *ok*, but steps such as 36°, 72° (for pentagons) are extremely useful in mapping and wouldnt be able to be hit with this. I think a different snap step should be used to hit more frequently used rotations that are feasibly used, i'd recommend a step of 18 since it divides better into commonly used rotation angles.

2023-04-08 12:08 UTC, Micha-ohne-el commented
@MaxKruse I personally (a bit of mapping experience) think 15° is more intuitive and more broadly useful than 18°, but I'd be open to change it to whatever number is best.

I think ideally this should be configurable. The editor already has a section “Snapping” in the sidebar on the right, maybe a dropdown of common values would be good? Or an integer slider ranging from 1° to 45°? Something like that?
I'm just throwing ideas around here, maybe someone can think about this more.

I just want to say that while I would love to make this configurable, I don't feel qualified to do that myself. I don't have the time to familiarize myself with the code enough. This PR is simple enough for me. I don't want to bite off more than I can chew, so maybe we leave it as a fixed number (be it 15 or 18) for now and open an issue to make it configurable in the future?

2023-04-08 12:20 UTC, Micha-ohne-el commented
> Also optionally, I'd update the tooltip to have a (snapped) included when snapping to an angle.

Added.

I made the string localizable, including the `0.0°` part. Not sure if that's actually smart, so I would like to hear some feedback on it. Happy to change it back at any time.

2023-04-08 13:34 UTC, peppy commented
I think 15 degrees is a better starting point. We can figure a way to allow changing the snap angle in the future.

> This was [attempted before](https://github.com/ppy/osu/pull/21368) but was then rejected for being too obscure and arbitrary. What's changed?

Shift definitely works better than control, and an angle of 15 degrees feels more correct. I've checked a few image editing apps and they match both of these points. Not sure why I closed the previous PR rather than suggesting changes, but I'm pretty happy with this one this time around.

> Not sure what you mean, I did implement that and it does work for me. See the added `OnKeyDown` and `OnKeyUp` overrides. Did I make a mistake?

It wasn't working for me. I've pushed some changes that seem to fix it, though.

2023-04-10 13:12 UTC, bdach commented
I've simplified one function (6fec476147b04d30be33bcba642c262fd6a8c811) and also fixed the localisations which had no chance of ever working (73bd0feef58ed190df4317b507a9a4cae882fa53). Tip: every time you call `.ToString()` on a `LocalisableString`, you break localisation.

Seems to work well enough otherwise.

2023-04-10 13:12 UTC, bdach approved these changes

2023-04-10 15:45 UTC, peppy approved these changes

2023-04-10 15:45 UTC, merged