Add progressive DT/HT mod multipliers
ppy/osu pull request #23177
Opened 2023-04-10 04:45 UTC by smoogipoo

Resolves https://github.com/ppy/osu/issues/22699

For DT, the multiplier is in the range [1.0, 1.2].
For HT, the multiplier is in the range [0.5, 0.9].

- For DT, I intended to make the multiplier for 1.5x speed as close to 1.12 as possible, and it now sits at 1.1x.
- For HT, I took a bit of a liberty since the original 0.3 multiplier doesn't really correspond to anything. In this case, I made it scale in increments of 0.1, which is still harsher than DT's scaling but not as harsh as the original multiplier. Something similar to the original multiplier can be achieved with 2x scaling, however it would result in 0.5x having a multiplier of 0 which doesn't feel right.

2023-04-10 05:00 UTC, frenzibyte requested changes

2023-04-10 11:42 UTC, bdach approved these changes

2023-04-10 12:27 UTC, peppy approved these changes

2023-04-10 12:27 UTC, merged

2023-04-16 08:33 UTC, cdwcgt commented
I'm a little bit doubt, that is to say, the default HT speed 0.75 has the same multiplier as the adjusted speed to 0.7, but obviously 0.7 is easier?