Make VisualTests/nUnit work again
ppy/osu pull request #2321
Opened 2018-03-28 03:40 UTC by peppy

WIP, needs solution configuration and vscode project updates.

2018-03-28 06:58 UTC, peppy commented
Dropping this here as a current issue (vs2017 nuget restore fails, command line works fine): https://github.com/NuGet/Home/issues/4706

2018-03-29 03:36 UTC, smoogipoo requested changes

2018-03-29 03:36 UTC, smoogipoo commented on osu.Desktop/osu.Desktop.csproj
> -    <FileVersion>0.0.0.0</FileVersion>
I don't think you want to remove these two versions - they're used during deploy.

2018-03-29 03:58 UTC, smoogipoo approved these changes

2018-03-29 03:58 UTC, merged