Make wiki content follow the current language setting
ppy/osu pull request #23296
Opened 2023-04-23 15:19 UTC by cdwcgt

Wiki content now redirects to the language version of the current game if not specified.
If there is no corresponding translation for the specified content, the English version will be returned (solved by osu-web)

But it will not show the prompt that there is no translation for the current language, and it cannot be added through existing methods, because he is not in markdown but to judge by `available_locales` array (which include the list of supported language)

`WikiNoticeContainer` and markdown are highly coupled, so it cannot be solved by directly adding after judgment.

When changing languages, the page will be re-refreshed to apply the language settings.

Finally, the language that use unicode characters will have a line break problem when displaying the main page, but it is not within the scope of this pr I think

![image](https://user-images.githubusercontent.com/34775378/233847740-375af5af-c57a-4d21-8b7b-18a573bd635d.png)

2023-04-25 11:37 UTC, cdwcgt commented
I'm planning to add a selector for it and have localization issues (zh-tw <=> zh-hant) to work out, so going to draft for now

2023-05-03 03:03 UTC, peppy requested changes

2023-05-03 03:03 UTC, peppy commented on osu.Game/Overlays/Wiki/WikiLanguageDropdown.cs
> +    public void UpdateDropDown(APIWikiPage page)
Dropdown, not DropDown

2023-05-03 03:03 UTC, peppy commented on osu.Game/Overlays/Wiki/WikiLanguageDropdown.cs
> +        foreach (string langString in page.AvailableLocales)
```suggestion
        foreach (string locale in page.AvailableLocales)
```

2023-05-03 03:03 UTC, peppy commented on osu.Game/Overlays/WikiOverlay.cs
> +            Header.LanguageDropdown.UpdateDropDown(response);
I'd rather the two parameters are passed through rather than the whole response.

2023-05-03 03:03 UTC, peppy commented on osu.Game/Overlays/Wiki/WikiLanguageDropdown.cs
> +    }
This could probably be moved to the `WikiOverlay` level, as it has the same bindable available there.

2023-06-06 09:14 UTC, peppy commented
I'm not sure about just plopping a huge dropdown where it currently is. It feels way too present for something that's probably going to be used by 1 user ever.

2023-06-07 13:25 UTC, cdwcgt commented
you mean let this dropdown menu more like osu-web or we don't need it?

2023-06-08 00:22 UTC, frenzibyte commented
Yes, right now it's too large compared to the wiki overlay. Making it look like the osu-web variant would be slightly better, but altering it further to only display the flag in idle state would probably be even better (something similar to the language button next to the profile in osu-web).

2025-09-15 00:29 UTC, cdwcgt commented
rewrite

2025-09-15 00:29 UTC, closed without merging