Add support for replay mods
ppy/osu pull request #2400
Opened 2018-04-13 13:58 UTC by tgi74

Adds a way to convert a mod enum to Mod objects, then bind them to the player Mods

2018-04-13 15:39 UTC, Frontear commented
May I ask what this aims to accomplish?

2018-04-15 14:35 UTC, peppy commented on osu.Game/OsuGame.cs
> +            Beatmap.Value.Mods.BindTo(new Bindable<IEnumerable<Mod>>(s.Mods));
You probably don't want this to be a `BindTo`, but just a set.

2018-04-16 11:43 UTC, smoogipoo requested changes

2018-04-16 11:43 UTC, smoogipoo commented on osu.Game/Rulesets/Ruleset.cs
> +        public abstract IEnumerable<Mod> GetLegacyModsFor(LegacyMods mods);
* Virtual, not abstract.
* Rename to `ConvertLegacyMods`.
* xmldoc something like `Converts mods from legacy enum values. Do not override if you're not a legacy ruleset.`

2018-04-16 11:43 UTC, smoogipoo commented on osu.Game/Beatmaps/Legacy/LegacyMods.cs
> +    }
Use the following instead:
```
[Flags]
public enum Mods
{
    None                   = 0,
    NoFail                 = 1 << 0,
    Easy                   = 1 << 1,
    TouchDevice            = 1 << 2,
    Hidden                 = 1 << 3,
    HardRock               = 1 << 4,
    SuddenDeath            = 1 << 5,
    DoubleTime             = 1 << 6,
    Relax                  = 1 << 7,
    HalfTime               = 1 << 8,
    Nightcore              = 1 << 9,
    Flashlight             = 1 << 10,
    Autoplay               = 1 << 11,
    SpunOut                = 1 << 12,
    Relax2                 = 1 << 13,
    Perfect                = 1 << 14,
    Key4                   = 1 << 15,
    Key5                   = 1 << 16,
    Key6                   = 1 << 17,
    Key7                   = 1 << 18,
    Key8                   = 1 << 19,
    FadeIn                 = 1 << 20,
    Random                 = 1 << 21,
    Cinema                 = 1 << 22,
    Target                 = 1 << 23,
    Key9                   = 1 << 24,
    KeyCoop                = 1 << 25,
    Key1                   = 1 << 26,
    Key3                   = 1 << 27,
    Key2                   = 1 << 28,
}
```

2018-04-16 11:43 UTC, smoogipoo commented on osu.Game.Rulesets.Catch/CatchRuleset.cs
> +
Extra newline.

2018-04-16 11:43 UTC, smoogipoo commented on osu.Game.Rulesets.Osu/OsuRuleset.cs
> +
Extra newline.

2018-04-18 05:06 UTC, smoogipoo approved these changes

2018-04-18 05:06 UTC, smoogipoo commented
Looks good to me 👍

2018-04-18 05:09 UTC, merged