Add 'End replay' button
ppy/osu pull request #2430
Opened 2018-04-20 09:55 UTC by UselessToucan

I want to be able to exit replay using mouse.
https://www.youtube.com/watch?v=LnXfhS0o_PQ

2018-04-20 09:59 UTC, peppy commented
We really need something like this for play modes too. @arflyte anything in mind?

2018-04-20 10:10 UTC, arflyte commented
An "exit" button for play mode and replay?

2018-04-20 10:11 UTC, peppy commented
Some mechanism to exit gameplay, for touch users for instance.

2018-04-20 11:07 UTC, arflyte commented
Haven't worked on touch interface elements yet. Use this for now, will revisit the buttons again later.

![spectator-screen](https://user-images.githubusercontent.com/3632750/39047701-cfb2563c-44d5-11e8-8576-4b0639655c36.jpg)

To quit, player have to hold the button for 1s. "Hold to Quit" fades away after 5s. It's either "Quit" or "Resign", depends on the mode.

On hold, the action icon becomes bigger, "Hold to Quit" is visible again, and progress ring appears.

![ee3397bea7](https://user-images.githubusercontent.com/3632750/39047691-c879b59a-44d5-11e8-9e23-2b8fa303f835.png)

2018-04-20 11:09 UTC, peppy commented
Note that this should be displayed in both play and replay, but probably doesn't need to completely fade during replay.

During play it should fade out until the cursor is hovering it and then appear again.

2018-04-21 17:32 UTC, UselessToucan commented
Looks ok to me
https://www.youtube.com/watch?v=lg4_EXMZiSs

However I don't know what to do with this new HoldToQuit UI element during actual gameplay.
1. As osu! standard player I just don't need this thing.
2. During gameplay `Exit` call causes player to pause(pause != quit). https://www.youtube.com/watch?v=RiqKzdcun48

2018-04-21 17:35 UTC, peppy commented
Where's the test case?

2018-04-21 17:37 UTC, UselessToucan commented
Not written yet. :(

2018-04-21 17:37 UTC, peppy commented
How did you even make this component without a test case? Please read the wiki regarding how to develop for this project before going any further.

2018-04-21 17:39 UTC, peppy commented
This whole thing can be done using transforms and without a clock or whatever.

```csharp

onMouseDown
{
    ring.FillTo(1, duration).OnComplete(_ =>
    {
        // exit
    });
}

onMouseUp
{
    ring.FillTo(0, duration/4); // interrupts the other transform and causes the exit to never occur.
}

```

2018-04-28 16:34 UTC, peppy commented
Did you see my comment above? It would clean up the implementation considerably.

2018-04-28 17:00 UTC, UselessToucan commented
I saw your comment, but I don't know how to implement this transform. :(

2018-05-02 09:56 UTC, smoogipoo reviewed
Needs some work on the design, but let's go with these reviews for now.

2018-05-02 09:56 UTC, smoogipoo commented on osu.Game/Screens/Play/Player.cs
> +            hudOverlay.HoldToQuit.Button.ExitAction = Exit;
Would rather that the button wasn't exposed. Make an `Action` property in `HoldToQuit` which proxies the passed value into the button. Make the button itself private.

2018-05-02 09:56 UTC, smoogipoo commented on osu.Game/Screens/Play/HUDOverlay.cs
> +            Margin = new MarginPadding { Bottom = Progress.Size.Y * 1.25f, Right = 5 }
Shouldn't be relative to progress. Just make it 70 or something.

2018-05-02 09:56 UTC, smoogipoo commented on osu.Game/Screens/Play/HUD/HoldToQuit.cs
> +    public class HoldToQuit : FillFlowContainer
Rename to `QuitButton`.

2018-05-02 09:56 UTC, smoogipoo commented on osu.Game/Screens/Play/HUD/HoldToQuit.cs
> +        public class HoldToQuitButton : CircularContainer
Rename to `Button`, make private.

2018-05-02 09:56 UTC, smoogipoo commented on osu.Game/Screens/Play/HUDOverlay.cs
> +        protected virtual HoldToQuit CreateHoldToQuit() => new HoldToQuit
Rename to `CreateQuitButton`.

2018-05-02 09:56 UTC, smoogipoo requested changes
as commented

2018-05-21 17:12 UTC, peppy commented
@UselessToucan highly recommend you check my code changes for this.  look how elegant the shared logic is now

2018-05-22 06:45 UTC, smoogipoo requested changes

2018-05-22 06:45 UTC, smoogipoo commented on osu.Game/Screens/Play/HUD/QuitButton.cs
> +            float adjust = Vector2.Distance(GetContainingInputManager().CurrentState.Mouse.NativeState.Position, button.ScreenSpaceDrawQuad.Centre) / 200;
As discussed, let's use ReceiveMouseInputAt() => true here.

2018-05-22 06:45 UTC, smoogipoo commented on osu.Game/Screens/Play/HUD/QuitButton.cs
> +            Alpha = stayVisible ? 1 : Interpolation.ValueAt(elapsed, Alpha, MathHelper.Clamp(1 - adjust, 0.04f, 1), 0, 200, Easing.OutQuint);
We'll want a debounce, otherwise it's going to trigger readily for 4:3 players.

2018-05-22 06:45 UTC, smoogipoo commented on osu.Game/Screens/Play/HUD/QuitButton.cs
> +            Alpha = stayVisible ? 1 : Interpolation.ValueAt(elapsed, Alpha, MathHelper.Clamp(1 - adjust, 0.04f, 1), 0, 200, Easing.OutQuint);
Also this affects the alpha while the pause screen is active, looks pretty weird.

2018-05-22 06:45 UTC, smoogipoo commented on osu.Game/Graphics/Containers/HoldToCofirmContainer.cs
> +    public abstract class HoldToCofirmContainer : Container
HoldToCo **n** firmContainer

2018-05-22 06:52 UTC, peppy commented on osu.Game/Screens/Play/Player.cs
> -                        RulesetContainer.Cursor?.CreateProxy() ?? new Container(),
Yeah, I think it feels better and makes more physical sense

![image](https://user-images.githubusercontent.com/191335/40346550-2cd176e8-5dd8-11e8-82de-84bddf76e115.png)

2018-05-22 06:53 UTC, peppy commented on osu.Game/Screens/Play/HUD/QuitButton.cs
> +                // temporarily unbind as to not look weird during flash animation.
not sure i follow

2018-05-22 06:55 UTC, peppy commented on osu.Game/Screens/Play/HUD/QuitButton.cs
> +                pendingAnimation = true;
no, it's used to stop a second confirmation while animatng (see it's only usage)

2018-05-22 06:57 UTC, peppy commented on osu.Game/Screens/Play/HUD/QuitButton.cs
> +                           .OnComplete(a => circularProgress.FadeOut(100).OnComplete(_ =>
that's intended (it's not flashing, just a fade out). i guess we should add special behaviour for a user continuing to hold the mouse button down

2018-05-22 06:59 UTC, smoogipoo commented on osu.Game/Screens/Play/Player.cs
> -                        RulesetContainer.Cursor?.CreateProxy() ?? new Container(),
So you're fine with it cursor being below:

1. Leaderboard
2. Key counters

?

I think we need to discuss what the scope of a hud is going to be. Should the hud handle combo pop-in images?

2018-05-22 07:47 UTC, peppy commented
All fixed 👍

2018-05-22 09:06 UTC, smoogipoo approved these changes
lgtm

2018-05-22 09:17 UTC, merged