Integrate past usernames tooltip to user profile overlay
ppy/osu pull request #24782
Opened 2023-09-11 13:37 UTC by ItsShamed

Closes #24737

![osu Game Tests_8fWne5qUrk](https://github.com/ppy/osu/assets/39100084/4ef5224d-a166-44a8-84a4-1868e946c6bf)

Just a matter of tweaking size and colour to match web as close as possible.

2023-09-11 13:55 UTC, bdach requested changes

2023-09-11 13:55 UTC, bdach commented on osu.Game/Graphics/OsuColour.cs
> +        public readonly Color4 B6 = Color4Extensions.FromHex(@"1c1719"); // hsl(333,10%,10%)
This is not a thing that should need adding. The colour you want already exists as `Background6` in `OverlayColourProvider` instead, I'm pretty sure.

2023-09-11 13:55 UTC, bdach commented on osu.Game/Overlays/Profile/Header/Components/PreviousUsernames.cs
> +                                AlwaysPresent = true,
Why? Every `AlwaysPresent` usage should ideally come with explanation. Ideally as an inline comment.

2023-09-11 23:51 UTC, Joehuu commented
I'd hope that this would overlap the cover (like web) to make it look better popping out

![firefox_o5yMdcEBKh](https://github.com/ppy/osu/assets/35318437/2c3af9ff-809e-4f21-bf18-151c500f7575)

2023-09-11 23:59 UTC, ItsShamed commented
Well, the problem comes from the layout itself: it's too low, and it's even lower when the user does not have a title.

You can test adding a title to the user to see the difference:
```diff
diff --git a/osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs b/osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
index 4f28baa849..2b32f9f653 100644
--- a/osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
+++ b/osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
@@ -133,7 +133,8 @@ public void TestPreviousUsernames()
                         Data = Enumerable.Range(2345, 85).ToArray()
                     },
                 },
-                PreviousUsernames = new[] { "tsrk.", "quoicoubeh", "apagnan", "epita" }
+                PreviousUsernames = new[] { "tsrk.", "quoicoubeh", "apagnan", "epita" },
+                Title = "Random title"
             }, new OsuRuleset().RulesetInfo));
         }
     }
```


![image](https://github.com/ppy/osu/assets/39100084/a64b8ed9-a767-438d-ae06-f86505c93c24)

I don't plan to deal with that in this PR.

2023-09-12 00:00 UTC, ItsShamed commented
I could make it offset upwards a little bit like in web, but that doesn't look right imo. Unless stated otherwise.

2023-09-12 06:54 UTC, peppy approved these changes
Probably fine.

2023-09-12 08:16 UTC, merged