Made it so that time display adjusts its self based on current time.
ppy/osu pull request #2487
Opened 2018-05-02 19:51 UTC by Qapples

When there is < 10 minutes, timer displays m:ss, when it is above 10 minutes, it displays mm:ss, and so on. This also happens with the hours and time remaining.
Can't seem to find a way to combine this pull request with the one I posted before, so I am making a new one. I'll reference this one in the orignal post.
This was suggested by swoolcock.
#2475

2018-05-04 07:45 UTC, peppy commented
Why are there two PRs open for the same thing (this and #2475)?

2018-05-04 21:57 UTC, Qapples commented
Aergwym explained my situation (somehow) perfectly on the discord. Not sure if you saw it or not. https://gyazo.com/c5bfae98412f5001b67413bee1378d47

2018-05-05 00:55 UTC, peppy commented
Please close one then. And check my feedback before doing so, because it is not applied to either.

2018-05-06 12:13 UTC, peppy commented
As mentioned in #2475, please keep it counting in minutes, not hours.

2018-05-09 04:26 UTC, smoogipoo requested changes

2018-05-09 04:26 UTC, smoogipoo commented on osu.Game/Screens/Play/SongProgressInfo.cs
> +                timeLeft.Text = "-" + Math.Floor(TimeSpan.FromMilliseconds(timeRemain).TotalMinutes) + ':' + TimeSpan.FromMilliseconds(timeRemain).ToString(@"ss");
Extract this into a method, and the following is a less convoluted way:

`private string formatTime(TimeSpan timeSpan) => $"{(timeSpan < TimeSpan.Zero ? "-" : "")}{timeSpan.Duration().TotalMinutes:N0}:{timeSpan.Duration().Seconds:D2}";`

with tests:

```
[Test]
public void TestNegativeTime()
{
    Assert.AreEqual("-0:01", formatTime(TimeSpan.FromMilliseconds(-1000)));
    Assert.AreEqual("-0:10", formatTime(TimeSpan.FromMilliseconds(-10000)));
    Assert.AreEqual("-1:00", formatTime(TimeSpan.FromMilliseconds(-60000)));
    Assert.AreEqual("-1:05", formatTime(TimeSpan.FromMilliseconds(-65000)));
    Assert.AreEqual("-65:00", formatTime(TimeSpan.FromMilliseconds(-3900000)));
    Assert.AreEqual("-65:05", formatTime(TimeSpan.FromMilliseconds(-3905000)));
}

[Test]
public void TestPositive()
{
    Assert.AreEqual("0:01", formatTime(TimeSpan.FromMilliseconds(1000)));
    Assert.AreEqual("0:10", formatTime(TimeSpan.FromMilliseconds(10000)));
    Assert.AreEqual("1:00", formatTime(TimeSpan.FromMilliseconds(60000)));
    Assert.AreEqual("1:05", formatTime(TimeSpan.FromMilliseconds(65000)));
    Assert.AreEqual("65:00", formatTime(TimeSpan.FromMilliseconds(3900000)));
    Assert.AreEqual("65:05", formatTime(TimeSpan.FromMilliseconds(3905000)));
}

[Test]
public void TestFractional()
{
    Assert.AreEqual("0:01", formatTime(TimeSpan.FromMilliseconds(1234)));
    Assert.AreEqual("0:12", formatTime(TimeSpan.FromMilliseconds(12345)));
    Assert.AreEqual("1:05", formatTime(TimeSpan.FromMilliseconds(65432)));
}

[Test]
public void TestZero()
{
    Assert.AreEqual("0:00", formatTime(TimeSpan.Zero));
}
```

2018-05-14 01:55 UTC, closed without merging