Update user profile overlay to show more than one tournament banner
ppy/osu pull request #25287
Opened 2023-10-28 23:08 UTC by frenzibyte

- Closes https://github.com/ppy/osu/issues/25284

Preview:

![CleanShot 2023-10-29 at 01 49 53](https://github.com/ppy/osu/assets/22781491/e7dfcb05-8fd9-41f5-a5ca-0c31836f6e28)

2023-10-29 00:10 UTC, Joehuu requested changes

2023-10-29 01:47 UTC, frenzibyte commented on osu.Game/Overlays/Profile/Header/BannerHeaderContainer.cs
> +                LoadComponentsAsync(banners.Select(b => new DrawableTournamentBanner(b)), AddRangeInternal, cancellationTokenSource.Token);
Interesting, I was under the thought that using `LoadComponentsAsync` should not result in any UI thread blockage.

2023-10-30 03:09 UTC, frenzibyte commented on osu.Game/Overlays/Profile/Header/BannerHeaderContainer.cs
> +                LoadComponentsAsync(banners.Select(b => new DrawableTournamentBanner(b)), AddRangeInternal, cancellationTokenSource.Token);
Uh, I misunderstood, you mean to add the banner as soon as it is loaded rather than delaying the display until all are loaded. Sure, sounds good.

2023-10-30 08:32 UTC, peppy approved these changes

2023-10-30 08:32 UTC, merged