Implement mania composer editor screen
ppy/osu pull request #2534
Opened 2018-05-13 11:55 UTC by AlFasGD

This implements the composer editor screen for osu!mania beatmaps. The following changes have been made overall:

- Add osu!mania playfield without showing judgements
- Add snap lines according to the current beat snap divisor (using osu!stable's colours)
- Test case (needs more implementation)

TODO:
[ ] Disable key input

2018-05-14 04:24 UTC, smoogipoo requested changes
Initial.

2018-05-14 13:57 UTC, AlFasGD commented on osu.Game.Rulesets.Mania/UI/ManiaStage.cs
> +        }
I don't really get what you're asking, could you do these changes yourself?

2018-05-21 05:52 UTC, smoogipoo commented
Please split out the mask stuff into a separate PR.

2018-07-17 04:17 UTC, smoogipoo commented
Closing for now to reduce clutter - this PR isn't going to go in in its current form in any case as each addition should be split out into its own PR. A significant portion of it is in https://github.com/ppy/osu/pull/2602 .

2018-07-17 04:17 UTC, closed without merging