Beatmaps are now filtered by their star rating settings.
ppy/osu pull request #2537
Opened 2018-05-14 02:18 UTC by DudeMartin

Resolves #2536.

2018-05-14 02:42 UTC, peppy commented
These added criterial should be in `FilterCriteria`

2018-05-14 02:49 UTC, DudeMartin commented
How do I use a `FilterCriteria` to filter a beatmap by its star rating? I looked at its definition, and it's not clear to me how to create a filter whose criterion is a star rating. Do I set `SearchText` to be something like `stars>=X stars <=Y` where *X* and *Y* are minimum and maximum stars, respectively?

2018-05-19 19:13 UTC, DudeMartin commented
Thank you for your input. I've added commits to address your comments.

2018-05-19 19:48 UTC, DudeMartin commented on osu.Game/Screens/Select/BeatmapCarousel.cs
> +            // set star rating criteria from the settings
It seems that always applying the star rating criteria makes the `TestCaseBeatmapCarousel#testTraversal()` test case fail. Does anyone have a suggestion for a better place to put these lines?

2018-05-19 23:38 UTC, DudeMartin commented
I'm pretty sure CodeFactor is actually broken for this PR. If you click on Details and look at the hash of the commit that it is referencing then you will see that it is not the latest one.

2018-05-20 13:11 UTC, peppy commented
For the time being it's fine to ignore CodeFactor. It's not a requirement for it to pass in order to have something merged.

2018-05-20 16:20 UTC, DudeMartin commented
As far as I'm aware there should be no code style issues. I addressed the issue it is complaining about in [this commit](https://github.com/ppy/osu/pull/2537/commits/66b4b231c04e2a52be65cd592bf5840afc8b6bfc).

Do I need to make any more changes before this can be merged?

2018-05-21 12:31 UTC, jorolf commented
What happens with maps which's star rating is higher than 10?

2018-05-21 14:40 UTC, peppy requested changes

2018-05-21 14:40 UTC, peppy commented on osu.Game/Screens/Select/FilterCriteria.cs
> +        public double MinimumStarDifficulty = OsuConfigManager.DEFAULT_DISPLAY_STARS_MINIMUM;
make these `double?` rather than funnelling in a default value from `OsuConfigManager`. Then if they are null you can bypass the filtering.

2018-10-10 10:18 UTC, peppy commented
@Aergwyn i think that silence is as good as permission to continue work on this!

2018-10-18 04:44 UTC, smoogipoo commented
Closing in favour of alternative in referencing PR.

2018-10-18 04:44 UTC, closed without merging