Fix catch applying positional clamping too early
ppy/osu pull request #25726
Opened 2023-12-11 12:54 UTC by smoogipoo

osu!stable applies the positional clamping after the RNG value is added. This is now replicated here.

Previous spreadsheet was empty so I'm going to rerun on this PR. If it's still empty then I'll dig up some examples where this is the case.

2023-12-11 12:54 UTC, smoogipoo commented
!diffcalc

RULESET=catch

2023-12-11 20:20 UTC, bdach requested changes

2023-12-11 22:30 UTC, smoogipoo commented
Hmmm... Indeed, that's wrong. Not sure how this happened.

2023-12-13 12:27 UTC, bdach approved these changes

2023-12-13 17:47 UTC, merged