Realization on Catch Star Rating
ppy/osu pull request #2593
Opened 2018-05-21 01:59 UTC by frankhjwx

The star rating algorithm is transplanted from https://gist.github.com/peppy/beac8bf3d0da2191ef14d420ff1119e4 and allows lazer to support visualizing catch star rating now.

2018-05-23 03:07 UTC, smoogipoo submitted a review, later dismissed

2018-05-23 03:07 UTC, smoogipoo commented on osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
> +        protected double StrainCalculator(List<double> highestStrains, double decayWeight)
`CalculateStrain`

Also should have an xmldoc with the first comment: "Finds the weighted sum of a sequence of strain intervals."

2018-06-06 00:21 UTC, DrabWeb requested changes
Please don't just copy-paste the stable reference, it's a reference for a reason.

2018-06-07 06:18 UTC, smoogipoo commented on osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyHitObject.cs
> +    internal class CatchDifficultyHitObject
Given that this is a direct re-implementation of osu!stable's calculation, I wouldn't be too harsh about this. The entire calculator should/will be reworked in the future anyway.

2018-06-21 04:08 UTC, smoogipoo commented
@peppy Requesting a review on this since I've made catcher changes.

It seems like the size is not quite exact to osu!stable (off by 20-40 pixels). At least one contributor is the missing 0.1f catch margins, but I'm not sure if they should be implemented anyway/what their purpose was.

It's a start at least.

2018-06-21 08:53 UTC, peppy approved these changes

2018-06-21 09:29 UTC, merged