Prevent custom divisor ranges from halting divisor preset cycling
ppy/osu pull request #26689
Opened 2024-01-24 13:41 UTC by myQwil

In the editor, if we enter a custom divisor of 24, it creates a custom divisor preset with the range:

`{1, 2, 3, 4, 6, 8, 12, 24}`

Then, when we try to switch back to the "common" or "triplets" presets, the divisor changes to the default value of those presets, but we're still stuck in the custom preset.

This happens because the custom preset contains both 4 and 6, and the preset will not change if the current valid divisor range already contains the proposed value. So the only way to manually break out of the custom preset is to enter a new custom divisor whose preset range won't contain 4 or 6.

This PR allows the current valid divisor range check to be skipped when cycling through presets.

2024-01-24 21:15 UTC, bdach requested changes
Please add tests

2024-01-25 05:43 UTC, peppy commented
Please avoid force pushing in the future.

2024-01-25 05:49 UTC, peppy commented on osu.Game/Screens/Edit/BindableBeatDivisor.cs
> +        /// <param name="force">Ignores the current valid divisor range when true.</param>
This reads wrong. Don't you mean "forces changing the valid divisors to a common preset"? I'd probably name this variable `preferKnownPresets` or experiment with extracting the logic out to a second method for this, called something like `SetPresetsForDivisor(int divisor)`.

2024-01-25 11:46 UTC, peppy approved these changes

2024-01-25 11:46 UTC, merged