Remove link colours from beatmap tags
ppy/osu pull request #2698
Opened 2018-05-31 17:25 UTC by Joehuu

~Since tags have the same colour and can link, it should be the same for sources. Not yet linked as a search term though.~

2018-06-02 18:04 UTC, peppy commented
If anything, the colour should be removed from the non-linking tags rather than added to more text which doesn't actually link.

2018-06-03 07:08 UTC, DrabWeb commented on osu.Game/Screens/Select/BeatmapDetails.cs
> +            description.TextColour = source.TextColour = tags.TextColour = Color4.White.Opacity(0.75f);
Just make this colour the default in `MetadataSection`.

2018-06-03 22:50 UTC, DrabWeb requested changes

2018-06-03 22:50 UTC, DrabWeb commented on osu.Game/Screens/Select/BeatmapDetails.cs
> +                textFlow.Colour = Color4.White.Opacity(0.75f);
This doesn't need to be done in BDL anymore and can be set when creating `textFlow`.

2018-06-04 22:55 UTC, DrabWeb approved these changes

2018-06-05 23:51 UTC, peppy approved these changes

2018-06-05 23:51 UTC, merged