Cache created judgement in `HitObject`
ppy/osu pull request #27114
Opened 2024-02-10 11:08 UTC by EVAST9919

Closes https://github.com/ppy/osu/issues/27104

2024-02-10 12:40 UTC, EVAST9919 commented
See https://github.com/ppy/osu/issues/27104#issuecomment-1936997683

2024-02-10 17:37 UTC, EVAST9919 commented
Reopening since it improves allocations during beatmap loading (OP has been updated), and potentially has other benefits.

2024-02-14 04:59 UTC, smoogipoo requested changes

2024-02-14 04:59 UTC, smoogipoo commented on osu.Game/Rulesets/Objects/HitObject.cs
> +        protected virtual Judgement CreateJudgement() => new Judgement();
I'd prefer if this doesn't change for now, to prevent breaking changes.

2024-02-14 05:09 UTC, smoogipoo commented
I think this is fine for as long as `Judgement` is only used to ferry fixed data. Looking through a few rulesets, it doesn't look like implementations do anything other than override `MaxResult`, which is good because that isn't really supported anyway.

We'll change this class [in the future](https://github.com/ppy/osu/pull/26563), at which time I'd reconsider the semantics around it - likely making it not a class and potentially moving it to the ctor.

Curious what @bdach thinks of this PR.

2024-02-14 08:26 UTC, bdach commented
I was deferring review of this as it seemed relatively low priority. Without looking the diff over, mixed thoughts because I'm scared of this going wrong and storing data it shouldn't be storing, but also thinking that if we're ever to actually fix issues in editor stemming from lack of frame stability without _relying_ on frame stability it'd be by storing stuff more permanently to hitobjects rather than rely on DHOs for storing object state, which this helps in. https://github.com/ppy/osu/issues/11980 is also semi-relevant in thix context.

2024-02-14 08:42 UTC, smoogipoo commented
One other thing to consider - and bear in mind I'm just listing my thoughts and doesn't necessarily affect this PR - is that at some point we'll probably want to pool `HitObject`s as they're the single highest source of GC pressure affecting things like diffcalc.
Anything stateful inside `HitObject` should probably consider that it may become transient at some point so that we don't inadvertently lock ourselves into more breaking changes further down the track

2024-02-14 19:20 UTC, peppy commented
the judgement class really needs very strong xmldoc saying that it shouldn't be storing state. or it should be forcefully sealed from adding new fields if that's even a thing we can do.

2024-02-15 08:52 UTC, smoogipoo commented
> or it should be forcefully sealed from adding new fields

Unfortunately not 😢 

But yeah I would see it going in a `struct` direction, it effectively sealing it. Something like:
```
ctor()
{
    Criteria = new JudgementCriteria
    {
        MaxResult = LargeTickHit,
        [MinResult = ...]
    }
}
```

2024-02-15 09:26 UTC, peppy commented
Sounds good.

2024-02-18 10:07 UTC, peppy approved these changes

2024-02-18 10:07 UTC, merged