Use high performance session during gameplay
ppy/osu pull request #27391
Opened 2024-02-26 13:27 UTC by smoogipoo

This was originally implemented in https://github.com/ppy/osu/pull/13525 and subsequently reverted in https://github.com/ppy/osu/pull/13591 because players experienced stutters.

`SustainedLowLatency` (the `GameHost` default) allows the GC to perform minimal gen0/gen1 collections, instead grouping them into larger batches. `LowLatency` instead significantly reduces gen0 size so that collections occur more frequently.  
A sub effect of this is that objects that survive gen0 are promoted to gen1, and collections there can take just as long as gen0. This is why it's not good to use LowLatency when a lot of alloc is being done, such as in SongSelect.

It's a balancing game, which is why I've put effort in this PR to make sure that the mode is only enabled during gameplay, and that the switch to it is invisible to the user (when the screen is mostly static).

Players previously experienced stutters because the class relied on `LocalUserPlaying`, which only becomes `true` at the first hitobject's start time. A little bit too late.

2024-02-26 14:54 UTC, peppy commented on osu.Game/OsuGame.cs
> +        protected virtual HighPerformanceSessionManager CreateHighPerformanceSessionManager() => new HighPerformanceSessionManager();
Was there a reason for this being `virtual`? Mobile or something? If not required, then:

```diff
diff --git a/osu.Game/OsuGame.cs b/osu.Game/OsuGame.cs
index f23a78d2dc..13e80e0707 100644
--- a/osu.Game/OsuGame.cs
+++ b/osu.Game/OsuGame.cs
@@ -792,8 +792,6 @@ public override Task Import(ImportTask[] imports, ImportParameters parameters =
 
         protected virtual UpdateManager CreateUpdateManager() => new UpdateManager();
 
-        protected virtual HighPerformanceSessionManager CreateHighPerformanceSessionManager() => new HighPerformanceSessionManager();
-
         protected override Container CreateScalingContainer() => new ScalingContainer(ScalingMode.Everything);
 
         #region Beatmap progression
@@ -1088,7 +1086,7 @@ protected override void LoadComplete()
             loadComponentSingleFile(new AccountCreationOverlay(), topMostOverlayContent.Add, true);
             loadComponentSingleFile<IDialogOverlay>(new DialogOverlay(), topMostOverlayContent.Add, true);
 
-            loadComponentSingleFile(CreateHighPerformanceSessionManager(), Add, true);
+            loadComponentSingleFile(new HighPerformanceSessionManager(), Add, true);
 
             loadComponentSingleFile(new BackgroundDataStoreProcessor(), Add);
 
diff --git a/osu.Game/Performance/HighPerformanceSessionManager.cs b/osu.Game/Performance/HighPerformanceSessionManager.cs
index c5146933b7..22c929083c 100644
--- a/osu.Game/Performance/HighPerformanceSessionManager.cs
+++ b/osu.Game/Performance/HighPerformanceSessionManager.cs
@@ -14,11 +14,11 @@ public partial class HighPerformanceSessionManager : Component
 
         public IDisposable BeginSession()
         {
-            EnableHighPerformanceSession();
-            return new InvokeOnDisposal<HighPerformanceSessionManager>(this, static m => m.DisableHighPerformanceSession());
+            enableHighPerformanceSession();
+            return new InvokeOnDisposal<HighPerformanceSessionManager>(this, static m => m.disableHighPerformanceSession());
         }
 
-        protected virtual void EnableHighPerformanceSession()
+        private void enableHighPerformanceSession()
         {
             originalGCMode = GCSettings.LatencyMode;
             GCSettings.LatencyMode = GCLatencyMode.LowLatency;
@@ -27,7 +27,7 @@ protected virtual void EnableHighPerformanceSession()
             GC.Collect(0);
         }
 
-        protected virtual void DisableHighPerformanceSession()
+        private void disableHighPerformanceSession()
         {
             if (GCSettings.LatencyMode == GCLatencyMode.LowLatency)
                 GCSettings.LatencyMode = originalGCMode;

```

2024-02-27 08:40 UTC, peppy commented on osu.Game/OsuGame.cs
> +        protected virtual HighPerformanceSessionManager CreateHighPerformanceSessionManager() => new HighPerformanceSessionManager();
as long as it's not an `OperationNotSupported` 😅

2024-02-27 08:50 UTC, bdach requested changes
Dies on android:

```
2024-02-27 08:49:39 [error]: An unhandled error has occurred.
2024-02-27 08:49:39 [error]: System.PlatformNotSupportedException: Operation is not supported on this platform.
2024-02-27 08:49:39 [error]: at System.Runtime.GCSettings.SetGCLatencyMode(GCLatencyMode newLatencyMode)
2024-02-27 08:49:39 [error]: at System.Runtime.GCSettings.set_LatencyMode(GCLatencyMode value)
2024-02-27 08:49:39 [error]: at osu.Game.Performance.HighPerformanceSessionManager.enableHighPerformanceSession()
2024-02-27 08:49:39 [error]: at osu.Game.Performance.HighPerformanceSessionManager.BeginSession()
2024-02-27 08:49:39 [error]: at osu.Game.Screens.Play.PlayerLoader.pushWhenLoaded()
2024-02-27 08:49:39 [error]: at osu.Framework.Threading.ScheduledDelegate.InvokeTask()
2024-02-27 08:49:39 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-02-27 08:49:39 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-02-27 08:49:39 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

2024-02-27 08:57 UTC, bdach commented on osu.Game/Performance/HighPerformanceSessionManager.cs
> +        }
I'd like to see logging in these methods too to be able to tell when this is being toggled.

2024-02-27 12:50 UTC, peppy approved these changes

2024-02-27 15:27 UTC, bdach approved these changes
let's see how this behaves in the wild this time round i guess

2024-02-27 15:28 UTC, merged