Improve `EditorTable` performace
ppy/osu pull request #27648
Opened 2024-03-17 13:25 UTC by EVAST9919

092856347a10893e76758172093900768ca1a632 removes `GridContainer` from the input subtree since all the input is being handled by the background.

The rest of pr: implementation of `EditorTableBackground` component, which mimics behavior of a vertical `FillFlowContainer` full of clickable items in an efficient way. Tests are included.

Map example with a huge "control point" and "verify" tables: https://osu.ppy.sh/beatmapsets/1238185#mania/2574372

|master|092856347a10893e76758172093900768ca1a632|full pr|
|---|---|---|
|![master](https://github.com/ppy/osu/assets/22874522/f7d63c4c-b4ac-4c12-a3dc-79de86ab5d5f)|![input](https://github.com/ppy/osu/assets/22874522/485e7514-63c8-4587-b41b-bff456dfd6d7)|![pr](https://github.com/ppy/osu/assets/22874522/913d93a8-f215-4ffe-955e-4869d8b785d9)|

2024-03-17 16:06 UTC, peppy commented
the hell is this diff? is this considered a code quality improvement from your end?

2024-03-17 16:36 UTC, EVAST9919 commented
> the hell is this diff? is this considered a code quality improvement from your end?

Most of it is a new component + tests. The rest is moving objects handling outside of the background to the table iself, which I would consider a better practice. Or you mean it would be better to make a separate pr for each change?

2024-03-18 12:56 UTC, bdach requested changes
Structurally this is unacceptable

2024-03-18 12:56 UTC, bdach commented on osu.Game/Screens/Edit/EditorTableBackground.cs
> +        }
No. I am not having the "background" of a table handle input.

2024-03-18 12:56 UTC, bdach commented on osu.Game/Screens/Edit/EditorTableBackground.cs
> +        public EditorTableBackgroundRow Select(int itemIndex)
I am not having the "row background" of a table having a separate selection method from the actual row. It's the row. The user is performing the operation of selecting the _row_. It is the _**row**_ you're selecting.

2024-03-18 12:56 UTC, bdach commented on osu.Game/Screens/Edit/EditorTable.cs
> +        public virtual void SetNewItems(IEnumerable<T> newItems)
Why?

2024-03-18 17:52 UTC, closed without merging