Remove NF penalty from pp calculation
ppy/osu pull request #28275
Opened 2024-05-21 08:19 UTC by Givikap120

NF penalty is one of the most pointless things in the performance calculation and I have no idea how it's stays in the code to this day
pp meant to be objective difficulty measure, and having some very questionable penalties is not good at all
especially considering the fact that NF in top plays is mostly used to avoid scorev1-ning (overriding better score with worse one)
for one who will be against it - I would like to hear how exactly 1 miss score with NF is easier than 1 miss score without NF

2024-05-21 08:42 UTC, RubiksImplosion commented
> NF penalty is one of the most pointless things in the performance calculation

From the mania perspective, maps often have a difficult burst somewhere that "gate" the map from awarding pp to lower skilled players. Since mania pp cares only cares about overall accuracy and not miss count, NF not being penalized would let players farm maps far above their skill level by mashing through the bursts while using the accuracy built up beforehand as a buffer.

2024-05-21 08:43 UTC, Givikap120 commented
> > NF penalty is one of the most pointless things in the performance calculation
> 
> From the mania perspective, maps often have a difficult burst somewhere that "gate" the map from awarding pp to lower skilled players. Since mania pp cares only cares about overall accuracy and not miss count, NF not being penalized would let players farm maps far above their skill level by mashing through the bursts while using the accuracy built up beforehand as a buffer.

click on the "files changed" button in PR

2024-05-21 08:45 UTC, cl8n commented
I thought the miss-scaling thing was already a clever solution to this issue, in that a score where health is already not a factor (i.e. FC) won't be penalized, but everything else will to some degree. removing this penalty entirely would cause problems as everyone already mentioned, but maybe there's a way to tweak how the penalty scales to better match what you're expecting..?

2024-05-21 08:47 UTC, RubiksImplosion commented
Ah, I had checked beforehand but you addressed it while I was writing my response.

2024-05-21 08:49 UTC, Givikap120 commented
> I thought the miss-scaling thing was already a clever solution to this issue, in that a score where health is already not a factor (i.e. FC) won't be penalized, but everything else will to some degree. removing this penalty entirely would cause problems as everyone already mentioned, but maybe there's a way to tweak how the penalty scales to better match what you're expecting..?

I still yet to see any score that satisfy those conditions:
- It's in person top100 (7 digits with 10 star maps 0pp don't count)
- It have NF
- It would be failed if no NF

2024-05-21 08:59 UTC, cl8n commented
okay, and there may be none... do you feel that invalidates what people are & have been saying about this?

imo the purpose of this penalty is not to strictly say that the score was less difficult to pull off with NF, it's an arbitrary measure to discourage turning off one of the core game mechanics. having the penalty scale based on how much that mechanic could possibly be relevant seems like a good compromise

2024-05-21 09:00 UTC, Givikap120 commented
> okay, and there may be none... do you feel that invalidates what people are & have been saying about this?
> 
> imo the purpose of this penalty is not to strictly say that the score was less difficult to pull off with NF, it's an arbitrary measure to discourage turning off one of the core game mechanics. having the penalty scale based on how much that mechanic could possibly be relevant seems like a good compromise

remind me the purpose of pp?
I remember it being measuring the difficulty
1 miss with NF isn't any easier than 1 miss without NF

2024-05-21 09:01 UTC, apollo-dw commented
Putting a "no" vote in on my end for pp committee. Seems lame to not have anything at all for entirely removing the risk of failure on a play. That's literally the worst thing that can happen in a play: a fail. Removing it is absurd in my eyes.

❌

2024-05-21 09:05 UTC, Givikap120 commented
> Putting a "no" vote in on my end for pp committee. Seems lame to not have anything at all for entirely removing the risk of failure on a play. That's literally the worst thing that can happen in a play: a fail. Removing it is absurd in my eyes.
> 
> ❌

why taiko don't have NF penalty then?

2024-05-21 09:45 UTC, Givikap120 commented
Changed std penalty to the one that will not nerf scores that are not likely to be failed

2024-05-22 07:13 UTC, smoogipoo commented
!diffcalc

2024-05-22 12:40 UTC, Givikap120 commented
> Target: #28275 Spreadsheet: https://docs.google.com/spreadsheets/d/1hWGGkZ7KE_nuxKqJi3NWAy_HskyE3nsLeTRnKqvL1fM/edit

you can sort by %difference and see which scores have maximum buff (+11%), and which have lower buff

2024-05-23 08:31 UTC, Eve-ning commented
```
multiplier *= Math.Max(0.75, 1.0 - 0.02 * countMiss);
```

looks arbitrary, honestly I don't think it'll matter on the big picture
1. top scores usually don't use NF
2. top scores that use NF will usually have `countMiss > 13`, which negates this

I'd rather you not change this just because it adds complexity, unless I've missed some justification?

2024-05-23 08:43 UTC, bastoo0 commented
I don't see any issue with catch having the same NF scaling as current std. This was agreed upon with the community and was planned for whatever changes would come next. Though it's quite low in priority.

2024-05-23 09:00 UTC, Kominaru commented
> **Mania Changes**
> 
> ```
> multiplier *= Math.Max(0.75, 1.0 - 0.02 * countMiss);
> ```
> 
> looks arbitrary, I'm not sure if it matters in the big picture
> 
> 1. top scores usually don't use NF
> 2. top scores that use NF will usually have `countMiss > 13`, which negates this
> 
> I'd recommend we not change this just as it adds cognitive complexity, unless I've missed some justification?

Fully agreeing with Evening's rationale here. 

Using NF on osu!mania (which has easier HP recovery) means you assume a misscount orders of magnitude higher than 13, a condition that renders the change effectless. 

While a corner case would be maps with high HP values (think HP10), this is not true in practice: only 4 ranked maps with HP10 in 11 years, all of which have patterning tuned to avoid chained misses.

For osu!mania I wholeheartedly believe this adds unnecessary complexity with no real effect. 

Cheers, 
Komi

2024-05-23 14:02 UTC, Givikap120 commented
> > **Mania Changes**
> > ```
> > multiplier *= Math.Max(0.75, 1.0 - 0.02 * countMiss);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > looks arbitrary, I'm not sure if it matters in the big picture
> > 
> > 1. top scores usually don't use NF
> > 2. top scores that use NF will usually have `countMiss > 13`, which negates this
> > 
> > I'd recommend we not change this just as it adds cognitive complexity, unless I've missed some justification?
> 
> Fully agreeing with Evening's rationale here.
> 
> Using NF on osu!mania (which has easier HP recovery) means you assume a misscount orders of magnitude higher than 13, a condition that renders the change effectless.
> 
> While a corner case would be maps with high HP values (think HP10), this is not true in practice: only 4 ranked maps with HP10 in 11 years, all of which have patterning tuned to avoid chained misses.
> 
> For osu!mania I wholeheartedly believe this adds unnecessary complexity with no real effect.
> 
> Cheers, Komi



> > **Mania Changes**
> > ```
> > multiplier *= Math.Max(0.75, 1.0 - 0.02 * countMiss);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > looks arbitrary, I'm not sure if it matters in the big picture
> > 
> > 1. top scores usually don't use NF
> > 2. top scores that use NF will usually have `countMiss > 13`, which negates this
> > 
> > I'd recommend we not change this just as it adds cognitive complexity, unless I've missed some justification?
> 
> Fully agreeing with Evening's rationale here.
> 
> Using NF on osu!mania (which has easier HP recovery) means you assume a misscount orders of magnitude higher than 13, a condition that renders the change effectless.
> 
> While a corner case would be maps with high HP values (think HP10), this is not true in practice: only 4 ranked maps with HP10 in 11 years, all of which have patterning tuned to avoid chained misses.
> 
> For osu!mania I wholeheartedly believe this adds unnecessary complexity with no real effect.
> 
> Cheers, Komi

if it doesn't have negative effects, but can potentially save pp when you accidentally left NF on - don't see any reason why NF penalty in mania should be different from other gamemodes

"unnecessary complexity" is absolutely irrelevant when your pp system already 10 times less complex than std pp system
especially considering the fact that this "unnecessary complexity" is not even a line difference, but like 30 chars difference in one line
calling this "complexity" is a very big overestimation

2024-05-23 18:34 UTC, Givikap120 commented
> I fundamentally disagree with all of these, including the current osu! implementation which I would like to see undone at some point.
> 
> I don't want to push players towards using NF any more than they already are, using tournaments as an example where it's used 100% of the time.

how is unnerfing scores that are most likely not failed is pushing players towards NF
why are you gonna use NF in a map you're trying to FC outside of "accidentally left over" or "anti-scorev1"

2024-05-23 19:25 UTC, Givikap120 commented
>Also I'll point out that PP is already pushing players to play DT because HR has a much lower value even though it is not >necessarily easier. It's not directly discouraging the use of HR but it is indirectly leading to it.

This is just not correct. "Not necessarily easier"? HR is easier than DT in 99% of the cases. And when it's not - HR star rating will most likely be bigger than DT. 
The main reason of DT meta on high-end is not "discouraging of HR" but the simple fact that with DT you have 100x more maps to farm.

> Let me answer with a question: why would players play without NF?

Let me answer with a question: you have a map that you're going to farm. 
By putting on NF you're making yourself appear much lower in the leaderboards. 
By not putting NF you have extremely close to 0 chance of loosing your top100 play. This chance is higher if you play in stable (notelock) or with HR (high HP drain). 
In first case rn you have scorev1 and NF provide an advantage of "anti-scorev1". 
In second case by putting on NF your chance of getting punished is much higher in my PR, so this point is resolved. 
So what are you gonna choose? 

I personally and most of the people I asked - won't play with NF.

> "well, if you use NF and do well you won't be punished anyway, so just use it and forget about HP"

you will be punished if you missed too much, have you looked in the PR code?

> but there have been talks of removing score multipliers altogether

why would you remove score multipliers? that just makes 0 sense

2024-05-23 20:03 UTC, smoogipoo commented
> And when it's not - HR star rating will most likely be bigger than DT.

Got an example? There should be basically zero cases where HR increases SR beyond DT, barring low-SR maps, because DT affects all strains whereas HR only affects one.

> the simple fact that with DT you have 100x more maps to farm.

There are at least an order of magnitude more HR maps to "farm" than DT maps. The only reason DT is farmed is instead is because of its effective pp rating.

But, at the same time, since 2013 DT has seen an explosive growth in use to the point that your local neighborhood grandma will play it. Player skill has changed, monitors have changed, mapping has changed, players have adapted, yet PP still treats it as if it was 2017.

I'll be talking with a few players myself on this point, because it's very likely that I'm not aligned with the majority.

> why would you remove score multipliers?

Because lazer has some 15 additional mods (and growing!) over stable and a fixed score cap which doesn't translate well to mods.

You're welcome to provide an alternative that doesn't include using pp to determine the score multiplier.

> you will be punished if you missed too much, have you looked in the PR code?

Read my sentence again. There's a word you missed.

Basically it culminates to:
- If you do bad then who cares because your score would've been bad anyway. Either on the leaderboards or nerfed by other ppcalc strains.
- If you do well then who cares _again_ because NF won't punish you.

It's a free removal of a gameplay mechanic.

> So what are you gonna choose?

Well, you said it yourself. For as long as NF is lower on the leaderboards then I probably wouldn't choose it. However, if that weren't the case, or I didn't care about score -- eg. if score multiplier is removed OR when pp leaderboards come into existence -- then I would play with it 100% of the time.

2024-05-23 22:02 UTC, Givikap120 commented
> It's a free removal of a gameplay mechanic.

free removal? how it's free removal if you're not going to fail in score where you have 3 miss and 98 acc
it's already removed

2024-05-23 22:16 UTC, Flawnpiece commented
I genuinely think you guys won't come to a same conclusion regarding NF simply because your arguments can go both ways.

--> If you get a good score with NF, then you could make the penality goes away as it doesn't matter, but you could also argue that there was no need of having NF in the first place. 

--> If you get a bad score with NF, then whether the penality goes away or not doesn't matter as your play is not good.

In the end, it all comes to the reason as to why failing and the HP mechanic exist in the first place. It act as a barrier for players playing outside their skill, but once a map is on your skill level, you can pretty much forget about HP and dying which comes back to --> why would you put NF in the first place or why would NF penality would apply if you won't die. 

For some people the removal of a gameplay mechanic is a big deal but for others they don't really care about it. So I think this discussion should take a direction of why would this be an improvement for the game and it's players or the opposite.

2024-05-24 06:58 UTC, bdach commented
> So I think this discussion should take a direction of why would this be an improvement for the game and it's players or the opposite.

I'm not sure how this framing changes things because that is what is already being talked about in this thread? The assessment of these factors is subjective and thus as long as there is a fundamental difference of opinion there will be no consensus.

2024-05-26 19:31 UTC, Givikap120 commented
> I genuinely think you guys won't come to a same conclusion regarding NF simply because your arguments can go both ways.
> 
> --> If you get a good score with NF, then you could make the penality goes away as it doesn't matter, but you could also argue that there was no need of having NF in the first place.
> 
> --> If you get a bad score with NF, then whether the penality goes away or not doesn't matter as your play is not good.
> 
> In the end, it all comes to the reason as to why failing and the HP mechanic exist in the first place. It act as a barrier for players playing outside their skill, but once a map is on your skill level, you can pretty much forget about HP and dying which comes back to --> why would you put NF in the first place or why would NF penality would apply if you won't die.
> 
> For some people the removal of a gameplay mechanic is a big deal but for others they don't really care about it. So I think this discussion should take a direction of why would this be an improvement for the game and it's players or the opposite.

so why my 400pp peak should be 370pp because I had NF?
map became 30pp easier?

2024-05-26 21:11 UTC, cl8n commented
there's no need to keep restating the premise when everyone already understands it. this is just getting frustrating how many times the discussion has gone in circles (here and in discord)

2024-05-26 21:19 UTC, Givikap120 commented
> there's no need to keep restating the premise when everyone already understands it. this is just getting frustrating how many times the discussion has gone in circles (here and in discord)

I'm just very annoyed that because of very ghostly probability of people suddenly starting to play with NF - some absolutely innocent scores are nerfed
Like come on, most of the community doesn't understand how pp works even on the surface level, and you're telling me that they gonna analyze my formula and somehow get sure that they won't be punished for it because they're gonna miss less than 4 times on this map
This doesn't makes sense at all
Like I'm 99.99% sure that scenario Smoogi talked about is super unrealistic
If people will suddenly start playing with NF after this change - I will apologize and you can just revert this change
Don't see any issues here

2024-05-26 21:20 UTC, Givikap120 commented
Why improvement for the game? pp system is better at measuring players performance = game is better

2024-05-27 19:29 UTC, stanriders requested changes
First of all, I don't agree with the idea of allowing certain mods to be used for other purposes than the intended one. The only reason NF even has a progressive penalty is because some people abused it before. Making it more lenient will open more room for abuse (some even already stated in OP post). Disabling a game mechanic should ideally always be punished in my opinion.

Second, I think this PR should be split into one PR per ruleset to allow for better reviewing, discussion and just overall management (like for example what if catch people agree with it while mania and osu dont? how do we merge it?)

2024-05-27 21:46 UTC, koopafou commented
If the argument is to prevent people from abusing NF, then why are we still allowing players to exploit NF for sudden rank drops for the sole purpose of entering lower level tournaments ?

2024-05-27 22:14 UTC, Givikap120 commented
> First of all, I don't agree with the idea of allowing certain mods to be used for other purposes than the intended one. The only reason NF even has a progressive penalty is because some people abused it before. Making it more lenient will open more room for abuse (some even already stated in OP post). Disabling a game mechanic should ideally always be punished in my opinion.
> 
> Second, I think this PR should be split into one PR per ruleset to allow for better reviewing, discussion and just overall management (like for example what if catch people agree with it while mania and osu dont? how do we merge it?)
> 
> I think this isn't really fixing a core issue which is when people have NF on when they don't need it. I think an alternative might be that NF would get automatically removed for full combo scores, but that's more of a gameplay discussion than a difficulty calculation one

this purpose (scorev1-ning) is going to be fixed automatically with incoming osu-performance changes
considering that previous lenience suggestion was accepted with quote "let's see how meta shifts, if there will sudden spike in NF usage - we will revert this"
don't see why we can't use the same logic here
I think I will create a catch PR but no mania cuz mania players seem to be against the change

2024-10-07 11:46 UTC, smoogipoo commented
Closing as stale/out of date. See https://discord.com/channels/188630481301012481/188630652340404224/1292814514215059497

2024-10-07 11:46 UTC, closed without merging