Fix dialog overlay playing double samples on show/hide
ppy/osu pull request #2849
Opened 2018-06-21 07:48 UTC by peppy

2018-06-27 04:11 UTC, smoogipoo requested changes

2018-06-27 04:11 UTC, smoogipoo commented on osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
> +        protected virtual void OnStateChanged(Visibility visibility)
Why was this made virtual/protected?

2018-06-27 04:13 UTC, peppy commented on osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
> +        protected virtual void OnStateChanged(Visibility visibility)
probably no longer necessary

2018-06-29 09:41 UTC, smoogipoo approved these changes

2018-06-29 09:59 UTC, merged