Implement a bunch of rhythm difficulty calculation fixes
ppy/osu pull request #28871
Opened 2024-07-15 09:57 UTC by stanriders

This PR addresses a couple of rhythm evaluation issues in osu!:

1. Removes island length size bonus completely
2. Heavily nerf repeated islands (https://www.desmos.com/calculator/poxy4s3yng)
3. Changes delta difference comparisons to use hitwindow-based epsilon

2024-07-15 18:20 UTC, tsunyoku requested changes

2024-07-15 18:20 UTC, tsunyoku commented on osu.Game.Rulesets.Osu/Difficulty/Evaluators/RhythmEvaluator.cs
> +                        }
replace with a `TryAdd`

2024-07-15 18:20 UTC, tsunyoku commented on osu.Game.Rulesets.Osu/Difficulty/Evaluators/RhythmEvaluator.cs
> +                            effectiveRatio *= Math.Pow(1.0 / islandCounts[island], power);
we might want to scale this harsher since the common offenders of island repetition aren't really nerfed as much as I'd like

2024-07-16 01:34 UTC, smoogipoo commented
!diffcalc

2024-07-20 06:45 UTC, smoogipoo commented
!diffcalc

2024-09-23 09:18 UTC, tsunyoku approved these changes

2024-09-23 22:36 UTC, apollo-dw approved these changes
LGTM

2024-09-24 08:52 UTC, stanriders commented
@smoogipoo this change is good to go

2024-09-27 01:00 UTC, Givikap120 commented on osu.Game.Rulesets.Osu/Difficulty/Evaluators/RhythmEvaluator.cs
> +                        double doubletapness = prevObj.GetDoubletapness((OsuDifficultyHitObject?)prevObj.Next(0));
`currObj`?

2024-10-04 13:04 UTC, Givikap120 commented on osu.Game.Rulesets.Osu/Difficulty/Evaluators/RhythmEvaluator.cs
> +                        double doubletapness = prevObj.GetDoubletapness((OsuDifficultyHitObject?)prevObj.Next(0));
> I think it's related to the fact `prevObj.Next(0)` is the same as `currObj`

this is correct
sorry for unclear message

2024-10-07 06:41 UTC, bdach commented
@ppy/osu-pp-committee please advise how to fix merge conflict with https://github.com/ppy/osu/pull/29980

![1728283285](https://github.com/user-attachments/assets/89e1e1c4-c7f0-4857-a212-a451552fb315)

2024-10-07 06:45 UTC, stanriders commented
> @ppy/osu-pp-committee please advise how to fix merge conflict with #29980
> 
> ![1728283285](https://private-user-images.githubusercontent.com/20418176/374057472-89e1e1c4-c7f0-4857-a212-a451552fb315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODM2NjUsIm5iZiI6MTcyODI4MzM2NSwicGF0aCI6Ii8yMDQxODE3Ni8zNzQwNTc0NzItODllMWUxYzQtYzdmMC00ODU3LWEyMTItYTQ1MTU1MmZiMzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA2NDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODQ0YTBkNDcyMGYwYjUzYWQyZTgyODlkMWNjZTI1N2E3NGQxN2RlNTRkMTlkNTMxMTQzYzdhMzY1YWZiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O0PAlua-Z6SxnY54pBrDX8ePs6ADzoK5RFePP_N8zTU)

Can use any value here, you can ignore any merge conflicts in `Aim` `skillMultiplier` as long as https://github.com/ppy/osu/pull/29998 is the final pr that's getting merged

2024-10-07 06:49 UTC, bdach commented
?_?

i guess i'm going to merge https://github.com/ppy/osu/pull/29998 into this instead if that is the case, after https://github.com/ppy/osu/pull/29980#issuecomment-2396024786 sheet is done

2024-10-07 06:55 UTC, smoogipoo commented
Any reason for waiting on the sheet? I only requested a sheet to be queued, but is not required for merge.

2024-10-07 06:57 UTC, bdach commented
well i mean if i run a sheet for the sake of running the sheet i can, but given that this touches the same code the preceding pull touched, it would make sense to verify that one doesn't do anything obviously broken before going forward? or not? but in that case we might as well run one sheet at the end of everything?

this is a complete mess to manage.

2024-10-07 07:13 UTC, smoogipoo commented
If you're expecting branches to be working 100% as expected from the get-go, then sheets must look good before merge with no exceptions.

But, as we discussed, I'm fine not doing that in order to keep things moving at a rapid pace. My only requirement is for a sheet to be queued for each PR. It leaves a bit of a paper trail, if not to figure out where things went wrong / if a change has some edge case that was not known during rapid-merge, then to potentially be referenced if data is required to understand the implications.

2024-10-07 07:28 UTC, bdach commented
Alright well I'm merging master into this, then merging https://github.com/ppy/osu/pull/29998 into this, then fixing tests, then queueing sheet. Means we can skip one sheet for https://github.com/ppy/osu/pull/29998.

2024-10-07 07:45 UTC, bdach commented
!diffcalc

2024-10-07 08:44 UTC, bdach commented
Queueing again with explicit `OSU_A` spec since I realised [this might not work as intended](https://discord.com/channels/188630481301012481/188630652340404224/1292768071823523860) if I do it as above.

!diffcalc
OSU_A=https://github.com/ppy/osu/commit/cf66d40b008ba70ec3037d11713bbaa0bda04e91

2024-10-07 08:50 UTC, merged