Hover to expand mod customise panel
ppy/osu pull request #29136
Opened 2024-07-27 10:20 UTC by Cai1Hsu

I didn't see anyone asking for this feature, but it feels fluent for me to select and adjust mods quickly.

The only place where I feel bad is that you have to click the header twice(collapse and expand the panel) to keep the panel expanded. I like that when hovering the header, you can click it to "pin" the panel so that it will not collapse when the cursor is left, and click it again to collapse it, as shown in the video at about 20s. but I didn't apply the [patch](https://gist.github.com/Cai1Hsu/c24a1da8b34d0be2254317b828050b6e) in the commits because I don't know if people like it.

## video demo

https://github.com/user-attachments/assets/e252c136-4d23-408f-8081-c39c151bc903

2024-07-31 02:22 UTC, shiumano commented
Faster customization would be nice, but it seems a bit busy due to large panels opening and overlapping shadows. I would like a moment of grace.
Also, with touch input, where hover and click occur simultaneously, the concern about having to click twice on the header (collapsing and expanding the panel) is noticeable.

https://github.com/user-attachments/assets/02e7d2c0-1fb0-484f-8873-b2e3bf5a7990

2024-07-31 04:37 UTC, peppy commented
I like this, but mobile obviously needs a fix.

2024-07-31 08:48 UTC, Cai1Hsu commented
> Also, with touch input, where hover and click occur simultaneously, the concern about having to click twice on the header (collapsing and expanding the panel) is noticeable.

Thanks, I'm going to push a fix.

> but it seems a bit busy due to large panels opening and overlapping shadows. I would like a moment of grace.

could you make it more explicit? any suggestion for improvement?

2024-08-01 08:01 UTC, bdach requested changes

2024-08-01 08:01 UTC, bdach commented on osu.Game/Overlays/Mods/ModCustomisationHeader.cs
> +        protected new ModCustomisationPanel? Parent => (ModCustomisationPanel?)base.Parent;
This is dodgy. Pass the parent via the constructor instead.

2024-08-01 08:01 UTC, bdach commented on osu.Game/Overlays/Mods/ModCustomisationPanel.cs
> +            public new ModCustomisationPanel? Parent => (ModCustomisationPanel?)base.Parent;
As above

2024-08-06 16:36 UTC, peppy submitted a review, later dismissed

2024-08-07 12:09 UTC, bdach approved these changes

2024-08-07 12:46 UTC, merged