Fix toolbar PP change showing `+0` instead of `0`
ppy/osu pull request #29512
Opened 2024-08-19 11:52 UTC by peppy

| Before | After |
| :---: | :---: |
| ![osu Game Tests 2024-08-19 at 11 52 22](https://github.com/user-attachments/assets/8247103d-37db-42f7-be2c-7675a6b859e9) | ![osu Game Tests 2024-08-19 at 11 52 03](https://github.com/user-attachments/assets/e6fad7de-4bde-4ba2-8600-ec3995c1c6f9) |

2024-08-19 12:04 UTC, smoogipoo submitted a review, later dismissed

2024-08-19 12:18 UTC, bdach requested changes

2024-08-20 18:27 UTC, frenzibyte commented on osu.Game/Overlays/Toolbar/TransientUserStatisticsUpdateDisplay.cs
> +                    pp.Display((int)(update.Before.PP ?? update.After.PP.Value), (int)Math.Abs((update.After.PP - update.Before.PP) ?? 0M), (int)update.After.PP.Value);
We probably want to do `(int)after - (int)before` on the second argument.

2024-08-22 07:22 UTC, peppy commented on osu.Game/Overlays/Toolbar/TransientUserStatisticsUpdateDisplay.cs
> +                    pp.Display((int)(update.Before.PP ?? update.After.PP.Value), (int)Math.Abs((update.After.PP - update.Before.PP) ?? 0M), (int)update.After.PP.Value);
Probably fine.

2024-08-22 10:08 UTC, bdach approved these changes

2024-08-22 10:08 UTC, merged