Completely disable Velopack when using an external updater
ppy/osu pull request #29805
Opened 2024-09-09 01:29 UTC by smallketchup82

This PR will completely disable Velopack if `OSU_EXTERNAL_UPDATE_PROVIDER` is provided. The morale for this PR was caesay's reponse [here](https://github.com/NixOS/nixpkgs/pull/340125#issuecomment-2335713181).

### Testing Checklist
- [ ] Test if Velopack gets disabled after passing environment variable
- [ ] Test if Velopack gets enabled if the environment variable is not passed

Opening as a draft since I haven't tested it yet, but I'll get around to it soon.

2024-09-09 07:04 UTC, smoogipoo requested changes

2024-09-09 07:04 UTC, smoogipoo commented on osu.Desktop/Program.cs
> +            string? packageManaged = Environment.GetEnvironmentVariable("OSU_EXTERNAL_UPDATE_PROVIDER");
Can this be moved to a common (static) location so that it's not referenced twice by name in two different places?

2024-09-09 09:09 UTC, peppy approved these changes

2024-09-11 07:27 UTC, smoogipoo approved these changes

2024-09-11 07:27 UTC, merged