Implement beat-synchronized animation in break overlay
ppy/osu pull request #29866
Opened 2024-09-13 19:32 UTC by nekupaw

I think the new beat-synced animation in the break overlay is really cool, so I implemented pretty much the same approach in the skip overlay.
I also rounded the corners by replacing the box with a circle.

Let me know what you think.

https://github.com/user-attachments/assets/6bf3fe3f-421c-4b78-a52e-9875851414ac

2024-09-13 19:38 UTC, nekupaw commented
ahh, I didn't mean to merge it directly. It's my first pull request, so sorry.

2024-09-13 20:05 UTC, nekupaw commented
Yeah, I was surprised too. It happened after I ran a code formatter over it, or rather, entered the command dotnet format into the command line.
I'll fix it right away, just a moment please.

2024-09-13 20:31 UTC, bdach commented
Yeah we don't use `dotnet format` anymore here.

2024-09-17 15:06 UTC, peppy commented
Should not be merged without squash.

Also @nekupaw please stop merging master.

2024-09-17 15:13 UTC, nekupaw commented
Sorry, I forgot to create a branch at the start. I just intended to include the new merges.

2024-09-18 07:01 UTC, bdach requested changes
while addressing this review please fix history as requested by force-pushing (this PR should consist of a single commit)

2024-09-18 07:01 UTC, bdach commented on osu.Game/Screens/Play/SkipOverlay.cs
> +            float progress = (float)(gameplayClock.CurrentTime - displayTime) / (float)(fadeOutBeginTime - displayTime);
Why is `fadeOutBeginTime` checked against current time (therefore clamping from the left), but progress is not forcefully clamped to be no larger than 1?

2024-09-18 20:46 UTC, nekupaw commented
I'll create a pull request using a new branch now, I think this is the easiest way.

2024-09-18 20:46 UTC, closed without merging