Various speed distance difficulty calculation changes
ppy/osu pull request #29980
Opened 2024-09-24 10:20 UTC by tsunyoku

Intended to be a general nerf to flow aim.

Changes:
- Distance bonus on speed is now additive instead of being a multiplier
- Distance bonus power increased to scale differently for smaller spacing
- Introduced `distance_multiplier` to overall decrease the distance bonus

2024-09-24 10:22 UTC, stanriders requested changes

2024-09-24 10:22 UTC, stanriders commented on osu.Game.Rulesets.Osu/Difficulty/Evaluators/SpeedEvaluator.cs
>              // speedBonus will be 1.0 for BPM < 200
```suggestion
            // speedBonus will be 0.0 for BPM < 200
```

2024-09-25 12:12 UTC, stanriders approved these changes

2024-09-25 18:48 UTC, apollo-dw approved these changes

2024-10-07 06:31 UTC, merged

2024-10-07 06:37 UTC, smoogipoo commented
!diffcalc
OSU_A=https://github.com/ppy/osu/commit/944f8f5f6714db045e67a235a1e44e8342c1a7ba