Decrease HD bonus for slideraim
ppy/osu pull request #29996
Opened 2024-09-25 13:36 UTC by Givikap120

Part of this PR - https://github.com/ppy/osu/pull/27303

This change is reducing HD pp bonus for slideraim in 2 times. To compensate nerf on normal maps - HD bonus was increased by 0.01.
This is mainly made to fix the maps like Oshama Scramble EZHDHT having undeservingly high HD bonus.
This change will allow to rework HD curve for low AR to buff actually hard AR0 +HD maps

2024-09-27 09:50 UTC, stanriders requested changes
This makes absolutely 0 sense to me. How are sliders with HD twice easier to play?

2024-09-27 09:59 UTC, Givikap120 commented
> This makes absolutely 0 sense to me. How are sliders with HD twice easier to play?

Because you can see the whole slider in the most cases (it's fading as you aim it, but it's not even visible on most actually hard sliders, as they're too fast to even notice this). The only case where it makes sense is very long sliders, but those are already giving 0 pp.
The meaning of this change is nerfing one of the main EZ abuse maps - Oshama Scramble EZHDHT, so you can increase global HD bonus for AR0

2024-09-27 10:03 UTC, stanriders commented
So this change is pretty much made to nerf _one map_?

2024-10-09 23:34 UTC, Givikap120 commented
https://www.desmos.com/calculator/tngkn90zlg

2025-02-26 16:17 UTC, closed without merging