Replace unsafe casting in `ManiaDifficultyCalculator` with generic column count calculation
ppy/osu pull request #30026
Opened 2024-09-27 17:33 UTC by Givikap120

This is a prerequisite for https://github.com/ppy/osu/pull/29989 to work
Makes this function work with any generic `IBeatmap`, not only `ManiaBeatmap`

2024-10-03 06:22 UTC, bdach commented
!diffcalc
RULESET=mania

2024-10-04 06:37 UTC, bdach commented
Well something ain't right here, since I'd expect the spreadsheet to be empty. And yet it's not.

2024-10-04 14:41 UTC, Givikap120 commented
> Well something ain't right here, since I'd expect the spreadsheet to be empty. And yet it's not.

Hmmm, very weird
I personally checked around 100 maps (including both converts and og maps) and they were matching
I will look into this

2024-10-04 15:05 UTC, Givikap120 commented
> Well something ain't right here, since I'd expect the spreadsheet to be empty. And yet it's not.

Checked in the latest lazer - the output is the same as this branch
This looks like problem with lazer in general

![image](https://github.com/user-attachments/assets/11f4d565-0f67-40ee-89f0-af6680d917e4)
![image](https://github.com/user-attachments/assets/cf66503c-84d2-4cbc-8eb3-9bc0ef55e2e1)

2024-10-04 15:13 UTC, Givikap120 commented
@smoogipoo can you run mania sheet on master branch?

2024-10-04 15:22 UTC, bdach commented
The spreadsheet generated above is *against* master branch...? What are you hoping to achieve with that?

2024-10-04 15:29 UTC, Givikap120 commented
> The spreadsheet generated above is _against_ master branch...? What are you hoping to achieve with that?

both master lazer and master osu-tools output value the same as this branch (39pp)
when sheet claims that master value is 43pp

2024-10-04 15:56 UTC, Givikap120 commented
Also, I found out that this change breaks osu-tools
Reason - `LegacyBeatmapConversionDifficultyInfo.FromBeatmapInfo`
This function takes ObjectCount from `BeatmapInfo`. This is intentionally used instead of `FromBeatmap` because latter will produce incorrect results as passed Beatmap is already converted, changing object count
But, in osu-tools (and potentially in some other places) - ObjectCount in `BeatmapInfo` is not populated

2024-10-07 06:30 UTC, smoogipoo requested changes

2024-10-07 06:30 UTC, smoogipoo commented on osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
> +            var skills = CreateSkills(beatmap.Beatmap, playableMods, clockRate);
This is not correct - it will give the original beatmap, not the post-mod one.

2024-10-07 06:33 UTC, smoogipoo commented
See review above. Current code is very intentional, and I'm not sure you'll be able to resolve the review without a total rewrite of this PR/if at all.

2024-10-07 06:33 UTC, closed without merging

2024-10-07 10:15 UTC, Givikap120 commented
> See review above. Current code is very intentional, and I'm not sure you'll be able to resolve the review without a total rewrite of this PR/if at all.

This PR was needed for correct functioning of `IDifficultyCalculatorBeatmap` because it failed a cast
but if this way of fixing isn't acceptable - I can add `IBeatmap IDifficultyCalculatorBeatmap.BaseBeatmap` method
I just thought that this way would be better

2024-10-07 12:09 UTC, smoogipoo commented
!diffcalc
RULESET=mania

2024-10-07 12:14 UTC, smoogipoo commented
I think you might be able to get away with storing the `IWorkingBeatmap` from the constructor, local to `ManiaDifficultyCalculator`.

I looked back on this PR because I also don't understand why the values changed and may indicate something going wrong in osu-difficulty-calculator, which would be a must-fix for next release.

2024-10-07 12:29 UTC, Givikap120 commented
> I think you might be able to get away with storing the `IWorkingBeatmap` from the constructor, local to `ManiaDifficultyCalculator`.
> 
> I looked back on this PR because I also don't understand why the values changed and may indicate something going wrong in osu-difficulty-calculator, which would be a must-fix for next release.

I assume that it's because mania have merged but not deployed changes for a while now

2024-10-07 12:31 UTC, smoogipoo commented
The comparison is against `master`, so that's not relevant.

2024-10-07 12:36 UTC, Givikap120 commented
> The comparison is against `master`, so that's not relevant.

well idk how it's comparison against `master` if my lazer release client show values in line with this PR instead of `master`