Fix conflicting keybind for "convert to stream" in editor
ppy/osu pull request #30252
Opened 2024-10-12 21:53 UTC by LBlend

Closes #30169

`Ctrl-Shift-F` is now `Ctrl-Shift-Z`.

## Why Z?

`Ctrl-Shift-S` and `Ctrl-Shift-A` were already in use. `Ctrl-Shift-D` is used to close windows in GNOME by default. The "G" key in `Ctrl-Shift-G` is too far away, in my opinion. Using "Z" seemed like the best option, although not ideal.

2024-10-12 22:07 UTC, Joehuu requested changes, later dismissed
This now conflicts with the alternative redo shortcut.

![osu!_5qplPgH88v](https://github.com/user-attachments/assets/3997febc-cedd-4dcd-b935-326de678cb73)

This also only fixes the hotkey hint. You would need to apply the change here too:
https://github.com/ppy/osu/blob/2de19558923160116a0139a955fa431008ef5d89/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs#L394-L398

2024-10-12 22:25 UTC, LBlend commented
My bad! I suck at greping. Sorry about that 😅

If I haven't managed to overlook something again, X should be available.

2024-10-12 22:35 UTC, LBlend reviewed
`Z` => `X`

Does this make the "change requested" box go away. We'll find out now

2024-10-12 22:38 UTC, Joehuu commented
Seems fine now, but I can't make the call on whether this is the desired shortcut.

2024-10-13 04:10 UTC, bdach commented
I think changing the hotkey is a cop-out and will get us dissatisfaction from users (I can already picture the twitter posts, "why did you change this hotkey over some random skin crap I don't ever need?!?!") and the resolution here is to *make the editor use the stream binding over the random skin binding*.

This already is the case for other editor hotkeys that are rebindable. However only hotkeys that are valid for all rulesets are currently rebindable. Thus, I would want to explore possibilities of having ruleset-specific rebindable editor hotkeys. I'm not yet sure *how" it would be done, but I think that's better over this change. 

All in all I'm opposed to merging this.

2024-10-13 05:03 UTC, Joehuu commented
Didn't check that this keybinding was also in stable when I was reviewing. If this was a lazer-only feature, this change would have less reaction as the conflict went unnoticed since https://github.com/ppy/osu/pull/19250.

2024-10-13 05:40 UTC, smoogipoo commented
It sounds like we may want to move the FPS toggle into overlay key bindings?

https://github.com/ppy/osu/blob/2de19558923160116a0139a955fa431008ef5d89/osu.Game/Input/Bindings/GlobalActionContainer.cs#L104-L106

I'm not sure any of the three I linked to there really deserve to be "global" keybinds.

2024-10-13 06:15 UTC, Joehuu commented
The shortcut is currently hardcoded on `OnKeyDown()` and if it gets rebindable it should be a ruleset-specific keybind as bdach said above. Unless the "convert to stream" is relevant to other game modes and will be implemented later.

2024-10-13 08:32 UTC, mixalisnew commented
ca someone tell me why we cant just re bind editor keys to our liking?

2024-10-13 11:52 UTC, peppy commented
Changing the FPS toggle to anything else (or removing the default) is the correct path.

2024-10-13 11:53 UTC, closed without merging