Remove Peak Strain Reduction
ppy/osu pull request #30923
Opened 2024-11-29 23:09 UTC by TextAdventurer12

#28844 but on the new branch.

This change is intended to go alongside the other PRs relating to flow aim and length bonus
It removes the reduction of the highest few strains, with the idea that it can be better handled through the length bonus PR, as well as being less necessary with the recent changes to the miss penalty.

2024-12-10 12:18 UTC, stanriders requested changes

2024-12-10 12:22 UTC, stanriders approved these changes

2024-12-10 12:22 UTC, tsunyoku approved these changes

2025-02-14 16:16 UTC, peppy commented
Is this one coming in a future push? Curious on its approved-but-not-merged state.

2025-02-14 16:18 UTC, tsunyoku commented
Yeah, it was in a state of approved because it's a change we'd like to see but it's almost guaranteed that #31181 will be merged in it's place as it replaces it with something else rather than being a straight-up removal.

In either case, definitely not something to be considered for this batch of changes.

2025-02-26 16:17 UTC, closed without merging