Restore key counters state on replay rewinding
ppy/osu pull request #3100
Opened 2018-07-22 18:06 UTC by UselessToucan

resolves #3080 

I'm trying to resolve #3080 using Memento design pattern.
Participants:
`KeyCounterMemento` - Memento
`KeyCounter` - Originator
`KeyCounterCollection` - Caretaker

The problem is that seeking backwards causes the game to perform key presses which ruins the restored state. ([Video](https://youtu.be/H4S4GAfpfbA))

2018-07-22 18:08 UTC, peppy commented
`Memento` -> `State`, as we call such states everywhere else in the game.

2018-07-22 18:12 UTC, peppy requested changes

2018-07-22 18:12 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterCollection.cs
> +        private readonly Dictionary<string, List<KeyCounterMemento>> keyCountersState = new Dictionary<string, List<KeyCounterMemento>>();
can't exist (ugly and should not be `string` based). why not store states inside the `KeyCounter` removing the need for this?

2018-07-22 18:12 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterMemento.cs
> +    public class KeyCounterMemento
KeyCounterState

2018-07-22 18:12 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterMemento.cs
> +        public double CurrentTime { get; }
Time

2018-07-22 18:12 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterMemento.cs
> +        public int CountPresses { get; }
Count

2018-07-22 18:12 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterMemento.cs
> +        public double CurrentTime { get; }
also these can probably be `readonly`

2018-07-22 18:12 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterCollection.cs
> +                var targetState = keyCountersState[counter.Name].LastOrDefault(state => state.CurrentTime <= time);
what happens on default (null)? looks to be nullref exception?

2018-07-22 18:12 UTC, peppy commented
also no tests.

2018-07-24 10:28 UTC, peppy requested changes

2018-07-24 18:54 UTC, UselessToucan commented on osu.Game/Screens/Play/KeyCounter.cs
> +        public IClock AudioClock { get; set; }
Can't find any `public` clock objects upward of the scene graph.
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/Player.cs#L65
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/PauseContainer.cs#L43
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/PauseContainer.cs#L44

2018-07-24 19:07 UTC, UselessToucan commented on osu.Game/Screens/Play/HUDOverlay.cs
> +                KeyCounter.RestoreKeyCounterState(pos);
Don't understand where to find `ElapsedTime`
![image](https://user-images.githubusercontent.com/22450664/43160470-e31afd52-8f8d-11e8-8ae6-99f2d3600aba.png)

2018-07-24 22:36 UTC, peppy commented on osu.Game/Screens/Play/HUDOverlay.cs
> +                KeyCounter.RestoreKeyCounterState(pos);
`Drawable.Clock.ElapsedFrameTime`

2018-07-24 22:37 UTC, peppy commented on osu.Game/Screens/Play/KeyCounter.cs
> +        public IClock AudioClock { get; set; }
`this.Clock`

2018-08-14 05:21 UTC, peppy requested changes
as mentioned

2018-09-04 23:52 UTC, peppy requested changes

2018-09-04 23:52 UTC, peppy commented on osu.Game/Screens/Play/KeyCounter.cs
> +            states.RemoveRange(targetIndex + 1, states.Count - (targetIndex + 1));
in the case targetIndex is null you probably don't want to run this.

2018-09-05 00:33 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterCollection.cs
> +                key.Clock = basedClock;
this needs a comment as to why it is done.

2018-09-05 00:33 UTC, peppy commented on osu.Game/Screens/Play/KeyCounterCollection.cs
> +            if (AudioClock != null && AudioClock is IFrameBasedClock basedClock)
Is there any reason it's not just an `IFrameBasedClock` in the first place?

2018-09-15 07:54 UTC, peppy approved these changes

2018-09-15 07:59 UTC, merged