Adjustement to DifficultyValue curve to avoid lower sr of osu!taiko being too inflated
ppy/osu pull request #31067
Opened 2024-12-10 21:47 UTC by YaniFR

This pull request aims to change the actual DifficultyValue Curve to a Splitted Curve Calculation to ensure a lower DifficultyValue on lower StarRating (under 5.5*) without affecting higher StarRating (above 5.5) 

You can see the actual graph of the modified curve 
![](https://dzboss.s-ul.eu/kB16yLDB.png)
And the difference between the value where g(x) equal the new curve
![](https://dzboss.s-ul.eu/WHVAuiOn)

Here are some example :

cosMo@BousouP feat. Hatsune Miku - Hatsune Miku no Shoushitsu (Chromoxx) [Hivie's Muzukashii] 5.06* for SS : 
Confirmed Changes : 293pp 
Curve Adjustment : 281pp

Chroma - sink to the deep sea world (Idealism) [hivie's ura muzukashii] 4.45* for SS : 
Confirmed Changes : 246pp 
Curve Adjustment : 225pp

2024-12-11 03:52 UTC, Lawtrohux requested changes
formatting needs to be fixed

2024-12-11 03:52 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
> +
```suggestion
            double difficultyValue = Math.Min(Math.Pow(baseFormula, 3) / 69052.51, Math.Pow(baseFormula, 2.25) / 1150.0);
```

2024-12-11 03:52 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
> +            double difficultyValue = Math.Min(Math.Pow(baseFormula, 3) / 69052.51, Math.Pow(baseFormula, 2.25) /1150.0);
```suggestion
```

2024-12-11 10:00 UTC, Lawtrohux approved these changes
Lgtm. Whilst there may be some apprehensions on magic numbers used, scaling and graph both make sense.

2024-12-12 05:39 UTC, smoogipoo commented
!diffcalc
RULESET=taiko

2024-12-16 11:48 UTC, Lawtrohux commented
Works as intended, still lgtm.

2024-12-18 15:18 UTC, stanriders approved these changes
Reapproving after a master merge

2024-12-18 18:11 UTC, merged