Add back right-click-for-new-combo and right-click-delete when in compose mode
ppy/osu pull request #31148
Opened 2024-12-16 07:18 UTC by peppy

Requested too many times to count.

I'm not sure what to do about the code quality of this. It's a bit weird that there's no way to check the current composition tool from a higher level.

Also it was discussed IRL that there should be some kind of hinting that existing notes will be deleted when they are hovered, but I'm not sure how well this will work in normal mapping flows, since it will display even in cases that users aren't intending to delete an object. Still willing to explore this direction though (it's just non-trivial to implement so I haven't yet).

This is almost definitely not going to pass tests, just want to get this out for initial thoughts before I polish things up.

2024-12-16 08:30 UTC, bdach commented
> It's a bit weird that there's no way to check the current composition tool from a higher level.

Maybe it could work by making `ComposeBlueprintContainer.CurrentTool` a bindable and binding that down to the appropriate `SelectionHandler`s. Although now that I say that I get a very sudden deja vu that I've said those exact words previously and it didn't work as intended for whatever reason...?

Maybe worth trying. Not sure.

2025-02-26 08:33 UTC, peppy commented
Looking back at this I'm thinking the flow I had was already fine to go ahead with, so I'll work with that in mind (and just fix tests).

2025-02-27 13:22 UTC, bdach requested changes

2025-03-12 05:54 UTC, peppy commented on osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
> +            }
Sorry for the late reply, somehow missed this.

> On a code organisation level, why is this pulled two levels up from..

Did you mean the whole input handling, or the new combo state property? If you meant the whole input handling, I have a strong feeling I had to it here to avoid other things handling it first, but will need to re-learn that fail cases before asserting anything.

2025-03-12 06:01 UTC, peppy commented on osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
> +            }
Probably going to have to re-think this based on the fail cases you found anyway. Right click handling is an absolute nightmare at the moment and I really don't know how to fix. The fail here is `performMouseDownActions` returning `true` but [this logic](https://github.com/ppy/osu/blob/15b6e28ebe888b1a87574891be1a0db3b04093b7/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs#L121-L129) still deciding that we need a context menu, but instead the toggle is happening because we apparently don't do a context menu anymore. Might be as easy as updating these conditionals but we'll see..

2025-03-12 07:30 UTC, peppy commented on osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
> +            }
So there's more reason to the placement location I chose:

```
ComposeScreen
|- OsuContextMenuContainer                 // right click opens context menu
   |- TimelineBlueprintContainer
      |- TimelineSelectionHandler
   |- (Osu)HitObjectComposer
      |- (Osu)EditorBlueprintContainer     // right click selects hovered blueprint
         |- (Osu)EditorSelectionHandler    // right click deletes hovered blueprint
```

Input is handled from innermost outwards, so to "only toggle new combo if nothing else handled", HOC seemed like the only choice I had. Obviously it still fails with the context menu flow as you pointed out.

2025-03-12 07:57 UTC, peppy commented on osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
> +            }
I've pushed fixes for the pointed out issues and an inline explanation of why the logic is where it is. I'm open to any suggestion on how to improve things. We could move the logic into `SelectionHandler` and call it remotely I guess, similar to https://github.com/ppy/osu/blob/db7d1f32d7801099caef27aa92272a2715657d38/osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs#L266?

2025-03-12 09:21 UTC, bdach requested changes

2025-03-12 09:21 UTC, bdach commented on osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
> +                return true;
As per test failures, this prevents the context menu from showing at all on selected blueprints :grimacing:

2025-03-12 09:27 UTC, peppy commented on osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
> +                return true;
Pretty obvious why.. luckily the fix is using the same conditions I used elsewhere in this change.

2025-03-13 07:23 UTC, bdach approved these changes
can't seem to break this on a quick check

2025-03-13 07:24 UTC, merged