Scale tablet output size when UI Scaling mode is "Everything"
ppy/osu pull request #31141
Opened 2024-12-16 04:56 UTC by DanielPower

Fixes #12098

## WIP

I'm new to both C# and osu! lazer development, so I'm putting this up early to get feedback on the solution. There is a known bug which I'm working on, and unit tests need to be updated.

## Description

Based on discussions in the issue, scaling tablet output when UI Scaling mode is set to "Everything" will address the needs of full area tablet players who use screen scaling. With this PR, tablet output will not scale when UI Scaling is set to "Gameplay Only" or "Exclude Overlays" since this results in elements being non-interactable with the tablet, which may or may not be desirable for some users and requires further discussion.

## Known issues (to be resolved before ready for review)

- Tablet output scaling does not update when window is resized

## Dependencies

Depends on `osu-framework` changes: https://github.com/ppy/osu-framework/pull/6460

2024-12-24 09:38 UTC, timschumi commented
As a side note, I can't immediately tell from the diff here since I'm not very familiar with the code, but the "conform to current game aspect ratio" button might also need adjustments to use the correct aspect ratio.

While trying to tackle the problem myself a few days ago, I solved it like this (although most of it can now be replaced with usages of the `outputAreaSize` bindable, which is probably preferable):

```diff
diff --git a/osu.Game/Overlays/Settings/Sections/Input/TabletSettings.cs b/osu.Game/Overlays/Settings/Sections/Input/TabletSettings.cs
index 00ffbc1120..ae0c24cad6 100644
--- a/osu.Game/Overlays/Settings/Sections/Input/TabletSettings.cs
+++ b/osu.Game/Overlays/Settings/Sections/Input/TabletSettings.cs
@@ -154,7 +154,19 @@ private void load(OsuColour colours, LocalisationManager localisation)
                             Text = TabletSettingsStrings.ConformToCurrentGameAspectRatio,
                             Action = () =>
                             {
-                                forceAspectRatio((float)host.Window.ClientSize.Width / host.Window.ClientSize.Height);
+                                float clientWidth = host.Window.ClientSize.Width;
+                                float clientHeight = host.Window.ClientSize.Height;
+
+                                if (config.Get<ScalingMode>(OsuSetting.Scaling) == ScalingMode.Everything)
+                                {
+                                    float sizeX = config.Get<float>(OsuSetting.ScalingSizeX);
+                                    float sizeY = config.Get<float>(OsuSetting.ScalingSizeY);
+
+                                    clientWidth *= sizeX;
+                                    clientHeight *= sizeY;
+                                }
+
+                                forceAspectRatio(clientWidth / clientHeight);
                             },
                             CanBeShown = { BindTarget = enabled }
                         },
```

2025-08-27 23:31 UTC, DanielPower commented
Framework changes have been merged, and this is now ready for review. I've added a discussion point to the PR description regarding the impact of this update to users who already use UI Scaling set to "Everything". I'm open to suggestions on how best to minimize impact to users.

2025-09-14 20:29 UTC, Mrcubix commented
If i understand this correctly, the output area is being saved & loaded in settings.
The output area isn't something that can be fine-tuned in lazer, so it doesn't really make sense to be stored in settings.
Especially when it's not specific to a single tablet.

Also i might be missing something but `host.Window` should be providing the scaled size (to avoid us having to calculate it again).
It being provided by the game would make fixing this way simpler.

2025-09-14 22:58 UTC, DanielPower commented
> If i understand this correctly, the output area is being saved & loaded in settings. The output area isn't something that can be fine-tuned in lazer, so it doesn't really make sense to be stored in settings. Especially when it's not specific to a single tablet.

Scaling size, position, and mode are being loaded from settings. These settings already exist, they are not being introduced in this PR. When those values change, the tablet output area is recalculated. Modifying tablet output area is implemented in https://github.com/ppy/osu-framework/pull/6460.

> Also i might be missing something but host.Window should be providing the scaled size (to avoid us having to calculate it again).

`host.Window` is on the `osu-framework` side, and to my understanding isn't related to the scaling functionality implemented in Lazer's UI. So I wouldn't think it would know about the UI scaling. Please correct me if I'm wrong, I'm new to these code bases.

2025-10-02 06:42 UTC, bdach requested changes

2025-10-02 06:42 UTC, bdach commented on osu.Game/Overlays/Settings/Sections/Input/TabletSettings.cs
> +                                }
Use the bindable fields instead of fetching the values via `osuConfig` again:


```suggestion
                                if (scalingMode.Value == ScalingMode.Everything)
                                {
                                    gameplayWidth *= scalingSizeX.Value;
                                    gameplayHeight *= scalingSizeY.Value;
                                }
```

2025-10-02 06:42 UTC, bdach commented on osu.Game/Overlays/Settings/Sections/Input/TabletSettings.cs
> +            scalingPositionY.BindValueChanged(_ => updateScaling());
This updating logic cannot reside here.

Why? If this logic is here, it is *tied to the tablet settings having loaded at least once*. Imagine that a user that already has scaling mode set to `Everything` launches a game update with this change included as is. Initially, their output tablet area *will not have changed at all*. The actual time instant when their output tablet area will change in line with the intent of this change is *when they open settings for the first time*, which is broken.

This sort of logic should be in a game-global place that is not dependent on the first load of the settings controls.

2025-11-18 13:52 UTC, bdach approved these changes
have resolved issues myself, @ppy/team-client would appreciate double-check

2025-11-18 15:24 UTC, DanielPower commented
Sorry, I've been meaning to get back to this. I moved in October and my free time has been significantly reduced.
I really appreciate you making the changes required, and am excited for this feature 🙏

2025-12-09 16:40 UTC, peppy approved these changes

2025-12-09 16:40 UTC, merged