Use proportion of difficult sliders to better estimate sliderbreaks on classic accuracy scores
ppy/osu pull request #31234
Opened 2024-12-22 04:52 UTC by TextAdventurer12

Works out individual top weighted strain count for hitcircles and sliders, and then multiplies countmiss by 1 + the proportion of top weighted strain on sliders to account for misses on sliders sliderbreaks. This assumes that the player breaks equally on difficult hitcircles and sliders, which is the most fair assumption in my opinion.

Spinners are handled incorrectly (they're included in the hitcircle strain count) but because spinners are 0 difficulty anyways there is negligible values impact, so making a better solution would probably be more effort than it's worth.
There is a wasteful calculation being done, as it calculates top weighted strain count on hitcircles, sliders, and then both combined. I'm unsure if the performance cost is worth the code cleanliness from doing it this way, but I'll leave it up to pp committee to decide.
This has no combo scaling, which may be desired from a sliderbreak estimator, but it doesn't really fit with the model that I've built this under so I left it absent.
`TopWeightedSliderFactor` may be infinity on maps with no circles. This doesn't have any adverse values effects, because `estimatedSliderbreaks` is capped at `countMeh + countOk`, but I'm unsure if it's going to cause any other weirdness.
This probably wants some form of miss penalty or `effectiveMissCount` adjustment, because currently every affected score is losing.
Sliderbreaks may be double dipped, as it uses `effectiveMisscount + estimatedSliderbreaks`, while `effectiveMissCount` may already contain some estimated sliderbreaks. I'm not really sure of a good way to resolve this, and a little doubtful that resolving it would have any significant effect.

2025-01-07 11:25 UTC, tsunyoku requested changes

2025-01-07 11:25 UTC, tsunyoku commented on osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
> +                aimValue *= calculateMissPenalty(effectiveMissCount + (usingClassicSliderAccuracy ? estimatedSliderbreaks : 0), attributes.AimDifficultStrainCount);
Could we instead add the `estimatedSliderbreaks` to `effectiveMissCount` where `effectiveMissCount` is calculated so everywhere else doesn't have to be aware or care about the sliderbreak calculations?

2025-01-07 12:13 UTC, tsunyoku commented on osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
> +                aimValue *= calculateMissPenalty(effectiveMissCount + (usingClassicSliderAccuracy ? estimatedSliderbreaks : 0), attributes.AimDifficultStrainCount);
I realise we can't because we need the aim/speed slider factors. In that case, could we move the calculation into a method that takes the required parameters (i.e the weighted slider factor)?

2025-01-09 09:37 UTC, tsunyoku approved these changes, later dismissed

2025-01-09 10:09 UTC, stanriders requested changes

2025-01-09 10:09 UTC, stanriders commented on osu.Game.Rulesets.Osu/Difficulty/Skills/OsuStrainSkill.cs
> +            return SliderStrains.Sum(s => 1.1 / (1 + Math.Exp(-10 * (s / consistentTopStrain - 0.88))));
Use `DifficultyCalculationUtils.Logistic`

2025-01-09 10:09 UTC, stanriders commented on osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
>          public double GetDifficultSliders()
Can't we combine this with `CountTopWeightedSliders`? They're doing essentially the same thing

2025-01-09 10:19 UTC, tsunyoku commented on osu.Game.Rulesets.Osu/Difficulty/Skills/OsuStrainSkill.cs
> +            return SliderStrains.Sum(s => 1.1 / (1 + Math.Exp(-10 * (s / consistentTopStrain - 0.88))));
We should change this for the other places too (separate PR)

2025-01-09 10:23 UTC, stanriders commented on osu.Game.Rulesets.Osu/Difficulty/Skills/OsuStrainSkill.cs
> +            return SliderStrains.Sum(s => 1.1 / (1 + Math.Exp(-10 * (s / consistentTopStrain - 0.88))));
I'm pretty sure I did in most places

2025-01-13 01:34 UTC, TextAdventurer12 commented on osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
>          public double GetDifficultSliders()
they are doing different things. Sliderbreaks happen on sliderheads, so `TopWeightedSliders`is calculated with `aimNoSliders`, to focus on the difficulty of sliderheads. `DifficultSliders`is used for the sliderend penalty, so it uses aim with sliders.

2025-01-13 01:35 UTC, TextAdventurer12 commented on osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
>          public double GetDifficultSliders()
they could probably both use the same curve, but it would be a balancing change and I don't really like using one curve for multiple different things (same reason speed note count is still separate to `TopWeightedStrains`)

2025-03-07 22:00 UTC, tsunyoku commented
I've updated this branch to the latest `pp-dev`, performed some clean-ups and also added missing attribute IDs for the new difficulty attributes.

2025-05-01 11:26 UTC, tsunyoku commented
I've fixed up the compilation errors caused by dodgy rebases/merging. Please be careful with pushing your changes up in future.

2025-05-01 11:42 UTC, tsunyoku commented
!diffcalc
RULESET=osu
OSU_A=https://github.com/ppy/osu/tree/pp-dev
OSU_B=https://github.com/ppy/osu/pull/31234

2025-05-06 08:24 UTC, tsunyoku commented
!diffcalc
RULESET=osu
OSU_A=https://github.com/ppy/osu/tree/pp-dev
OSU_B=https://github.com/ppy/osu/pull/31234

2025-05-07 09:11 UTC, tsunyoku commented
!diffcalc
RULESET=osu
OSU_A=https://github.com/ppy/osu/tree/pp-dev
OSU_B=https://github.com/ppy/osu/pull/31234
SCORE_PROCESSOR_A=https://github.com/tsunyoku/osu-queue-score-statistics/tree/add-hd-so-to-relevant-legacy-mods
SCORE_PROCESSOR_B=https://github.com/tsunyoku/osu-queue-score-statistics/tree/add-hd-so-to-relevant-legacy-mods

2025-05-08 11:19 UTC, bdach commented on osu.Game.Rulesets.Osu/Difficulty/Skills/OsuStrainSkill.cs
I'm just passing through examining this because of https://discord.com/channels/188630481301012481/380598781432823815/1369990921906556969 but can we not do this type of hackery please? Having a protected list in a base class only for the `CountTopWeightedSliders()` helper is rather awful. Make the helper static and have it accept a list, and have the list be local to both skills please.

2025-05-08 11:22 UTC, tsunyoku commented on osu.Game.Rulesets.Osu/Difficulty/Skills/OsuStrainSkill.cs
Fair. Probably other cases of this too, I should refactor them all

2025-05-08 12:39 UTC, tsunyoku commented
!diffcalc
RULESET=osu
OSU_A=https://github.com/ppy/osu/tree/pp-dev
OSU_B=https://github.com/ppy/osu/pull/31234
SCORE_PROCESSOR_A=https://github.com/tsunyoku/osu-queue-score-statistics/tree/add-hd-so-to-relevant-legacy-mods
SCORE_PROCESSOR_B=https://github.com/tsunyoku/osu-queue-score-statistics/tree/add-hd-so-to-relevant-legacy-mods

2025-05-09 09:59 UTC, tsunyoku commented
!diffcalc
RULESET=osu
OSU_A=https://github.com/ppy/osu/tree/pp-dev
OSU_B=https://github.com/ppy/osu/pull/31234
SCORE_PROCESSOR_A=https://github.com/tsunyoku/osu-queue-score-statistics/tree/add-hd-so-to-relevant-legacy-mods
SCORE_PROCESSOR_B=https://github.com/tsunyoku/osu-queue-score-statistics/tree/add-hd-so-to-relevant-legacy-mods

2025-05-12 12:52 UTC, stanriders approved these changes
Still kinda hate this solution, but we don't really have any alternatives (except nuking stable) so it'll do

2025-05-12 12:53 UTC, tsunyoku approved these changes

2025-05-12 13:05 UTC, merged