Add `consistentRatioPenalty` to the `Colour` skill.
ppy/osu pull request #31285
Opened 2024-12-26 11:20 UTC by Lawtrohux

## osu!taiko Colour Skill Fix

Relies on #31284 for values to look good. Both of these are available for testing on huismetbenen together.

Introduces a new method, consistentRatioPenalty, to evaluate a consistency penalty based on the number of consecutive consistent intervals in rhythmic ratios. The function is designed to penalise patterns with excessive consistency in rhythmic sequences.

- Consistency Check: Compares the ratio of current and previous rhythmic intervals, applying a penalty if the percentage difference between the ratios is within a defined margin of error (threshold).
- 
- Penalty Calculation: The penalty scales based on the number of consecutive consistent intervals (consistentRatioCount) and the cumulative sum of their ratios (totalRatioCount).

The loop terminates when no valid previous TaikoDifficultyHitObject is available, as well as terminating on rhythm change, to ensure that this doesn't affect performance of the calculator, this has been tested with minimal increase to map load and calculation times.

2024-12-26 11:45 UTC, stanriders requested changes

2024-12-26 11:45 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
> +            var taikoObject = (TaikoDifficultyHitObject)hitObject;
```suggestion
            var taikoObject = (TaikoDifficultyHitObject)hitObject;
            TaikoDifficultyHitObjectColour colour = taikoObject.Colour;
```

2024-12-26 12:17 UTC, YaniFR commented
I am not too sure about performance when the loops running for long periods (example: long streams), can you post some benchmarks (even using system.stopwatch) to ensure that things still look good?

2024-12-28 15:01 UTC, YaniFR approved these changes
lgtm

2025-01-07 09:12 UTC, stanriders requested changes

2025-01-07 09:12 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
> +                if (previousHitObject.Previous(1) is not TaikoDifficultyHitObject)
I think using `if (previousHitObject.Index <= 1)` reads better because as is it looks like there can be non-taiko objects somehow

2025-01-07 09:12 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
> +            while (current.Previous(1) is TaikoDifficultyHitObject previousHitObject)
This feels really iffy. Did you test it on some absurdly long maps? Since diffcalc might run just when scrolling through the  song select this might noticeably lag people's game, and when taking pp counter in account (which runs diffcalc pretty much every object) I think this might be unacceptable.
Wouldn't using a constant amount of objects be enough here? Even something big like 256 would be way better

2025-01-07 09:12 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
> +                if (Math.Abs(1 - currentRatio / previousRatio) <= threshold)
Wouldn't it make sense to break when an interval is different or do you want to go through all of the map? 

e: looking at the PR description you indeed want to break on interval change, but I don't see it actually happening?

2025-01-07 10:26 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
> +                if (Math.Abs(1 - currentRatio / previousRatio) <= threshold)
it would. sorted and adjusted to be in line with before

2025-01-07 10:32 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
> +                if (current?.Previous(1) is not TaikoDifficultyHitObject previousHitObject || previousHitObject.Index <= 1)
```suggestion
                if (current?.Index <= 2)
```

2025-01-07 10:57 UTC, stanriders approved these changes

2025-01-07 11:36 UTC, merged