Add `Alt`+`MouseWheel` as a global volume adjust binding
ppy/osu pull request #31281
Opened 2024-12-26 05:13 UTC by peppy

This offers the defaults users have come to expect while also allowing rebinding (if they don't want it) and better compatibility with other global actions (since this is no longer implemented using `OnScroll` event flow).

Addresses part of https://github.com/ppy/osu/issues/31267.

2024-12-26 08:48 UTC, bdach commented
relevant test failures, same as https://github.com/ppy/osu/pull/31278 this breaks alt-scroll for timeline zoom in editor. maybe fixable by moving alt-scroll for timeline zoom to a editor hotkey, although that's sorta icky because the whole `ZoomableScrollContainer` machinery is too generic for its own good so if it ever gets reused outside of editor contexts it'll get stupid (that said it doesn't seem like we do that yet).

2024-12-26 08:48 UTC, bdach requested changes
as above

2025-01-02 06:11 UTC, peppy commented
> relevant test failures, same as #31278 this breaks alt-scroll for timeline zoom in editor. maybe fixable by moving alt-scroll for timeline zoom to a editor hotkey, although that's sorta icky because the whole `ZoomableScrollContainer` machinery is too generic for its own good so if it ever gets reused outside of editor contexts it'll get stupid (that said it doesn't seem like we do that yet).

That's surprising... aren't raw actions handled before the `OnPressed` flow..?;

2025-01-02 06:15 UTC, smoogipoo commented
If I'm understanding the above comment correctly (haven't looked at the issue or contents), it's likely because GAC has `Prioritised => true` causing it to handle bindings before raw inputs:
https://github.com/ppy/osu/blob/1cb2c8610452312abd04b3d02fd6abfa77335385/osu.Game/Input/Bindings/GlobalActionContainer.cs#L15-L17

2025-01-02 06:18 UTC, peppy commented
Yeah I think that's it. We have too many flags 😅 .

2025-01-02 06:41 UTC, peppy commented
I don't really like any of this, but your proposal of adding a key binding for timeline zoom seems like the best so let's go with that for now.

Alternative would be to undo these changes and just handle the alt-scroll as a special case game-level.

2025-01-02 06:43 UTC, peppy commented
Nope, it's shit. It will break precision scrolling and what not.

I'll just revert everything?

2025-01-02 06:43 UTC, closed without merging