Stamina balancing for osu!taiko
ppy/osu pull request #31337
Opened 2024-12-29 11:31 UTC by Lawtrohux

### Stamina Rebalance

- Adds a buff to mono notes in stamina skill. This begins at 5 and caps at past 20 notes.
- Checks for consecutive note count, the higher the consecutive note count, the higher the bonus provided, gives a bonus past 100 and is capped past 800 objects to prevent overbuffing, similar to the colour ratio check.

2025-01-14 13:26 UTC, YaniFR approved these changes

2025-01-14 13:26 UTC, YaniFR commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/StaminaEvaluator.cs
>              TaikoDifficultyHitObject taikoCurrent = (TaikoDifficultyHitObject)current;
sounds good, i think you removed the comment above that line by error

2025-01-15 09:36 UTC, stanriders requested changes

2025-01-15 09:36 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Skills/Stamina.cs
> +                return (currentStrain) / (1 + Math.Exp(-(index - 10) / 2.0));
`DifficultyCalculationUtils.Logistic`?

2025-01-15 10:11 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/Skills/Stamina.cs
> +                return (currentStrain) / (1 + Math.Exp(-(index - 10) / 2.0));
good call

2025-01-16 08:37 UTC, stanriders approved these changes

2025-01-16 10:30 UTC, merged