osu!taiko star rating and performance points rebalance
ppy/osu pull request #31338
Opened 2024-12-29 11:35 UTC by Lawtrohux

## osu!taiko star rating and performance points rebalance

### Star rating changes

- Increased multiplier to rhythm
- Increased multiplier to stamina

- Introduces strain length bonus and penalty, aims to smoothly nerf burst rhythm difficulty, and increase the very top end of rhythm difficult strains. This is the same for stamina. 

### Performance points changes

- Slightly decrease top end performance points valued (1150 to 1200)
- Increase accuracy scaling on difficulty performance points

2025-01-14 15:24 UTC, YaniFR approved these changes
good, most of these changes were tested on huismetbenen and were good

2025-01-15 09:41 UTC, stanriders requested changes

2025-01-15 09:41 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
> +            double accScalingShift = 500 - 100 * attributes.MonoStaminaFactor;
This was balanced together with https://github.com/ppy/osu/pull/31499 right?

2025-01-15 09:41 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
> +            double staminaDifficultStrains = stamina.CountTopWeightedStrains() * clockRate;
Why is it multiplied by clockrate here? Shouldn't clockrate be included in the strain calculation already?

2025-01-15 10:08 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
> +            double accScalingShift = 500 - 100 * attributes.MonoStaminaFactor;
Yep, was balanced together.

2025-01-16 10:39 UTC, stanriders approved these changes

2025-01-16 21:14 UTC, merged