osu!taiko further considerations for rhythm
ppy/osu pull request #31339
Opened 2024-12-29 11:39 UTC by Lawtrohux

After some feedback from players, it was noted how rhythm changes should be harshly penalised based on their repeated patterns.

This change aims to:
- Add consideration for both interval and ratio
- Provide different penalties based on either value
- Is no longer a strict check, to be able to penalise similar offsnaps inflating difficulty.

2025-01-14 15:20 UTC, YaniFR approved these changes
lgtm, these changes approved a lot rhythm in most parts

2025-01-15 09:47 UTC, stanriders requested changes

2025-01-15 09:47 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/RhythmEvaluator.cs
> +            return double.IsInfinity(ratio) || double.IsNaN(ratio) ? 0 : ratio;
You can use [double.IsNormal](https://learn.microsoft.com/en-us/dotnet/api/system.double.isnormal?view=net-9.0)

2025-01-15 09:47 UTC, stanriders commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/RhythmEvaluator.cs
> +            double durationPenalty = Math.Max(1 - sameRhythmHitObjects.Duration * 2 / hitWindow, 0.5);
Was increasing map OD leading to decreased SR fixed?

2025-01-15 10:11 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/RhythmEvaluator.cs
> +            double durationPenalty = Math.Max(1 - sameRhythmHitObjects.Duration * 2 / hitWindow, 0.5);
yes, had to switch the logic around in order for it to behave properly.

2025-01-15 10:13 UTC, Lawtrohux commented on osu.Game.Rulesets.Taiko/Difficulty/Evaluators/RhythmEvaluator.cs
> +            return double.IsInfinity(ratio) || double.IsNaN(ratio) ? 0 : ratio;
copy that

2025-01-15 10:25 UTC, stanriders commented
!diffcalc
RULESET=taiko
OSU_A=https://github.com/ppy/osu/tree/pp-dev
OSU_B=https://github.com/ppy/osu/pull/31339

2025-01-16 06:41 UTC, Lawtrohux commented
Sheet looks good, as it doesn't contain balancing changes it easily displays that the new rhythm is working as it should.

2025-01-17 11:15 UTC, stanriders approved these changes

2025-01-17 11:15 UTC, merged