Hit error judgements
ppy/osu pull request #3210
Opened 2018-08-12 20:52 UTC by zachllogan

- Closes #3209 

---

Adds an option to enable Hit Error Judgements, which colors judgments based off of their hit error (perfect timing is white and as hit error becomes earlier the judgement becomes bluer, as it becomes later the judgement becomes redder).

2018-08-12 22:12 UTC, UselessToucan requested changes

2018-08-12 22:12 UTC, UselessToucan commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +        protected Color4 JudgementColour(Judgement judgement)
`else if` and `return Color4.White` are redundant.

`protected Color4 JudgementColour(Judgement judgement) => judgement.TimeOffset >= 0 ? Color4.FromHcy(baseSlowColor + (maxSlowColor - baseSlowColor) * (float)(judgement.TimeOffset / JudgedObject.HitObject.HitWindows.HalfWindowFor(HitResult.Meh))) : Color4.FromHcy(baseFastColor + (maxFastColor - baseFastColor) * (float)(-judgement.TimeOffset / JudgedObject.HitObject.HitWindows.HalfWindowFor(HitResult.Meh)));`

2018-08-12 22:12 UTC, UselessToucan commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +        protected Color4 JudgementColour(Judgement judgement)
also, I would place a blank line between readonly fields and this method

2018-08-12 22:12 UTC, UselessToucan commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +                Colour = hitErrorJudgements ? JudgementColour(Judgement) : judgementColour(Judgement.Result),
As far as I see, this is the only `hitErrorJudgements` usage. Hence, it may be converted to a local variable.

2018-08-12 22:46 UTC, zachllogan commented
Should the colors be changed? Perhaps going from black or dark grey to light colors would make more sense for high background dims? (that way the worst you timing the more the judgement sticks out)

2018-09-09 13:27 UTC, peppy commented
This is definitely something we want, but I'm not sure if colours are the best way to show this. If they are, they should probably be made to match the 300/100/50 colour scheme rather than being RGB extremities.

2018-09-09 13:28 UTC, peppy commented on osu.Game/Rulesets/Judgements/DrawableJudgement.cs
> +        private readonly Vector4 baseFastColor = new Vector4(0.5f, 0.0f, 1.0f, 1);
At very least these should be `Color4`s

2019-09-06 09:46 UTC, peppy commented
I'm closing this one for now, since we have the hit error display.

I believe if a colour is applied to judgements, it shouldn't be applied directly to them, as they are coloured by the default (and many custom) skin.

2019-09-06 09:46 UTC, closed without merging