Fixes hyperdash computation (for nested objects)
ppy/osu pull request #3416
Opened 2018-09-12 17:55 UTC by Hanamuke

Fix #2586 
Rewrite from #2610 
Fixes hyperdash computation to take juice streams into account correctly.
I tested the patch, with high/low CS, converted/native and did not notice anything fondamently wrong.

2018-09-13 03:44 UTC, smoogipoo requested changes
Logic looks good in general, just a few minor fixups.

2018-09-13 03:44 UTC, smoogipoo commented on osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
> +            double halfCatcherWidth = CatcherArea.CATCHER_SIZE * objectWithDroplets[0].Scale / CatchPlayfield.BASE_WIDTH / 2;
This is being done in multiple locations now. Expose a static method from `CatcherArea`, `GetCatcherSize(BeatmapDifficulty difficulty)` and pass `Beatmap.BeatmapInfo.BaseDifficulty` available here in.

Moving forward, we need to keep catcher-specific calculations within `CatcherArea`/`Catcher`.

2018-09-13 03:44 UTC, smoogipoo commented on osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
> +        /// The difference between the distance of the next object
"Difference between the distance to the next object and the distance that would have triggered a hyper dash. A value close to 0 indicates a difficult jump (for difficulty calculation)."

2018-09-13 17:53 UTC, Hanamuke commented
I was concerned about Fruit that were during a JuiceStream, as it happens in some freestyle map, so i sorted the objects.

2018-09-14 02:27 UTC, smoogipoo approved these changes
Looks good to me for an initial implementation 👍

2018-09-14 02:36 UTC, merged