Tournament bracket display
ppy/osu pull request #3491
Opened 2018-09-25 01:28 UTC by peppy

PRing to potentially get some feedback on this. Is a big change but only going to grow over the week as I am for functional completion to replace current tournament streaming UI in preparation for OWC.

Remaining tasks:

- [ ] Add date entry
- [ ] Fix zoom logic
- [ ] Move as much event bind/reactive logic to non-drawable classes as possible
- [ ] Add proper non-visualtests project and remove menu shortcut for drawings

2019-05-15 09:01 UTC, smoogipoo requested changes

2019-05-15 09:01 UTC, smoogipoo commented on osu.Game/Overlays/Settings/SettingsItem.cs
> +                controlWithCurrent?.Current.UnbindBindings();
```suggestion
                if (bindable != null)
                    controlWithCurrent?.Current.UnbindFrom(bindable);
```

2019-06-13 07:43 UTC, peppy commented on osu.Game.Tournament/Components/DateTextBox.cs
> +                    bindable.Value = DateTimeOffset.Parse(sender.Text);
newText is a bool here

2019-06-13 07:44 UTC, peppy commented on osu.Game.Tournament/Components/DateTextBox.cs
> +                    bindable.TriggerChange();
This resets the text to its previous value on a fail to parse. Will add comment.

2019-06-13 07:51 UTC, peppy commented on osu.Game.Tournament/Components/TournamentBeatmapPanel.cs
> +                    Texture = new LargeTextureStore(new TextureLoaderStore(new StorageBackedResourceStore(storage))).Get($"mods/{mods}"),
no idea!

2019-06-13 07:53 UTC, peppy commented on osu.Game.Tournament/Screens/Ladder/Components/DrawableMatchTeam.cs
> +            //todo: tournamentgamebase?
no, still valid. i wanted to remove a lot of the action flow from the Drawable classes. still haven't been done yet.

2019-06-13 07:58 UTC, peppy commented on osu.Game.Tournament/Screens/Ladder/Components/MatchPairing.cs
> +        [JsonProperty]
was to get around this:
![image](https://user-images.githubusercontent.com/191335/59414423-73778b00-8dfc-11e9-805a-ff3b77299bdd.png)

open to suggestion (it's only read from serialisation currently; no in-game interface

2019-06-13 07:59 UTC, peppy commented on osu.Game.Tournament/Screens/Ladder/Components/TournamentGrouping.cs
> +        [JsonProperty]
Same reasoning as above. Shall I add it to all the other properties to match?

2019-06-13 08:01 UTC, peppy commented on osu.Game.Tournament/Screens/Ladder/LadderEditorScreen.cs
> +            ((Container)InternalChild).Add(new LadderEditorSettings
This is specifically adding to the container created by `LadderScreen`. ie. a Composite's `Content`. I'll name and expose as Content.

2019-06-13 08:03 UTC, peppy commented on osu.Game.Tournament/Screens/Ladder/LadderEditorScreen.cs
> +        private class JoinRequestHandler : CompositeDrawable
it visualises and creates a result (the click logic results in a join being fulfilled). i'm fine with renaming though.

2019-06-17 10:41 UTC, peppy commented
This is mostly ready to go now.

Changes made:
- Cleaned up bindable flow in many areas
- Made sure the tools can be used from scratch
- Added UI editing of all elements (except Team's players, coming soon)
- Improved render and invalidation logic of main bracket display

These are ready to be used be non-world-cup tournament for an enthusiast user. There's plenty of UX improvements to be applied, but I'm quite happy for an initial release.

2019-06-17 12:09 UTC, peppy commented
Added player editor and fixed startup issues when videos are not present.

2019-06-18 09:10 UTC, peppy commented
- Added round-beatmap editor.
- Made a very easily extensible base class for editor screens.
- Added ability to pre-populate teams with countries.
- Added ability to clear out all teams or rounds quickly.
- Extracted all `OsuGame` changes to dependent PRs (there should now be zero line added, and only `Drawings` screen extraction resulting in removals)
- Renamed classes to be more logical (`MatchPairing` -> `TournamentMatch`; `Grouping` -> `TournamentRound`).
- Added folder grouping to rider run configurations (they were getting cluttered).
- Added folders to tournament visual tests and added any missing tests.

@smoogipoo i'm seriously done on this now. Any further changes will be in follow-up PRs.

2019-06-21 06:49 UTC, smoogipoo commented
@peppy I've pushed a few fixed, there's nothing super bad here and can be cleaned up later. See if you agree with my changes.

2019-06-21 06:50 UTC, smoogipoo approved these changes

2019-06-21 07:02 UTC, merged