Update ruleset bindable only if enabled
ppy/osu pull request #3549
Opened 2018-10-05 11:14 UTC by plankp

Fix #3548

2018-10-05 11:18 UTC, peppy commented
Probably want to investigate how this regressed before blindly merging, since I don't think this crash used to exist.

2018-10-05 11:50 UTC, plankp commented
The issue only begin to appear in 2018.1004.0 Going to try to find what actually happened.

2018-10-05 12:19 UTC, smoogipoo commented
The reason for this is https://github.com/ppy/osu/pull/3523 . `ToolbarRulesetSelector` should do `PropagatePositionalInputSubTree => false` instead of `HandlePositionalInput => false`.

It's worth going through the PR I mentioned and verifying any similar cases have been converted over appropriately.

2018-10-08 18:11 UTC, plankp commented
Also fixes #3562

2018-10-09 06:32 UTC, peppy requested changes

2018-10-09 06:32 UTC, peppy commented on osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
> +        public override bool PropagatePositionalInputSubTree => !ruleset.Disabled;
`&& base.` for safety (see two lines above)?

2018-10-09 19:39 UTC, plankp commented
I think somewhere between github and appveyor broke...

2018-10-10 11:04 UTC, peppy approved these changes

2018-10-10 11:15 UTC, merged