Allowing auto-restarts on fail for Perfect and Sudden Death mod
ppy/osu pull request #3594
Opened 2018-10-14 15:21 UTC by plankp

Partially fixes #3380 since this does perform the auto-restart, but it is not optional.

2018-10-24 17:39 UTC, plankp commented
Now fully addresses #3380: By default auto-restart for SD and PF is disabled, but can be enabled in settings under the mods section.

2018-10-29 03:41 UTC, smoogipoo commented
I think this would work better if it was integrated into the game rather than being an option, tbh. Something like the restart button having a 3sec timer counting down which is cancelled upon pressing escape or the exit button.

2018-10-30 03:54 UTC, smoogipoo submitted a review, later dismissed

2018-10-30 03:54 UTC, smoogipoo commented on osu.Game/Rulesets/Mods/IApplicableRestartOnFail.cs
> +    public interface IApplicableRestartOnFail : IApplicableMod
How about combining this into `IApplicableFailOverride`? Make a property like `RestartOnFail` in it.

2018-10-30 19:19 UTC, peppy commented
The fail doesn't actually happen with the current code. It doesn't stop the audio. The restart can be called multiple times before it actually completes. Was this actually tested?

2018-10-31 05:18 UTC, smoogipoo requested changes

2018-10-31 05:18 UTC, smoogipoo commented on osu.Game/Screens/Play/Player.cs
> +                return false;
This should `return true` otherwise `onFail()` is going to be called multiple times.

2018-10-31 18:55 UTC, peppy commented
`osu-stable` does not auto restart for sudden death. was this an oversight or intentional change?

2018-10-31 18:58 UTC, plankp commented
Intentional (extract from linked issue: *It could work not only for Perfect but also SuddenDeath.*), but I could change it back.

2018-11-01 04:09 UTC, peppy commented
As long as it's a conscious change I guess this is fine for now. The idea is it will be a mod-specific setting in the future (when we have support for these).

2019-09-18 16:54 UTC, peppy commented
See #6159.

2019-09-18 16:54 UTC, closed without merging