Show a warning prior to opening external links
ppy/osu pull request #3625
Opened 2018-10-22 20:58 UTC by UselessToucan

Closes #3496 

![external-link-warning](https://user-images.githubusercontent.com/22450664/47317471-4c443180-d652-11e8-907d-c5c485865173.JPG)

About using safe browsing which was mentioned [here](https://github.com/ppy/osu/issues/3496#issuecomment-424377671): Google has [free](https://developers.google.com/safe-browsing/v4/pricing) safebrowsing service, but its basic [usage limits](https://developers.google.com/safe-browsing/v4/usage-limits) are suitable only for development and testing. In order to use it production, peppy will have to request additional quota.

2018-10-23 17:58 UTC, R0slaN commented
may i request you to add a "trust this domain in the future" button?
i'd imagine this feature would get annoying quickly without one.

2018-10-26 08:47 UTC, smoogipoo requested changes
In general seems fine, just needs some cleanup

2018-10-26 08:47 UTC, smoogipoo commented on osu.Game/OsuGame.cs
> +        public void OpenUrlExternally(string url) => externalLinkOpener.OpenUrlExternally(url);
Please put methods below the constructor and `load()` methods. Those that are currently not there are also misplaced but you don't have to change them for now.

2018-10-26 08:47 UTC, smoogipoo commented on osu.Game/Overlays/Chat/ExternalLinkDialog.cs
> +            HeaderText = "Confirm opening external link";
Maybe "Are you sure you want to open the following?"

2018-10-26 08:47 UTC, smoogipoo commented on osu.Game/Online/Chat/ExternalLinkOpener.cs
> +            void externalAction() => host.OpenUrlExternally(url);
Really don't need a nested function here, just in-line it in the two places.

2018-10-26 08:47 UTC, smoogipoo commented on osu.Game/Configuration/OsuConfigManager.cs
> +        WarnAboutOpeningExternalLink
`ExternalLinkWarning`

2018-10-26 08:47 UTC, smoogipoo commented on osu.Game/Online/Chat/ExternalLinkOpener.cs
> +        private Bindable<bool> warnAboutOpeningExternal;
`externalLinkWarning`

2018-11-23 06:20 UTC, smoogipoo approved these changes

2018-11-23 06:28 UTC, merged