Fixed formatting issue caused by tryAddInfoRightLine().
ppy/osu pull request #3640
Opened 2018-10-25 21:59 UTC by swstegall

Issue #3633 demonstrates that formatting issues in the profile will occur if a supplied string in the profile header is too large. After testing, I found that supplying tryAddInfoRightLine() with a string with more than 34 characters will cause formatting to break. To replicate how this is handled on the osu.Web interface, I added a case where any string with over 34 characters supplied to tryAddInfoRightLine() will print a substring of the first 31 characters and an ellipsis to the string before passing it along to infoTextRight.AddText().

Add any details pertaining to developers above the break.

- [ ] Depends on #PR
- Closes #3633

---

Fixed formatting issue in User ProfileHeader with strings with more than 34 characters.

Add a sentence or two describing this change in plain english. This will be displayed on the [changelog](https://osu.ppy.sh/home/changelog). A single screenshot or short gif is also welcomed.

2018-10-25 22:34 UTC, jorolf commented
You don't have to create 3 different pull requests. You should've added changes to the first one.

2018-10-25 22:52 UTC, swstegall commented
> You don't have to create 3 different pull requests. You should've added changes to the first one.

That was my mistake. I'm still fairly new to GitHub and I'm sure my excessive pull requests do not look good.

I still do not understand why my build checks are failing. AppVeyor complains about excessive whitespace on a certain line, but that line contains no additional whitespace, hence why I made the improper choice of duplicating my commit with changes to try and rectify this issue.

2018-10-25 22:55 UTC, morguldir commented on osu.Game/Overlays/Profile/ProfileHeader.cs
> +            const int LocalCharLimit = 31;
```suggestion
            const int LocalCharLimit = 31;
```

2018-10-26 01:21 UTC, Krystool submitted a review, later dismissed

2018-10-26 10:32 UTC, VPeruS commented on osu.Game/Overlays/Profile/ProfileHeader.cs
>              infoTextRight.AddIcon(icon);
```suggestion
             infoTextRight.AddIcon(icon);

             var line = " " + str;
             if (line.Length > local_char_limit)
                 line = str.Substring(0, local_char_limit) + "..."
```

2018-10-26 10:36 UTC, Aergwyn commented
This seems to be about the good ol' truncating topic? See https://github.com/ppy/osu/pull/2826 for reference where something similar was discussed.

2018-10-26 11:12 UTC, VPeruS commented on osu.Game/Overlays/Profile/ProfileHeader.cs
> +            const int local_char_limit = 31;
Glyphs can have different width, for example size of "i" != "w".

2018-10-27 06:43 UTC, swstegall commented
> This seems to be about the good ol' truncating topic? See #2826 for reference where something similar was discussed.

After analyzing the suggestions in that pull request, I still find myself a bit lost on how this should be handled. Are you suggesting passing the truncation off to another method and then including that method inside tryAddInfoRightLine()? Perhaps something like this:
```csharp
private string Truncate(string str, int bound)
{
    if (str.Length > bound)
        return str.Substring(0, bound) + "...");
}
```

And then calling that method inside tryAddInfoRightLine() with a block like this:
```csharp
private void tryAddInfoRightLine(FontAwesome icon, string str, string url = null)
{
    const int local_char_limit = 31;
    if (string.IsNullOrEmpty(str) == true) return;
    
    infoTextRight.AddIcon(icon);

    var line = " " + str;
    if (line.Length > local_char_limit)
        Truncate(line, local_char_limit);
    if(url != null)
        infoTextRight.AddLink(line, url);
    else
        infoTextRight.AddText(line);

    infoTextRight.NewLine();
}
```

2018-10-27 07:16 UTC, Aergwyn commented
No. It was more about that a truncate logic should exist at `SpriteText` level so this kind of localised logic that we'd need at many more places isn't necessary.

2018-10-27 07:42 UTC, swstegall commented
> No. It was more about that a truncate logic should exist at `SpriteText` level so this kind of localised logic that we'd need at many more places isn't necessary.

I see. I will have to do some more research and testing before attempting to develop a solution that would work on that scale. Thank you for your patience.

2018-10-29 03:46 UTC, smoogipoo requested changes
* Truncation should be implemented inside SpriteText itself (osu!framework).
* You changed the line ends of the entire file.

2019-06-17 03:49 UTC, Joehuu commented
Can be closed as referenced issue in OP was resolved with new design.

2019-06-17 03:56 UTC, closed without merging