Added basic sorting functionality
ppy/osu pull request #368
Opened 2017-02-17 22:17 UTC by tacchinotacchi

At the moment only logic is available, need tabs for graphic interactions

2017-02-17 22:32 UTC, Nabile-Rahmani requested changes

2017-02-17 22:32 UTC, Nabile-Rahmani commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        return string.Compare(x.BeatmapSet.Metadata.Artist, y.BeatmapSet.Metadata.Artist);
Can you replace these three lambda bodies by an expression ? (`groups.Sort((x, y) => string.Compare([...]);`)

2017-02-17 22:32 UTC, Nabile-Rahmani commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        else if (Equals(x.BeatmapSet.Beatmaps.First().BaseDifficulty.OverallDifficulty,
These two `else` can be dropped.

2017-02-17 22:32 UTC, Nabile-Rahmani commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        if (x.BeatmapSet.Beatmaps.First().BaseDifficulty.OverallDifficulty >
It's probably a good idea to leave a TODO comment there so we can replace `OverallDifficulty` by the actual star rating whenever it gets implemented.

2017-02-17 22:52 UTC, tacchinotacchi commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        return string.Compare(x.BeatmapSet.Metadata.Artist, y.BeatmapSet.Metadata.Artist);
I tried Compare, but for some reason it didn't have any effect. It's late in my timezone, so I'm gonna give it a look tomorrow

2017-02-17 22:57 UTC, tacchinotacchi commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        else if (Equals(x.BeatmapSet.Beatmaps.First().BaseDifficulty.OverallDifficulty,
I was trying to follow the standard, but I'll drop them if the results are the same

2017-02-18 14:55 UTC, tacchinotacchi commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        else
IMO leaving one `else` improves readability. Feel free to change

2017-02-20 15:39 UTC, UselessToucan requested changes

2017-02-20 15:39 UTC, UselessToucan commented on osu.Desktop.VisualTests/Tests/TestCasePlaySongSelect.cs
> +        private Random rnd = new Random();
[osu.Framework.MathUtils.RNG](https://github.com/ppy/osu-framework/blob/master/osu.Framework/MathUtils/RNG.cs)

2017-02-21 07:01 UTC, peppy commented on osu.Desktop.VisualTests/Tests/TestCasePlaySongSelect.cs
> +            OnArtist = () => { songSelect.Filter.Sort = FilterControl.SortMode.Artist; };
why even make these when you could put the anonymous delegates in the AddButton lines below?

2017-02-21 07:02 UTC, peppy commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        else
p.s. star ratings are implemented now.

2017-02-22 05:11 UTC, Nabile-Rahmani requested changes

2017-02-22 05:11 UTC, Nabile-Rahmani commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        if (x.BeatmapSet.Beatmaps.First().StarDifficulty >
You could compute the mean star difficulty value of the sets.

2017-02-25 07:38 UTC, Nabile-Rahmani requested changes

2017-02-25 07:38 UTC, Nabile-Rahmani commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        float xAverage=0, yAverage=0;
[Average](https://msdn.microsoft.com/en-us/library/system.linq.enumerable.average(v=vs.110).aspx) ?

2017-02-26 21:16 UTC, tacchinotacchi commented on osu.Game/Screens/Select/CarouselContainer.cs
> +                        float xAverage=0, yAverage=0;
As far as I know, Average, unlike Sort, does not accept delegates. If that's the case, Average would only work with integers, doubles, etc.

2017-03-02 09:46 UTC, merged