SongSelect advanced filtering criteria
ppy/osu pull request #3906
Opened 2018-12-23 11:57 UTC by phosphene47

Will resolve #3781, but does not implement everything described in that issue, so don't merge yet.

The syntax is `<key><op><value>`, e.g. `stars:5`, `stars>3`, `stars<5`

Currently can filter by:

- Star difficulty
- Approach rate
- Beat divisor
- Beatmap length

2018-12-23 14:01 UTC, ticotaco72 commented
Wouldn't it be better to be done in UI?

2019-01-15 09:08 UTC, peppy requested changes

2019-01-15 09:08 UTC, peppy commented on osu.Game/Screens/Select/FilterCriteria.cs
> +            public bool IsTrue(double value)
I'd probably call this function `IsInRange`.

2019-07-28 16:31 UTC, peppy commented
@phosphene47 I know it's been a while, but do you want to bring this up-to-date? Length has since been added so your database changes can be removed from this PR.

2019-07-28 22:23 UTC, phosphene47 commented
Sure. Would it be wiser to start a brand new PR from current master? I'm guessing there were a lot of changes since last December.

2019-07-29 03:15 UTC, peppy commented
If you can get this PR in line, there's no need to make a new branch.

2019-09-18 17:51 UTC, peppy commented
See #6161.

2019-09-18 17:51 UTC, closed without merging