Fix global idle state being entered when overlays are visible
ppy/osu pull request #3919
Opened 2018-12-26 09:41 UTC by peppy

- [ ] Depends on ppy/osu-framework#2051.

May want to localise this behaviour to MainMenu / ButtonSystem.

2018-12-29 14:07 UTC, UselessToucan commented on osu.Game/OsuGame.cs
> +            private readonly List<OverlayContainer> overlays;
As far as I see, this field is not used.

2019-01-23 10:00 UTC, peppy commented
This still needs attention (causes really bad UX on platforms without escape key still). @smoogipoo

2019-01-23 10:32 UTC, smoogipoo requested changes

2019-01-23 10:32 UTC, smoogipoo commented on osu.Game/Input/IdleTracker.cs
> +            isIdle.Value = TimeSpentIdle > timeToIdle && AllowIdle;
I really don't think we want to be querying the containing input manager every frame.

2019-01-25 10:50 UTC, smoogipoo approved these changes

2019-01-25 11:18 UTC, merged