Add performance counter
ppy/osu pull request #3971
Opened 2018-12-30 06:00 UTC by Poyo-SSB

Obvious use-case for #3909. As with the aforementioned PR, the code in its current state is horrible and gross; this PR has been opened to facilitate discussion regarding how a proper implementation should be done.

- [ ] Depends on #3909

---

2019-01-16 16:39 UTC, holly-hacker requested changes

2019-01-16 16:39 UTC, HoLLy-HaCKeR commented on osu.Game/Graphics/UserInterface/PerformanceCounter.cs
> +            return $@"{Math.Round(count, 2)}pp";
Minor nitpick, but you can use format specifiers here.
```suggestion
            return $@"{count:N2}pp";
```

2019-01-16 16:39 UTC, HoLLy-HaCKeR commented on osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
> +        public DifficultyAttributes Calculate(double upTo, params Mod[] mods)
I'd create an overload for this, since you can't assign a default value to upTo.

2019-01-16 16:39 UTC, HoLLy-HaCKeR commented on osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
> +        protected override DifficultyAttributes Calculate(double upTo, IBeatmap beatmap, Mod[] mods, double timeRate)
Putting this as the first parameter everywhere requires all usages to be updated. In this case, I'd move the upTo parameter to the end and assign it a default value (for example, `DifficultyAttributes Calculate(IBeatmap beatmap, Mod[] mods, double timeRate, double upTo = Double.PositiveInfinity)`).

This way it won't break existing usages and your diff will be smaller.

2019-01-16 16:39 UTC, HoLLy-HaCKeR commented on osu.Game/Screens/Play/HUDOverlay.cs
> +                PerformanceCounter.Current.Value = performanceCalculator.Calculate(performanceClock.CurrentTime);
No null check, `performanceCalculator` can be null if it is not yet implemented for the current mode.

2020-08-30 16:18 UTC, ArniDagur commented
I'm curious: Is there anything major besides the need to rebase onto `master`, which is holding this PR and https://github.com/ppy/osu/pull/4479 back?

2020-08-30 16:21 UTC, bdach commented
Aside from the review comments not being addressed, seeing that the branches are years old at this point this code will be either horrible to merge, use members/paradigms that are entirely incorrect, or both.

The performance counter will return in due time.

2020-08-31 03:57 UTC, smoogipoo commented
The dependent PR is mostly the issue, which isn't taking a suitable path.

2021-06-03 08:16 UTC, peppy commented
While cleaning up pull requests, we found that your contributions here were forgotten about either due to dangling reviews or going in a direction we did not fully agree with. Given its age and inactivity, we're going to close this for now.

If you're still interested in seeing this change happen, either by bringing this pull request up-to-date or re-opening as a fresh one, please let us know in this thread before doing so and we will elaborate on what needs to be done (and whether it's a change we see being mergeable in the future).

(most of the actual logic in the PR is from the dependency of #4479 which has since been closed. when that is eventually resolved reimplementing this should be trivial)

2021-06-03 08:16 UTC, closed without merging