Add Beatmap Skin Toggle to General Settings
ppy/osu pull request #4091
Opened 2019-01-18 00:22 UTC by nwabear

Added "Use beatmap skins" button to general settings

Add any details pertaining to developers above the break.

- [ ] Depends on #PR
- Closes #ISSUE

---

This patch adds a "Use beatmap skins" button to the general settings page under the skin section. Having this button along with the one in the visual settings should remove confusion from users switching from osu! to osu!lazer.

2019-01-18 07:09 UTC, peppy commented
Want to add the checkbox for hitsounds too, since that is the only one remaining msising?

2019-01-20 11:22 UTC, peppy requested changes

2019-01-21 14:05 UTC, nwabear commented on osu.Game/Overlays/Settings/Sections/Audio/VolumeSettings.cs
> +                new SettingsCheckbox       { LabelText = "Use beatmap hitsounds", Bindable = config.GetBindable<bool>(OsuSetting.BeatmapHitsounds) },
Sorry about that, I moved it to the skin section.

2019-01-22 01:08 UTC, peppy approved these changes

2019-01-22 01:15 UTC, merged