Update with framework bindable changes
ppy/osu pull request #4303
Opened 2019-02-21 10:07 UTC by smoogipoo

1. All methods marked as `updateX` use the pattern `.ValueChanged += e => updateX(e.NewValue)`
2. All methods marked as `XChanged` use the pattern `void XChanged(ValueChangedEvent<T> e)`

2019-02-21 10:08 UTC, smoogipoo commented
Note: Build will compile with warnings until https://github.com/ppy/osu/pull/4300 is also merged.

2019-02-22 02:52 UTC, peppy requested changes

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/NotePiece.cs
> +                colouredBox.Anchor = colouredBox.Origin = direction.Value == ScrollingDirection.Up ? Anchor.TopCentre : Anchor.BottomCentre;
```suggestion
                colouredBox.Anchor = colouredBox.Origin = e.NewValue == ScrollingDirection.Up ? Anchor.TopCentre : Anchor.BottomCentre;
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Mania/UI/Components/ColumnBackground.cs
> +                backgroundOverlay.Anchor = backgroundOverlay.Origin = direction.Value == ScrollingDirection.Up ? Anchor.TopLeft : Anchor.BottomLeft;
```suggestion
                backgroundOverlay.Anchor = backgroundOverlay.Origin = e.NewValue == ScrollingDirection.Up ? Anchor.TopLeft : Anchor.BottomLeft;
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
> +                Anchor anchor = direction.Value == ScrollingDirection.Up ? Anchor.TopLeft : Anchor.BottomLeft;
```suggestion
                Anchor anchor = e.NewValue == ScrollingDirection.Up ? Anchor.TopLeft : Anchor.BottomLeft;
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Mania/UI/Components/ColumnKeyArea.cs
> +                    direction.Value == ScrollingDirection.Up ? Color4.Black : Color4.Black.Opacity(0),
```suggestion
                    e.NewValue == ScrollingDirection.Up ? Color4.Black : Color4.Black.Opacity(0),
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Mania/UI/Components/ColumnKeyArea.cs
> +                    direction.Value == ScrollingDirection.Up ? Color4.Black.Opacity(0) : Color4.Black);
```suggestion
                    e.NewValue == ScrollingDirection.Up ? Color4.Black.Opacity(0) : Color4.Black);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
> +                this.beatmap.ValueChanged += e => calculateScale();
```suggestion
                this.beatmap.ValueChanged += _ => calculateScale();
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
> +                cursorScale.ValueChanged += e => calculateScale();
```suggestion
                cursorScale.ValueChanged += _ => calculateScale();
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
> +                autoCursorScale.ValueChanged += e => calculateScale();
```suggestion
                autoCursorScale.ValueChanged += _ => calculateScale();
```

2019-02-22 02:52 UTC, peppy commented on osu.Game.Tests/Visual/TestCaseDrawableDate.cs
> +                drawableDate.Current.ValueChanged += e => flash.FadeOutFromOne(500);
```suggestion
                drawableDate.Current.ValueChanged += _ => flash.FadeOutFromOne(500);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Beatmaps/WorkingBeatmap.cs
> +            Mods.ValueChanged += e => applyRateAdjustments();
```suggestion
            Mods.ValueChanged += _ => applyRateAdjustments();
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/BeatmapSet/Header.cs
> +                    downloadButtonsContainer.Child = new osu.Game.Overlays.Direct.DownloadButton(BeatmapSet.Value)
```suggestion
                    downloadButtonsContainer.Child = new osu.Game.Overlays.Direct.DownloadButton(e.NewValue)
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/BeatmapSet/Header.cs
> +                    downloadButtonsContainer.Child = new DownloadButton(BeatmapSet.Value);
```suggestion
                    downloadButtonsContainer.Child = new DownloadButton(e.NewValue);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/BeatmapSet/Header.cs
> +                    downloadButtonsContainer.Child = new DownloadButton(BeatmapSet.Value);
```suggestion
                    downloadButtonsContainer.Child = new DownloadButton(e.NewValue);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/BeatmapSet/Header.cs
> +                        downloadButtonsContainer.Add(new DownloadButton(BeatmapSet.Value, true));
```suggestion
                        downloadButtonsContainer.Add(new DownloadButton(e.NewValue, true));
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/Music/PlaylistItem.cs
> +            artistBind.BindValueChanged(e => recreateText(), true);
```suggestion
            artistBind.BindValueChanged(_ => recreateText(), true);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/Settings/SettingsItem.cs
> +                    bindable.ValueChanged += e => UpdateState();
```suggestion
                    bindable.ValueChanged += _ => UpdateState();
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/Settings/SettingsItem.cs
>                      bindable.DisabledChanged += disabled => UpdateState();
```suggestion
                    bindable.DisabledChanged += _ => UpdateState();
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/SocialOverlay.cs
> +            Header.Tabs.Current.ValueChanged += e => Scheduler.AddOnce(updateSearch);
```suggestion
            Header.Tabs.Current.ValueChanged += _ => Scheduler.AddOnce(updateSearch);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Overlays/SocialOverlay.cs
> +            Filter.Tabs.Current.ValueChanged += e => Scheduler.AddOnce(updateSearch);
```suggestion
            Filter.Tabs.Current.ValueChanged += _ => Scheduler.AddOnce(updateSearch);
```

2019-02-22 02:52 UTC, peppy commented on osu.Game/Screens/Multi/Match/Components/MatchChatDisplay.cs
> +            roomId.BindValueChanged(e => updateChannel(), true);
```suggestion
            roomId.BindValueChanged(_ => updateChannel(), true);
```

2019-02-22 02:53 UTC, peppy commented
Proposal #1:

Use the previous variable names instead of `e`. I think this will read better (`channel.NewValue` rather than `e.NewValue`).

Proposal #2:

Give ValueChangedEvent implicit operator that returns `NewValue` by default, so we don't need the NewValue suffix in most cases. Not sure about this one, but seems like it may tidy this back up?

2019-02-22 08:54 UTC, peppy submitted a review, later dismissed

2019-02-22 09:01 UTC, peppy approved these changes

2019-02-22 09:04 UTC, merged