Don't show the supporter text if the user already has supporter status
ppy/osu pull request #4332
Opened 2019-02-25 22:52 UTC by jorolf

This was suggested a while ago in the discord server however he never finished/pr'ed it

2019-02-25 23:34 UTC, peppy commented
Can we at least fade it? Also may want tick sister unbinding on suspend as a safety measure.

2019-02-26 04:58 UTC, peppy commented on osu.Game/Screens/Menu/Disclaimer.cs
> +                    textFlow.RemoveRange(supporterDrawables);
```csharp
textFlow.FadeOut(200, Easing.OutQuint).Expire();
```

should work quite well i believe.

2019-02-28 08:22 UTC, smoogipoo requested changes

2019-02-28 08:22 UTC, smoogipoo commented on osu.Game/Screens/Menu/Disclaimer.cs
> +            api.LocalUser.BindValueChanged(userChanged, true);
Is there a reason why you're not creating a local bindable? This sort of usage of bindables (binding to the outside's valuechanged) is generally seen as unsafe.

2019-03-03 11:22 UTC, merged