Give Multiplayer its own background stack
ppy/osu pull request #4451
Opened 2019-03-11 02:19 UTC by nyquillerium

Currently, the background for beatmaps is incorrectly showing in the base background stack in MatchSongSelect. This will give MatchSongSelect its own background stack.

Worth noting that the toolbar will still use the base background stack, which may or may not be what we want.

2019-03-11 05:29 UTC, peppy commented
This is adding a new meaning to excessive overdraw, but as discussed with @smoogipoo this is probably fine to do for the time being pending second-pass optimisations.

2019-03-11 05:29 UTC, peppy approved these changes

2019-03-11 05:30 UTC, peppy commented
The stack here needs parallax applied. It looks wrong currently.

2019-03-11 05:30 UTC, peppy requested changes
as specified

2019-03-11 08:18 UTC, peppy requested changes

2019-03-11 08:18 UTC, peppy commented on osu.Game/Screens/Multi/Multiplayer.cs
> +                            backgroundParallax = new ParallaxContainer
variable unnecessary (see CI)

2019-03-11 13:09 UTC, peppy requested changes

2019-03-11 13:09 UTC, peppy commented on osu.Game/Screens/OsuScreenStack.cs
> +            backgroundScreenStack = new BackgroundScreenStack { RelativeSizeAxes = Axes.Both };
move inline

2019-03-12 01:45 UTC, nyquillerium commented
gonna block this while I look through visual tests for using the new OsuScreenStrack

2019-03-20 11:39 UTC, peppy requested changes

2019-03-20 11:39 UTC, peppy commented on osu.Game/Screens/OsuScreenStack.cs
> +            ScreenPushed += setParallax;
shouldn't `ScreenExited` also be handled? else parallax is going to get stuck int he wrong state

2019-03-20 11:43 UTC, peppy requested changes

2019-03-20 11:43 UTC, peppy commented on osu.Game/OsuGame.cs
> +            screenStack = new OsuScreenStack { RelativeSizeAxes = Axes.Both };
move back to old location unless there's a reason for it to be here.

2019-03-20 11:43 UTC, peppy commented on osu.Game/OsuGame.cs
> +                screenStack.Push(new Loader
needs a comment as to why this is done here (also newline above).

2019-03-22 05:52 UTC, peppy commented
Did you test the test you added? It's not pushing a screen, and even if it was, the parallax would not be changing so it's quite pointless.

2019-03-22 06:10 UTC, nyquillerium commented
I added a sprite text to each screen to make it visually confirmable that a screen has been pushed, as well as say what should be confirmed visually.

2019-03-22 07:04 UTC, peppy commented
I didn't like having the parallax test inside the `ScreenStack` based on current screen. It has potential to fail since it's not explicitly checking values in the test step logic.

Refactored accordingly.

2019-03-22 08:13 UTC, peppy requested changes

2019-03-22 08:13 UTC, peppy commented on osu.Game/OsuGame.cs
> +                screenStack.Push(new Loader
this comment is wrong. loader is not being created synchronously, nor is it done to successfully DI the background stack.

the comment is supposed to explain why it's laded after the logo, which is the true intent here, no?

2019-03-22 08:13 UTC, peppy commented on osu.Game/OsuGame.cs
> +            screenStack = new OsuScreenStack { RelativeSizeAxes = Axes.Both };
hasn't been resolved

2019-03-22 08:13 UTC, peppy commented on osu.Game/Tests/Visual/ScreenTestCase.cs
>              Children = new Drawable[]
Child =

2019-03-22 08:13 UTC, peppy commented on osu.Game/Screens/OsuScreenStack.cs
> +            if (next != null)
i think a better default would be `1` when next is null (since that what the initial value is when constructing the container).

2019-03-25 03:43 UTC, peppy submitted a review, later dismissed

2019-03-25 03:54 UTC, peppy approved these changes

2019-03-25 04:12 UTC, merged