Implement skinning for slider border thickness
ppy/osu pull request #4471
Opened 2019-03-14 20:10 UTC by santerinogelainen

resolves #4422

Legacy parsing might be useless since legacy client doesn't have that skin.ini option implemented afaik, but i still added it.

Size is given as a percentage (integer) so 100 = default, 20 = 20% of the default, 200 = 200% of the default and so on.

2019-03-16 02:36 UTC, peppy commented
do we use int percentages like this anywhere else? also no limiting? what happens if you set to zero or 1000000?

2019-03-16 02:37 UTC, peppy requested changes

2019-03-16 02:37 UTC, peppy commented on osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
> +        public int BorderSize {
B races go in new line

2019-03-16 05:13 UTC, swoolcock commented on osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
> +            private float calucatedBorderPortion => BorderSize / 100f * border_portion;
Typo.

2019-05-12 14:09 UTC, peppy commented
Generally I'd still prefer to add new skinning features before all existing ones have been completed (and in the process, the skin system fleshed out).

For instance, this one is under `[General]` because it has no better place to be, but such settings should be per-ruleset and adjustable in-game, not just from skin.ini (both parts of a larger refactor of skinning coming in the future).

2019-05-12 14:09 UTC, peppy approved these changes

2019-05-12 14:10 UTC, peppy approved these changes

2019-05-12 15:02 UTC, merged