Add toggle for hiding "great" judgement in osu
ppy/osu pull request #4641
Opened 2019-04-18 11:08 UTC by YoDevil

As a player the "great" text showing after each hit is annoying.
In legacy we get around this with skinning hacks, but those hacks don't always work in the legacy skins here. This also allows to hide it in the default skin too.
Open to discussions on whether this is the right way to procede.

I'm not sure if this is a thing in other Rulesets too, i made it for osu only as it's what i play.

Also first contribution ༼ つ ◕_◕ ༽つ

2019-04-18 11:45 UTC, frenzibyte requested changes
I think the option should be more like Hide Great Judgement than Show it

2019-04-18 11:51 UTC, LeNitrous commented
Instead of filling up Settings, it would be wiser to make this an option in skinning (which is not yet implemented).

2019-04-18 12:30 UTC, YoDevil commented
> I think the option should be more like Hide Great Judgement than Show it
Ok, I'll wait for more feedback

> Instead of filling up Settings, it would be wiser to make this an option in skinning (which is not yet implemented).
Some skins are already doing it, i'm not sure how but probably with blank png's.
I think the default skin in lazer has potential, but i can't use it with 'great' appearing everywhere

2019-04-18 12:36 UTC, iiSaLMaN commented
I think LeNitrous meant that the option will be inside the skin in an information file or smth, but wouldn't that make a problem for the stable, i would say you put it as an option in the settings

2019-04-18 12:40 UTC, LeNitrous commented
There is a planned skinning system for lazer. There is a reason why skins from stable are called "Legacy"

2019-04-18 12:41 UTC, iiSaLMaN commented
I see, thanks for pointing out.

2019-04-18 23:17 UTC, Joehuu commented
See https://github.com/ppy/osu/pull/2921#issuecomment-401523773.

2019-04-19 09:33 UTC, YoDevil commented
So this definitely is a concern in other rulesets too.
Then I agree that it should be done independently of the ruleset, but i'm not convinced that it should be skinning.

I believe i heard that the plan is to have _layerable_ skins, which means that ideally there could be a 'hide great/perfect judgements' skin to overlay to whatever other skins are being played. But at that point why not have it as a gameplay toggle instead?

2019-04-19 10:12 UTC, peppy commented
Because by adding gameplay toggles they are just going to have to be reimplemented or removed later. It's pointless.

2019-04-22 09:25 UTC, closed without merging