Implement S+ and SS+ Grading
ppy/osu pull request #4642
Opened 2019-04-18 12:45 UTC by iiSaLMaN

Implement SH and XH (S+ and SS+) Grades.

2019-04-20 03:36 UTC, iiSaLMaN commented
I'm thinking about simplifying the rank adjusting way, instead of calling a function to adjust the rank from completion function, how about we simply create a field that tells the grading function whether to adjust the rank or not, and will be set from ApplyToScoreProcessor

2019-04-21 03:57 UTC, peppy requested changes

2019-04-21 03:57 UTC, peppy commented on osu.Game/Rulesets/Mods/IApplicableToScoreProcessor.cs
> +        ScoreRank AdjustRank(ScoreRank rank);
missing newline, missing xmldoc.

2019-04-21 03:57 UTC, peppy commented on osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
> +            public ScoreRank AdjustRank(ScoreRank rank)
`=> rank;`

2019-04-21 03:57 UTC, peppy commented on osu.Game/Rulesets/Mods/ModFlashlight.cs
> +        public ScoreRank AdjustRank(ScoreRank rank)
`=> rank;`

2019-04-21 12:36 UTC, iiSaLMaN commented
I guess i'm gonna close this and create another branch for implementing the grades and make sure it will not contain any issues

2019-04-21 12:36 UTC, closed without merging