Add number sign in front of profile rankings
ppy/osu pull request #4691
Opened 2019-05-01 03:49 UTC by Joehuu

![](https://puu.sh/DmghF/70d29f5a33.png)

---

2019-05-01 11:06 UTC, peppy commented
Please check CI issues.

2019-05-01 11:13 UTC, jorolf commented on osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
> -            detailGlobalRank.Content = user?.Statistics?.Ranks.Global?.ToString("#,##0") ?? "-";
You can include the sign in the original ``ToString()`` call

2019-05-01 22:54 UTC, jorolf requested changes

2019-05-01 22:54 UTC, jorolf commented on osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
> +            detailGlobalRank.Content = user?.Statistics?.Ranks.Global == null ? "-" : $"#{user?.Statistics?.Ranks.Global?.ToString("#,##0")}";
```suggestion
            detailGlobalRank.Content = user?.Statistics?.Ranks.Global?.ToString("\\##,##0") ?? "-";
```

2019-05-01 22:54 UTC, jorolf commented on osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
> +            detailCountryRank.Content = user?.Statistics?.Ranks.Country == null ? "-" : $"#{user?.Statistics?.Ranks.Country?.ToString("#,##0")}";
```suggestion
            detailCountryRank.Content = user?.Statistics?.Ranks.Country?.ToString("\\##,##0") ?? "-";
```

2019-05-02 03:55 UTC, peppy approved these changes

2019-05-02 03:55 UTC, merged