Track ButtonSystem over a duration when entering mode
ppy/osu pull request #4813
Opened 2019-05-17 02:35 UTC by nyquillerium

Closes https://github.com/ppy/osu/issues/4792

The issue was caused by the immediate 0 duration tracking of the `OsuLogo` when starting tracking of `ButtonSystem`, and the fact that in the first place the initial location of the `Facade` is not centered on the logo itself, but where the `ButtonSystem` should be. 

To resolve this, I made the logo track over the same length of the `ButtonSystem` suspending transform. This modifies the tracking animation slightly, but I think it looks fine. Here's a preview using a modified `TestCaseButtonSystem`:

https://streamable.com/m380g

2019-07-03 08:43 UTC, peppy requested changes

2019-07-03 08:43 UTC, peppy commented on osu.Game/Screens/Menu/ButtonSystem.cs
> +                    // When coming from the Initial (untracked) state, interpolate to the tracking position over a brief duration instead of tracking immediately.
comment explains code 1:1 and therefore unnecessary.

2019-07-03 08:43 UTC, peppy commented
Was there supposed to be a test added for this? How do I check it's working?

2019-07-03 09:14 UTC, nyquillerium commented
I modified `TestSceneButtonSystem` like this to visualize, but it seemed kinda messy to have in the test case
```
foreach (var s in Enum.GetValues(typeof(ButtonSystemState)).OfType<ButtonSystemState>().Skip(1))
  AddStep($"State to {s}", () =>
  {
      buttons.State = s;

      if (buttons.State == ButtonSystemState.EnteringMode)
      {
        buttons.FadeOut(400, Easing.InSine);
        buttons.MoveTo(new Vector2(-800, 0), 400, Easing.InSine);
        logo.FadeOut(300, Easing.InSine)
         .ScaleTo(0.2f, 300, Easing.InSine);
      }
      else
      {
          buttons.FadeIn(400, Easing.OutQuint);
          buttons.MoveTo(new Vector2(0), 400, Easing.OutQuint);
          logo.FadeColour(Color4.White, 100, Easing.OutQuint);
          logo.FadeIn(100, Easing.OutQuint);
      }
  });
```

2019-07-03 10:44 UTC, peppy commented
I think it's fine to have as its own test method, as we do elsewhere. If it's not there as a test the potential for regression is higher (even if not automated).

2019-07-05 02:31 UTC, peppy commented
I split out the test into its own test method (as I proposed) which may have revealed another flaw in logic currently: the animation is different if it is executed earlier.

Not a regression, but worth noting.

2019-07-05 03:56 UTC, nyquillerium commented
Ah, I didn't understand the initial proposal.

The 400 is a length specified locally in `OnSuspending` of `MainMenu`, and the transform is applied screen-wide. https://github.com/ppy/osu/blob/0ec01f7b0fa5ca4ae8b4f3a76182ff5be2fdb493/osu.Game/Screens/Menu/MainMenu.cs#L174

2019-07-05 04:00 UTC, peppy commented
please expose and use the constant so it's obvious, then.

2019-07-05 07:04 UTC, peppy commented on osu.Game/Screens/Menu/ButtonSystem.cs
> +                    logoTrackingContainer.StartTracking(logo, lastState == ButtonSystemState.Initial ? 400 : 0, Easing.InSine);
.

2019-07-06 15:01 UTC, peppy approved these changes

2019-07-06 15:41 UTC, merged