Make IAPIProvider.IsLoggedIn bindable
ppy/osu pull request #4854
Opened 2019-05-25 10:55 UTC by UselessToucan

I would like to be able to track auth state using `IsLoggedIn` property without relying on other properties like `LocalUser`.

see https://github.com/UselessToucan/osu/blob/replace_raw_actions_with_commands/osu.Game/Input/Commands/ToggleOnlineOverlayCommand.cs#L20
I know it won't merged, but it is still can be used as an example.

2019-05-28 03:43 UTC, smoogipoo commented
@peppy what do you think of this? I'm sure you already know of the reservations I have w.r.t when do you use `LocalUser.BindValueChanged` vs `OnStageChanged / IOnlineComponent`, and this feels like it might be adding more fuel to that fire.

2019-05-28 03:47 UTC, peppy requested changes

2019-05-28 03:47 UTC, peppy commented on osu.Game/Online/API/DummyAPIAccess.cs
> +        public Bindable<bool> IsLoggedIn => new Bindable<bool>(true);
incorrectly implemented (see `logout`)

2019-05-28 03:47 UTC, peppy commented on osu.Game/Online/API/APIAccess.cs
> +        private bool getIsLoggedInInternal() => LocalUser.Value.Id > 1;
should not be done like this. follow the same path that `LocalUser` gets set in.

2019-05-28 03:47 UTC, peppy commented on osu.Game/Online/API/APIAccess.cs
> +        public Bindable<bool> IsLoggedIn => new Bindable<bool>(getIsLoggedInInternal());
remove initial value specification here (see next comment).

2019-05-28 03:47 UTC, peppy commented on osu.Game/Online/API/APIAccess.cs
> +        public Bindable<bool> IsLoggedIn => new Bindable<bool>(getIsLoggedInInternal());
also should be `IBindable`

2019-05-28 03:48 UTC, peppy commented
@smoogipoo i think this is alright, although to me it makes little sense why you'd use this as opposed to `LocalUser` bindable, since basically 100% of the time you want to know the user that is logged in when checking whether logged in.

2019-06-24 16:01 UTC, peppy commented
On further discussion we were no longer sure whether this is a good direction. It means a use can either bind to `IsLoggedIn.ValueChanged` or `LocalUser.ValueChanged`. The issue is if a user queries one of these two from the other's `ValueChanged`, what is the expectation? There is going to be one out of two scenarios where the other variable state is stale.

2019-06-27 07:00 UTC, closed without merging