Fix solo results' horizontal size on match song select
ppy/osu pull request #4890
Opened 2019-06-01 14:33 UTC by Joehuu

Also fixes title on the header.

---

2019-06-01 14:42 UTC, peppy commented
If not resolving an issue, please provide a screenshot.

2019-06-01 14:46 UTC, Joehuu commented
Before:
![osu_2019-06-01_07-43-19](https://user-images.githubusercontent.com/35318437/58749977-31843780-8441-11e9-8bc1-096d9a2d3eae.jpg)


After:
![osu_2019-06-01_07-44-18](https://user-images.githubusercontent.com/35318437/58749982-347f2800-8441-11e9-9d6a-9c5389435b85.jpg)

2019-06-02 12:05 UTC, peppy commented on osu.Game/Screens/Play/MatchSoloResults.cs
> +    public class MatchSoloResults : SoloResults, IMultiplayerSubScreen
This should probably go in the multiplayer namespace.

2019-06-15 16:18 UTC, smoogipoo requested changes

2019-06-15 16:18 UTC, smoogipoo commented on osu.Game/Screens/Select/SongSelect.cs
> +        public virtual void ShowResults() => BeatmapDetails.Leaderboard.ScoreSelected += s => this.Push(new SoloResults(s));
Keep it as it was before, but add/use a `CreateResultsScreen(ScoreInfo score)` method.

2019-08-03 05:22 UTC, Joehuu commented
Closing as the original issue this PR was trying to resolve was fixed after the `BackButton` changes. Code quality that was done here may be done with the redesign.

2019-08-03 05:22 UTC, closed without merging