Tween track frequency on pause
ppy/osu pull request #4973
Opened 2019-06-09 15:57 UTC by peppy

Quality of life change to avoid sudden track stop on pause.

2019-06-09 16:13 UTC, miterosan requested changes

2019-06-09 16:13 UTC, miterosan commented on osu.Game/Screens/Play/GameplayClockContainer.cs
> +            this.TransformBindableTo(pauseFreqAdjust, 0, 200, Easing.Out).OnComplete(_ => { adjustableClock.Stop(); });
Remove parentheses

```suggestion
            this.TransformBindableTo(pauseFreqAdjust, 0, 200, Easing.Out).OnComplete(_ => adjustableClock.Stop());
```

2019-06-09 16:13 UTC, miterosan commented on osu.Game/Screens/Play/GameplayClockContainer.cs
> +        protected override void Dispose(bool isDisposing)
Move below Update()

2019-06-09 16:17 UTC, miterosan approved these changes

2019-06-11 09:31 UTC, smoogipoo approved these changes

2019-06-11 09:44 UTC, merged