Unuse the gameplay clock in KeyCounter
ppy/osu pull request #5088
Opened 2019-06-20 19:48 UTC by iiSaLMaN

Using the gameplay clock causes the key counter to slow down due to the rate slowing down on failing state, unusing it should be better.

Closes #4993

2019-06-20 21:37 UTC, naoei requested changes

2019-06-20 21:37 UTC, Altenhh commented on osu.Game/Screens/Play/KeyCounter.cs
>          private void load(TextureStore textures, GameplayClock clock)
```suggestion
        private void load(TextureStore textures)
```

2019-06-20 22:56 UTC, peppy commented
On a quick check, this PR in its current state breaks rewind logic (the counters no longer rewind when seeking backwards in a replay). Probably means we are short on tests.

2019-06-24 16:02 UTC, peppy requested changes
As mentioned, this regresses behaviour.

2019-06-24 20:37 UTC, iiSaLMaN commented
I'm not sure if that is possible to fix...

2019-06-24 21:18 UTC, peppy commented
If you don't think you have a solution in sight, closing this PR is a valid option. Breaking the replay support is far worse than potentially fixing #4993, which is but a visual glitch.

2019-06-25 17:32 UTC, iiSaLMaN commented
I'll close it for now till i find a better fix for it, i have a lot of work to do for other PRs atm.

2019-06-25 17:32 UTC, closed without merging