Add deferred toggle for ChannelSelectionOverlay if no channels are joined
ppy/osu pull request #5169
Opened 2019-06-27 09:49 UTC by nyquillerium

* Fixes https://github.com/ppy/osu/issues/5161
* [ ] Depends on https://github.com/ppy/osu/pull/5156

This makes it so we don't show an empty `ChannelSelectionOverlay` when chat is toggled, but toggles it whenever available channels are loaded in.

2019-06-27 11:02 UTC, peppy requested changes

2019-06-27 11:02 UTC, peppy commented on osu.Game/Overlays/ChatOverlay.cs
> +            else if (!channelManager.JoinedChannels.Any())
duplicated code

2019-06-27 11:02 UTC, peppy commented on osu.Game/Overlays/ChatOverlay.cs
> +            if (!channelManager.JoinedChannels.Any() && State.Value == Visibility.Visible)
state visible is always true here, right..?

2019-06-27 11:02 UTC, peppy commented
99% sure this will fail if the user is joined to the second available channel.

2019-06-27 11:12 UTC, nyquillerium commented
I see. Will check.

2019-07-03 04:26 UTC, peppy requested changes

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> -            typeof(ChatLine),
why?

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> +                Child = channelManagerContainer = new ChannelManagerContainer(new List<Channel> { channel1, channel2 }) { RelativeSizeAxes = Axes.Both, };
why?

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> -
add back

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> +            public void AddRange(List<Channel> channels) => AvailableChannels.AddRange(channels);
remove

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> +            public void ClearAvailable() => AvailableChannels.Clear();
remove

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> +            public BindableList<Channel> AvailableChannels => (BindableList<Channel>)ChannelManager.AvailableChannels;
remove

2019-07-03 04:26 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
> +        private void fakeInitializeChat()
no need to call it "fake". name it to explain what it's doing
also share the code with the main SetUp method, which is basically doing the same thing anyway.

2021-06-10 09:55 UTC, peppy commented
Going to close this for now as it doesn't look like a clean solution to the issue (and the underlying code has changed to a point that resolving the conflicts would likely not be worthwhile).

2021-06-10 09:55 UTC, closed without merging