Add beatmap counter for beatmap sections in profile overlay
ppy/osu pull request #5173
Opened 2019-06-27 22:33 UTC by EVAST9919

2019-07-01 06:43 UTC, frenzibyte requested changes

2019-07-01 06:43 UTC, iiSaLMaN commented on osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
> +            counterDrawable.FadeTo(count > 0 ? 1 : 0);
The fading should be moved inside `Counter`, also, i suggest using a bindable and bind it to `Counter` instead of 2 fields

2019-07-01 06:43 UTC, iiSaLMaN commented on osu.Game/Online/API/Requests/GetUserBeatmapsRequest.cs
> +        public GetUserBeatmapsRequest(long userId, BeatmapSetType type, int offset = 0, int limit = 0)
why 0? it should be 5 or at least 1 by default (same applied to all requests below)

2019-07-11 03:20 UTC, peppy commented
Getting those weird arrays in api fixed before merging this (https://github.com/ppy/osu-web/issues/4640).

2019-07-18 05:06 UTC, peppy commented
@EVAST9919 this can be updated to remove arrays now (See https://github.com/ppy/osu-web/pull/4683).

2019-07-23 22:17 UTC, EVAST9919 commented
Closing for now. Should be implemented at least after https://github.com/ppy/osu/pull/5427 since the counter have more usages (First place ranks section)

2019-07-23 22:17 UTC, closed without merging