Refactor Ruleset Selector in Direct
ppy/osu pull request #5214
Opened 2019-07-02 10:09 UTC by EVAST9919

2019-07-02 10:23 UTC, UselessToucan commented on osu.Game/Overlays/Direct/DirectRulesetSelector.cs
> +                if (IsHovered || Active.Value)
I think you should remove brackets in the `if` block

2019-07-02 10:23 UTC, UselessToucan commented on osu.Game/Overlays/Direct/DirectRulesetSelector.cs
> +                if (IsHovered || Active.Value)
Also, I guess it can be written in 1 line
`icon.FadeColour(IsHovered || Active.Value ? Color4.White : Color4.Gray, 120, Easing.InQuad);`

2019-07-03 08:56 UTC, peppy requested changes

2019-07-03 08:56 UTC, peppy commented on osu.Game/Overlays/Direct/DirectRulesetSelector.cs
> +                    icon = (SpriteIcon)value.CreateInstance().CreateIcon(),
It's unsafe to assume this is always going to be an icon. Accept the drawable and use `Scale` (or the `ConstrainedIcon` class like in `ConstrainedIconContainer`) instead if you need to adjust its size.

2019-07-03 16:00 UTC, peppy approved these changes

2019-07-03 16:24 UTC, merged