Add ability to see a top score in song select menu
ppy/osu pull request #5355
Opened 2019-07-14 11:05 UTC by EVAST9919

2019-07-15 07:06 UTC, peppy commented
Is there a reason the personal best can't be clicked (to view the results screen)?

2019-07-15 08:56 UTC, EVAST9919 commented
No, just forgot about it..

2019-07-22 14:17 UTC, peppy commented
@EVAST9919 please check changes i made, mostly just code quality.

not 100% happy with the transition but that can be fixed later on.

2019-07-22 14:28 UTC, peppy commented
- Loading circle doesn't appear sometimes
- When it does appear, it appears at a random height.

2019-07-22 14:28 UTC, peppy requested changes
needs work

2019-07-22 22:21 UTC, EVAST9919 commented
> * Loading circle doesn't appear sometimes
> * When it does appear, it appears at a random height.

1. Can't reproduce
2. Fixed with latest changes (not sure if it looks good though)

2019-07-23 02:45 UTC, peppy commented
It's still flying all over the place. I'll fix it.

2019-07-23 03:07 UTC, peppy commented
Here's a solution:

- Move the `TopScore` inside the leaderboard. You can either use `Content` in the base leaderboard to expose an area to add arbitrary footer content, or just make a `protected Container Footer`.
- Remove the bindable TopScore as it is not needed; handle it in the scores retrieval response.
- Remove all the `AutoSizeDuration`; it's not necessary.

Note that you'll probably want to create a `SongSelectLeaderboard` which has this added logic.

2019-07-25 04:44 UTC, iiSaLMaN commented on osu.Game/Online/Leaderboards/LeaderboardScore.cs
> +                            Text = rank <= 999 ? rank.ToString() : rank.ToMetric(decimals: rank < 100000 ? 1 : 0),
is `rank <= 999` necessary?, `123.ToMetric()` => `"123"`

2019-09-19 00:19 UTC, EVAST9919 commented
Closing due to my unability implement this properly

2019-09-19 00:44 UTC, peppy commented
I'll take this over.

2019-09-19 00:48 UTC, EVAST9919 commented
> I'll take this over.

Thanks. I wasn't sure about this at all, so didn't want to waste our time.

2019-09-19 06:44 UTC, peppy submitted a review, later dismissed

2019-09-19 06:46 UTC, peppy submitted a review, later dismissed

2019-09-19 07:04 UTC, peppy commented
@EVAST9919 i'm done with the required changes if you want to take a look.

2019-09-19 07:09 UTC, EVAST9919 commented
Sure. That was a lot faster than it could've been if I tried to implement this by myself

2019-09-19 11:49 UTC, smoogipoo approved these changes

2019-09-19 12:17 UTC, merged