Update profile scores in line with the web
ppy/osu pull request #5442
Opened 2019-07-23 21:52 UTC by EVAST9919

2019-09-13 08:34 UTC, peppy requested changes

2019-09-13 08:34 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/Ranks/DrawableTotalScore.cs
> +        protected readonly FillFlowContainer Accuracy;
This should be called something else. You are using it to contain more than just accuracy.

2019-09-15 14:58 UTC, peppy commented
Why isn't this sharing implementation with `DrawableMostPlayedBeatmap`?

2019-09-15 15:27 UTC, EVAST9919 commented
> Why isn't this sharing implementation with `DrawableMostPlayedBeatmap`?

I thought it wasn't necessary because their mutual properties are only height and hover/idle colors

2019-09-15 15:30 UTC, peppy commented
And corner radius, and box, no?

2019-09-17 02:53 UTC, peppy requested changes

2019-09-17 02:53 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/DrawableUserInfoItem.cs
> +    public class DrawableUserInfoItem : OsuHoverContainer
why isn't this called DrawableProfileRow or something? `UserInfoItem` tells me nothing about nothing name i could nothing.

2019-09-17 02:53 UTC, peppy commented on osu.Game/Overlays/Profile/Sections/Ranks/DrawableWeightedScore.cs
> +            InfoContainer.Add(new OsuSpriteText
these names are still useless. `DetailInfo`? `InfoContainer`?









how about `LeftContent` / `RightContent` or something that makes sense to look at?

2019-09-17 02:54 UTC, peppy commented
How were you developing this? There's not even a test with `DrawableWeightedScore` as a compilable type.

2020-01-18 00:44 UTC, EVAST9919 commented
Superseded by https://github.com/ppy/osu/pull/7554

2020-01-18 00:44 UTC, closed without merging