Add a basic skin line-up test scene
ppy/osu pull request #5504
Opened 2019-07-29 08:33 UTC by peppy

Current elements are largely placeholder and will require further iteration.

- [ ] Depends on https://github.com/ppy/osu/pull/5502.
- [ ] Depends on https://github.com/ppy/osu/pull/5503.

2019-07-30 09:57 UTC, smoogipoo requested changes

2019-07-30 09:57 UTC, smoogipoo commented on osu.iOS.props
> +    <CodesignKey>iPhone Developer</CodesignKey>
Intended?

2019-07-30 09:57 UTC, smoogipoo commented on osu.Game.Rulesets.Osu.Tests/SkinnableTestScene.cs
> +        protected SkinnableTestScene()
ctor at the very bottom?

2019-07-30 09:57 UTC, peppy commented on osu.iOS.props
> +    <CodesignKey>iPhone Developer</CodesignKey>
very much no.

2019-07-30 09:58 UTC, smoogipoo commented
What's a "metrics" skin? Is this some random skin that you've copied into our source? If so it needs to be removed and replaced with assets that are original.

2019-07-30 09:58 UTC, peppy commented
You mean "special"?

2019-07-30 09:59 UTC, smoogipoo commented
Ah yes, bottom right is special.

2019-07-30 13:33 UTC, smoogipoo approved these changes

2019-07-30 14:08 UTC, merged

2019-07-30 19:38 UTC, jorolf commented
I'm currently trying to make some tests for #5497, and I was going to add some ``hitXX`` textures. How should they look? ``default`` should probably have the textures from stable but what about the others?

2019-07-31 05:57 UTC, smoogipoo commented
As far as I understood it, the metrics skin has the exact outlines and expected paddings for elements. E.g. for hitcircles it has the dots on the side that indicate the padding, and the crosshair in the centre that should be visible. The special skin is just a user skin of some kind.

@peppy give direction plz

2019-07-31 07:25 UTC, peppy commented
Metrics should be a png crafted to make it easy for the test viewer to know that the metrics are correct. In the case of `hitcircle`/`hitcircleoverlay`, I showed the relationship between them. For hit explosions, there's less to worry. Maybe a circle that starts precisely the same size as the hitcircle itself would be good (so scale animations are very apparent). Probably just a border, not filled.