Add part command
ppy/osu pull request #5601
Opened 2019-08-04 16:57 UTC by hbnrmx

adds part of #5595

2019-08-04 21:51 UTC, peppy requested changes

2019-08-04 21:51 UTC, peppy commented on osu.Game/Online/Chat/ChannelManager.cs
> +                case "p":
i don't think we should support `/p`.

2019-08-04 21:51 UTC, peppy commented on osu.Game/Online/Chat/ChannelManager.cs
>                      target.AddNewMessages(new InfoMessage("Supported commands: /help, /me [action]"));
missing help

2019-08-05 03:50 UTC, smoogipoo commented
This is opening up the channel selection overlay when a channel is parted.

2019-08-05 05:23 UTC, peppy commented
It probably should if you part the last channel you were joined, but no other case.

2019-08-06 20:44 UTC, TPGPL commented
probably should implement the shortened version of the command as well - `/p`

2019-08-06 20:45 UTC, jorolf commented
> 
> 
> probably should implement the shortened version of the command as well - `/p`

https://github.com/ppy/osu/pull/5601#discussion_r310405265

2019-08-06 20:50 UTC, TPGPL commented
o nevermind then

2019-08-11 18:47 UTC, hbnrmx commented
> This is opening up the channel selection overlay when a channel is parted.

Took me a while to figure out why this happens for `/part` and not closing by button. 

(See here: https://github.com/ppy/osu/blob/907cf18960acd6bf460c057dbd60e95f103cbda4/osu.Game/Overlays/ChatOverlay.cs#L232)

Turns out calling `LeaveChannel()` in `ChannelManager` isn't enough. 
Instead I think we want to invoke `ChannelTabControl`'s `OnRequestClose` since all the necessary tab closing logic is handled there.

This feels kinda backwards / cyclic though. Any idea how this should be handled?

2019-08-11 19:38 UTC, peppy commented
`ChannelTabControl` should handle leaving a channel only. the request close should just fire the leave action, so everything comes in through a single path.

2019-08-11 20:06 UTC, hbnrmx commented
> 
> 
> `ChannelTabControl` should handle leaving a channel only. the request close should just fire the leave action, so everything comes in through a single path.

I can read your comment in two different ways, so just to confirm:

You're saying I should move the tab selection logic 
(https://github.com/ppy/osu/blob/907cf18960acd6bf460c057dbd60e95f103cbda4/osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs#L108
)
from `ChannelTabControl` to `ChannelManager` ?

2019-08-11 20:11 UTC, peppy commented
`ChannelTabControl` should probably be handling operations based on `JoinedChannels` bindable. it's a larger change to make to fix things up (probably a prereq for this PR to happen).

2019-08-11 20:15 UTC, closed without merging