Disallow adding to score after the player has failed
ppy/osu pull request #5637
Opened 2019-08-07 17:02 UTC by iiSaLMaN

Mostly for the health bar to not increment, but thought it's actually weird for the score to increment even though the player is in a failed state, as for real-time players and reviving logic, can be done by adding a boolean that allows that or something.

2019-08-08 04:28 UTC, peppy submitted a review, later dismissed
i think this seems ok

2019-08-08 04:40 UTC, smoogipoo commented
This should have an inverse operation inside `RevertResult()`. A simple way of doing this is to store another property inside the result `HasFailedAtJudgement`, and use that to decide whether the judgement should be reverted.

2019-08-08 04:40 UTC, smoogipoo requested changes

2019-08-08 04:40 UTC, smoogipoo commented on osu.Game/Rulesets/Scoring/ScoreProcessor.cs
>              result.HealthAtJudgement = Health.Value;
Along with the previous comment, the return should be _after_ all these are set.

2019-08-08 12:01 UTC, iiSaLMaN commented
> This should have an inverse operation inside `RevertResult()`. A simple way of doing this is to store another property inside the result `HasFailedAtJudgement`, and use that to decide whether the judgement should be reverted.

I don't quite understand you, you mean to invoke `RevertResult` if the player has failed after `NewResult` is finished? or invoke it somewhere else?

2019-08-08 12:06 UTC, smoogipoo commented
No, RevertResult is used to un-apply the results while rewinding. If ApplyResult has been invoked, RevertResult will also be invoked for the same result during rewind.

We may at some point, implement some mechanic that rewinds to a non-failed state.

2019-08-09 05:10 UTC, smoogipoo commented
@iiSaLMaN I've refactored it as I originally envisioned it: https://github.com/ppy/osu/pull/5637/commits/88fa06efbadc23501209021ad4df1436bd4acb7f

Note that I've removed the `HasFailed` revert since it isn't handled well, but I've added a todo for it.

@peppy requesting review

2019-09-06 07:14 UTC, peppy submitted a review, later dismissed

2019-09-06 08:11 UTC, merged