VolumeControl: add controls for Effects and Music
ppy/osu pull request #57
Opened 2016-10-09 17:51 UTC by UselessToucan

It is now possible to adjust Effects and Music volume.
![osu_volume](https://cloud.githubusercontent.com/assets/22450664/19222469/e82f0bbe-8e61-11e6-96d6-cddcb69622f5.png)

2016-10-10 06:04 UTC, peppy commented on osu.Game/VolumeControl.cs
> +            if (VolumeMeterSample.Contains(state.Mouse.Position))
rather than using contains logic here, i'd rather you moved it inside VolumeControl (and pass through the bindable).

2016-10-11 18:29 UTC, ddevault requested changes
If you use the scroll wheel while hovering over no meter in particular, it should adjust all the meters at once.

2016-10-11 18:31 UTC, peppy commented
i think you mean master only >.>

2016-10-11 18:31 UTC, SirCmpwn commented
Heh, sure.

2016-10-12 14:38 UTC, UselessToucan commented
I didn't manage to do it in a different way, don't know is it acceptable or not. I would be glad if you explain me how to do it better.

2016-10-12 14:41 UTC, SirCmpwn commented
You've gotta solve merge conflicts and check the build status.

2016-10-12 16:23 UTC, peppy commented on osu.Game/VolumeMeter.cs
> +            return base.OnWheelUp(state);
you want to return true here. return true when you handle the event (then it won't propagate further).

2016-10-12 16:23 UTC, peppy commented on osu.Game/VolumeMeter.cs
> +            return base.OnWheelDown(state);
same here

2016-10-12 18:10 UTC, UselessToucan commented on osu.Game/VolumeControl.cs
> +            if (volumeMetersContainer.Children.All(vm => !vm.Contains(state.Mouse.Position)))
Yes, it does not work as expected without these checks.

2016-10-13 11:55 UTC, peppy commented on osu.Game/VolumeControl.cs
> +            VolumeGlobal.ValueChanged += volumeChanged;
Please override dispose and unbind these.

2016-10-13 15:16 UTC, huoyaoyuan commented on osu.Game/VolumeMeter.cs
> +                new SpriteText {Text = meterName, Anchor = Anchor.BottomCentre,Origin = Anchor.BottomCentre,Position = new Vector2(0,-20)}
Consider to make this tidy

2016-10-13 16:07 UTC, UselessToucan commented on osu.Game/VolumeMeter.cs
> +                new SpriteText {Text = meterName, Anchor = Anchor.BottomCentre,Origin = Anchor.BottomCentre,Position = new Vector2(0,-20)}
Should it be like this?
```
new SpriteText
{
    Text = meterName,
    Anchor = Anchor.BottomCentre,
    Origin = Anchor.BottomCentre,
    Position = new Vector2(0,-20)
}
```

2016-10-13 16:07 UTC, SirCmpwn commented on osu.Game/VolumeMeter.cs
> +                new SpriteText {Text = meterName, Anchor = Anchor.BottomCentre,Origin = Anchor.BottomCentre,Position = new Vector2(0,-20)}
Yes

2016-10-14 06:19 UTC, peppy commented on osu.Game/VolumeMeter.cs
> +                    Position = new Vector2(0,-20)
rather than use a position offset here, just set `Origin = Anchor.TopCentre`?

2016-10-14 06:20 UTC, peppy requested changes
just need the one fix, else looks good.

2016-10-14 06:50 UTC, merged