Add "AimAssist" mod
ppy/osu pull request #5774
Opened 2019-08-19 22:05 UTC by MaxOhn

Rough cut of the AimAssist mod, inspired by [this video](https://www.youtube.com/watch?v=afI_6X0PdM8).
HitCircles and Sliders move towards the cursor and sliders continue moving so that the SliderBall sticks to the cursor.
Including the overall way I implemented it which probably has a much nicer solution, there's still a couple of other things to fix.
Also references the issue #5760

Preview: https://streamable.com/ew7mj

2019-08-20 04:43 UTC, frenzibyte requested changes

2019-08-20 04:43 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +                    return true; // never happens(?)
just set a default case, probably on `DrawableHitCircle`

2019-08-20 04:43 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +            using (d.BeginAbsoluteSequence(h.StartTime - h.TimePreempt))
I don't see any transforms..?

2019-08-20 04:43 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +            playfield.Cursor.ActiveCursor.OnUpdate += drawableCursor =>
Subscribing to the cursor update every playfield update?? you probably want `IApplicableToDrawableRuleset` instead

2019-08-20 04:43 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +            if (!(drawable is DrawableOsuHitObject d))
```suggestion
            if (drawable is DrawableOsuHitObject d)
                movingObjects.Add(d);
```

2019-08-20 04:43 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +        private readonly HashSet<DrawableOsuHitObject> movingObjects = new HashSet<DrawableOsuHitObject>();
why is this a hashset...?

2019-08-20 04:53 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +                            circle.MoveTo(drawableCursor.DrawPosition, Math.Max(0, h.StartTime - currentTime));
Preempt time of the object is what you want
```suggestion
                            circle.MoveTo(drawableCursor.DrawPosition, h.TimePreempt);
```

2019-08-20 08:35 UTC, Desconocidosmh commented
Did you think about making it snap to the cursor only at a certain range? I think it would make this more of a separate mod that makes the circles feel "bigger", therefore it would be more of an actual "assist", rather that being basically the autopilot in disguise.

2019-08-21 11:25 UTC, MaxOhn commented
@Desconocidosmh Not uninteresting but I feel like there is little incentive to play such a mod, especially because it would be unranked anyway. I'm leaning more towards Aim Assist being a laid-back fun mod. It's an idea for a potential mod  in the future though 😄

2019-08-21 23:26 UTC, HoLLy-HaCKeR commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +     */
You probably want to place this in your issue, so it is visible for everyone.

2019-08-21 23:27 UTC, HoLLy-HaCKeR commented
Should this be a Multimod with Relax?

2020-01-05 00:36 UTC, WheelChairUser420 commented on osu.Game.Rulesets.Osu/Mods/OsuModAimAssist.cs
> +using System;
Nerf shit

2022-01-04 07:40 UTC, peppy commented
@MaxOhn shall we close this one for now? seems the TODO items you had are still present.

2022-01-04 09:44 UTC, MaxOhn commented
Oh right I put this project aside and completely forgot about it, my apologies.
I'll see to get into it again in the next few days, otherwise I'll close this within the next week-ish.

2022-01-05 12:37 UTC, MaxOhn commented
I've updated everything w.r.t. the current lazer state to the best of my abilities.
Unfortunately, I'm stuck on the remaining issues I listed in the top comment and I'm honestly not too keen on spending more time to figuring them out.
Unless there is interest from others, I'd be fine with closing this.

2022-01-06 06:37 UTC, peppy commented
Thanks for bringing it up-to-date. I'll try and fit in a review pass and see if the issues are simple enough to fix (some sound like they should be quick fixes).

2022-01-06 06:48 UTC, peppy commented
Actually not sure how simple this will be to get right. For a start, you should be using interpolation rather than `MoveTo`, or at least rate limiting the usage of `MoveTo` to avoid transforming every frame. Maybe the latter as it's the only want to make rewind semi-consistent.

2022-01-06 15:14 UTC, MaxOhn commented
Assist strength is now configurable. I don't think spinners and ongoing sliders should be modified on partial assistance so I now ignore them.
I'm not sure how to ratelimit the update properly. For now I just update once every 100ms but I'm assuming that could cause inconsistencies.
The notes flashing in their original position is still an issue I'm also clueless about.

2022-02-02 07:36 UTC, peppy commented
I've done an initial refactor and clean-up pass on this after discussion with @smoogipoo. It should be in a visually correct state now, but replay support is ad-hoc at best. Making it work well in replays is potentially achievable, but will add a lot of complexity that I'd rather avoid in an initial implementation.

Note that I brought back the removed slider behaviour (tracking the sliders) as it feels really good, but I have not added the spinner spinning. I think spinner support could work if done well, but tweaking it will require some dedication, of which I don't have right now.

2022-02-02 07:37 UTC, peppy approved these changes, later dismissed

2022-02-02 18:45 UTC, bdach commented
I've pushed 7463744 to fix a minor issue - `OsuModAimAssist` was declaring incompatibility with `ModAutoplay`, but the osu!-specific autoplay implementations weren't declaring incompatibility with `OsuModAimAssist`, resulting in some weird behaviours.

Before:

https://user-images.githubusercontent.com/20418176/152217209-de74ed82-922c-41cc-a4df-de3d3f6e266f.mp4

After:

https://user-images.githubusercontent.com/20418176/152217197-3eb2f479-0ba8-4fe2-9d21-29b47516c847.mp4

Note the aim assist mod missing from tooltips on first video, as well as the weird behaviour of the autoplay button (blocked from operation when aim assist is selected).

Other than that this seems okay. I will say that as someone who likes to turn everything off (I turn off all HUD entirely in gameplay, as I don't really ever look at the HP bar or the hit error meters), turning judgements off is a bit of an issue as I don't get any timing feedback anymore. That said I don't really feel like spending time on fixing that for this mod, so possibly fine. I'll leave it to someone else to merge.

2022-02-02 18:47 UTC, bdach approved these changes

2022-02-03 01:36 UTC, peppy commented
> Other than that this seems okay. I will say that as someone who likes to turn everything off (I turn off all HUD entirely in gameplay, as I don't really ever look at the HP bar or the hit error meters), turning judgements off is a bit of an issue as I don't get any timing feedback anymore. That said I don't really feel like spending time on fixing that for this mod, so possibly fine. I'll leave it to someone else to merge.

I did have a quick look at what would be required to fix judgements, but unless doing a mod level hack to update their positions it does seem non trivial due to the data flow.

2022-02-03 01:40 UTC, merged