Implement RankingsScopeSelector
ppy/osu pull request #6052
Opened 2019-09-10 01:21 UTC by EVAST9919

2019-09-10 11:38 UTC, frenzibyte requested changes

2019-09-10 11:38 UTC, iiSaLMaN commented on osu.Game.Tests/Visual/Online/TestSceneRankingsScopeSelector.cs
> +            Bindable<RankingsScope> scope = new Bindable<RankingsScope>();
```suggestion
            var scope = new Bindable<RankingsScope>();
```

2019-09-10 11:38 UTC, iiSaLMaN commented on osu.Game.Tests/Visual/Online/TestSceneRankingsScopeSelector.cs
> +            Add(new RankingsScopeSelector
use `AddRange`

2019-09-12 14:06 UTC, peppy requested changes

2019-09-13 05:10 UTC, peppy approved these changes

2019-09-13 05:27 UTC, merged