Exit confirmation dialog
ppy/osu pull request #619
Opened 2017-04-11 12:22 UTC by EVAST9919

2017-04-11 12:24 UTC, Jorolf commented on osu.Game/Screens/Menu/ExitConfirmDialog.cs
> +            BodyText = @"You'll left";
You'll leave

2017-04-11 12:25 UTC, EVAST9919 commented on osu.Game/Screens/Menu/ExitConfirmDialog.cs
> +            BodyText = @"You'll left";
That was just a random text

2017-04-11 12:32 UTC, Jorolf commented on osu.Game/Screens/Menu/MainMenu.cs
>              if (!args.Repeat && state.Keyboard.ControlPressed && state.Keyboard.ShiftPressed && args.Key == Key.D)
If you're going to add a seperate if statement for testing if a key press was repeated you can remove this here

2017-04-11 15:07 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                dialog?.Push(new ExitConfirmDialog()
this is wrong. you're doing a null check but in the case it fails what happens? nothing.

2017-04-11 15:08 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +            dialog = dialogOverlay;
don't call the same variable different things.

`this.dialog = dialog`

2017-04-11 15:12 UTC, peppy commented
- this doesn't cover alt-f4, only escape
- this only covers exiting at the main menu. what about exiting from another screen?

pretty sure you'll want to look into `OnExiting` callbacks and not handle this local to the main menu.

2017-04-12 07:43 UTC, peppy requested changes
as commented

2017-04-30 00:47 UTC, closed without merging