Introduce SessionStatics
ppy/osu pull request #6216
Opened 2019-09-23 05:18 UTC by iiSaLMaN

- Introduces SessionStatics component which is based on an in-memory config manager that can be used to save static values for the entire session of the game.

2019-09-24 02:20 UTC, peppy commented
Can you update the one case you found for use here so there is a sample usage? (I believe it was somewhere in the menu?)

2019-09-24 02:24 UTC, iiSaLMaN commented
> Can you update the one case you found for use here so there is a sample usage? (I believe it was somewhere in the menu?)

You mean whether the muted notification is shown?

2019-09-24 02:25 UTC, peppy commented
No, you mentioned one other case already in master, I believe.

2019-09-24 02:28 UTC, smoogipoo commented
Why SessionStatics and not SessionConfigManager?

2019-09-24 02:46 UTC, iiSaLMaN commented
> Why SessionStatics and not SessionConfigManager?

It's not really a configuration so it would be kinda misleading adding `ConfigManager` to it in my opinion.

2019-09-24 22:28 UTC, iiSaLMaN commented
Fixed crash issue, happened due to the config manager not initialized with values for their lookups, I moved the in-memory logic to a base class in case we wanted in-memory store later on.

2019-09-25 04:45 UTC, peppy requested changes

2019-09-25 04:45 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                if (!statics.Get<bool>(Statics.LoginOverlayDisplayed))
i think it'd be cleaner to use the BDL load method to retrieve a bindable only, rather than querying `statics` multiple times.

2019-09-28 12:22 UTC, peppy approved these changes

2019-09-28 12:33 UTC, merged