Truncate long metadata on beatmap info wedge
ppy/osu pull request #6250
Opened 2019-09-24 23:39 UTC by Joehuu

Fixes part of #3504.

Issues:
- Truncation doesn't update when ui scale is changed.
- Not sure about the padding/margin values. Tried to keep current values the same.

Text length on test was determined on fullscreen 1920x1080.

2019-09-24 23:50 UTC, frenzibyte requested changes

2019-09-24 23:50 UTC, iiSaLMaN commented on osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
> +        public void testNullBeatmap()
```suggestion
        public void TestNullBeatmap()
```

2019-09-24 23:50 UTC, iiSaLMaN commented on osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
> +        public void testTruncation()
ditto

2019-09-24 23:54 UTC, frenzibyte approved these changes

2019-10-04 02:50 UTC, smoogipoo approved these changes

2019-10-04 03:44 UTC, merged