Implement API for rankings
ppy/osu pull request #6274
Opened 2019-09-26 05:30 UTC by EVAST9919

Still without charts due to web reasons

2019-09-26 05:43 UTC, bdach commented
What kind of web reasons are we talking about?

2019-09-26 05:44 UTC, EVAST9919 commented
> What kind of web reasons are we talking about?

https://github.com/ppy/osu-web/issues/4898

2019-09-26 07:20 UTC, peppy requested changes

2019-09-26 07:20 UTC, peppy commented on osu.Game.Tests/Visual/Online/TestSceneRankingsApi.cs
> +        private IAPIProvider api { get; set; }
Should be using `API` instead, with `UseOnlineAPI => true`

2019-09-26 09:24 UTC, smoogipoo commented on osu.Game/Online/API/Requests/GetRankingsRequest.cs
> +            req.AddParameter("page", page.ToString());
I think this is fine for now as this isn't the final API.

2019-10-07 10:53 UTC, EVAST9919 commented
Closing because it's already included in https://github.com/ppy/osu/pull/6293 and there's no a good way to test it without ui (which is already included in https://github.com/ppy/osu/pull/6293)

2019-10-07 10:53 UTC, closed without merging