Add random intro!
ppy/osu pull request #6310
Opened 2019-09-28 19:21 UTC by V1ntagezTV

Simple "Random" intro

2019-09-28 19:28 UTC, elleyer commented
Any reason for that? Also, you should delete not English comments.

2019-09-28 19:29 UTC, bdach commented
@elleyer The submitter aims to resolve #6284 with this.

2019-09-28 19:31 UTC, bdach requested changes

2019-09-28 19:31 UTC, bdach commented on osu.Game/Screens/Loader.cs
> +        {//вот именно что не показывает ни всплывающих подсказок нихера
Please keep all source, including comments, in English. Additionally your whitespace needs fixing (as reported by CI).

2019-09-28 19:31 UTC, bdach commented on osu.Game/Screens/Loader.cs
> +            Random random = new Random();
* Use `var` here.
* This allocation can be moved into the `switch` case.

2019-09-28 23:53 UTC, frenzibyte requested changes
This can be fairly simplified by just picking a random intro sequence enum value.

```csharp
switch (introSequence)
{
    case IntroSequence.Random:
        var introSequences = Enum.GetValues(typeof(IntroSequence)).Except(new[] { IntroSequence.Random }).ToList();
        return getIntroSequence(introSequences[RNG.Next(introSequences.Count)]);
}
```

Notes to be took from the above snippet:
 - `RNG` is used instead of `Random` which is a simplified way of seedless randomizing.

2019-09-29 06:37 UTC, peppy approved these changes

2019-09-29 06:53 UTC, merged

2019-09-29 08:06 UTC, smileyhead commented
Nice, thanks! :-)