Fix username overlap timestamp in match chatroom
ppy/osu pull request #6348
Opened 2019-10-01 13:57 UTC by GSculerlor

Fix #6061 

| This PR | Master Branch  |
| ------------- | ------------- |
| <img width="600" alt="Screen Shot 2019-10-01 at 20 45 00" src="https://user-images.githubusercontent.com/6506864/65968293-2263d380-e48d-11e9-9478-c00f737dafa8.png"> | <img width="600" alt="Screen Shot 2019-10-01 at 20 44 11" src="https://user-images.githubusercontent.com/6506864/65968294-2263d380-e48d-11e9-9e43-65327b0347e6.png">
<img width="800" alt="Screen Shot 2019-10-01 at 20 22 30" src="https://user-images.githubusercontent.com/6506864/65968296-22fc6a00-e48d-11e9-951b-c38b5cb6b3e3.png"> |  <img width="800" alt="Screen Shot 2019-10-01 at 20 23 17" src="https://user-images.githubusercontent.com/6506864/65968297-22fc6a00-e48d-11e9-995e-b75ff72ca302.png">

I just give a shot to fix this, but still not sure this is the correct way to solve it. Also `TimestampPadding` is obtained from trial and error so not sure this is pixel perfect.

2019-10-01 14:29 UTC, frenzibyte submitted a review, later dismissed
Good job! 👍

2019-10-01 15:14 UTC, Joehuu requested changes

2019-10-01 15:14 UTC, Joehuu commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                            Padding = new MarginPadding { Left = TimestampPadding },
Not needed.
```suggestion
```

2019-10-01 15:14 UTC, Joehuu commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                MaxWidth = default_message_padding - TimestampPadding
```suggestion
                MaxWidth = MessagePadding - TimestampPadding
```

2019-10-01 15:14 UTC, Joehuu commented on osu.Game/Online/Chat/StandAloneChatDisplay.cs
> +            protected override float TimestampPadding => 130;
```suggestion
            protected override float TimestampPadding => 50;
```

2019-10-01 16:41 UTC, Joehuu approved these changes

2019-10-02 01:46 UTC, smoogipoo approved these changes
👍

2019-10-02 01:46 UTC, merged