Fix incorrect beatmap set info equality check for local beatmapsets
ppy/osu pull request #6522
Opened 2019-10-15 20:48 UTC by iiSaLMaN

2019-10-16 04:16 UTC, peppy commented
Can you explain the case this is fixing? Is there a reproduction somewhere we can test against?

2019-10-16 08:30 UTC, smoogipoo requested changes

2019-10-16 08:30 UTC, smoogipoo commented on osu.Game/Beatmaps/BeatmapSetInfo.cs
> +                return ReferenceEquals(this, other);
Should check by `ID` first, if it's non-zero.

2019-10-16 21:24 UTC, iiSaLMaN commented
> Can you explain the case this is fixing? Is there a reproduction somewhere we can test against?

Found this issue after creating a bindable of `BeatmapSetInfo`, realized it checks whether it's equal with another value by `BeatmapSetInfo.Equals`, which made issues to the bindable not calling value changed events, will provide tests.

2019-10-16 21:27 UTC, bdach commented
> Found this issue after creating a bindable of `BeatmapSetInfo`, realized it checks whether it's equal with another value by `BeatmapSetInfo.Equals`, which made issues to the bindable not calling value changed events, will provide tests.

Mind expounding on what the actual *values* were? Was it the case of a pair of maps that were different but didn't have an online ID, or some other less obvious scenario?

2019-10-16 21:28 UTC, iiSaLMaN commented
> > Found this issue after creating a bindable of `BeatmapSetInfo`, realized it checks whether it's equal with another value by `BeatmapSetInfo.Equals`, which made issues to the bindable not calling value changed events, will provide tests.
> 
> Mind expounding on what the actual _values_ were? Was it the case of a pair of maps that were different but didn't have an online ID, or some other less obvious scenario?

2 beatmaps with same online ID (null)

2019-10-16 21:34 UTC, bdach commented
In that case I'm not completely sold that `ReferenceEquals` is correct here, could be too strict in cases there are duplicate references that actually point to the same beatmap set - `BeatmapSetInfo.Hash` could be more appropriate here? Would ensure that the actual beatmap set content is the same and account for multiple instances representing a single underlying set.

2019-10-18 03:20 UTC, smoogipoo approved these changes

2019-10-18 03:20 UTC, merged