changing repetition of code to foreach
ppy/osu pull request #6532
Opened 2019-10-17 21:49 UTC by YuriCunha

2019-10-17 22:02 UTC, bdach requested changes
Please trim unnecessary whitespace as per CI suggestions. You can [run code analysis locally](https://github.com/ppy/osu#code-analysis) to ensure style correctness before pushing again.

2019-10-17 22:02 UTC, TPGPL requested changes

2019-10-17 22:02 UTC, TPGPL commented on osu.Game/OsuGameBase.cs
> +
you should probably delete all this whitespace

2019-10-17 22:36 UTC, frenzibyte requested changes
If this is to be corrected for, It should probably be looking up for any font inside the `Fonts` folder rather than having a hardcoded list containing the fonts.

2019-10-17 22:55 UTC, swoolcock commented on osu.Game/OsuGameBase.cs
> +        private readonly IList<string> fontPaths = new List<string>()
Use `IEnumerable<string>` and an array.

2019-10-26 05:58 UTC, peppy commented
Closing as low quality / abandoned. Please re-open if you wish to fix this.

2019-10-26 05:58 UTC, closed without merging