Slider tooltip and letterboxing/dim changes
ppy/osu pull request #658
Opened 2017-04-20 12:56 UTC by Jorolf

2017-04-21 03:15 UTC, peppy commented on osu.Game/Graphics/UserInterface/OsuSliderBar.cs
> +                    return bindableDouble.Value.ToString(@"n1", CultureInfo.InvariantCulture);
pretty sure we want variant culture

2017-04-21 03:19 UTC, huoyaoyuan commented on osu.Game/Graphics/UserInterface/OsuSliderBar.cs
> +                    return bindableDouble.Value.ToString(@"n1", CultureInfo.InvariantCulture);
seems locale engine can provide the `CultureInfo` for `ToString()`?

2017-04-21 06:44 UTC, peppy commented on osu.Game/Graphics/UserInterface/OsuSliderBar.cs
> +        public Func<T, string> TooltipTextFunc { get; set; }
why not just make `TooltipText` `virtual` and make classes for special cases? i think that's a lot more elegant than this.

2017-04-22 11:19 UTC, peppy commented
can you rebase your stuff?
9/12 of your commits are merges of master...

2017-04-23 13:51 UTC, Jorolf commented
_rebased_

2017-04-24 03:43 UTC, peppy requested changes

2017-04-24 03:43 UTC, peppy commented on osu.Game/Overlays/Options/Sections/SkinSection.cs
> +                new OptionSlider<double,SizeSlider>
space after comma

2017-04-24 04:01 UTC, peppy commented
This can't be merged until https://github.com/ppy/osu-framework/pull/659 is merged. Everyone who has an existing setting for dim will have it set incorrectly as there is no consideration given to migration.

2017-04-25 10:38 UTC, peppy approved these changes

2017-04-25 11:03 UTC, merged