Add retry button and hotkey support to results screen
ppy/osu pull request #6691
Opened 2019-11-01 06:52 UTC by peppy

- Closes https://github.com/ppy/osu/issues/6439.
- [ ] Depends on https://github.com/ppy/osu/pull/6689.

2019-11-01 06:58 UTC, frenzibyte requested changes

2019-11-01 06:58 UTC, iiSaLMaN commented on osu.Game/Screens/Ranking/Results.cs
> +            allCircles.ForEach(c => { c.ScaleTo(0, transition_time, Easing.OutSine); });
```suggestion
            allCircles.ForEach(c => c.ScaleTo(0, transition_time, Easing.OutSine));
```

2019-11-01 13:00 UTC, bdach commented
Both happy paths seem to work nicely, and I got to play some while testing this, so definitely a fun one to review 😄 

I've got one small visual issue though - it's very likely out of scope of this, but I'm not too keen on the fact that the fade to black when using the hotkey doesn't cover the top bar ([see video](https://streamable.com/dku5b)). To me it's especially jarring on beatmaps with light backgrounds.

2019-11-01 13:01 UTC, peppy commented
That is indeed weird. I'd probably open that in a separate issue as it's a bit out of scope of this change.

2019-11-01 13:06 UTC, bdach submitted a review, later dismissed

2019-11-02 01:32 UTC, smoogipoo submitted a review, later dismissed

2019-11-02 12:41 UTC, merged