Fix carousel filtering twice on startup due to unpopulated ruleset
ppy/osu pull request #6833
Opened 2019-11-13 10:07 UTC by peppy

Fixes #3058.

2019-11-13 13:07 UTC, bdach submitted a review, later dismissed
I suppose I'll trust the test on this one 👍

2019-11-13 23:30 UTC, bdach commented on osu.Game/Screens/Select/SongSelect.cs
> +            // initial value transfer is requried for FilterControl (it uses our re-cached bindables in its asynd loac for the initial filter).
Sorry for doing this, but
```suggestion
            // initial value transfer is required for FilterControl (it uses our re-cached bindables in its async load for the initial filter).
```

2019-11-14 00:20 UTC, bdach submitted a review, later dismissed

2019-11-15 09:15 UTC, smoogipoo requested changes

2019-11-15 09:15 UTC, smoogipoo commented on osu.Game/Screens/Select/SongSelect.cs
> +        protected BeatmapOptionsOverlay BeatmapOptions;
These need private setters.

2019-11-15 09:22 UTC, peppy commented
Should be good 👍

2019-11-15 11:20 UTC, smoogipoo commented
Seems to cause some weird filtering: https://streamable.com/ed1pw

Steps to repro:
1. Enter song select with taiko ruleset.
2. Exit song select.
3. Change to osu! ruleset.
4. Enter song select again.

2019-11-15 11:21 UTC, smoogipoo requested changes

2019-11-15 11:21 UTC, smoogipoo commented on osu.Game/Screens/Select/SongSelect.cs
> +        protected virtual void ApplyFilterToCarousel(FilterCriteria criteria) => Carousel.Filter(criteria);
Move before `load()`

2019-11-15 13:31 UTC, peppy commented
Hmm, I'm not sure how we should handle that case you mentioned, if at all. The changes I've made do not re-filter in the background - they just guarantee a second filter won't happen if nothing changed externally.

In the case you've video'd there *is* an external change. It kind of makes sense it's doing a second filter on entry in this case, although optimally it may be better if we can delay the screen push until it is in a good state, not sure.

2019-11-20 09:29 UTC, smoogipoo approved these changes
Let’s go with this for now

2019-11-20 10:39 UTC, merged