Use localised metadata in PlayerLoader
ppy/osu pull request #685
Opened 2017-04-28 18:07 UTC by EVAST9919

2017-04-30 11:45 UTC, Jorolf commented on osu.Game/Screens/Play/PlayerLoader.cs
>                  var metadata = beatmap?.BeatmapInfo?.Metadata ?? new BeatmapMetadata();
why don't you just use this instead of saving WorkingBeatmap.

2017-05-01 01:37 UTC, peppy commented on osu.Game/Screens/Play/PlayerLoader.cs
> +            [BackgroundDependencyLoader]
please move private method below ctor.

2017-05-01 01:38 UTC, peppy requested changes
see comment

2017-05-01 01:58 UTC, peppy requested changes

2017-05-01 01:58 UTC, peppy commented on osu.Game/Screens/Play/PlayerLoader.cs
>                  Children = new Drawable[]
you could just move this into the `load()` method to avoid storing references, too.

2017-05-01 03:02 UTC, peppy approved these changes

2017-05-01 03:07 UTC, merged