Fix unnecessary beatmap fetch for peatmap panel in multiplayer room
ppy/osu pull request #7054
Opened 2019-12-03 22:10 UTC by EVAST9919

Depends on:
- [ ] https://github.com/ppy/osu/issues/7039

In multiplayer room we already have a populated beatmapset, so there's no neeed to fetch one when clicking on beatmap panel

2019-12-04 02:00 UTC, smoogipoo requested changes

2019-12-04 02:00 UTC, smoogipoo commented on osu.Game/Overlays/Direct/DirectPanel.cs
> +        protected DirectPanel(BeatmapSetInfo setInfo, bool fetchOnline = false)
Any reason this is `false` by default whereas `DirectGridPanel` has `true` by default?

2019-12-05 02:22 UTC, peppy commented
I don't really like this flow, and think it may be best to always fetch for safety.

Passing bools down the heirarchy is prone to error – if we're going to bypass fetches it should be done in an automated and well-tested way (ie. BeatmapSetOverlay should decide whether it needs to fetch or not, based on whether the incoming request has everything it needs for display).

2019-12-05 02:28 UTC, EVAST9919 commented
As mentioned above, this needs different approach

2019-12-05 02:28 UTC, closed without merging