Legacy cursor rotation
ppy/osu pull request #7095
Opened 2019-12-08 12:12 UTC by mcendu

Resolves #6776 

Problems left to address:
- [ ] Does not initiate rotation all the time.
- [ ] Rotation is always turned on, without checking whether it is enabled in skin.

2019-12-08 12:32 UTC, bdach commented on osu.Game.Rulesets.Osu/Skinning/LegacyCursor.cs
> +            cursor.Spin(10000, RotationDirection.Clockwise);
This duration should probably be compared with stable's - did you check if the rate of spins is the same?

2019-12-08 12:34 UTC, bdach commented
What do you mean by "not initiating rotation all the time"? Did you try to debug that?

2019-12-09 04:04 UTC, smoogipoo requested changes

2019-12-09 04:04 UTC, smoogipoo commented on osu.Game.Rulesets.Osu/Skinning/LegacyCursor.cs
> +        private readonly bool rotate;
Rename to `spin`.

2019-12-09 05:44 UTC, smoogipoo commented
Thanks. I've moved the retrieval into LegacyCursor to follow the existing pattern inside `LegacySliderBall`.

2019-12-09 05:44 UTC, smoogipoo approved these changes

2019-12-09 06:31 UTC, merged