Add difficulty adjustment mod
ppy/osu pull request #7157
Opened 2019-12-11 12:03 UTC by LeNitrous

Adds a new mod "Difficulty Adjust" where the user can override a beatmap's difficulty settings.
Resolves #3201.

Things that are considered:
* Mania
    * Circle Size and Approach Rate are unused thus not present
    * Drain Rate should not be modified according to the ranking criteria
* Catch
    * Overall Difficulty uses the Approach Rate's value to comply with the ranking criteria
    * Changed "Circle Size" label to "Fruit Size" to match the ruleset's theme
* Taiko
    * Circle Size and Approach Rate are unused thus not present

2019-12-11 12:13 UTC, peppy commented
can this feasibly just be settings on HR?

2019-12-11 12:19 UTC, LeNitrous commented
Sounds fine.

2019-12-11 12:24 UTC, peppy commented
I'd try and make the settings on easy / HR (limited in opposite directions), as multipliers.

2019-12-11 12:26 UTC, LeNitrous commented
I just realized that HR in the osu! ruleset alters the positions of the hitobjects and what I'm aiming for is to purely change the beatmap settings alone.

2019-12-11 12:31 UTC, peppy commented
fair enough

2019-12-11 12:42 UTC, peppy commented
Would it not make more sense to draw defaults from the selected beatmap? I'm not 100% sure how most people would use, but it seems like you'd be adjusting from the mapper's settings rather than always using a set combination.

2019-12-11 13:04 UTC, LeNitrous commented
It would certainly make more sense with that.

2019-12-12 12:35 UTC, peppy commented
Are you going to give that a shot? Should be a pretty simple change.

2019-12-12 13:12 UTC, LeNitrous commented
I will. I'm still skimming over the code to know how to set the slider's default values based on the beatmap since `IApplicableToDifficulty` only applies when we move over to the `Player` screen.

2019-12-12 13:26 UTC, peppy commented
I see. Changes may need to happen to have this trigger from song select, on beatmap change.

2019-12-19 04:37 UTC, peppy commented
- Default not updating correctly on sliders (depends on https://github.com/ppy/osu-framework/pull/3123 and subsequent logic changes osu-side). Can probably go ahead with this PR without that being fixed as long as it isn't forgotten.
- Display values not updating after mod settings change. This needs to be fixed (as a separate PR) before this is merged.

2019-12-20 09:02 UTC, peppy commented
@LeNitrous this needs to be split out into per-ruleset implementations. Mania shouldn't have "circle size" adjustments, for instance.

2019-12-20 10:38 UTC, LeNitrous commented
I've taken considerations with Taiko and Mania where CS and AR are unused according to the wiki

For Circle Size:
> This option is visible in osu!taiko, but it does not do anything that affects gameplay.

> Key Count, also known as Keys, replaces the Circle Size metric for osu!mania-specific beatmaps.

For Approach Rate:
> This option is visible in osu!taiko and osu!mania, but it does not do anything that affects gameplay. This is mainly because both use a scroll speed, which is based on BPM (beats per minute).

2019-12-21 22:21 UTC, peppy requested changes

2019-12-21 22:21 UTC, peppy commented on osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
> +        public virtual BindableNumber<float> DrainRate { get; }
`DrainRate` is present in all rulesets, so can be in the base class.

2019-12-21 22:21 UTC, peppy commented on osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
> +        public virtual BindableNumber<float> CircleSize { get; }
Move unused members *out* of the base class.

2019-12-21 22:21 UTC, peppy commented on osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
> +                if (CircleSize != null)
do this in the implementation, not base class.

2019-12-21 22:21 UTC, peppy commented on osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
> +        public virtual BindableNumber<float> OverallDifficulty { get; }
same for OD. it's in all four rulesets so didn't need to be moved.

2019-12-25 08:37 UTC, merged