HUD Mod display
ppy/osu pull request #720
Opened 2017-05-05 04:02 UTC by peppy

- Builds off of (and supersedes) https://github.com/ppy/osu/pull/702.
- Adjusts namespaces of HUD elements to better group them (they are no longer related to Ruleset logic.
- Improves ModIcon/ModSection handling to avoid the need for ModIcons with null mod values.

2017-05-05 04:23 UTC, peppy commented
This should be ready for review 👍

2017-05-07 18:00 UTC, huoyaoyuan commented on osu.Game/Overlays/Mods/ModButtonEmpty.cs
> +    public class ModButtonEmpty : Container
curious as a name of base class

2017-05-07 18:07 UTC, huoyaoyuan commented
I dislike the type `MultiMod`.
A `ModButton` can receive multiple mods for select, so it should receive a `Mod[]` directly.
I think it should expose both `Mod` and `Mods` property for set, as many buttons are just receiving one.

2017-05-07 19:24 UTC, peppy commented on osu.Game/Overlays/Mods/ModButtonEmpty.cs
> +    public class ModButtonEmpty : Container
please provide a suggestion. i think this is a step up from using `ModButtonBase` (i'm really against using the base suffix, even though we use it in a few places).

2017-05-07 23:40 UTC, smoogipoo requested changes

2017-05-07 23:40 UTC, smoogipooo commented on osu.Game/Overlays/Mods/ModButton.cs
> +            set { buttonColour = value; }
No longer a need for property.

2017-05-07 23:40 UTC, smoogipooo commented on osu.Game/Rulesets/UI/ModIcon.cs
> +                default: return Color4.White;
This is a weird structure to this default. Please follow the case statement structure (incl. removing the newline before it).

2017-05-07 23:40 UTC, smoogipooo commented on osu.Game/Screens/Play/Player.cs
> +                    hudOverlay.ModDisplay.FadeOut(200);
This is HUD-specific and should not be a part of Player.

2017-05-07 23:40 UTC, smoogipooo commented on osu.Game/Rulesets/UI/ModIcon.cs
> +                    return OsuColour.FromHex(@"66ccff");
Use colours from OsuColour.

2017-05-07 23:42 UTC, EVAST9919 commented on osu.Game/Overlays/Mods/ModButton.cs
> +            set { buttonColour = value; }
it's needable, because we need that colour after switching back from selected state

2017-05-08 00:01 UTC, smoogipooo commented on osu.Game/Overlays/Mods/ModButton.cs
> +            set { buttonColour = value; }
I mean all this property is doing is wrapping a local private.

2017-05-08 00:03 UTC, smoogipooo commented on osu.Game/Rulesets/UI/ModIcon.cs
> +        private void reapplySize()
Function is unneeded. Just set the properties in here directly in the ctor.

2017-05-08 02:37 UTC, peppy commented on osu.Game/Screens/Play/Player.cs
> +                    hudOverlay.ModDisplay.FadeOut(200);
how shall we handle this? pass in a bool `HasReplay` to hudoverlay?

2017-05-08 02:46 UTC, smoogipooo commented on osu.Game/Screens/Play/Player.cs
> +                    hudOverlay.ModDisplay.FadeOut(200);
That's one possibility, although I was leaning more towards using hudOverlay.BindHitRenderer.

2017-05-08 02:46 UTC, peppy commented on osu.Game/Screens/Play/Player.cs
> +                    hudOverlay.ModDisplay.FadeOut(200);
ooh, didn't realise it's already passed in.

2017-05-08 02:54 UTC, smoogipoo approved these changes
👍

2017-05-08 02:55 UTC, merged