[Multiplayer] Add User panels
ppy/osu pull request #725
Opened 2017-05-06 14:41 UTC by Naeferith

![User Panels](http://i.imgur.com/p6b7BZk.png)
_flyte's design_

2017-05-06 14:46 UTC, RemieRichards commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                        statusString = "Hosting a Room";
aren't these backwards?

2017-05-06 14:47 UTC, Naeferith commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                        statusString = "Hosting a Room";
Indeed, thanks :)

2017-05-06 14:48 UTC, RemieRichards commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public void UpdatePanel(MultiUserPanel panel)
Is this supposed to do more than just set the spritetext? otherwise just make ```statusString``` a property that sets the spritetext

2017-05-06 14:49 UTC, turbedi commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +        public override string Description => @"User pannel in a multiplayer room";
typo

2017-05-06 14:50 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public void UpdatePanel(MultiUserPanel panel)
an instance method that always taking this as a parameter is stupid

2017-05-06 14:50 UTC, RemieRichards commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                new Container //Avatar
Avatars are implemented, you should probably store a ```User``` on this class, and instantiate a new ```Avatar(some_user)```

2017-05-06 14:53 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public MultiUserPanel(string user = "Unknown")
Take an instance of `User` class, instead of a string

2017-05-06 14:53 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                new Container //Avatar
There is an already done `Avatar`

2017-05-06 14:53 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                                new Container //Country Flag
`DrawableFlag`

2017-05-06 14:59 UTC, huoyaoyuan commented
btw where do you get the design?

2017-05-06 15:00 UTC, Naeferith commented
I got it from @peppy himself

2017-05-06 16:24 UTC, MrTheMake commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            Add(panelContainer = new FlowContainer //Positionning container
typo in comment

2017-05-06 19:01 UTC, huoyaoyuan commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +        public User User = new User
This could be created in `Reset()`, rather than save it(see visual test of leaderboard)

2017-05-06 19:01 UTC, huoyaoyuan commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            switch (action)
What's this for?

2017-05-06 19:01 UTC, huoyaoyuan commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            Add(panelContainer = new FillFlowContainer
My suggestion:
  - make a generic container
  - allow adding new panel
  - set host via the container, not a reference to specified panel

2017-05-06 19:01 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public const int PANEL_HEIGHT = 100;
private consts

2017-05-06 19:01 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        private string userName;
consider if you DO need fields for username and status string

2017-05-06 19:01 UTC, huoyaoyuan commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                    Colour = new Color4(34,34,34, 255),
format code manually(the IDE formatter doesn't work in nested object initializer lol)

2017-05-08 00:42 UTC, smoogipoo requested changes
A few changes requested, but pretty okay otherwise!

I'm not sure about being too pent up on having Anchors/Origins at the top of object initializers, so I'll let it pass for now.

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +
We don't use new lines in switch statements.

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +
Extra new line.

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                        statusSprite.Text = "Waiting in a Room";
"Waiting in a room" // "Hosting a room" (casing)

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +
No spaces in object initializers.

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                    Colour = new Color4(17, 136, 170, 128),
Use colours from the OsuColour palette.
```
[BackgroundDependencyLoader]
private void load(OsuColour colours)
{
   myBox.Colour = colours.MyColour;
}
```

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                    Text = "Waiting in a Room",
Also casing here. Consider making these text pieces into private consts for now (will be localised later).

2017-05-08 00:42 UTC, smoogipooo commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            int newHost = RNG.Next(panelContainer.Children.Count());
Let's avoiod rng in test cases - just make this cycle through them.

2017-05-08 00:42 UTC, smoogipooo commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            newHostPanel.State = MultiUserPanel.UserState.Host;
This is going to be a pretty common use case. I suggest making a MultiUserPanelContainer which has, say, a property such as
```
public User Host
{
    get { return Children.FirstOrDefault(c => c.Host); }
    set { Children.ForEach(c => c.Host = c == value); }
}
```

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public enum UserState
Move enum to separate file.

2017-05-08 00:42 UTC, smoogipooo commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public UserState State
Would avoid the enum for now and keep it simple with a `bool Host`.

2017-05-08 08:37 UTC, Naeferith commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +        public enum UserState
You told me to use a bool instead right ?

2017-05-08 09:08 UTC, Naeferith commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            newHostPanel.State = MultiUserPanel.UserState.Host;
The c parameter is defined as a Drawable and not a MultiUserPanel, is there a way I can cast this parameter ?

2017-05-08 09:48 UTC, huoyaoyuan commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            newHostPanel.State = MultiUserPanel.UserState.Host;
Use a generic container: `FillFlowContainer<MultiUserPanel>`

2017-05-08 10:56 UTC, Naeferith commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            newHostPanel.State = MultiUserPanel.UserState.Host;
The FirstOrDefault method will return a MultiUserPanel, should I change the type of ```Host``` into MultiUserPanel or store a User in the MultiUserPanel class so I can do 
```return Children.FirstOrDefault(c => c.Host).User;``` ?

2017-05-08 11:14 UTC, Naeferith commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            newHostPanel.State = MultiUserPanel.UserState.Host;
Setting ```Host``` as a ```MultiUserPanel``` should do the trick

2017-05-08 11:22 UTC, huoyaoyuan commented on osu.Desktop.VisualTests/Tests/TestCaseMultiUserPanel.cs
> +            newHostPanel.State = MultiUserPanel.UserState.Host;
If there is a type `MultiUserPanelContainer`, it can keep a reference to host panel

2017-05-09 00:12 UTC, MrTheMake commented on osu.Game/Screens/Multiplayer/MultiUserPanel.cs
> +                switch(host)
I would use an if-statement here since the argument is a boolean

2017-05-22 13:02 UTC, Naeferith commented
See #825

2017-05-22 13:02 UTC, closed without merging