Add a visualizer around the OsuLogo
ppy/osu pull request #726
Opened 2017-05-06 17:27 UTC by ColdVolcano

- [ ] Requieres https://github.com/ppy/osu-framework/pull/701

2017-05-06 17:40 UTC, Tom94 commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                        audioData = (beatmap.Value.Track as TrackBass).GetChannelData();
Raw bass methods should never be called from the main thread. Probably should make `GetChannelData` an internal thing to the framework, store its result in a local variable, and copy that local variable whenever it's requested from here. Similar to how other bass calls are used to update values inside the `Update` method of the audio tracks (which is always invoked from the audio thread).

That aside, your code here will crash if `Track` is not `TrackBass` which is not okay. It should be implementation agnostic.

2017-05-11 02:32 UTC, peppy requested changes

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/OsuLogo.cs
> +        private readonly MenuVisualisation visualizer;
why is it called menu visualisation when it's inside the osu logo

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                b.ScaleTo(new Vector2(1, b.Scale.Y > 0.25f ? b.Scale.Y - 0.1f : b.Scale.Y * 0.8f), 50);
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                    b.Alpha = MathHelper.Clamp(b.Scale.Y - 0.01f, 0, 0.15f) * .2f / 0.15f;
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                        if (indexOffset > 250)
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                                index -= 250;
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                        -(float)Math.Sin((float)(j + i * (bars_per_visualizer / 5)) / bars_per_visualizer * 2 * MathHelper.Pi) / 2,
magic numbers everywhere
repeated code everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +            audioData = new float[256];
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +
excess newlines

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                    if (timeOfLastUpdate + 50 <= Clock.CurrentTime)
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                                b.Scale = new Vector2(1, audioData[index] * 3.8f);
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +                            if (audioData[index] * 3.8f >= b.Scale.Y)
magic numbers everywhere

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +        private int indexOffset = 0;
`= 0` not needed

2017-05-11 02:32 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +        private float[] audioData;
why even store this when you're getting it every update

2017-05-11 02:38 UTC, peppy commented on osu.Game/Screens/Menu/MenuVisualisation.cs
> +            FadeTo(newValue ? 2.5f : 1, 75);
fading to 250% alpha?

2017-05-11 02:39 UTC, peppy commented
Thanks for your contribution. Unfortunately your code is not up to the standards of this project. Please use the above feedback as a general direction of where you should be going , but review *yourself* every line of your code and try and improve before submitting it for us to consider.

2017-05-11 14:31 UTC, ColdVolcano commented
Will close this for the time being.

2017-05-11 14:31 UTC, closed without merging