Implement kiai flash of hit circles
ppy/osu pull request #7316
Opened 2019-12-21 12:53 UTC by mcendu

Closes #7174

2019-12-21 13:01 UTC, frenzibyte requested changes

2019-12-21 13:27 UTC, mcendu commented on osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
> +                    Size = new Vector2(0.921875f),
Actual circle size (118) / Sprite size (128)

2019-12-21 13:50 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
> +                    Size = new Vector2(0.921875f),
Should put `118f / 128f` and add an inline comment referencing the circle and sprite sizes, putting the result with no reference is not accepted I believe.

2019-12-21 13:57 UTC, smoogipoo commented on osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
> +                    Size = new Vector2(0.921875f),
`Size = OsuLegacySkinTransformer. LEGACY_CIRCLE_RADIUS * 2` should be enough.

2019-12-21 14:38 UTC, mcendu commented on osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
> +                    Size = new Vector2(0.921875f),
> `Size = OsuLegacySkinTransformer. LEGACY_CIRCLE_RADIUS * 2` should be enough.

Should be divided by `128` to make it fit the circle.

2019-12-21 14:48 UTC, mcendu commented on osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/KiaiFlash.cs
> +        public Drawable FlashComponent { get; set; }
To ease implementation of flashing glow behind circles, but later thought that `Child` also fulfills that task so removed this property.

2019-12-21 19:32 UTC, peppy requested changes

2019-12-21 19:32 UTC, peppy commented on osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
> +                    Child = new Box
I'm confused as to why this child box isn't in the `KiaiFlash` class itself. Also not sure a legacy implementation should be made with a separate design unless it matches stable 1:1 (this code doesn't look to be).

2019-12-21 19:32 UTC, peppy commented
How are you testing this? Doesn't look like any tests were added.

2020-01-23 09:05 UTC, peppy commented
@mcendu any updates? This still needs a basic test method added int he osu! ruleset tests.

2021-06-04 05:53 UTC, peppy commented
I've tidied this up and added a legacy implementation.

Couple of notes:
- Doesn't include the slider body, which stable does, but this PR is focused on hitcircles so I think that's fine for now.
- The test doesn't seem to correctly actuate kiai flashes if run at <100% playback speed, not sure why. Needs further investigation but probably fine for now.
- To keep things simple I haven't brought across one of the stable timing details which is that if a kiai flash is going to exceed the `EndTime` of a hitobject it will be faded out faster to meet that point. I don't think this is required (was probably a workaround for animations not playing out correctly if the kiai one overlapped hit explode animations).

2021-06-04 05:53 UTC, peppy approved these changes

2021-06-04 06:07 UTC, smoogipoo approved these changes

2021-06-04 06:31 UTC, merged