Move mania stage hint to its own class
ppy/osu pull request #7381
Opened 2019-12-28 05:50 UTC by mcendu

2019-12-28 08:40 UTC, peppy commented
Is this a prereq for skinning support?

2019-12-28 09:43 UTC, mcendu commented
Mostly yes

2019-12-28 15:02 UTC, mcendu commented on osu.Game.Rulesets.Mania/UI/Components/StageHint.cs
> +        public abstract Color4 AccentColour { get; set; }
Change to virtual as legacy stage hints wouldn't be colored.

2019-12-29 14:50 UTC, peppy requested changes

2019-12-29 14:50 UTC, peppy commented on osu.Game.Rulesets.Mania/UI/Components/StageHint.cs
> +    public abstract class StageHint : CompositeDrawable, IHasAccentColour
not sure this base implementation need exist if it's this empty. if accent colour is the only usage, you can just null-cast is to pass in the colour:

```csharp
if (hitTarget is IhasAccentColour colouredHitTarget)
	colouredHitTarget.AccentColour = AccentColour;
```

2019-12-29 14:50 UTC, peppy commented
Not sure about the "stage hint" terminology. Where does this come from?

2019-12-29 15:07 UTC, GSculerlor commented
If this PR is targeting for skin support, then it should be referring to `mania-stage-hint` (source from [wiki](https://osu.ppy.sh/help/wiki/Skinning/osu%21mania)). But on stable, `mania-stage-hint` is for full-width playfield, not per column

2019-12-30 02:11 UTC, peppy commented on osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
> +                    hitTargetBar.Anchor = hitTargetBar.Origin = anchor;
not sure doing the full bindable flow here is required (could just pass on the anchor from self to children) but should be fine for now.

2019-12-30 02:11 UTC, peppy approved these changes

2019-12-30 02:11 UTC, merged