Add the skin setting "Color the sliderballs according to the color of the sliders"
ppy/osu pull request #7459
Opened 2020-01-06 21:12 UTC by Azn9

This is only a small visual modification, but which can be useful for some people. For example, in some beatmaps, the slider colors are very dark so the sliderball and the followcircle arn't easily viewable.

2020-01-06 21:41 UTC, bdach requested changes
This doesn't work correctly if the setting is toggled in the middle of gameplay since there's no `BindValueChanged` on the added bindable and `ApplySkin` triggers only on skin changes.

2020-01-06 21:41 UTC, bdach commented on osu.Game/Overlays/Settings/Sections/SkinSection.cs
> +                    LabelText = "Color the sliderballs according to the color of the sliders",
I'd follow stable text:
```suggestion
                    LabelText = "Use combo colour as tint for slider ball",
```

2020-01-06 21:42 UTC, bdach commented
Also an open question if we even want to bring this over from stable in lieu of #4924 (might allow editing the skin setting instead of globally enabling/disabling tint).

2020-01-06 21:54 UTC, Azn9 commented
A parameter depending on the current skin which would be activated or deactivated then? So be able to modify `OsuSkinConfiguration.AllowSliderBallTint`?

2020-01-06 21:56 UTC, bdach commented
> A parameter depending on the current skin which would be activated or deactivated then? So be able to modify `OsuSkinConfiguration.AllowSliderBallTint`?

That's what I'm thinking of, yes. Although I'm definitely not at liberty here to make an executive decision about that myself.

2020-01-07 01:50 UTC, peppy commented
Thanks for the contribution, but this is not the direction we're going in. As mentioned above, this would be a setting at the skin level, not global. The only global settings that should be present for skins are very high level decisions for the users, like "never/always use skin hitsounds".

2020-01-07 01:50 UTC, closed without merging