Spinner's needed spm depends on beatmap's OD
ppy/osu pull request #748
Opened 2017-05-12 23:28 UTC by EVAST9919

2017-05-13 11:11 UTC, RemieRichards commented on osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
> +        private float beatmapOd;
Overall Difficulty is frequently referred to as OD, should probably be maintained here too. (would require adding it as an abbreviation to the solution's DotSettings)

The ```//TODO``` you removed below also referred to it as OD.

2017-05-13 12:10 UTC, smoogipooo commented on osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
> +            beatmapOd = game?.Beatmap?.Value.Beatmap.BeatmapInfo.Difficulty.OverallDifficulty ?? 5;
You shouldn't be retrieving spins required like this. Override ApplyDefaults() in Spinner.cs and set a publicly visible local "SpinsRequired" or something, then refer to it in DrawableSpinner by `HitObject.SpinsRequired`. Look at DrumRoll.cs for an example of this.

2017-05-13 12:17 UTC, smoogipooo commented
The correct algorithm is `Duration / 1000 * DifficultyRange(OD, 3, 5, 7.5)`.

2017-05-14 06:14 UTC, smoogipooo commented on osu.Game.Rulesets.Osu/Objects/Spinner.cs
> +            SpinsRequired = Duration / 1000 * BeatmapDifficulty.DifficultyRange(difficulty.OverallDifficulty, 3, 5, 7.5);
This should just be (int) casted.

2017-05-14 06:16 UTC, smoogipoo requested changes
Looks good for a merge after the change mentioned in my last comment is applied.

2017-05-14 06:26 UTC, smoogipoo submitted a review, later dismissed

2017-05-14 06:41 UTC, smoogipoo approved these changes

2017-05-14 06:41 UTC, smoogipooo commented
Good stuff.

2017-05-14 06:41 UTC, merged