Allow changing volume in song select with arrow keys when pressing alt
ppy/osu pull request #7528
Opened 2020-01-14 06:37 UTC by Joehuu

![](https://puu.sh/EZEqI/3129b61255.png)

Volume overlay still needs navigation with left and right arrows for more usability, tracked in https://github.com/ppy/osu/issues/7527.

2020-01-14 06:42 UTC, bdach commented
Have you made sure this doesn't break non-English keyboard layouts/special char entry? I think this conditional might be too general.

2020-01-14 06:56 UTC, Joehuu commented
I'm not sure how to check that, but if someone notices a bug, we'll reconsider the change.

2020-01-14 07:05 UTC, bdach commented
Some layouts use <kbd>Alt</kbd> as a modifier to printable keys in order to insert special characters. I'll check whenever I get the chance, but if you want to, you could try one of those (US International should have some I believe).

If it turns out to be a problem, we could either go for a more targeted check or a platform action.

2020-01-14 07:06 UTC, peppy commented
Shouldn't affect arrow keys, I don't think.

2020-01-14 11:23 UTC, peppy requested changes

2020-01-14 11:23 UTC, peppy commented on osu.Game/Screens/Select/BeatmapCarousel.cs
> +            if (direction == 0 || e.AltPressed)
It's unfortunate that this is how we have to do it, but I can't find a better way. Ultimately, we would want `OnkeyDown` and `OnPressed` to both be handled at the same time in a single tree iteration so we could correctly handle this at the receptor.

I think at very least, the early return should be moved to the top of this method, and commented with reasoning as to why it's done (so we can hopefully implement in a better way in the future).

2020-01-15 06:12 UTC, peppy approved these changes

2020-01-15 06:12 UTC, merged