fix tooltip capitalization
ppy/osu pull request #7534
Opened 2020-01-14 19:28 UTC by revelsix

closes #7515

2020-01-14 19:30 UTC, revelsix commented
bruh i forgot mods, 1 sec

2020-01-14 19:35 UTC, frenzibyte requested changes

2020-01-14 19:35 UTC, iiSaLMaN commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                        new OsuMenuItem("view profile", MenuItemType.Highlighted, Action)
menu items are not tooltips, although I wouldn't mind making them lowercase (osu! text style is mostly in lowercase), but in a different PR please.

2020-01-14 19:35 UTC, iiSaLMaN commented on osu.Game/Users/UserPanel.cs
> +            new OsuMenuItem("view profile", MenuItemType.Highlighted, ViewProfile),
same as above.

2020-01-14 21:57 UTC, jcspeet approved these changes

2020-01-14 23:58 UTC, peppy commented
Blocked until further discussion happens regarding consistency with `osu-web` (which as mentioned, uses title case for tooltips).

2020-01-16 03:38 UTC, peppy approved these changes
Looks like we're going with lower case for now.

2020-01-16 03:46 UTC, merged