Make iconless mods display acronyms on their icon
ppy/osu pull request #7537
Opened 2020-01-15 09:41 UTC by mcendu

Closes #7529

Partially resolves #6966 considering mania key mods.

2020-01-15 12:25 UTC, iiSaLMaN commented on osu.Game/Rulesets/Mods/ModDaycore.cs
> +        public override IconUsage? Icon => null;
redundant

2020-01-15 17:26 UTC, bdach commented
I'm starting to wonder if `ModIcon` wouldn't fare better as a `ModelBackedDrawable`. Your current implementation looks quite close already, although not overly obviously (it's not a straightforward change, but more of a major refactor).

2020-01-16 02:32 UTC, smoogipoo requested changes
Just a few nits

2020-01-16 02:32 UTC, smoogipoo commented on osu.Game/Rulesets/UI/ModIcon.cs
> +                    Font = OsuFont.Numeric.With(null, size - 57.5f),
```suggestion
                    Font = OsuFont.Numeric.With(null, 22f),
```
.5 isn't significant, also prefer to have things defined - would like the `size - 35` below to be simplified to `45` also.

2020-01-16 02:32 UTC, smoogipoo commented on osu.Game/Rulesets/UI/ModIcon.cs
> +
```suggestion
```

2020-01-16 02:33 UTC, smoogipoo commented
Definitely could do with a refactor to MBD but it's not super necessary for now though, imo.

2020-01-17 13:32 UTC, smoogipoo approved these changes
seems ok for now

2020-01-18 05:57 UTC, merged