Match osu-stable FollowCircle behaviour and size
ppy/osu pull request #7704
Opened 2020-02-01 16:00 UTC by TheWildTree

Brings `FollowCircle` behaviour in line with stable by introducing `InternalFollowCircle` (not sure about this name though) and making it scale instantly to `2.4f`, so the input check matches stable, while the visual part scales to `2f` on its own as it previously did.

2020-02-01 16:04 UTC, frenzibyte requested changes
~~That's a little bit of a hacky way to do this, what you probably want to do is create that circular container inside the `FollowCircleContainer` **internally**.~~

2020-02-01 16:10 UTC, TheWildTree commented
If done that way, would it let me scale the internal circle to a size bigger than the visible one (its parent)?

2020-02-01 16:12 UTC, bdach commented
I think it would if you specified a relative `Size` bigger than 1 (1.2 in this case, I suppose). I wouldn't say the current solution is *hacky* per se, but encapsulation is better, I agree.

2020-02-01 16:34 UTC, TheWildTree commented
Encapsulating it doesn't make sense to me, since they have to scale separately (one instantly, one over time) - if done as proposed, scaling will always be wonky for one of the circles (depending on which one we'd make the parent). Unless there is a way to decouple the scaling part, of course, but that seems counterproductive in a parent-child relationship.

2020-02-02 08:01 UTC, frenzibyte requested changes
On second thought, this may actually be fine currently FWIW. also if possible, would be nice to add tests following the slider with the cursor beyond the follow circle to ensure no issues with this.

2020-02-02 08:01 UTC, iiSaLMaN commented on osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
> +                InternalFollowCircle = new CircularContainer
The name of this drawable is definitely misleading given what it does, how about `TrackingArea` or `FollowingArea`, with an in-line comment explaining why it's there. (and reference to osu-stable)

2020-02-02 12:48 UTC, peppy requested changes

2020-02-02 12:48 UTC, peppy commented on osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
> +                    Alpha = 0
this shouldn't be required

2020-02-02 12:48 UTC, peppy commented on osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
> +        public readonly Drawable TrackingArea;
i think this can be private

2020-02-02 18:20 UTC, TheWildTree commented
Added tests checking for the tracking area radius. Please let me know if that's the right way to test this - I'm a bit curious about tracking dropping on hitobjectradius * 1.2f (so theoretically on the edge of tracking area which is scaled to 2.4f), I thought it's gonna drop tracking only after passing that point (so at >1.2f), but I guess that's not the case.

2020-02-02 20:34 UTC, TheWildTree commented
Testing this behaves differently in visual testing than it does in CLI. In visual browser, cursor `circle_radius * 1.2f` away from the center was enough to drop tracking, while in CLI it needed >1.2f to drop. 

I don't know which one was behaving correctly, so for now I decreased the precision of tests to not trigger those edge cases, as they seem to be out of scope for this PR.

2020-02-03 00:58 UTC, peppy commented
I think that is fine for the time being. We will likely to a precision pass once we are closer to requiring this from replay playback / recording.

2020-02-03 01:55 UTC, peppy commented
Probably important to note (though I don't think it requires a comment) that the tests are using `hit object radius * 1.2`, which is only correct because it's using default CS5

2020-02-03 01:58 UTC, peppy approved these changes

2020-02-03 01:58 UTC, merged

2020-02-03 02:25 UTC, smoogipoo commented
What about our prior discussion where we concluded that the user should always see their input matching with something on screen? With this, not only does it not scale up but it also doesn’t match the visual representation anymore.

2020-02-03 02:37 UTC, peppy commented
You raise a good point, completely missed that this is actually going against that.

We may want to just fix the size / tracking region to match for the time being, and revert this fix until it can be applied in a legacy-only way.