Added Spun Out mod
ppy/osu pull request #7731
Opened 2020-02-05 04:55 UTC by TK421bsod

2020-02-05 05:09 UTC, peppy commented
Please stop doing what you are doing

2020-02-05 05:16 UTC, TK421bsod commented
My bad. I'll leave it open.

2020-02-05 05:30 UTC, bdach requested changes

2020-02-05 05:30 UTC, bdach commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +        public override ModType Type => ModType.DifficultyIncrease;
I'm pretty sure Spun Out is not supposed to be a difficulty increase mod.

2020-02-05 05:30 UTC, bdach commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> -        public override Type[] IncompatibleMods => new[] { typeof(ModAutoplay), typeof(OsuModAutopilot) };
As far as I can tell `ModAutopilot` was erroneously dropped here as well.

2020-02-05 05:30 UTC, bdach commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +                inputManager.AllowUserCursorMovement = true;
These repeated assignments of the same values to the same variable are not necessary.

2020-02-05 05:30 UTC, bdach commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +                    requiresHold |= (osuHit is DrawableSpinner);
Repeated condition check.

2020-02-05 05:30 UTC, bdach commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +                    else if (Math.Abs(replayFrames[currentFrame + 1].Time - time) <= Math.Abs(replayFrames[currentFrame].Time - time))
I'm not sure I'm following this check, mind explaining? In fact I think this could have a bug in it.

2020-02-05 05:30 UTC, bdach commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +                wasLeft = !wasLeft;
What's the purpose of this? Does this mean that the held key will alternate every replay frame?

2020-02-05 05:35 UTC, mcendu commented
Hijacking the input manager looks like a hack to me.

2020-02-05 05:37 UTC, smoogipoo commented
hijacking like done here is the proper way to do it

2020-02-05 06:30 UTC, mcendu commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +                if (!(drawable is DrawableOsuHitObject osuHit))
I suppose we will never reach such a situation?

2020-02-07 19:23 UTC, bdach commented
After checking out this PR to see if it's salvageable, it is unfortunately my opinion that fixing this current implementation would require almost as much work as starting from scratch. To recap:

* Code style is not adhered to. Errors indicated by CI have not been addressed.
* The mod has the wrong icon (see mod icons on web for the proper one), is in the wrong section if aiming for parity with stable (should be in `Automation`) and still has the wrong mod incompatibility settings.
* During gameplay the mouse cursor (I don't mean the manager, but the actual mouse cursor) is hijacked directly and crudely. While the spinner is being auto-spun, the user has no perception of where on the screen they're currently pointing. Moreover, when control is handed back to the user, it is handed back to the current absolute position of the mouse cursor, causing disorienting jumps.

  Compare this behaviour with stable, where the user can visually see and track the mouse cursor the whole way through, while the spinner auto-spins *on its own*.

2020-02-08 01:12 UTC, mcendu commented on osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
> +                if (!(drawable is DrawableOsuHitObject osuHit))
Please resolve this

2020-02-11 06:16 UTC, peppy commented
Closing in favour of #7764.

2020-02-11 06:16 UTC, closed without merging