Add ability to load long comment trees in CommentsContainer
ppy/osu pull request #7775
Opened 2020-02-09 10:00 UTC by EVAST9919

Depends on resolving https://github.com/ppy/osu-web/issues/5611

2020-02-09 14:06 UTC, bdach requested changes
I feel like this is an incorrect direction to take. IMO performing incremental updates on the comment tree should be coordinated by one top-level component for the entire tree.

2020-02-09 14:15 UTC, EVAST9919 commented on osu.Game/Overlays/Comments/CommentsPage.cs
> +                }
Because we receiving the same thing (`CommenBundle`), but we need to manipulate it differently.
Where should I put it then?

2020-02-09 14:22 UTC, bdach commented on osu.Game/Overlays/Comments/CommentsPage.cs
> +                }
Differently how? Where's the other version? As far as I can see the original implementation in `CommentBundle.Comments.set` got removed.

2020-02-09 18:58 UTC, EVAST9919 commented on osu.Game/Overlays/Comments/CommentsPage.cs
> +                }
Other version is in the `GetCommentRepliesButton`

2020-02-10 09:49 UTC, EVAST9919 commented
@bdach do you think it should be handled by `CommentsPage` for example? Like it should provide an action for each `DrawableComment` and if fired - it should fetch comments and send them back to the `DrawableComment`?

2020-02-12 11:59 UTC, EVAST9919 commented
Personally prefer https://github.com/ppy/osu/pull/7786 because it's more scalable in the future

2020-02-12 11:59 UTC, closed without merging