Display a login placeholder in direct when user isn't logged in.
ppy/osu pull request #7854
Opened 2020-02-15 21:35 UTC by Game4all

# Summary

- This PR adds a login placeholder to the osu!direct overlay through the use of an OnlineViewContainer.
Since the direct overlay inherits `SearchableListOverlay` and only online overlays derive from this class, I chose to implement it in `SearchableListOverlay` as it allows every overlay inheriting from this class to inherit the functionality (social overlay now benefits of this)

- The displayed placeholder message can be customized through the  abstract`SearchableListOverlay.LoginPlaceholder` property.

## Visual Demo

[Avalaible here](https://streamable.com/s/3uad5/zdgijt)

2020-02-15 21:55 UTC, frenzibyte requested changes

2020-02-15 21:55 UTC, iiSaLMaN commented on osu.Game/Overlays/SearchableList/SearchableListOverlay.cs
> +        }
I thought `OnlineViewContainer` would only be used for inheritance. but after I've given this usage a couple of reads, I would argue that this container should not be abstract at all.

2020-02-15 21:55 UTC, iiSaLMaN commented on osu.Game/Overlays/SocialOverlay.cs
> +        protected override string LoginPlaceholder => @"Please sign in to browse social!";
(spacing please)
```suggestion

        protected override string LoginPlaceholder => @"Please sign in to browse social!";
```

2020-02-15 21:55 UTC, iiSaLMaN commented on osu.Game/Overlays/DirectOverlay.cs
> +        protected override string LoginPlaceholder => @"Please sign in to browse direct!";
(also here)
```suggestion

        protected override string LoginPlaceholder => @"Please sign in to browse direct!";
```

2020-02-15 21:58 UTC, TheWildTree commented
> I chose to implement it in SearchableListOverlay as it allows every overlay inheriting from this class to inherit the functionality

`SearchableListOverlay` itself shouldn't be tied to any online-related code IMO, as it might be used for non-online stuff in the future. 

For me, you should either create a separate, online-tied version of `SearchableListOverlay` deriving from it and use that for direct / social overlays, or implement the placeholder logic directly inside of them.

The second option would be better because it also makes the placeholder able to hide the search / filter parts of the overlays, which IMO would look much better.

2020-02-16 01:02 UTC, peppy commented
I think it's fine hiding only the results area, but special attention should be given to how changes to the search criteria work.

2020-02-16 11:04 UTC, Game4all commented
> `SearchableListOverlay` itself shouldn't be tied to any online-related code IMO, as it might be used for non-online stuff in the future.

A look at `SearchableListOverlay` inheritance tree shows that it derives from `FullscrenOverlay` which in turn implements `IOnlineComponent`, which somehows indicate that it is intended to be used in an online context. So I doubt it will be used in a non-online context (please correct me if I'm wrong) thus it is pointless to me to abstract online behaviour in another class.

2020-02-20 19:02 UTC, bdach commented
I'm not too sure if we're not going to want to apply this to the `BeatmapListingOverlay` which is being developed in parallel to this instead, as I don't know if it's intended to be a replacement for direct.

2020-02-21 04:53 UTC, peppy commented
@bdach it is intended to replace the direct overlay. i'm not sure why it wasn't a refactor instead of a new class, to be honest (maybe @EVAST9919 can answer that).

that being said, as this component is likely going to disappear maybe it's a good opportunity to merge this and see how it behaves before it gets replaced?

2020-02-21 04:55 UTC, EVAST9919 commented
I just wanted to replace everything at once (to make sure we still have fully working overlay) while implementing component by component.

2020-02-21 04:59 UTC, peppy requested changes

2020-02-21 04:59 UTC, peppy commented on osu.Game/Overlays/SearchableList/DisplayStyleControl.cs
> +            DisplayStyle.DisabledChanged += disabled => Dropdown.Current.Disabled = disabled;
i'd argue this control doesn't even need to be disabled.

2020-02-21 04:59 UTC, peppy commented on osu.Game/Overlays/SocialOverlay.cs
> +        protected override string LoginPlaceholder => @"Please sign in to browse social!";
this sounds really weird.

just make it "Please sign in to view content" for all cases for now.

2020-02-21 05:02 UTC, peppy commented
This whole thing feels weird. The "disabled" stuff should probably not be required and the `OnlineViewContainer ` should be similar to (or share a parent class with) `ProcessingOverlay`.

2020-02-21 16:52 UTC, turbedi commented on osu.Game/Overlays/SearchableList/SearchableListFilterControl.cs
> +                }
```
Tabs.Current.Disabled = disabled.NewValue;
DisplayStyleControl.DisplayStyle.Disabled = disabled.NewValue;
Search.Current.Disabled = disabled.NewValue;
```

2020-02-23 08:47 UTC, Game4all commented
I'm going to close this to work on a refactor of `OnlineViewContainer` first as I agree the container behaviour isn't as great as I imagined.

2020-02-23 08:47 UTC, closed without merging