Implement BeatmapListingSortTabControl component
ppy/osu pull request #7864
Opened 2020-02-17 00:42 UTC by EVAST9919

![Screenshot_1](https://user-images.githubusercontent.com/22874522/74616194-7539e100-5137-11ea-9259-714967c54308.png)

2020-02-17 18:54 UTC, bdach requested changes

2020-02-17 18:54 UTC, bdach commented on osu.Game.Tests/Visual/UserInterface/TestSceneBeatmapListingSort.cs
> +        }
It's test code, so not too relevant, but a bit staggering nonetheless - you could as well have added the two sprite texts to the hierarchy in the constructor, assigned them to fields and only changed their `.Text` values in the two `BindValueChanged` callbacks.

2020-02-17 18:54 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapListingSortTabControl.cs
> +            private class BeatmapSortTabItem : SortTabItem
Getting a little too nested - can this not be side-by-side with the tab control inside `BeatmapListingSortTabControl`? They're both private anyways.

2020-02-17 18:54 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapListingSortTabControl.cs
> +                private class BeatmapTabButton : TabButton
Same thing with the nesting here, this doesn't need to be encapsulated this much.

2020-02-17 18:54 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapListingSortTabControl.cs
> +                            icon.Margin = direction.NewValue == Overlays.SortDirection.Ascending ? new MarginPadding { Top = 1 } : new MarginPadding { Top = 2 };
This shouldn't be required.

2020-02-17 18:58 UTC, EVAST9919 commented on osu.Game/Overlays/BeatmapListing/BeatmapListingSortTabControl.cs
> +                            icon.Margin = direction.NewValue == Overlays.SortDirection.Ascending ? new MarginPadding { Top = 1 } : new MarginPadding { Top = 2 };
Are you talking about margin?

2020-02-17 18:58 UTC, bdach commented on osu.Game/Overlays/BeatmapListing/BeatmapListingSortTabControl.cs
> +                            icon.Margin = direction.NewValue == Overlays.SortDirection.Ascending ? new MarginPadding { Top = 1 } : new MarginPadding { Top = 2 };
Yes, looks fine with it removed.

2020-02-17 20:08 UTC, bdach approved these changes
Looks ok for now.

2020-02-18 01:17 UTC, smoogipoo approved these changes

2020-02-18 01:51 UTC, merged