Mania endtime object conversion
ppy/osu pull request #790
Opened 2017-05-18 10:33 UTC by smoogipooo

Prereqs:
- [ ]  https://github.com/ppy/osu/pull/788

I think one at a time is the best for these, so here's the one that creates patterns for spinners.

2017-05-21 23:11 UTC, peppy requested changes

2017-05-21 23:11 UTC, peppy commented on osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternType.cs
> +        None = 0,
Can we use `= 1 << 0` notation instead?

2017-05-21 23:11 UTC, peppy commented on osu.Game.Rulesets.Mania/Beatmaps/Patterns/Pattern.cs
> +        /// Whether this pattern already contains a hit object in a code.
"Check whether" "column"

2017-05-21 23:11 UTC, peppy commented on osu.Game.Rulesets.Mania/Beatmaps/Patterns/Pattern.cs
> +        public bool IsFilled(int column) => hitObjects.Exists(h => h.Column == column);
`CheckColumnHasObject` might be a better name.

2017-05-21 23:11 UTC, peppy commented on osu.Game.Rulesets.Mania/Beatmaps/Patterns/Pattern.cs
> +        public int ColumnsFilled => HitObjects.GroupBy(h => h.Column).Count();
`ColumnsWithObjects` maybe

2017-05-21 23:11 UTC, peppy commented on osu.Game.Rulesets.Mania/Beatmaps/Patterns/Pattern.cs
> +            other.HitObjects.ForEach(Add);
might be able to use `hitObjects.AddRange(other.HitObjects)`

2017-05-21 23:11 UTC, peppy commented on osu.Game.Rulesets.Mania/Objects/ManiaHitObject.cs
> +        public int Siblings { get; set; }
o_O

2017-05-21 23:11 UTC, peppy commented on osu.Game/Beatmaps/Events/EventInfo.cs
> +    public class EventInfo
still don't think we want this. just make a list of breaks inside Beatmap for now

2017-05-21 23:13 UTC, peppy approved these changes

2017-05-21 23:33 UTC, peppy requested changes

2017-05-21 23:33 UTC, peppy commented on osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/EndTimeObjectPatternGenerator.cs
> +            while (PreviousPattern.IsFilled(nextColumn))
add a check whether all columns are filled before attempting this. could endless loop.

2017-05-22 01:23 UTC, smoogipooo commented
Comments before the merge fixed in https://github.com/ppy/osu/pull/822 .

2017-05-22 03:22 UTC, peppy approved these changes

2017-05-22 03:22 UTC, merged