Open Rankings when clicking on charts button
ppy/osu pull request #7955
Opened 2020-02-22 10:59 UTC by Game4all

Closes #7946
- Wires up the charts button in the main menu to the rankings overlay.
- Also removes unused ChartListing and ChartInfo screens

2020-02-22 13:20 UTC, bdach submitted a review, later dismissed

2020-02-22 14:57 UTC, Joehuu submitted a review, later dismissed

2020-02-25 10:04 UTC, smoogipoo commented
For the time being, this should link to the spotlights tab in the rankings overlay.

2020-02-25 10:04 UTC, smoogipoo requested changes
As mentioned

2020-02-25 23:33 UTC, smoogipoo commented
This is fine for now since it's such a simple change. The whole spotlights/charts thing is going to change in the (near?) future.

2020-02-25 23:33 UTC, smoogipoo approved these changes

2020-02-26 00:30 UTC, merged