Fix crash when clicking on ShowMore button in CommentsContainer
ppy/osu pull request #7982
Opened 2020-02-24 02:55 UTC by EVAST9919

The reason is we can receive duplicated comments not only in `IncludedComments` list but also in the `Comments` list.

2020-02-24 19:42 UTC, bdach requested changes
I don't like the unnecessary code duplication this introduces. I'd rather go for a
```csharp
foreach (var child in bundle.Comments.Concat(bundle.IncludedComments))
```
or a local function.

2020-02-24 21:05 UTC, bdach commented
I moved the inline comment into a more-suitable place (looks better near the actually relevant conditional).

In general the change looks ok and obvious enough, but when submitting PRs for bugs/crashes I'd generally like to see a test reproducing the crash scenario to make sure it doesn't regress again. I would have submitted one but I'd have to expose things in `CommentsPage` to do so and I don't want to interfere with your other PRs so I abstained from doing this.

2020-02-24 21:06 UTC, bdach submitted a review, later dismissed
approving even though I pushed here, since I only made one cosmetic change

2020-02-25 03:16 UTC, peppy commented
Can a test be added showing this crash?

2020-02-25 07:32 UTC, EVAST9919 commented
Added

2020-02-25 10:23 UTC, smoogipoo commented
Just confirmed with the osu-web, this is fine for now. The proper solution is to use cursors, but the documentation for that is neither available (right now) nor does the logic around it fit into our existing cursor response usages (`ResponseWithCursor`).

2020-02-25 10:24 UTC, smoogipoo approved these changes

2020-02-25 11:14 UTC, merged