Remove CommentsPage component and move it's logic to CommentsContainer
ppy/osu pull request #8010
Opened 2020-02-26 15:39 UTC by EVAST9919

2020-02-26 20:09 UTC, bdach submitted a review, later dismissed

2020-02-26 20:09 UTC, bdach commented on osu.Game.Tests/Visual/Online/TestSceneOfflineCommentsContainer.cs
> -        }
What was the point of having these tests if they're going to get removed with this refactoring? The first one in particular was a *regression test*. This is unacceptable.

2020-02-27 03:32 UTC, smoogipoo requested changes

2020-02-27 03:32 UTC, smoogipoo commented on osu.Game/Overlays/Comments/CommentsContainer.cs
> +            var topLevelComments = AppendComments(response);
Really not feeling this. Some comments are async-loaded while others parts aren't.

The loading part itself should be moved inside `AppendComments`. The other stuff done here can exist outside of the load.

2020-07-12 08:03 UTC, bdach reviewed
otherwise looks ok I suppose

2020-07-12 08:24 UTC, EVAST9919 commented on osu.Game.Tests/Visual/Online/TestSceneOfflineCommentsContainer.cs
> +                CommentCounter.Current.Value = 0;
`ClearComments` called even if we are switching the sort which looks a bit weird. (when it jumps from `number` to 0 and then to this exact number again)

2021-08-09 12:45 UTC, gagahpangeran commented
What is the state of this PR?

I want to add pinned comment support and looks like this structure is easier to use.

2021-08-13 04:24 UTC, smoogipoo approved these changes
This can be refactored further, but I think it's fine to get in for the time being, so progress can be made in areas such as pinning.

2021-08-13 05:11 UTC, merged