Refactor OnlineViewContainer
ppy/osu pull request #8044
Opened 2020-02-28 17:16 UTC by Game4all

# Summary
As pointed out in a previous PR, the way the OnlineViewContainer exists now isn't as good as envisioned as it requires inheritance to be used and the current behaviour of completely hiding children isn't so great. This PR aims to transform the `OnlineViewContainer` into an overlay drawable with behaviour similar to `LoadingLayer`, hiding itself automatically when the user is logged in.

## Visual Demo of new behaviour
https://streamable.com/qhtum

## Remarks
The big diff is likely due to the renaming of `OnlineViewContainer` to `OnlineViewLayer`

2020-03-02 20:59 UTC, bdach requested changes
Out of curiosity, have you tried to apply this in more places and is changing to a layer a conclusion you've arrived to after trying that? I'm a bit worried that we'll flip-flop between the two variants.

2020-03-02 20:59 UTC, bdach commented on osu.Game.Tests/Visual/Online/TestSceneOnlineViewLayer.cs
> +            AddAssert("content is dimmed", () => con.Colour != Color4.White);
Might also be worth checking that the button underneath is not interactable.

2020-03-02 20:59 UTC, bdach commented on osu.Game/Online/OnlineViewLayer.cs
> +                placeholder = new LoginPlaceholder(placeholderMessage)
Doesn't really make sense to have a `LoginPlaceholder` be used here, in a general `OnlineViewLayer` - should be either abstracted away to just a `Placeholder` or renamed to reflect the new more-general purpose.

2020-03-02 20:59 UTC, bdach commented on osu.Game.Tests/Visual/Online/TestSceneOnlineViewLayer.cs
> +            AddWaitStep("wait for animation to finish", 5);
Probably more reliable to use an `UntilStep`. No need to expose the placeholder either, can use `ChildrenOfType<>`.

2020-03-02 20:59 UTC, bdach commented on osu.Game/Online/OnlineViewLayer.cs
> +        protected LoadingSpinner LoadingSpinner;
If this is exposed just for the test, might as well use `ChildrenOfType<>` for that too instead and not expose.

2020-03-03 15:16 UTC, Game4all commented
It may be better as you pointed out to let both exist as variants.

2020-03-03 18:10 UTC, bdach commented
If that ends up being the case they should share logic as much as possible, but then I don't think they *both* should be permitted to exist if it's at all avoidable.

2020-03-04 22:53 UTC, Game4all commented
The only place where I found an usage for OnlineViewLayer for now is for online overlays where it is preferable to dim content instead of hiding it. 
The logic could have been embedded in shared a class if all online-overlays inherited a same class but since the ChatOverlay doesn't, it needs to exist as a variant to OVC.

2020-04-21 02:09 UTC, peppy commented
@Game4all i know this is a bit out of date now and didn't really get reviewed in time. We now have an `OnlineView<>` class for the new dashboard setup which can potentially become one of these. Did you want to give it a shot and see if it fits well?

2020-04-21 08:28 UTC, Game4all commented
Sounds fine, will give it a shot to try integrating offline behaviour handling. It get the feeling that this may basically supersede what this PR proposed if it turns to work well. (Although it may require quite a bit of refactoring to make use of it in all online-only overlays)

2020-04-23 11:51 UTC, Game4all commented
@peppy After messing a bit with `OverlayView<>`, I get the feeling that `OverlayView<>` can definitely supersede this PR contents if it were to have the offline logic handling added directly to it, altough it may require tweaking transitions. Thus, I'm closing this and will start from scratch implementing the behaviour proposed by this PR in `OverlayView<>`.

2020-04-23 11:51 UTC, closed without merging