osu!direct (basic logic and layout)
ppy/osu pull request #805
Opened 2017-05-19 22:14 UTC by DrabWeb

API integration to come in a follow up PR.

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/Overlays/DirectOverlay.cs
> +    public class DirectOverlay : WaveOverlayContainer
Is it discussed to be an overlay?
There is an screen for direct existing.

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/Overlays/DirectOverlay.cs
> +            foreach (BeatmapSetInfo b in BeatmapSets)
linq can be used here

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/osu.Game.csproj
> +  <ItemGroup />
These empty item groups should be removed.

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/Overlays/Direct/FilterControl.cs
> +            Height = 35 + 32 + 30 + (padding * 2); // search + mode toggle buttons + sort tabs + padding
avoid magic numbers and use sum of consts
_why not auto size?_

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/Overlays/Direct/FilterControl.cs
> +                    Margin = new MarginPadding { Top = Height - 25 - padding, Right = DirectOverlay.WIDTH_PADDING },
magic number here

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/Overlays/Direct/DirectListPanel.cs
> +                icon.ScaleTo(1, 500, EasingTypes.OutElastic);
uniform 1 and 1f

2017-05-19 22:35 UTC, huoyaoyuan commented on osu.Game/Overlays/Direct/DirectListPanel.cs
> +                                    Alpha = SetInfo.Metadata.Source == @"" ? 0 : 1,
`string.IsNullOrEmpty` (and other places)

2017-05-19 22:51 UTC, DrabWeb commented on osu.Game/Overlays/DirectOverlay.cs
> +    public class DirectOverlay : WaveOverlayContainer
It's assumed due to the way that it's displayed, it overlays the content below it instead of moving to a new screen.

2017-05-20 05:53 UTC, peppy commented
I think there may be one or two more locations you can apply the `ReverseDepthFillFlowContainer` to by the way. I remember adding one recently.

2017-05-20 07:17 UTC, peppy commented
On a visual inspection:

- Ruleset icons should be either toggle or radio selection style. Let's go with radio for now (one selected maximum at a time). Actually, thinking about this they may not even be required any more as we have the global mode selector in the toolbar, but let's go with radio for now 🚢 .
- The textbox should maintain focus.
- We'll need to see how the non-anchoring search area goes with more results. It may make sense to anchor it in a similar way to the settings search area.

Will go through the code soon, this was just from checking VisualTest. Looking pretty good otherwise.

2017-05-22 05:55 UTC, peppy requested changes

2017-05-22 05:55 UTC, peppy commented on osu.Game/Overlays/Direct/DirectPanel.cs
> +                Texture = new OnlineWorkingBeatmap(SetInfo.Beatmaps.FirstOrDefault(), textures, null).Background,
This is evaluating `GetBackground` outside an async context. Check out `BeatmapBackgroundSprite` instead.

2017-05-23 08:54 UTC, peppy commented
This is going to be a minor pain to implement, but right now it looks really bad when you scroll through results. The counts should scroll along with the panels:

![image](https://cloud.githubusercontent.com/assets/191335/26346332/cbed18de-3fe0-11e7-95fb-38f7dc57faf5.png)

2017-05-24 05:06 UTC, peppy commented on osu.Game/Overlays/Direct/DirectListPanel.cs
> +                                            Text = @"mapped by ",
remove @ prefix from any strings which need future localisation

2017-05-24 05:08 UTC, peppy commented on osu.Game/Overlays/Direct/FilterControl.cs
> +            Height = HEIGHT;
is there a reason we can't autosize this?

2017-05-24 05:10 UTC, peppy commented on osu.Game/Overlays/Direct/FilterControl.cs
> +            Height = HEIGHT;
oh, the dropdown?

2017-05-24 05:17 UTC, peppy commented on osu.Game/Overlays/Direct/FilterControl.cs
> +    public class ResultCounts
either move these to their own file or nest inside class (we're trying to maintain one object per file)

2017-05-24 05:18 UTC, smoogipooo commented on osu.Game/Overlays/Direct/DirectListPanel.cs
> +                                            Text = @"mapped by ",
Would avoid using them at all for now in general.

2017-05-24 05:19 UTC, peppy commented on osu.Game/Overlays/Direct/DirectListPanel.cs
> +                                            Text = @"mapped by ",
we should be using them, so when we get to adding localisation it can be added automatically

2017-05-24 07:02 UTC, peppy approved these changes

2017-05-24 07:02 UTC, merged