Menu flashes
ppy/osu pull request #812
Opened 2017-05-20 16:16 UTC by ColdVolcano

Prereqs:

- [ ] https://github.com/ppy/osu-framework/pull/736
- [ ] https://github.com/ppy/osu/pull/777 (Merge first)

2017-05-22 08:47 UTC, smoogipooo commented
Please merge https://github.com/ppy/osu/pull/828 into here and update this with the latest framework master.

2017-05-22 08:48 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                    ColourInfo = ColourInfo.GradientHorizontal(new Color4(255, 255, 255, box_max_alpha), Color4.Transparent),
Using transparent black here is better (`new Color4(0, 0, 0, 0)`). Would also suggest putting TransparentBlack into OsuColour as I foresee it being used quite a bit.

2017-05-22 08:50 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            beatmap = game.Beatmap;
Don't use game's bindable like this. Create a local private one and do `beatmap.BindTo(game.Beatmap)`.

2017-05-22 08:52 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            beatmap = game.Beatmap;
weird part is that a local one already exists. make that one `readonly` and do ^

2017-05-22 08:53 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            if (!beatmap?.Value?.Track?.IsRunning ?? false)
I don't think this is ever going to be true, given the logic inside BeatSyncedContainer. You wouldn't want to do it this way anyway though - if you need to speed up the fade out it's better to bind to `beatmap.ValueChanged`.

2017-05-22 08:53 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            else if (newBeat >= 0)
With the above comment applied this can be inverted.

2017-05-22 08:53 UTC, ColdVolcano commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            if (!beatmap?.Value?.Track?.IsRunning ?? false)
I changed many things locally (why aren't they pushed?)

2017-05-22 08:59 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                if (kiai ? nextIsLeft : newBeat % (int)timeSignature == 0)
Can you combine this with `nextIsLeft`? It also seems like kiai mode should be a special "blinding mode" that always gets full brightness regardless of amplitude.

2017-05-22 09:00 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                    leftBox.FadeTo(Math.Max(0, (amp.LeftChannel - amplitude_dead_zone) / alpha_multiplier), 65);
Isn't this going to be > 1 if amp.LeftChannel = 1? Is this intended?

2017-05-22 09:01 UTC, ColdVolcano commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                    leftBox.FadeTo(Math.Max(0, (amp.LeftChannel - amplitude_dead_zone) / alpha_multiplier), 65);
in fact it is 0.55

2017-05-22 09:52 UTC, smoogipoo requested changes

2017-05-22 09:52 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            }
Newline after brace.

2017-05-22 09:52 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                return;
Newline after return.

2017-05-22 09:52 UTC, smoogipooo commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            if (newBeat % (kiai ? 2 : (int)timeSignature) == 0)
Can this be `if (kiai ? newBeat % 2 == 0 : newBeat % (int)timeSignature == 0)`? Just want to keep it consistent with the other if statement

2017-05-22 09:52 UTC, smoogipooo commented
Looks good after requested changes.

2017-05-22 10:16 UTC, smoogipoo submitted a review, later dismissed

2017-05-22 10:40 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                    Width = 300,
constant

2017-05-22 10:41 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                    ColourInfo = ColourInfo.GradientHorizontal(new Color4(255, 255, 255, box_max_alpha), Color4.Black.Opacity(0)),
make statics for each of the two colours as they are used in two places.

```private static readonly gradient_bright = ...
private static readonly gradient_dark = ...```

2017-05-22 10:47 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                leftBox.ClearTransforms();
find a way to not duplicate this code twice. hint: a method.

2017-05-22 10:51 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                rightBox.FadeTo(Math.Max(0, (amp.RightChannel - amplitude_dead_zone) / (kiai ? kiai_multiplier : alpha_multiplier)), 65);
65 should be a constant

2017-05-22 10:51 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                rightBox.DelayReset();
this line is unnecessary

2017-05-22 10:52 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +                rightBox.ClearTransforms();
this line is unnecessary

2017-05-22 10:53 UTC, peppy commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            TrackAmplitudes amp = beatmap.Value.Track.CurrentAmplitudes;
why not build this in to the beatsync container? it feels so wrong to access beatmap here when nothing else relies on beatmap

2017-05-22 10:59 UTC, ColdVolcano commented on osu.Game/Screens/Menu/MenuSideFlashes.cs
> +            TrackAmplitudes amp = beatmap.Value.Track.CurrentAmplitudes;
@smoogipooo

2017-05-23 08:26 UTC, peppy commented
Let's not merge this until https://github.com/ppy/osu/pull/831 is ready.

2017-05-23 09:12 UTC, smoogipooo commented
Looks better 👍

2017-05-23 09:13 UTC, smoogipoo submitted a review, later dismissed

2017-05-23 16:08 UTC, peppy commented
Don't have permission to push to remote, so can't fix this.

Please
- Resolve conflicts
- Merge upstream master
- Fix method signature changes in BeatSyncedContainer

2017-05-23 18:24 UTC, peppy requested changes
as cited

2017-05-24 01:10 UTC, peppy approved these changes

2017-05-24 02:40 UTC, merged