Fix CatcherAnimationState is Fail if missing banana shower
ppy/osu pull request #8230
Opened 2020-03-11 18:14 UTC by EVAST9919

2020-03-11 18:25 UTC, bdach commented
Having a test for this behaviour would be nice.

2020-03-11 19:28 UTC, EVAST9919 commented
We already have one `TestSceneDrawableHitObjects`

2020-03-11 19:38 UTC, bdach commented
...which doesn't have asserts, so if this ever breaks the test is useless for checking this logic.

2020-03-11 20:11 UTC, EVAST9919 commented
Added

2020-03-12 07:19 UTC, peppy commented on osu.Game.Rulesets.Catch/UI/CatcherArea.cs
> +                }
can combine else and if here

2020-03-12 07:19 UTC, peppy requested changes

2020-03-12 07:19 UTC, peppy commented on osu.Game.Rulesets.Catch/UI/CatcherArea.cs
> +            public CatcherAnimationState CurrentState;
private set

2020-03-12 11:10 UTC, merged