Add beatmap loading timeout to prevent runaway loading scenarios
ppy/osu pull request #8260
Opened 2020-03-13 05:13 UTC by smoogipoo

I've set the timeout to a very lenient 10 seconds, just to cover for slower devices. Although this stuff should really complete within a second on a normal beatmap (e.g. centipede takes <120ms across all modes).

2020-03-15 05:14 UTC, peppy requested changes

2020-03-15 05:14 UTC, peppy commented on osu.Game/Beatmaps/IWorkingBeatmap.cs
> +        /// <param name="timeout">The loading timeout.</param>
```suggestion
        /// <param name="timeout">The maximum lenght in milliseconds to wait for load to complete. Defaults to 10,000ms.</param>
```

2020-03-15 05:14 UTC, peppy commented on osu.Game/Beatmaps/WorkingBeatmap.cs
> +                    cancellationSource.Token.ThrowIfCancellationRequested();
sure we don't want to re-throw this as a `TimeoutException`? Seems a bit weird for callers to handle `OperationCancelledException` when they don't pass in a token.

2020-03-15 14:18 UTC, bdach reviewed
Tested the cancellation path by dropping in a `Thread.Sleep` in one spot. Kind of eh that it shows two notifications (one from wedge, one from player):

![image](https://user-images.githubusercontent.com/20418176/76703173-f9986900-66cf-11ea-923a-2b212f459156.png)

Log excerpt:

```
2020-03-15 14:15:25 [error]: Could not load beatmap sucessfully!
2020-03-15 14:15:25 [error]: System.OperationCanceledException: The operation was canceled.
2020-03-15 14:15:25 [error]: at System.Threading.CancellationToken.ThrowOperationCanceledException()
2020-03-15 14:15:25 [error]: at System.Threading.CancellationToken.ThrowIfCancellationRequested()
2020-03-15 14:15:25 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset, IReadOnlyList`1 mods, Nullable`1 timeout) in D:\Open Source\osu\osu.Game\Beatmaps\WorkingBeatmap.cs:line 132
2020-03-15 14:15:25 [error]: at osu.Game.Screens.Select.BeatmapInfoWedge.BufferedWedgeInfo.getInfoLabels() in D:\Open Source\osu\osu.Game\Screens\Select\BeatmapInfoWedge.cs:line 322
2020-03-15 14:15:25 [debug]: Focus changed from nothing to NotificationOverlay.
2020-03-15 14:15:27 [error]: Could not load beatmap sucessfully!
2020-03-15 14:15:27 [error]: System.OperationCanceledException: The operation was canceled.
2020-03-15 14:15:27 [error]: at System.Threading.CancellationToken.ThrowOperationCanceledException()
2020-03-15 14:15:27 [error]: at System.Threading.CancellationToken.ThrowIfCancellationRequested()
2020-03-15 14:15:27 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset, IReadOnlyList`1 mods, Nullable`1 timeout) in D:\Open Source\osu\osu.Game\Beatmaps\WorkingBeatmap.cs:line 132
2020-03-15 14:15:27 [error]: at osu.Game.Screens.Play.Player.loadPlayableBeatmap() in D:\Open Source\osu\osu.Game\Screens\Play\Player.cs:line 318
```
Also besides @peppy's notes, a few comment / typo nits.

2020-03-16 02:45 UTC, smoogipoo commented
@bdach going forward, we'll likely be getting the playable beatmap only once in a central location like OsuGameBase. The whole `GetPlayableBeatmap` process is too open. There's going to be other places that will require it (like recomputing scores on leaderboards), and having many playable beatmaps computed is wasteful.

2020-03-16 21:00 UTC, bdach approved these changes
looks good 👍  the double load definitely out of scope here

2020-03-17 02:17 UTC, merged