Cold volcano/beat syncing
ppy/osu pull request #828
Opened 2017-05-22 08:22 UTC by smoogipooo

Superseeds https://github.com/ppy/osu/pull/777.

2017-05-22 08:29 UTC, ColdVolcano commented
Somehow the file is not in the csproj

2017-05-22 08:31 UTC, smoogipooo commented
:PsyLikeThis:

2017-05-22 10:19 UTC, peppy commented on osu.Game/Graphics/Containers/BeatSyncedContainer.cs
> +        private const int seek_tolerance = 20;
won't this container stop working completely at 50fps or less?

2017-05-22 10:21 UTC, peppy commented on osu.Game/Graphics/Containers/BeatSyncedContainer.cs
> +            int beat = controlPoint.BeatLength > 0 ? (int)((currentTrackTime - controlPoint.Time) / controlPoint.BeatLength) : 0;
can't we just return early if `BeatLength == 0` and avoid this `?;`?

2017-05-22 10:37 UTC, peppy requested changes
as above

2017-05-23 02:25 UTC, peppy approved these changes

2017-05-23 02:25 UTC, merged