Add local replay support for all rulesets
ppy/osu pull request #8428
Opened 2020-03-24 07:32 UTC by peppy

- [ ] Depends on #8427.
- Uses legacy format (for now).

Important frame (judgement based) logic is not implemented on a per-ruleset level yet. This will come in a future iteration after things have settled.

2020-03-24 07:40 UTC, iiSaLMaN commented
Closes https://github.com/ppy/osu/issues/5309

2020-03-25 10:53 UTC, smoogipoo requested changes

2020-03-25 10:53 UTC, smoogipoo commented on osu.Game/Rulesets/Replays/Types/IConvertibleReplayFrame.cs
> +        LegacyReplayFrame ConvertTo(IBeatmap beatmap);
Please rename to `ToLegacy`, and the one above to `FromLegacy`. It's very weird naming as is.

2020-03-25 12:15 UTC, smoogipoo approved these changes

2020-03-25 13:02 UTC, merged