Fix NullReferenceException when starting the downloaded without video version of a beatmap with video
ppy/osu pull request #8455
Opened 2020-03-26 16:15 UTC by Game4all

Fixes potential NRE when playing the downloaded without video version of a beatmap with a video file.

Can be reproduced with any beatmap that has a video by downloading the no video version of the beatmap, importing it and start it.

2020-03-26 22:44 UTC, bdach reviewed
Fix looks fine. It's a hard crash so this is pretty high priority.

Wondering however if we couldn't have an actual test for this. I don't think it should be too difficult to write (just try to display a storyboard from an `.osr` with a video event linking to a file that doesn't exist).

As an aside no video maps also have another regression in that the background image seems to no longer show (it's all black). That's another PR entirely, though.

2020-03-27 00:20 UTC, peppy commented
Really do need testing on this. Should have been there in the last PR to avoid this happening in the first place 🤕

2020-03-27 07:15 UTC, Game4all commented
Will come back with tests for this to ensure no further regresses

2020-03-27 07:20 UTC, peppy commented
@Game4all got an ETA on this? would like to get this fix out in a build today or tomorrow.

2020-03-27 09:02 UTC, Game4all commented
Here is my shot at writing a test case for this. It feels like it doesn't test for anything as it just ensures the storyboard throws no NRE and feels a bit hacky

2020-03-27 10:29 UTC, smoogipoo requested changes

2020-03-27 10:29 UTC, smoogipoo commented on osu.Game.Tests/Resources/storyboard_no_video.osu
> +Video,0,"nevo cute.avi"
We try to not copy full beatmaps for copyright reasons. Most of the contents of this .osu can be culled (just keep two hitobjects or something + the video). Likewise, remove the things above (name/creator/artist/etc).

2020-03-27 12:12 UTC, peppy approved these changes

2020-03-27 12:12 UTC, merged