Fix auto mod results screen not displaying correctly
ppy/osu pull request #8488
Opened 2020-03-29 14:30 UTC by peppy

- Closes https://github.com/ppy/osu/issues/8468.

Tidies up results screen handling, allowing ReplayPlayer to have its own logic.

2020-03-29 15:15 UTC, frenzibyte requested changes
~~I don't think this should close the linked issue, as we're supposed to fix the double-counting keys on the replay from the reported issue which I can still reproduce on this branch.~~

2020-03-29 15:17 UTC, iiSaLMaN commented
perhaps you meant to close https://github.com/ppy/osu/issues/8436 instead?

2020-03-29 17:11 UTC, bdach commented
Yeah, I think this works. `GotoRanking` existing is something that [was already discussed before but it turned out not to be necessary in the end](https://github.com/ppy/osu/pull/8084#issuecomment-596196608), so no objections there. Perhaps a smidge confusing that the normal player still has the replay path due to autoplay implementation details but I can't see a better way out right now.

The break waits could possibly go away when replay playback gets faster.

2020-03-30 02:01 UTC, smoogipoo approved these changes

2020-03-30 02:01 UTC, merged