Display handling of IRC ACTION (/me) messages
ppy/osu pull request #860
Opened 2017-05-26 06:40 UTC by walle303

Make ACTION messages render properly now, like so
![Example](https://i.imgur.com/0B5FSoC.png)

2017-05-26 06:50 UTC, peppy commented
This does solve the problem, but the code is not at all what we want.

- make an `IsAction` property in `Message`. Use it instead of manual checks everywhere.
- make the returned content from a message never include control characters. move the json input to a private field and make `Content` a property. Also move all of this to a `LegacyMessage : Message` as to not pollute the base class.
- Your code styling doesn't match our project.

2017-05-26 06:50 UTC, peppy commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                return message.Content.Substring(8,message.Content.Length-9);
ugly

2017-05-26 06:50 UTC, peppy commented on osu.Game/Overlays/Chat/ChatLine.cs
> +        private string getUsernameDisplayString(Message message)
all these methods are overkill and shouldn't be required. just inline the changes

2017-05-26 06:51 UTC, peppy requested changes
.

2017-05-26 07:48 UTC, walle303 commented
I think that covers the changes you wanted.

2017-05-26 08:32 UTC, peppy commented
It's looking much better already. I'll do another pass once you've had a look at the class changes 👍

2017-05-27 05:23 UTC, walle303 commented
It might be better to implement the handling of action messages and control characters serverside, so that action messages can be implemented in the new chat system as well.

It appears [ppy/osu-web/app/Http/Controllers/API/ChatController.php](https://github.com/ppy/osu-web/blob/master/app/Http/Controllers/API/ChatController.php) contains the code for this, am I correct?

2017-05-27 05:30 UTC, peppy commented
You are correct. We really should be doing this stuff server-side.

2017-05-28 16:58 UTC, walle303 commented
That should cover it until you go over ppy/osu-web#1201

2017-05-29 02:22 UTC, peppy commented on osu.Game/Overlays/ChatOverlay.cs
> +                } else if (postText == "/me") {
please format your code in line with the rest of the project. we don't ever put `else if` on the same line as braces

2017-05-29 02:22 UTC, peppy commented on osu.Game/Overlays/Chat/ChatLine.cs
> +
unnecessary newline

2017-05-29 02:32 UTC, peppy requested changes
fix the few remaining formatting issues

2017-05-29 03:38 UTC, peppy commented on osu.Game/Overlays/ChatOverlay.cs
> +                } else if (postText == "/me") {
also all of this code feels wrong. get the command portion of the word and split out the rest before doing any processing, then use `switch` on the command part.

2017-05-29 03:38 UTC, peppy commented
For future pull requests please make a branch before PRing (don't use your master branch).

2017-05-29 03:45 UTC, walle303 commented
Does that take care of the formatting changes?
(I usually do have a separate branch, just forgot to do so this time)

2017-05-29 03:54 UTC, peppy commented
Also are you on discord? Would be easier to discuss this implementation if you are.

2017-05-29 04:03 UTC, walle303 commented
I don't use discord for a variety of reasons and would prefer to use an IRC channel or [matrix](https://matrix.org/) room, but seeing as you already have a fairly large discord room (based on how many people the badge says are in it), that's probably not going to happen. [Well... there is a way to bridge a matrix room and a discord room, but the bridge is very unfinished] If you'd like to contact me via Matrix, my Matrix ID is [@walle303:kek.community](https://matrix.to/#/@walle303:kek.community)

2017-05-29 04:10 UTC, peppy commented
Okay so basically, you're adding help messages that aren't what I want to be displayed.

Keep each command in its own `case` block, including any error messages.

2017-05-29 04:55 UTC, walle303 commented
What would you rather the help messages say, or would you rather change them yourself afterwards?

2017-05-29 04:56 UTC, peppy commented on osu.Game/Overlays/ChatOverlay.cs
> +            switch (postText.Split(' ')[0])
check for the / before entering the switch..

2017-05-29 04:58 UTC, peppy commented
Something needs to be done about this:

![untitled](https://cloud.githubusercontent.com/assets/191335/26537025/dd04f44e-4476-11e7-9fde-05002692a0f3.png)

2017-05-29 20:38 UTC, walle303 commented
Is it possible to clear the textbox after postMessage returns? It looks like textbox is part of osu-framework.

2017-07-11 02:25 UTC, DrabWeb commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                    Padding = new MarginPadding { Left = message_padding + (Message.IsAction ? 5 : 15) },
`Message.IsAction ? 5 : padding`

2017-07-21 07:16 UTC, peppy commented on osu.Game/Online/Chat/Message.cs
> +        public override int GetHashCode() => Id.GetHashCode();
what's happening here?

2017-07-21 07:18 UTC, peppy commented
This has been implemented server-side. May be best to just rebase this and rewrite as a bit of the underlying code has changed. Let me know if you are still wanting to continue implementing this.

2017-07-24 04:11 UTC, walle303 commented
Yeah, sorry for the delay, was a bit busy, I can still working on this.

2017-08-22 07:43 UTC, peppy commented
`is_action` is now being correctly returned by the server, for what it's worth.

2017-08-24 02:14 UTC, peppy commented
Closing due to inactivity. Please reopen when you address the issues.

2017-08-24 02:14 UTC, closed without merging