add multimod animation
ppy/osu pull request #864
Opened 2017-05-26 14:13 UTC by Jorolf

![modanimation](https://cloud.githubusercontent.com/assets/12570757/26498035/e8d8f4dc-422d-11e7-90f2-a4339476456e.gif)

2017-05-26 19:47 UTC, Jorolf commented on osu.Game/Overlays/Mods/ModButton.cs
> +                    using (foregroundIcon.BeginDelayedSequence(mod_switch_duration))
would be really nice if DelayedSequences apply to children aswell

2017-05-26 19:47 UTC, Jorolf commented on osu.Game/Overlays/Mods/ModButton.cs
> +                    using (foregroundIcon.BeginDelayedSequence(mod_switch_duration))
/shrug

2017-05-27 01:13 UTC, peppy commented on osu.Game/Overlays/Mods/ModButton.cs
> +                    using (foregroundIcon.BeginDelayedSequence(mod_switch_duration))
there's a second parameter for that :winkyface:

2017-05-29 09:05 UTC, peppy submitted a review, later dismissed

2017-05-29 09:08 UTC, smoogipoo requested changes

2017-05-29 09:08 UTC, smoogipooo commented on osu.Game/Overlays/Mods/ModButton.cs
> +            if(backgroundIcon != null)
Spacing

2017-05-29 09:09 UTC, smoogipoo submitted a review, later dismissed

2017-05-29 09:10 UTC, smoogipoo approved these changes

2017-05-29 09:20 UTC, merged