Allow for variables in storyboards
ppy/osu pull request #866
Opened 2017-05-27 04:57 UTC by ColdVolcano

2017-05-29 08:49 UTC, smoogipoo submitted a review, later dismissed
👍

2017-05-29 08:56 UTC, peppy requested changes

2017-05-29 08:56 UTC, peppy commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +            } while (val.IndexOf('$') != -1);
why not while instead of do{}while? also `< 0` not `!= -1`

2017-05-29 08:58 UTC, smoogipooo commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +            } while (val.IndexOf('$') != -1);
I prefer `!= -1` when it's defined by the spec to be this value.

2017-05-29 08:58 UTC, peppy commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +                if (section != Section.Events && section != Section.TimingPoints && section != Section.HitObjects && section != Section.Variables)
this is just getting stupid. can we refactor it?

2017-05-29 08:59 UTC, peppy commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +                        key = val.Remove(val.IndexOf('=')).Trim();
`val.Split('=')`?

2017-05-29 09:00 UTC, peppy commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> +                    if (valSplit[i][0] == '$' && variables.ContainsKey(valSplit[i]))
assign valSplit[i] to a local rather than looking it up three times

2017-05-30 10:53 UTC, smoogipooo commented
@peppy please re-review/approve.

2017-05-30 11:33 UTC, peppy commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> -        private void handleGeneral(Beatmap beatmap, string key, string val)
`val` was used here for a reason (generally we avoid using `value` as it is a keyword in certain contexts)

2017-05-30 11:34 UTC, peppy commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> -        private void handleGeneral(Beatmap beatmap, string key, string val)
even github isn't smart enough to realise it's not a keyword here:

![allow_for_variables_in_storyboards_by_coldvolcano_ _pull_request__866_ _ppy_osu](https://cloud.githubusercontent.com/assets/191335/26581430/647f038c-4577-11e7-921c-4a29382f0c5b.png)

2017-05-30 11:36 UTC, smoogipooo commented on osu.Game/Beatmaps/Formats/OsuLegacyDecoder.cs
> -        private void handleGeneral(Beatmap beatmap, string key, string val)
Ouch :\

2017-05-31 06:59 UTC, peppy approved these changes

2017-05-31 07:03 UTC, merged