Add support for testing arbitrary API requests/responses via Dummy API
ppy/osu pull request #8714
Opened 2020-04-11 09:07 UTC by peppy

2020-04-13 11:57 UTC, smoogipoo requested changes

2020-04-13 11:57 UTC, smoogipoo commented on osu.Game/Online/API/APIRequest.cs
> +            Debug.Assert(Result == null);
I think this should be an exception instead. It's `internal` sure, but it's still much too open imo.

2020-04-13 11:57 UTC, smoogipoo commented on osu.Game/Online/API/DummyAPIAccess.cs
>          public void Perform(APIRequest request) { }
`HandleRequest` should be added here and in `PerformAsync` too

2020-04-13 16:50 UTC, bdach approved these changes
Good stuff, will definitely help with testing online 👍

2020-04-14 04:42 UTC, smoogipoo approved these changes

2020-04-14 05:08 UTC, merged