Fix osu!mania replays actuating incorrect keys when multiple stages are involved
ppy/osu pull request #8755
Opened 2020-04-14 07:53 UTC by peppy

- Closes https://github.com/ppy/osu/issues/8723.

Added tests and also manually tested on a 10k (5+5k) beatmap to be working as expected.

2020-04-14 13:37 UTC, smoogipoo requested changes

2020-04-14 13:37 UTC, smoogipoo commented on osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
> +        /// <returns></returns>
```suggestion
```

2020-04-14 13:37 UTC, smoogipoo commented on osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
> +                }
Unroll the inner loop.

```suggestion
                if (index >= stage.Columns)
                {
                    index -= stage.Columns;
                    continue;
                }

                return stage.IsSpecialColumn(index);
```

2020-04-14 13:37 UTC, smoogipoo commented on osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
> +            return false;
```suggestion
            throw new ArgumentException("Column index is too high.", nameof(index));
```

2020-04-14 13:37 UTC, smoogipoo commented on osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
> +                        int overallIndex = 0;
```suggestion
                        // the index inclusive of special keys.
                        int overallIndex = 0;
```

2020-04-14 13:37 UTC, smoogipoo commented on osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
> +                        }
Personally found this while loop very confusing due to the inverted condition and then the non-inverted following it.

Prefer to be rewritten as:
```suggestion
                        // iterate to find the index including special keys.
                        for (; overallIndex < maniaBeatmap.TotalColumns; overallIndex++)
                        {
                            // skip over special columns.
                            if (isColumnAtIndexSpecial(maniaBeatmap, overallIndex))
                                continue;

                            // found a non-special column to use.
                            if (nonSpecialKeyIndex == 0)
                                break;

                            // found a non-special column but not ours.
                            nonSpecialKeyIndex--;
                        }
```

2020-04-15 03:34 UTC, peppy commented on osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
> +                }
nice one

2020-04-15 04:08 UTC, smoogipoo approved these changes

2020-04-15 04:42 UTC, merged