Context Menu (without submenu)
ppy/osu pull request #880
Opened 2017-05-29 18:01 UTC by EVAST9919

2017-05-29 18:38 UTC, Jorolf commented on osu.Game/Graphics/Cursor/ContextMenuContainer.cs
> +                    return true;
Why do you return true here?

2017-05-29 18:38 UTC, Jorolf commented on osu.Game/Graphics/UserInterface/DismissContextMenuItem.cs
> +            TextColour = Color4.Red;
Any reason for doing this in load()

2017-05-29 20:53 UTC, DrabWeb commented on osu.Game/Graphics/UserInterface/ContextMenuItem.cs
> +        private const int width = 170;
Context menus should scale to the width of the largest item, not a static width.

2017-05-29 20:53 UTC, DrabWeb commented on osu.Game/Graphics/UserInterface/ContextMenuItem.cs
> +        public SampleChannel SampleClick, SampleHover;
Private, or maybe protected if you want subclasses to be able to change the samples.

2017-05-29 20:53 UTC, DrabWeb commented on osu.Game/Graphics/Cursor/ContextMenuContainer.cs
> +                    if(items != null)
Set children directly, don't do this whole remove old and add new.

2017-05-30 12:21 UTC, smoogipoo requested changes
Early code-only pass.

2017-05-30 12:21 UTC, smoogipooo commented on osu.Game/Graphics/IHasContextMenu.cs
> +        ContextMenuItem[] Items { get; }
Would rename Items to `ContextMenuItems`, Items sounds like a common name.

2017-05-30 12:21 UTC, smoogipooo commented on osu.Game/Graphics/IHasContextMenu.cs
> +        /// Menu that opens when clicked on the drawable
Menu items that appear when the drawable is right-clicked.

2017-05-30 12:21 UTC, smoogipooo commented on osu.Game/Graphics/Cursor/ContextMenuContainer.cs
> +                    menu.Position = ToLocalSpace(cursor.ActiveCursor.ScreenSpaceDrawQuad.TopLeft);
Was talking to peppy earlier and he suggested it might look nice if the menu would move with the hovered element (if, for example, it scrolls).

2017-05-30 12:21 UTC, smoogipooo commented on osu.Desktop.VisualTests/Tests/TestCaseContextMenu.cs
> +
No spaces in object initializers.

2017-05-31 11:52 UTC, peppy commented
Just from initial VisualTest testing and quickly passing over the code:
- We already have a Menu class, so you should probably look at using that here.
- Clicking items in the menu should be handled OnClick, not OnMouseDown
- If the menu is going to appear OnMouseDown, then you should be able to drag your mouse to an option and release to select it (macOS style). Let's do this for now.

2017-06-02 14:00 UTC, smoogipoo reviewed
I think `Menu` should take a generic parameter of menu items. Something like
```
public class Menu<TItem> : ...
    where TItem : MenuItem
{
    public readonly FillFlowContainer<TItem> ItemsContainer;
}
```

With probably alongside it a class like
```
public class Menu : Menu<MenuItem>
{
}
```

This would fix the remainder of your possible null ref warnings.

2017-06-02 14:00 UTC, smoogipooo commented on osu.Game/Graphics/Cursor/ContextMenuContainer.cs
> +            foreach (var item in contextMenu?.ItemsContainer?.InternalChildren)
`if (contextMenu?.ItemsContainer == null) return;` outside.

2017-06-02 14:00 UTC, smoogipooo commented on osu.Game/Graphics/Cursor/ContextMenuContainer.cs
> +                        (item as ContextMenuItem).Action += Close;
Does this need a cast? Would be able to remove the null ref warning.

2017-06-02 14:02 UTC, smoogipooo commented
Although they were dismissed by @peppy my previous comments still stand.

2017-06-04 12:12 UTC, EVAST9919 commented
Will be implemented in https://github.com/ppy/osu/pull/899

2017-06-04 12:12 UTC, closed without merging