Cancel select random in song select menu
ppy/osu pull request #891
Opened 2017-06-01 15:42 UTC by EVAST9919

2017-06-05 01:40 UTC, smoogipooo commented on osu.Game/Screens/Select/FooterButton.cs
> +        public bool ExcludePressWithShift;
I don't like this solution. Can the case where this is used (SelectRandom vs CancelRandom) not be handled inside SongSelect? Maybe rename the method and have something like...
```
var randomButton = new FooterButton(..., Keys.F2, TriggerRandom);

void TriggerRandom(InputState state)
{
    if (state.Keyboard.ShiftPressed)
        CancelRandom();
    else
        SelectRandom();
}
```

I don't like the naming of CancelRandom and SelectRandom either. Perhaps rename them to `SelectPreviousRandom` and `SelectNextRandom` respectively?

2017-06-05 01:53 UTC, smoogipoo requested changes
As commented.

2017-06-05 01:53 UTC, smoogipooo commented on osu.Game/Screens/Select/BeatmapCarousel.cs
> +            while (true)
```
while (!randomSelectedBeatmaps.Count > 0)
{
    var group = randomSelectedBeatmaps.Pop();
    if (visibleGroups.Conains(group))
    {
        selectGroup(group, group.SelectPanel);
        break;
    }
}
```

2017-06-14 05:45 UTC, smoogipooo commented on osu.Game/Screens/Select/BeatmapCarousel.cs
> +        private readonly Stack<BeatmapGroup> randomSelectedBeatmaps = new Stack<BeatmapGroup>();
Am thinking - how about storing this as a `Stack<KeyValuePair<BeatmapGroup, BeatmapPanel>>` and having `SelectPreviousRandom` work for panels too? At the moment if I filter e.g. AiAe, and F2, I can't go back.

osu!stable does random by panel as I suggest also.

2017-06-26 09:03 UTC, smoogipoo approved these changes
I'm happy with the current state of this.

2017-06-26 09:03 UTC, merged