add caps lock warning to the password textbox
ppy/osu pull request #897
Opened 2017-06-03 17:26 UTC by Jorolf

2017-06-04 05:51 UTC, peppy commented on osu.Game/Graphics/UserInterface/OsuPasswordTextBox.cs
> +            private void updateVisibility() => FadeTo(Console.CapsLock ? 1 : 0, 250, EasingTypes.OutQuint);
you can't do this with transform helpers. you need to store a state and run them only once, else they are going to run far longer than you expect.

2017-06-04 05:57 UTC, peppy commented
https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Console.cs#L556

Checking for caps lock needs to be done as a per-platform implementation. See other examples of how this is done in the framework.

2017-06-05 05:40 UTC, peppy requested changes
as above

2017-06-11 12:59 UTC, Jorolf commented
closed until I find a better way to test if capslock is enabled

2017-06-11 12:59 UTC, closed without merging