Fix taiko scroller not correctly adhering to gameplay time movement
ppy/osu pull request #9003
Opened 2020-05-12 06:25 UTC by peppy

- Closes https://github.com/ppy/osu/issues/8995
- Adds forgotten resources bump to make the scroller actually appear for default skin

More of a large change than I hoped for, but I think this method reads better. Maybe.

2020-05-12 11:13 UTC, bdach commented on osu.Game.Rulesets.Taiko/Skinning/LegacyTaikoScroller.cs
> +                && InternalChildren.First().ScreenSpaceDrawQuad.Width * InternalChildren.Count >= ScreenSpaceDrawQuad.Width * 2;
Once texture wrapping makes it in framework-side we might potentially look at removing this type of logic altogether in favour of just animating texture coords instead? Not sure how viable that is.

2020-05-12 11:16 UTC, smoogipoo commented on osu.Game.Rulesets.Taiko/Skinning/LegacyTaikoScroller.cs
> +                && InternalChildren.First().ScreenSpaceDrawQuad.Width * InternalChildren.Count >= ScreenSpaceDrawQuad.Width * 2;
Yeah that could work.

2020-05-12 11:17 UTC, peppy commented on osu.Game.Rulesets.Taiko/Skinning/LegacyTaikoScroller.cs
> +                && InternalChildren.First().ScreenSpaceDrawQuad.Width * InternalChildren.Count >= ScreenSpaceDrawQuad.Width * 2;
There's zero overhead of off-screen sprites? I did consider this.

Using texture wrapping may work or may be too hacky. We'll see when it's ready.

2020-05-12 11:21 UTC, smoogipoo commented
![image](https://user-images.githubusercontent.com/1329837/81680503-1cf05200-948e-11ea-9223-8b738a2dfffa.png)

This is creating hundreds of sprites.

2020-05-12 11:21 UTC, smoogipoo requested changes
As mentioned

2020-05-12 11:22 UTC, peppy commented
Can you provide a case that creates hundreds? That sounds insanely wrong. It's only supposed to generate 2x screen width.

2020-05-12 11:23 UTC, smoogipoo commented
Any beatmap. Here's one https://osu.ppy.sh/beatmapsets/587439#taiko/1244015

2020-05-12 11:23 UTC, peppy commented
Ah, beatmap specific skins?

2020-05-12 11:23 UTC, smoogipoo commented
Classic skin

2020-05-12 11:24 UTC, peppy commented
Again, that makes zero sense. I've heavily tested and cannot reproduce so please provide more details.

2020-05-12 11:28 UTC, peppy commented
Nevermind, looks to be a regression with the seemingly safe last commit.

2020-05-13 10:21 UTC, peppy commented
I've fixed the issue by converting from a `while` to `if`. It should not be noticeable under any sane scenario (would see the scroller incorrectly for maybe one frame during initial fade in on a super super ultra wide). Because this is a legacy component and may change with taiko playfield sizing changes (to allow it work work with `while`) or with texture wrapping (for a saner implementation) I see this as the most efficient fix for now.

2020-05-14 08:36 UTC, smoogipoo approved these changes
Seems fine for now, let's see how this goes.

2020-05-14 08:56 UTC, merged