Arrows control in Pause/Fail overlays
ppy/osu pull request #923
Opened 2017-06-10 00:21 UTC by EVAST9919

2017-06-11 07:54 UTC, peppy commented
haven't looked at the code, but please try and test the most *common* ways to break a new feature before submitting for review

![screen shot 2017-06-11 at 16 54 28](https://user-images.githubusercontent.com/191335/27009360-a76e92b8-4ec6-11e7-931f-9c377ac1866d.png)

2017-06-11 10:41 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +            foreach (var button in Buttons.Children)
This should only be done when pressing UP or DOWN.

2017-06-11 10:41 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                        selectedButton = 1;
I personally don't like the representation of "no button is selected" as 0. I think it is more intuitive to use -1.

2017-06-11 12:23 UTC, Jorolf commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                        selectedButton = 1;
0 is generally the start of an array/list so it is confusing to make 1 the first button

2017-06-11 12:23 UTC, Jorolf commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                    Buttons.Children.ElementAt(selectedButton - 1).TriggerOnHover(state);
this would remove the -1 here as well

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                        selectedButton = 1;
This should be changed to 0 now.

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                    if (selectedButton == -1 || selectedButton == buttonsAmount)
buttonsAmount - 1

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                    Buttons.Children.ElementAt(selectedButton - 1).Select(state);
...ElementAt(selectedButton)...

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                        Buttons.Children.ElementAt(selectedButton - 1).Deselect(state);
...ElementAt(selectedButton)...

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                    if (selectedButton == -1 || selectedButton == 1)
|| selectedButton == 0

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                    Buttons.Children.ElementAt(selectedButton - 1).Select(state);
...ElementAt(selectedButton)...

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                        Buttons.Children.ElementAt(selectedButton - 1).TriggerOnClick();
...ElementAt(selectedButton)...

2017-06-11 12:55 UTC, MrTheMake commented on osu.Game/Screens/Play/MenuOverlay.cs
> +                        Buttons.Children.ElementAt(selectedButton - 1).Deselect(state);
...ElementAt(selectedButton)...

2017-06-11 13:13 UTC, Jorolf commented on osu.Game/Screens/Play/MenuOverlay.cs
> +            if (args.Repeat) return false;
return true, otherwise the volume overlay shows

2017-06-18 19:09 UTC, smoogipoo requested changes
I'd say this is looking okay on an initial pass.

2017-06-18 19:09 UTC, smoogipooo commented on osu.Game/Screens/Play/MenuOverlay.cs
> +        private int buttonsAmount => Buttons.Children.Count();
`buttonCount`

2017-06-19 00:39 UTC, EVAST9919 commented
Don't review this yet, some mistakes has been founded.

2017-06-19 01:42 UTC, EVAST9919 commented
Main issue for now: button which has been selected and clicked by keyboard can't be deselected by selecting another button for the first time.

2017-06-25 21:43 UTC, EVAST9919 commented
Closing untill I found a better way to implement this

2017-06-25 21:44 UTC, closed without merging