Slightly adjust match/multiplayer designs
ppy/osu pull request #9372
Opened 2020-06-25 13:31 UTC by smoogipoo

From:
![Screenshot_2020-06-25_22-26-14](https://user-images.githubusercontent.com/1329837/85728959-5a095e80-b733-11ea-9cb4-7cf4a243c41e.png)
![Screenshot_2020-06-25_22-08-19](https://user-images.githubusercontent.com/1329837/85726604-37764600-b731-11ea-87b0-5f871f21b1d4.png)

To:
![Screenshot_2020-06-25_22-29-21](https://user-images.githubusercontent.com/1329837/85728980-5d9ce580-b733-11ea-98de-e24b16b10dba.png)
![Screenshot_2020-06-25_22-22-04](https://user-images.githubusercontent.com/1329837/85727899-5f19de00-b732-11ea-8a67-c4475713a43e.png)

2020-06-25 13:34 UTC, peppy commented
How does this look in vertical aspect ratio?

2020-06-25 13:38 UTC, peppy commented
Also just a personal opinion, but the match screen feels messy and overwhelming right now. Too much displayed and very hard to know what is related to / doing what.

I'll probably take some time to come up with a basic design in the near future, since it's clear the current "ask designer for everything" doesn't scale well (requirements are hard to convey when the designer isn't actually using / hasn't historically used the systems).

2020-06-25 14:01 UTC, peppy requested changes

2020-06-25 14:14 UTC, smoogipoo commented on osu.Game/Tests/Visual/ScreenTestScene.cs
> +        // [TearDownSteps]
Whoops I didn’t mean to commit this.

2020-06-26 03:16 UTC, smoogipoo commented
Going to close this one for now as we rethink the layout altogether.

2020-07-07 08:39 UTC, peppy commented
Reopening to use as a starting point for getting the match screen into a better state. Structure wise, I believe we still want many of the elements added in this. May revert some pieces as I go.

2020-07-07 09:40 UTC, peppy approved these changes

2020-07-07 10:22 UTC, merged