Shortened condition in Music Controller's beatmap changed function
ppy/osu pull request #939
Opened 2017-06-15 22:33 UTC by MrTheMake

2017-06-16 06:40 UTC, peppy commented
99% sure this is also changing behaviour

2017-06-18 10:52 UTC, peppy submitted a review, later dismissed

2017-06-26 09:11 UTC, smoogipooo commented
Was the "changing of behaviour" issue previously addressed in the dev discord or something? This is still changing behaviour.

2017-06-26 10:45 UTC, MrTheMake commented
I honestly don't see why this changes behavior. I talked to @huoyaoyuan and, if I remember correctly, he said that the assignment `direction = Transformation.None` is not needed as it is initialized to that value.

2017-07-05 20:21 UTC, smoogipooo commented
Ah. I didn't notice the default value. I thought this was an instance member.

2017-07-05 20:27 UTC, smoogipoo requested changes

2017-07-05 20:27 UTC, smoogipooo commented on osu.Game/Overlays/MusicController.cs
> +                if (!audioEquals)
Move audioEquals out of this if, and make the conditional just `if (!audioEquals)` to reduce nesting.

2017-08-01 02:33 UTC, peppy commented
This is still changing behaviour, as `current` is accessed within the `if` block.

2017-08-01 02:33 UTC, closed without merging