Add an option to loop the intro in the main menu
ppy/osu pull request #9391
Opened 2020-06-28 22:55 UTC by MiraiSubject

Closes https://github.com/ppy/osu/issues/9390

The default setting for this right now is set to `true`.
This might not be desired for `Triangles` considering the `welcome to osu!` is baked into the beatmap.
This should be fine for `Circles` and `Welcome` though.

2020-06-28 23:06 UTC, frenzibyte requested changes
I really don't think all intros should have their track looped, the `Triangles` intro would not work well for it (and doesn't seem to be made to), same goes to `Circles`. Only the `Welcome` intro would work well as it is made to produce a continuation when looping. 

So I think the welcome intro should just loop its own track by itself, and nothing more (with tests providing assertions).

2020-06-28 23:15 UTC, MiraiSubject commented
Makes sense.

I made it an option because there could be users that would like the `Welcome` intro but not having it loop. 
Then again it would only make sense for `Welcome` to be looped in the first place. 

I'll update it so only `Welcome` gets looped

2020-06-29 01:57 UTC, peppy commented
Is that how it is back in stable-fallback?

2020-06-29 02:45 UTC, Nyanekoy commented
> Is that how it is back in stable-fallback?

Yea it does loop always unless you switch to another song then you can only listen to it again until you restart

2020-06-29 02:51 UTC, peppy commented on osu.Game.Tests/Visual/Menus/TestSceneIntroWelcome.cs
> +            AddAssert("check if menu music loops", () =>
kinda pointless test but i guess it's fine.

2020-06-29 03:56 UTC, peppy approved these changes

2020-06-29 03:56 UTC, merged