Fix possible startup error when using custom directory
ppy/osu pull request #9418
Opened 2020-07-01 08:57 UTC by smoogipoo

Fixes https://github.com/ppy/osu/issues/9379

Prereqs:
- [ ] https://github.com/ppy/osu/pull/9417

If an error happens, the default storage directory is used and a notification is shown after the game finishes starting up. The config isn't cleared, because the user could potentially mount the device and fix the issue.

2020-07-01 21:59 UTC, bdach submitted a review, later dismissed
Tested by doing a `$ chmod -x` on a custom data directory, seems to be doing the job fine :+1:

2020-07-02 02:41 UTC, peppy commented
This works fine to cover the hard crash, but before merging there's a few points which we should probably discuss / reach consensus on:

- What happens when the target location is writeable but no longer exists?

We may want to show the same message and make the user aware that they have potentially moved the folder and osu! is no longer aware of this. Right now, it will create a new folder structure in the specified location, which is probably not what the user wants under any circumstance.

A common scenario for this happening is if the user moves the custom folder to a new location themselves, and still wants lazer to use it.

We probably want to have the "change location" use an already existing folder rather than erroring out if files already exist at the target location (as it currently does).

- If the user ignores the error, they now have two data locations

For the average user, I'd hope this be a fullscreen dialog on startup forcing action, rather than an ugly exception message. It should give the user a chance to resolve the issue or reset their folder location to the default. ie. a dialog with [ Retry ] [ Reset to default ] [ Choose new location ]. The third button would obviously work best if the above points were first resolved.

If you agree, I think changing the PR even to address only point 2 may be a saner starting point to handling this scenario.

2020-07-02 02:41 UTC, peppy requested changes
blocking pending discussion

2020-07-06 13:05 UTC, smoogipoo commented
I agree. I've updated the PR to add the dialog:

When empty:
![Screenshot_2020-07-06_21-54-18](https://user-images.githubusercontent.com/1329837/86596058-9743db00-bfd4-11ea-8801-4cb75b5b5bfe.png)

When not accessible:
![Screenshot_2020-07-06_21-55-22](https://user-images.githubusercontent.com/1329837/86596065-990d9e80-bfd4-11ea-8cf8-e7ca404898c3.png)

We could eventually add a folder selection dialog, but I didn't want to do that just yet as it would take quite some abstraction of the migration dialog (we don't want to migrate, and we also don't want to create the "osu-lazer" sub-directory, and we also probably want to prompt).

2020-07-06 13:30 UTC, peppy requested changes

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                BodyText = $"osu! encountered an error when trying to use the custom storage path ('{storage.CustomStoragePath}').\n\n";
```suggestion
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                        BodyText += $"The default storage path ('{storage.DefaultStoragePath}') is currently being used because the custom storage path is not accessible.\n\n"
```suggestion
                        BodyText += $"The specified osu! data location (\"{storage.CustomStoragePath}\") is not accessible. If it is on external storage, please reconnect the device and try again."
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                                    + "Is it on a removable device that is not currently connected?";
```suggestion
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                                Text = "Use the default path from now on",
```suggestion
                                Text = "Reset to default location",
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                                Text = "Only use the default path for this session",
```suggestion
                                Text = "Use default location for this session",
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                                    + "Have you moved the files elsewhere?";
```suggestion
                        BodyText = $"The specified osu! data location (\"{storage.CustomStoragePath}\") is empty. If you have moved the files, please close osu! and move them back.";
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                                Text = "Reset to default",
```suggestion
                                Text = "Reset to default location",
```

2020-07-06 13:30 UTC, peppy commented on osu.Game/Screens/Menu/MainMenu.cs
> +                                Text = "Keep using the custom path"
```suggestion
                                Text = "Start fresh at specified location"
```

I'd also put this button above the "reset to default"

2020-07-06 14:51 UTC, peppy approved these changes

2020-07-06 15:20 UTC, merged