Implement NewsCard component for NewsOverlay
ppy/osu pull request #9437
Opened 2020-07-06 04:35 UTC by EVAST9919

2020-07-06 19:44 UTC, bdach requested changes

2020-07-06 19:44 UTC, bdach commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +        public DateTime UpdatedAt { get; set; }
Pretty sure these should be `DateTimeOffset`s.

2020-07-06 19:44 UTC, bdach commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +        [JsonProperty(@"id")]
Raw string prefixes seem unnecessary.

2020-07-06 19:44 UTC, bdach commented on osu.Game/Overlays/News/NewsCard.cs
> +            public string TooltipText => date.ToString("d MMMM yyyy hh:mm:ss UTCz");
This tooltip is not consistent with web design. This should be using whatever `DrawableDate` is, probably by hoisting out `DrawableDate.DateTooltip` of the inner class and making it public.

2020-07-06 19:44 UTC, bdach commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +    public class APINewsPost
Where did you get this endpoint contract structure from? I looked at the news page on web and I can't find a straight API request that would just fetch this as JSON, [API docs are missing](https://osu.ppy.sh/docs/index.html#apiv2newsnews), and this PR does not have a web request attached that I can inspect.

2020-07-06 20:11 UTC, EVAST9919 commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +    public class APINewsPost
I just sent a raw request and checked the response
![Screenshot_1](https://user-images.githubusercontent.com/22874522/86637339-040fa300-bfde-11ea-9528-54ebf173fa9c.png)

2020-07-06 20:21 UTC, bdach commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +    public class APINewsPost
I notice an `&amp;` HTML entity in the `author` field of post with ID 802 (I'm betting it's possible for `title` and `preview` to contain HTML entities, too). This should be handled at some point using `WebUtility.HtmlDecode` - probably best at deserialisation time.

2020-07-06 20:26 UTC, EVAST9919 commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +    public class APINewsPost
Nice catch will consider!
Also, as a side note: web can't handle this either, should probably open an issue
![Аннотация 2020-07-06 232512](https://user-images.githubusercontent.com/22874522/86638520-168adc00-bfe0-11ea-8e29-7c50390072c7.png)

2020-07-06 20:49 UTC, bdach commented on osu.Game/Online/API/Requests/Responses/APINewsPost.cs
> +    public class APINewsPost
Opened ppy/osu-web#6274.

2020-07-07 04:35 UTC, smoogipoo requested changes
Looks fine otherwise

2020-07-07 04:35 UTC, smoogipoo commented on osu.Game/Graphics/DrawableDate.cs
> +        public class DateTooltip : VisibilityContainer, ITooltip
Would like this to be moved to a separate file.

2020-07-07 21:11 UTC, bdach commented
I've adjusted one font size to match web; otherwise than that looks good.

Going to make and exception and approve this despite having pushed to this PR as the change was menial.

2020-07-07 21:12 UTC, bdach approved these changes

2020-07-07 21:39 UTC, smoogipoo approved these changes

2020-07-08 11:37 UTC, merged