Implement OsuScreen::CanBeatmapChange and use it in the music controller
ppy/osu pull request #955
Opened 2017-06-19 12:35 UTC by MrTheMake

Used to disallow manipulating the current beatmap track in the player and the result screens

2017-06-19 15:55 UTC, DrabWeb requested changes

2017-06-19 15:55 UTC, DrabWeb commented on osu.Game/Screens/OsuScreen.cs
> +        internal virtual bool CanBeatmapChange => true;
Maybe `AllowBeatmapChange` to be more consistent with `AllowRulesetChange`.

2017-06-19 15:55 UTC, DrabWeb commented on osu.Game/OsuGameBase.cs
> +        public readonly Bindable<OsuScreen> CurrentScreen = new Bindable<OsuScreen>();
I really don't like exposing this, would suggest instead exposing something like `AllowBeatmapChange` on the `MusicController` and setting that in `screenChanged`.

2017-06-21 02:39 UTC, smoogipoo submitted a review, later dismissed

2017-06-21 02:39 UTC, smoogipooo commented on osu.Game/Overlays/MusicController.cs
> +            if(Alpha == 0)
Spacing.

2017-06-21 02:39 UTC, smoogipooo commented on osu.Game/Overlays/MusicController.cs
> +        public bool AllowBeatmapChange
This should probably be a bindable, and use e.g. `prevButton.BindTo(AllowBeatmapChange)`.

2017-06-21 02:39 UTC, smoogipooo commented on osu.Game/OsuGame.cs
> +            musicController.AllowBeatmapChange = currentScreen.AllowBeatmapChange;
And here, this could be `musicController.AllowBeatmapChange.BindTo(currentScreen.AllowBeatmapChange)`.

2017-06-25 18:10 UTC, peppy commented on osu.Game/Overlays/MusicController.cs
> +        private void beatmapDisabledChanged(bool newBeatmapBackingDisabled)
just call the bool `disabled`

2017-06-25 18:12 UTC, peppy commented on osu.Game/Screens/Ranking/Results.cs
> +        internal override bool AllowBeatmapChange => false;
put this at the top of the file with other `internal override`s

2017-07-14 10:12 UTC, peppy commented on osu.Game/Graphics/UserInterface/IconButton.cs
> +            if (!Enabled.Value)
you probably don't want this.

2017-07-14 10:12 UTC, peppy commented on osu.Game/Graphics/UserInterface/IconButton.cs
> +            if (!Enabled.Value)
nor this

2017-07-14 10:15 UTC, peppy commented on osu.Game/Overlays/MusicController.cs
> +        private bool showPlaylistOnceAvailable;
i don't get this

2017-08-02 03:51 UTC, peppy approved these changes

2017-08-02 03:51 UTC, merged