Remove SocialOverlay component as never being used
ppy/osu pull request #9611
Opened 2020-07-18 20:15 UTC by EVAST9919

Split from https://github.com/ppy/osu/pull/9610

2020-07-18 20:24 UTC, bdach commented
what about the classes from the `osu.Game.Overlays.Social` namespace?

2020-07-18 20:25 UTC, bdach requested changes
as above

2020-07-18 21:32 UTC, bdach approved these changes
seems fine

2020-07-20 10:56 UTC, smoogipoo approved these changes

2020-07-20 10:56 UTC, merged