Remove DragBar and replace with classes that inherit SliderBar
ppy/osu pull request #966
Opened 2017-06-22 16:49 UTC by jai-sharma

Each `SliderBar.Current` value is equal to the `CurrentTime` of the track playing such that a `OnSeek` action can directly use the `Current` value to perform the seek.

Depends on: https://github.com/ppy/osu-framework/pull/850

2017-06-22 17:50 UTC, marco-stephan requested changes

2017-06-22 18:02 UTC, jai-sharma commented on osu.Game/Screens/Play/SongProgress.cs
> +                    OnSeek = position => this.OnSeek?.Invoke(position),
Since the Action names are the same, I feel that it makes it clearer what the code is doing by keeping `this`.

2017-06-23 06:12 UTC, peppy commented on osu.Game/Screens/Play/SongProgress.cs
> +                    OnSeek = position => this.OnSeek?.Invoke(position),
fwiw it won't pass CI like this

2017-06-23 06:34 UTC, peppy commented on osu.Game/Overlays/MusicController.cs
> +            else if (t != null)
this don't look thread-safe

2017-07-18 05:37 UTC, peppy commented on osu.Game/Overlays/MusicController.cs
> +                    t.OnLoaded = null;
no no no no no

2017-07-18 06:39 UTC, peppy approved these changes

2017-07-18 06:43 UTC, merged