Basic Section Tracking
ppy/osu pull request #969
Opened 2017-06-23 23:57 UTC by EVAST9919

2017-06-25 02:39 UTC, ColdVolcano commented on osu.Game/Screens/Play/Player.cs
> +                                Background?.FadeTo(1, fade_duration);
I'm almost sure dimLevel should also play a role here

2017-06-25 02:42 UTC, ColdVolcano commented on osu.Game/Screens/Play/SectionTrackOverlay.cs
> +                Add(content = new Container
Is there a need for an extra level here?

2017-06-25 06:50 UTC, peppy commented
what does "basic section tracking" even men

2017-06-27 03:39 UTC, ColdVolcano commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +                    Children = new Drawable[]
Why not set children directly instead of adding a container with said children

2017-06-27 03:41 UTC, EVAST9919 commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +                    Children = new Drawable[]
We are doing the same thing in HudOverlay. I guess, we don't wanna hide the container itself, only the content inside this container.

2017-07-21 07:43 UTC, peppy commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +                    Schedule(() => resultIcon.FadeTo(0));
just use delay on the `resultIcon`  directly and don't use `Schedule`

2017-08-02 05:57 UTC, peppy commented
No TestCase? :(

2017-08-22 07:50 UTC, peppy commented on osu.Game/Screens/Play/Player.cs
> +                        letterboxInBreaksContainer = new Container
Please move this implementation to a new container; you're polluting `Player` again.

2017-08-22 07:50 UTC, peppy commented on osu.Game/Screens/Play/Player.cs
> +                        letterboxInBreaksContainer = new Container
Also make it IStateful and move the hide/show transform logic inside it.

2017-08-22 08:01 UTC, peppy commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +    public class BreakPeriodsTrackOverlay : Container
`BreakOverlay` sounds fine

2017-08-22 08:02 UTC, peppy commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +        private readonly BindableDouble healthBindable = new BindableDouble
no need for bindable suffix

2017-08-22 08:04 UTC, peppy commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +            if (breaks == null) return;
this whole method is what?

2017-08-22 08:04 UTC, peppy commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +            if (breaks == null) return;
you can't just overload update to do stuff like this. it's shocking for readability and extensibility.

2017-08-22 08:04 UTC, peppy requested changes
needs a lot of refactoring

2017-08-22 11:45 UTC, EVAST9919 commented on osu.Game/Screens/Play/BreakPeriodsTrackOverlay.cs
> +        private readonly BindableDouble healthBindable = new BindableDouble
That's because we already have `health` variable

2017-08-23 02:38 UTC, EVAST9919 commented
Will be refactored and reimplemened in future pr's

2017-08-23 02:38 UTC, closed without merging