DrawableRoom Design Update
ppy/osu pull request #970
Opened 2017-06-24 08:58 UTC by DrabWeb

![screen shot 2017-06-24 at 5 57 15 am](https://user-images.githubusercontent.com/6215387/27507276-0c70bfee-58a2-11e7-8334-47cd304f7378.png)

Didn't have the designs before so assumed alot wrong. Also includes general cleanup and shared code of/between `DrawableRoom` and `RoomInspector`.

2017-06-24 12:25 UTC, peppy commented on osu.Game/Screens/Multiplayer/DrawableRoom.cs
> +                    Padding = new MarginPadding { Top = content_padding, Bottom = content_padding, Left = side_strip_width + cover_width + content_padding, Right = content_padding },
i still think cases like this should be split into newlines per property setter.

2017-06-24 22:08 UTC, EVAST9919 requested changes

2017-06-24 22:08 UTC, EVAST9919 commented on osu.Game/Screens/Multiplayer/DrawableRoom.cs
> +                        Top = content_padding,
Use Vertical instead of Top and Bottom

2017-06-25 12:22 UTC, peppy commented
https://puu.sh/wtOMf/91cbedae7f.gif this probably needs to be fixed. if they are going to animate, they should only do so on the horizontal axis

2017-07-14 06:29 UTC, peppy commented
Looks good. Not going to nit-pick on this one since it's not being actively used yet. Will probably require some changes once we slot it all in.

2017-07-14 06:29 UTC, peppy approved these changes

2017-07-14 06:35 UTC, merged