Hide "Unranked" text in ModDisplay if play is ranked
ppy/osu pull request #978
Opened 2017-06-27 02:18 UTC by EVAST9919

2017-06-27 02:31 UTC, Nabile-Rahmani requested changes

2017-06-27 02:31 UTC, Nabile-Rahmani commented on osu.Game/Screens/Play/HUD/ModDisplay.cs
> +        private bool playIsRanked()
Turn that into a smaller property ? i.e.
```csharp
private bool IsRanked => !mods.Value.Any(m => !m.IsRanked);
```

2017-07-01 14:09 UTC, Jorolf commented on osu.Game/Screens/Play/HUD/ModDisplay.cs
> +                unrankedText.FadeTo(0);
`Hide()` ?

2017-07-11 01:36 UTC, DrabWeb commented on osu.Game/Screens/Play/HUD/ModDisplay.cs
> +            if (!playIsRanked)
Can just use `!mods.Value.Any(m => !m.Ranked)` here and remove `playIsRanked`.

2017-07-14 08:32 UTC, peppy approved these changes

2017-07-14 08:36 UTC, merged