add markdown support
ppy/osu pull request #987
Opened 2017-07-02 11:30 UTC by Jorolf

if you **really** want to emphasize _something_

2017-07-02 11:55 UTC, Nabile-Rahmani commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                    if (i != 0) //we shouldn't switch when the i is zero because then there wasn't a asterisk yet and we don't want to switch at the end because then there could've just been two aste
Can't you swap out that toggle for `italic = i % 2 != 0` ?

2017-07-02 11:57 UTC, Jorolf commented on osu.Game/Overlays/Chat/ChatLine.cs
> +                    if (i != 0) //we shouldn't switch when the i is zero because then there wasn't a asterisk yet and we don't want to switch at the end because then there could've just been two aste
that wouldn't support random bold text in an italic one

2017-07-02 12:59 UTC, Tom94 commented
First, this needs to support escaping via \. Smilies like *_* are impossible otherwise.
Next, if we go this way, then _ should be permitted for italic text, too, as it is very common in chat applications. Lastly, as far as I can tell the current implementation switches to italic if there is just a single * in a sentence. That should not happen either.

2017-07-03 00:42 UTC, huoyaoyuan commented on osu.Game/Overlays/Chat/ChatLine.cs
> +            markers.Sort((a, b) => a.Index.CompareTo(b.Index));
Make `SplitMarker : IComparable<SplitMarker>`, and then default sort method can be used.

2017-07-03 08:18 UTC, Tom94 commented on osu.Game/Overlays/Chat/ChatLine.cs
> +            markers.Sort((a, b) => a.Index.CompareTo(b.Index));
Why overengineer if this is perfectly sufficient? I prefer to leave the struct be just a dumb data container unless the abstractions are actually useful in multiple places.

2017-07-11 02:21 UTC, DrabWeb commented
I think this should be moved to the framework with `TextFlowContainer` (that's why it was originally called `Paragraph`, this was planned to be added).

2017-07-14 06:37 UTC, peppy commented
I agree we need this in the framework. I'm not sure it makes sense to implement it just for ChatLine here.

2017-07-14 17:48 UTC, Tom94 commented
If we put it into framework, then it should be a wrapper around the `TextFlowContainer` we have right now. Basically, taking markdown-formatted text and outputting a `TextFlowContainer` which has the correct pieces.

2017-08-01 02:34 UTC, peppy commented
Any chance you can reimplement this in the framework as discussed @jorolf? We definitely want to use it in more places than just `ChatLine`.

2017-08-01 02:45 UTC, peppy requested changes
Should be added to framework so we can reuse this across multiple use cases.

2017-08-16 21:22 UTC, jorolf commented
working on a framework implementation

2017-08-16 21:22 UTC, closed without merging